share/goodie/cheat_sheets/json/apache-pig.json

IA : https://duck.co/ia/view/apache_pig_cheat_sheet

New Apache Pig Cheat  Sheet

---

share/goodie/cheat_sheets/json/rails.json

https://duck.co/ia/view/rails_cheat_sheet

New Rails 4 Cheatsheet

---

share/goodie/cheat_sheets/json/opencv-python.json

I have created an IA page at https://duck.co/ia/view/opencv_python_cheat_sheet

Initial commit on OpenCV-Python Cheat Sheet

---

share/goodie/cheat_sheets/json/wunderlist-mac.json

New cheat sheet: Wunderlist Mac
IA Page: https://duck.co/ia/view/wunderlist_mac_cheat_sheet

New cheat sheet: Wunderlist Mac

---

share/goodie/cheat_sheets/json/facebook.json

This cheatsheet displays commands available to use on Facebook as well as the Web Messenger.
https://duck.co/ia/view/facebook_cheat_sheet

New Facebook and Web Messenger Cheat Sheet

---

share/goodie/cheat_sheets/json/sas.json

IA page : https://duck.co/ia/view/sas_cheat_sheet

New SaS cheat sheet

---

share/goodie/cheat_sheets/json/alt-codes.json

https://duck.co/ia/view/alt_codes_cheat_sheet

Alt key combinations cheat sheet

---

share/goodie/cheat_sheets/json/quackhack.json

https://duck.co/ia/view/quackhack_cheat_sheet

updated slack link for the heroku bot

---

share/goodie/cheat_sheets/json/flask.json

Flask is a Python microframework.
http://flask.pocoo.org/
flask cheat sheet
No triggers applied.
**Screenshot 1**
**Screenshot 2**
https://duck.co/ia/view/flask_cheat_sheet

New Flask cheat sheet.

---

share/goodie/cheat_sheets/json/bittorrent.json

Bit Torrent cheat sheet , keyboard shortcuts
IA Page: https://duck.co/ia/view/bittorrent_cheat_sheet

New Bit torrent cheat sheet

---

share/goodie/cheat_sheets/json/classic-cocktails.json

https://duck.co/ia/view/classic_cocktails_cheat_sheet

New Classic Cocktails Cheat Sheet

---

share/goodie/cheat_sheets/json/zypper.json

Instant Answer URL
https://duck.co/ia/view/zypper_package_manager_cheat_sheet

New Zypper Cheat Sheet Goodie

---

share/goodie/cheat_sheets/json/bittorrent.json

Fixed a typo in the Cheat Sheet ID
https://duck.co/ia/view/bittorrent_cheat_sheet

Fix bittorrent ID spelling

---

share/goodie/cheat_sheets/json/ipfs.json

IA: https://duck.co/ia/view/ipfs_cheat_sheet

new cheat sheet (terminal commands) for IPFS

---

share/goodie/cheat_sheets/json/meteor.json

https://duck.co/ia/view/meteor_cheat_sheet

New Meteor Cheat Sheet

---

share/goodie/cheat_sheets/json/arduino.json

https://duck.co/ia/view/arduino_cheat_sheet

New Arduino Cheat Sheet

---

share/goodie/cheat_sheets/json/sass.json

IA page : https://duck.co/ia/view/sass_cheat_sheet

New SaSS cheat-sheet

---

share/goodie/cheat_sheets/json/ocaml.json

A cheat sheet for the OCaml programming language.
https://ocaml.org/docs/cheat_sheets.html
No example queries.
No triggers applied.
**Screenshot 1**
**Screenshot 2**
https://duck.co/ia/view/ocaml_cheat_sheet

New OCaml cheat sheet.

---

share/goodie/cheat_sheets/json/language/dothraki.json

https://duck.co/ia/view/dothraki_cheat_sheet

New Dothraki Cheat Sheet

---

share/goodie/cheat_sheets/json/curl.json

IA Page: https://duck.co/ia/view/curl_cheat_sheet

New Curl Cheat Sheet

---

lib/DDG/Goodie/Stardate.pm
t/Stardate.t

This is a basic version that returns the current stardate.
Suggestions and improvements are welcome! :smile: 
IA Page: https://duck.co/ia/view/stardate

New Stardate Goodie

---

share/goodie/cheat_sheets/json/swift.json

https://duck.co/ia/view/swift_cheat_sheet
Maintainer: @gautamkrishnar

Fix typos and formatting for swift cheatsheet

---

share/goodie/cheat_sheets/json/iex.json

This commit also sorts alphabetically all the IEx commands as appears in the [official documentation](http://elixir-lang.org/docs/stable/iex/IEx.Helpers.html). Fixes #2899
-----
IA Page:  http://duck.co/ia/view/iex_cheat_sheet 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @pjhampton

IEx Cheat Sheet: Remove duplicate entry for import_file/1 command

---

template/t/Example.t

@zachthompson We can now use Test::Deep for tests, ain't that awesome?

Add Test::Deep to Goodie template

---

template/lib/DDG/Goodie/Example.pm
template/lib/DDG/Goodie/Minimal.pm
template/share/goodie/example/example.handlebars
template/share/goodie/example/example.js
template/t/Example.t

@zachthompson Some of the indentation was a bit off, spotted a couple of typos too.

Goodie Templates: Improve formatting

---

share/goodie/cheat_sheets/json/gom-player.json

created gom player cheat sheet
--------
ia: https://duck.co/ia/view/gom_player_cheat_sheet

New gom player cheat sheet

---

share/goodie/cheat_sheets/json/codio-mac.json
share/goodie/cheat_sheets/json/codio_mac.json

IA Page: https://duck.co/ia/view/codio_mac_cheat_sheet

New Codio Mac Cheat Sheet

---

share/goodie/cheat_sheets/json/ipfs.json

IA: https://duck.co/ia/view/ipfs_cheat_sheet

[ipfs cheatsheet] description shortened

---

share/goodie/cheat_sheets/json/angular2.json

IA Page: https://duck.co/ia/view/angular2_cheat_sheet

Use newline in Angular2 Cheat Sheet

---

share/goodie/help_line/triggers.yml

@GuiltyDolphin @yegg 
Fixes #2658.
`how to kill myself` trigger was already present. Added a couple of additional triggers. Please let me know if anything else needs to be done.
IA :  https://duck.co/ia/view/help_line

Added helpline triggers. Fixes #2658

---

share/goodie/cheat_sheets/json/vscode.json

Add key bindings for Visual Studio Code (Windows)
-----
VSCode cheat sheet: https://duck.co/ia/view/vscode_cheat_sheet

New VSCode Cheat Sheet

---

share/goodie/cheat_sheets/json/portal.json

https://duck.co/ia/view/portal_cheat_sheet

New Portal Cheat Sheet

---

share/goodie/cheat_sheets/json/kotlin.json

IA: https://duck.co/ia/view/kotlin

New Kotlin Cheat Sheet

---

CONTRIBUTING.md
README.md

Already merged on Spice - making these match

Better Contributing and Readme files (match format on Spice repos)

---

share/goodie/cheat_sheets/json/kotlin.json

Included suggestions by @moollaza and @GuiltyDolphin from the original PR #2909 
IA: https://duck.co/ia/view/kotlin

Kotlin cheat sheet: Fix spelling, indent, empty block

---

share/goodie/cheat_sheets/json/microsoft-excel.json

https://duck.co/ia/view/microsoft_excel_cheat_sheet
Maintainer: @ankushg07

Excel cheatsheet: Add aliases and fix typo

---

share/goodie/cheat_sheets/json/activeworlds.json

Adding new shortcuts based on feedback from ActiveWorlds community.
IA: https://duck.co/ia/view/activeworlds_cheat_sheet

ActiveWorlds Cheat Sheet: Adding new keyboard shortcuts

---

share/goodie/cheat_sheets/json/django.json

https://duck.co/ia/view/django_cheatsheet

django-cheatsheet

---

share/goodie/cheat_sheets/json/accounting.json

IA page : https://duck.co/ia/view/accounting_cheat_sheet

New Accounting cheat sheet

---

share/goodie/cheat_sheets/json/neko/neko-builtins.json

IA: https://duck.co/ia/view/neko_builtins

New Neko Builtins Cheat Sheet

---

share/goodie/cheat_sheets/json/unix-time-format.json

I've added some examples of existing formats, as well as improved the aliases.
---
IA Page: https://duck.co/ia/view/unix_time_format_cheat_sheet

Unix Time Format Cheat Sheet: Add examples

---

lib/DDG/Goodie/POTUS.pm
t/POTUS.t

Lo all,
Fixes #1863 
There're been 2 PR's for fixing this that have just died so I figured I'd just get it out of the way.
-------------------
IA Page: https://duck.co/ia/view/potus

POTUS: Fixes #1863

---

lib/DDG/Goodie/Average.pm
t/Average.t

---
IA page: https://duck.co/ia/view/average
Maintainer: @Mailkov

Updates Average Goodie Re #2767

---

lib/DDG/Goodie/Binary.pm
t/Binary.t

---
IA page: https://duck.co/ia/view/binary
Maintainer: @hunterlang

Updates Binary Goodie Re #2767

---

lib/DDG/Goodie/Chars.pm
t/Chars.t

Updates the IA to full template.
------
IA Page:  https://duck.co/ia/view/chars
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @mahi30795

Updates Chars Goodie Re #2767

---

lib/DDG/Goodie/Bitsum.pm
t/Bitsum.t

---
IA page: https://duck.co/ia/view/bitsum
Maintainer: @kste

Updates Bitsum Goodie Re #2767

---

lib/DDG/Goodie/Base.pm
t/Base.t

Upgrade the IA to full template.
---
IA page: https://duck.co/ia/view/base
Maintainer: @moritz

Updates Base Goodie Re: #2767

---

lib/DDG/Goodie/CallingCodes.pm
t/CallingCodes.t

Updates the IA to full template.
------
IA Page:  https://duck.co/ia/view/calling_codes
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @kablamo

Updates CallingCodes Goodie Re #2767

---

lib/DDG/Goodie/Base64.pm
t/Base64.t

---
IA page: https://duck.co/ia/view/base64
Maintainers: @dogweather

Updates Base64 Goodie Re: #2767

---

lib/DDG/Goodie/CalendarConversion.pm
t/CalendarConversion.t

---
IA page: https://duck.co/ia/view/calendar_conversion
Maintainer: @mattlehning

Updates CalendarConversion Goodie Re #2767

---

lib/DDG/Goodie/AspectRatio.pm
t/AspectRatio.t

The tests works but I have a error when I start the server:
```
Use of uninitialized value in concatenation (.) or string at /home/codio/perl5/perls/perl-5.18.2/lib/site_perl/5.18.2/App/DuckPAN/Web.pm line 442
```
This happen no matter which goodies I call.
---
IA Page: https://duck.co/ia/view/aspect_ratio
Maintainer: @mrshu

Updates AspectRatio Goodie Re: #2767

---

lib/DDG/Goodie/NoteFrequency.pm
t/NoteFrequency.t

Updates NoteFrequency Re: #2767
Maintainer: @sublinear
https://duck.co/ia/view/note_frequency

NoteFrequency: Update to full template

---

share/goodie/cheat_sheets/json/curl.json

Resolves https://github.com/duckduckgo/zeroclickinfo-goodies/pull/2665
IA Page: https://duck.co/ia/view/curl_cheat_sheet

Improve curl cheatsheet

---

share/goodie/cheat_sheets/json/language/dothraki.json

@GuiltyDolphin
---
Instant Answer Page: https://duck.co/ia/view/dothraki_cheat_sheet
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @varundey

Dothraki Cheat Sheet: Update aliases per #2967

---

share/goodie/cheat_sheets/json/ftp.json

https://duck.co/ia/view/ftp_cheat_sheet

New FTP Cheat Sheet

---

share/goodie/cheat_sheets/json/r.json

Replaces `global` with `deep` in description of this assignment operator: `<<-`
Fixes #2947 - clarifies the relevant `environment()`
ref: http://adv-r.had.co.nz/Environments.html
@GuiltyDolphin @cosi1
---
Instant Answer Page: http://duck.co/ia/view/r_cheat_sheet 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @laurenancona

R Cheat Sheet: Fix #2947

---

share/goodie/cheat_sheets/json/language/greek.json

(Partially) #2967 
---
Instant Answer Page: https://duck.co/ia/view/{{ID}}

Updaded aliases as per #2967

---

share/goodie/cheat_sheets/json/language/minionese.json

Update aliases
One of the tasks of #2967
---
Instant Answer Page: https://duck.co/ia/view/minionese_cheat_sheet
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): Me

Minionese Cheat Sheet: Update aliases as per #2967

---

share/goodie/cheat_sheets/json/git.json

I think it's a good idea to very briefly explain what the three stages are in git - the Git Directory, Working Directory and Staging Directory. 
n/a
---

Add in the three stages, from the git-scm site

---

share/goodie/cheat_sheets/json/git.json

The value "Undoes all commits after \[commit\], preserving changes locally" does not need escape characters (backslashes).
Issue reported on Slack, not GitHub.
Kudos to @chrissherlock for noticing.
---

Git cheatsheet: Fixed stray backslashes

---

share/goodie/cheat_sheets/json/git.json

The key-value pair was not following the standard order and it should be swapped to make it look consistent with other key-value data included on git cheatsheet JSON data.
git.JSON file modified
---

Swap key-value pair on `Three states` section of git cheatsheet

---

share/goodie/constants/constants.yml

Fixes: https://github.com/duckduckgo/zeroclickinfo-goodies/issues/2820
@momom4urice @Roysten @edgesince84 
---
Instant Answer Page: https://duck.co/ia/view/constants
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @hemanth

Constants: The Boltzmann and Stefan-Boltzman constants were confused

---

share/goodie/cheat_sheets/json/visual-studio.json

---
Instant Answer Page: https://duck.co/ia/view/visual_studio_cheat_sheet

Fix missing template type

---

share/goodie/cheat_sheets/json/language/telugu.json

Removed "english to telugu" and "basic telugu"
Fixes (partially) #2967 
---
Instant Answer Page: https://duck.co/ia/view/telugu_cheat_sheet
[Maintainer](https://github.com/roxxup): @roxxup

Telugu Cheat Sheet: Removed "english to telugu" and "basic telugu" aliases

---

share/goodie/cheat_sheets/json/finnish.json
share/goodie/cheat_sheets/json/high-valyrian.json
share/goodie/cheat_sheets/json/language/kannada.json
share/goodie/cheat_sheets/json/language/spanish.json
share/goodie/cheat_sheets/json/language/telugu.json

- [] Cheat Sheets: **`New {Cheat Sheet Name} Cheat Sheet`**
Fixes #2967 - Updated aliases
---
Instant Answer Page: https://duck.co/ia/view/finnish_cheat_sheet 
Instant Answer Page: https://duck.co/ia/view/high_valyrian_cheat_sheet 
Instant Answer Page: https://duck.co/ia/view/kannada_cheat_sheet 
Instant Answer Page: https://duck.co/ia/view/spanish_cheat_sheet 
Instant Answer Page: https://duck.co/ia/view/telugu_cheat_sheet 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @riqpe 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @siddhanjay …

Multiple CheatSheet: Updated aliases as per #2967

---

share/goodie/cheat_sheets/json/zfs.json

Provide an overview of common zfs commands. Tested on codio.com with the duckpan server.
Fixes #3020 - how specifically does it fix the issue?
---
Instant Answer Page: https://duck.co/ia/view/zfs_cheat_sheet
Maintainer: @s7nio

Create cheat sheet for zfs

---

share/goodie/cheat_sheets/json/logarithms.json

Added a couple of aliases as well.
---
https://duck.co/ia/view/logarithms_cheat_sheet
Maintainer: @poornagurram

Logarithms cheatsheet: Fixed description

---

share/goodie/cheat_sheets/json/zfs.json

Update the description of the zfs cheat sheet
---
Instant Answer Page: https://duck.co/ia/view/zfs_cheat_sheet
Maintainer: @s7nio

Update the description of the zfs cheat sheet

---

lib/DDG/Goodie/ValarMorghulis.pm
t/ValarMorghulis.t

Updates ValarMorghulis Goodie to use full template. For #2767.
---
Instant Answer Page: https://duck.co/ia/view/valar_morghulis
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @engvik

ValarMorghulis: Convert to full template

---

lib/DDG/Goodie/CountryCodes.pm
t/CountryCodes.t

Goodies have full support for templates, and it'd be great
to make sure that all goodies use full templates.
The "simple structured_answer" was provided as a temporary
workaround.
* change to 'text' template for structured_answer object
* refactored test suite
See also: Updates CountryCodes Goodie Re: #2767
---
Instant Answer Page: https://duck.co/ia/view/country_codes
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @killerfish

Convert CountryCodes to full template goodie

---

share/goodie/cheat_sheets/json/emacs-evil-mode.json

---
https://duck.co/ia/view/emacs_evil_mode_cheat_sheet

added cheat sheet for evil-mode for emacs

---

share/goodie/cheat_sheets/json/backbone-js.json

Update IA ID and aliases
Fixes https://github.com/duckduckgo/zeroclickinfo-goodies/issues/3024
---
Instant Answer Page: https://duck.co/ia/view/backbone_js_cheat_sheet 

BackboneJS CheatSheet: Update IA ID and aliases

---

share/goodie/cheat_sheets/json/c.json

Re arranged the operators in their separate sections to match the order of precedence.
No issues
@tagawa 
---
Instant Answer Page: https://duck.co/ia/view/c_cheat_sheet

C cheat sheet: Re-arranged operators according to precedence (fixes #2938)

---

lib/DDG/Goodie/RandomNumber.pm
t/RandomNumber.t

Goodies have full support for templates, and it'd be great to
make sure all Goodies use full templates.
The "simple structured_answer" was provided as a temporary
workaround.
* change to 'text' template for structured_answer object
* refactored test suite
See also: Updates RandomNumber Goodie Re: #2767
---
Instant Answer Page: https://duck.co/ia/view/random_number

Convert RandomNumbers to full template goodie

---

t/RandomNumber.t

Fixes a rogue test.
---
Instant Answer Page: https://duck.co/ia/view/random_number
Wasn't allowing the case for numbers like `1.3e-7`.

RandomNumber: Fix test for real numbers

---

share/goodie/cheat_sheets/json/youtubedl.json

IA : [youtube-dl](https://duck.co/ia/view/youtube_dl_cheat_sheet)

New youtube-dl cheat sheet

---

share/goodie/cheat_sheets/json/wget.json

IA : [Wget Cheat sheet](https://duck.co/ia/view/wget_cheat_sheet)

New wget Cheat sheet

---

lib/DDG/Goodie/TitleCase.pm
t/TitleCase.t

---
Instant Answer Page: https://duck.co/ia/view/title_case
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @moollaza (you're the maintainer on this!?)

Titlecase: Converting to text template

---

lib/DDG/Goodie/Lowercase.pm
t/Lowercase.t

Ref: #2767
---
Instant Answer Page: https://duck.co/ia/view/lowercase
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @DavidMascio

Lowercase: Flipping out to Text template

---

lib/DDG/Goodie/Uppercase.pm
t/Uppercase.t

---
Instant Answer Page: https://duck.co/ia/view/uppercase
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @gdrooid

Uppercase: Converting to text template

---

lib/DDG/Goodie/Combination.pm
t/Combination.t

ref: https://github.com/duckduckgo/zeroclickinfo-goodies/issues/2767
---
Instant Answer Page: https://duck.co/ia/view/combination
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @richardscollin

Combination: Switching to text template

---

lib/DDG/Goodie/POTUS.pm
t/POTUS.t

In ref to: https://github.com/duckduckgo/zeroclickinfo-goodies/issues/2767 switching out to use the text template
Instant Answer Page: https://duck.co/ia/view/potus
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @numbertheory

POTUS: Flipping out to text template

---

share/goodie/cheat_sheets/json/css.json

There was a typo on css cheatsheet and this should be fixed.
See also: #2937
---
Instant Answer Page: https://duck.co/ia/view/css_cheat_sheet
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @ethanchewy

Fix typo on css cheatsheet

---

lib/DDG/Goodie/HexToDec.pm
t/HexToDec.t

---
Instant Answer Page: https://duck.co/ia/view/hex_to_dec
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @majuscule

HexToDec: Converting to text template

---

lib/DDG/Goodie/Factors.pm
t/Factors.t

---
Instant Answer Page: https://duck.co/ia/view/factors
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @austinheimark

Factors: Converting to text template

---

lib/DDG/Goodie/Fortune.pm
t/Fortune.t

---
Instant Answer Page: https://duck.co/ia/view/fortune
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @frncscgmz

Fortune: Switching to text template

---

lib/DDG/Goodie/GenerateMAC.pm
t/GenerateMAC.t

REF: https://github.com/duckduckgo/zeroclickinfo-goodies/issues/2767
---
Instant Answer Page: https://duck.co/ia/view/generate_mac
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @UnGround

GenerateMAC: Switching to text template

---

lib/DDG/Goodie/LeetSpeak.pm
t/LeetSpeak.t

---
Instant Answer Page: https://duck.co/ia/view/leet_speak

LeetSpeak: Converting to Text Template

---

lib/DDG/Goodie/ConvertLatLon.pm
t/ConvertLatLon.t

---
Instant Answer Page: https://duck.co/ia/view/convert_lat_lon
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @wilkox

ConvertLatLon: Switching to text template

---

lib/DDG/Goodie/HelpLine.pm
t/HelpLine.t

---
Instant Answer Page: https://duck.co/ia/view/help_line
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @conorfl

HelpLine: Switching to text template

---

share/goodie/cheat_sheets/json/c-sharp-snippets.json

Added Valid locations to insert snippet
@tagawa and @edgesince84
---
Instant Answer Page: https://duck.co/ia/view/c_sharp_snippets_cheat_sheet
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @Khalimov

C# cheat sheet: added Valid locations to insert snippet (Fixes #2936)

---

lib/DDG/Goodie/MD4.pm
t/MD4.t

---
Instant Answer Page: https://duck.co/ia/view/md4

MD4: Converting to text template

---

lib/DDG/Goodie/Coin.pm
t/Coin.t

I updated a regex to accept 'coin flip'
Fixes #2646 - how specifically does it fix the issue?
@stevenmg 
---
Instant Answer Page: https://duck.co/ia/view/coin
Updated a regular expression that sets the number of coins to flip.
Now it will accept 'coin flip' and then flip 1 coin.

Coin: Triggers on 'coin flip'

---

lib/DDG/Goodie/MD5.pm
t/MD5.t

---
Instant Answer Page: https://duck.co/ia/view/md5
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @jarmokivekas

MD5: Converting to text template

---

share/goodie/cheat_sheets/json/bash.json

Full description of Parameter Expansion features was missing (substring replacement, extraction, deletion).
PS: I've just discovered the dev side of DDG. I love you <3

Added string manipulation Parameter Expansion to Bash cheat sheet

---

lib/DDG/Goodie/Weight.pm
t/Weight.t

Updates Weight Goodie to use the full template. Re: #2767 
---
Instant Answer Page: https://duck.co/ia/view/weight
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @wongalvis

Weight: Convert to full template

---

lib/DDG/Goodie/MoonPhases.pm
t/MoonPhases.t

---
Instant Answer Page: https://duck.co/ia/view/moon_phases

Moon Phases: Convert to structured answer

---

lib/DDG/Goodie/Morse.pm
t/Morse.t

ref: https://github.com/duckduckgo/zeroclickinfo-goodies/issues/2767
---
Instant Answer Page: https://duck.co/ia/view/morse
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @und3f

Morse: Converting to text template

---

lib/DDG/Goodie/Fibonacci.pm
t/Fibonacci.t

I've also extended the test coverage around question formats that were previously untested
---
Instant Answer Page: https://duck.co/ia/view/fibonacci
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @koosha--

Fibonacci: Converting to Text Template

---

lib/DDG/Goodie/ISO639.pm
t/ISO639.t

REF: https://github.com/duckduckgo/zeroclickinfo-goodies/issues/2767
---
Instant Answer Page: https://duck.co/ia/view/iso639
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @tantalor

ISO639: Converting to text template

---

lib/DDG/Goodie/PaleoIngredientCheck.pm
t/PaleoIngredientCheck.t

---
Instant Answer Page: https://duck.co/ia/view/paleo_ingredient_check
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @javathunderman

PaleoIngredientCheck: Converting to text template

---

share/goodie/cheat_sheets/json/javaserver-pages.json

Cheat Sheet for JSP basics.
IA Page: https://duck.co/ia/view/javaserver_pages_cheat_sheet

New JavaServer Pages Cheat Sheet

---

share/goodie/cheat_sheets/json/haxe/haxe-operators.json
share/goodie/cheat_sheets/json/haxe/haxe-ops.json

IA: https://duck.co/ia/view/haxe_operators

New Haxe Operators Cheat Sheet

---

lib/DDG/Goodie/CheatSheets.pm

The 'grep' method was only working for single word ignores, so unless we
can get that working it looks like a regex is our best bet?
@zachthompson 
---
Instant Answer Page: https://duck.co/ia/view/cheat_sheets
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @zachthompson

CheatSheets: Ensure multi-word ignores are processed correctly

---

lib/DDG/Goodie/Wavelength.pm
t/Wavelength.t

---
Instant Answer Page: https://duck.co/ia/view/wavelength
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @nebulous

WaveLength: Switching to text template

---

lib/DDG/Goodie/Reverse.pm
t/Reverse.t

---
Instant Answer Page: https://duck.co/ia/view/reverse

Reverse: Converting to text template

---

lib/DDG/Goodie/Rafl.pm
t/Rafl.t

---
Instant Answer Page: https://duck.co/ia/view/rafl
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @Hercynium

Rafl: Switching to text template

---

lib/DDG/Goodie/RIPEMD.pm
t/RIPEMD.t

ref: https://github.com/duckduckgo/zeroclickinfo-goodies/issues/2767
---
Instant Answer Page: https://duck.co/ia/view/ripemd

RIPEMD: Converting to text template

---

lib/DDG/Goodie/PhoneAlphabet.pm
t/PhoneAlphabet.t

---
Instant Answer Page: https://duck.co/ia/view/phone_alphabet
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @stevelippert

PhoneAlphabet: Converting to text template

---

lib/DDG/Goodie/Roman.pm
t/Roman.t

---
Instant Answer Page: https://duck.co/ia/view/roman
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @mrshu

Roman: Switching to text template

---

lib/DDG/Goodie/Scramble.pm
t/Scramble.t

---
Instant Answer Page: https://duck.co/ia/view/scramble
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @Mailkov

Scramble: Switching to text template

---

lib/DDG/Goodie/Paper.pm
t/Paper.t

---
Instant Answer Page: https://duck.co/ia/view/paper

Paper: Converting to text template

---

lib/DDG/Goodie/Passphrase.pm
t/Passphrase.t

---
Instant Answer Page: https://duck.co/ia/view/passphrase
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @hunterlang

Passphrase: Converting to text template

---

lib/DDG/Goodie/WeekdaysBetween.pm
t/WeekdaysBetween.t

Updates WeekdaysBetween Goodie to use full template. Re: #2767 
---
Instant Answer Page: https://duck.co/ia/view/weekdays_between
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @syst3mw0rm

WeekdaysBetween: Convert to full template

---

lib/DDG/Goodie/Rot13.pm
t/Rot13.t

---
Instant Answer Page: https://duck.co/ia/view/rot13
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @unlisted

Rot13: Converting to text template

---

lib/DDG/Goodie/WorkdaysBetween.pm
t/WorkdaysBetween.t

Updates WorkdaysBetween to use the full template. Re: #2767 
---
Instant Answer Page: https://duck.co/ia/view/workdays_between
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @mgarriott

WorkdaysBetween: Convert to full template

---

lib/DDG/Goodie/DuckDuckGo.pm
share/goodie/duck_duck_go/responses.yml
t/DuckDuckGo.t

DDG::Goodie::DuckDuckGo: Initial DNS delegation explanation.

DDG::Goodie::DuckDuckGo: Initial DNS delegation explanation.

---

share/goodie/cheat_sheets/json/classic-cocktails.json

Just 3 more cocktails that were, sadly, missed on the first PR
IA page: https://duck.co/ia/view/classic_cocktails_cheat_sheet

Classic cocktails: More cocktails

---

lib/DDG/Goodie/Sort.pm
t/Sort.t

---
Instant Answer Page: https://duck.co/ia/view/sort
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @koosha--

Sort: Convert to text template

---

lib/DDG/Goodie/PercentOf.pm
t/PercentOf.t

@NaveenKarippai 
---
Instant Answer Page: https://duck.co/ia/view/percent_of
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @puskin94

PercentOf: Switching to text template

---

lib/DDG/Goodie/Week.pm
t/Week.t

---
Instant Answer Page: https://duck.co/ia/view/week
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @gsquire

Week: Switching to text template

---

lib/DDG/Goodie/TwelveOclock.pm
t/TwelveOclock.t

---
Instant Answer Page: https://duck.co/ia/view/twelve_oclock
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @stevenmg

TwelveOclock: Switching to text template

---

lib/DDG/Goodie/Coin.pm
t/Coin.t

As eluded to in https://github.com/duckduckgo/zeroclickinfo-goodies/pull/2966 I've just finished off the conversion to templates
@dbech 
---
Instant Answer Page: https://duck.co/ia/view/coin

Coin: Switching to text template

---

lib/DDG/Goodie/TimezoneConverter.pm
t/TimezoneConverter.t

---
Instant Answer Page: https://duck.co/ia/view/timezone_converter
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @GlitchMr

TimezoneConverter: Switching to text template

---

lib/DDG/Goodie/ParseCron.pm
t/ParseCron.t

---
Instant Answer Page:https://duck.co/ia/view/parse_cron
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @IndelibleStamp

ParseCron: Switching to text template

---

lib/DDG/Goodie/SHA3.pm
t/SHA3.t

---
Instant Answer Page: https://duck.co/ia/view/sha3

SHA3: Switching to text template

---

lib/DDG/Goodie/MagicEightBall.pm
t/MagicEightBall.t

---
Instant Answer Page: https://duck.co/ia/view/magic_eight_ball
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @jlbaez

MagicEightBall: Converting to text template

---

lib/DDG/Goodie/MagicEightBall.pm
t/MagicEightBall.t

Fix MagicEightBall tests

---

lib/DDG/Goodie/Kana.pm
t/Kana.t

---
Instant Answer Page: https://duck.co/ia/view/kana
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @hradecek

Kana: Updating to the text template

---

lib/DDG/Goodie/DateMath.pm
t/DateMath.t

Added forms like `3 days before today`, `4 weeks after 3rd Jan` etc...
------
IA Page:  http://duck.co/ia/view/date_math 

DateMath: Add before/after forms

---

share/goodie/cheat_sheets/json/lxde.json

Adds a cheat sheet for the LXDE desktop
Instant Answer Page: https://duck.co/ia/view/lxde_cheat_sheet

New LXDE cheat sheet

---

lib/DDG/Goodie/Password.pm
t/Password.t

@NaveenKarippai 
---
Instant Answer Page: https://duck.co/ia/view/password

Password: Switching to text template

---

lib/DDG/Goodie/HTMLEntitiesDecode.pm
t/HTMLEntitiesDecode.t

In reference to: #2767 ; I've not tested it in `duckpan server` yet as I can't run it from my current location.
--------------------------------
Instant Answer Page: https://duck.co/ia/view/htmlentities_decode
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @nishanths

HTMLEntitiesDecode: Converting to Text Template

---

share/goodie/cheat_sheets/json/neko/neko-std.json

IA: https://duck.co/ia/view/neko_std_cheat_sheet

New Neko Standard Library Cheat Sheet

---

share/goodie/cheat_sheets/json/cashjs.json

- [ X] New Instant Answer
- [X ] Cheat Sheets: **`New Cashjs Cheat Sheet`**
A new cheat sheet for Cashjs (or simply Cash), a absurdly small JavaScript library similar to jQuery.
---
Instant Answer Page: https://duck.co/ia/view/cashjs_cheat_sheet
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @bernardodsanderson

New Cashjs Cheat Sheet

---

lib/DDG/Goodie/Shuffle.pm
t/Shuffle.t

Shuffle 'dem lists!
---
Instant Answer Page: https://duck.co/ia/view/shuffle

New Shuffle Instant Answer

---

share/goodie/cheat_sheets/json/notepad-plus-plus.json

Adds new Notepad++ Cheat Sheet
---
Instant Answer Page: https://duck.co/ia/view/notepad_plus_plus_cheat_sheet
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @biscuitNinja

New Notepad_plus_plus Cheat Sheet 

---

share/goodie/cheat_sheets/json/atom.json

What I did ? 
Replaced Up arrow and Down arrow strings with their ASCII code.
Added brackets around or terms. 
https://duck.co/ia/view/atom_cheat_sheet
Maintainer: @typo

Atom : Replaced Uparrow string with its ASCII code

---

share/goodie/cheat_sheets/json/language/german.json

---
Instant Answer Page: https://duck.co/ia/view/german_cheat_sheet
Rechtschreibung und Zeichensetzung verbessert.
Spelling and punctuation improved.

German Cheat Sheet: corrections in german strings

---

share/goodie/cheat_sheets/json/language/esperanto.json

- [* ] Cheat Sheets: **`New Esperanto Cheat Sheet`**
Provides a cheat sheet for the Esperanto language.
Instant Answer Page: https://duck.co/ia/view/esperanto_cheat_sheet
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @abadojack

Create new Esperanto cheat sheet

---

lib/DDG/Goodie/DaysBetween.pm
t/DaysBetween.t

Goodies have full support for templates, and it'd be great
to make sure all Goodies use full templates.
The "simple structured_answer" was provided as a temporary
workaround.
* change to 'text' template for structured_answer object
* refactored test suite
Re: #2767
---
Instant Answer Page: https://duck.co/ia/view/days_between
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @JetFault

Convert DaysBetween to full template goodie

---

share/goodie/cheat_sheets/json/rust-types.json

Added floating point types f32 and f64 under Machine types.
Fixes #2952
@lambda @tagawa 
---
Instant Answer Page: https://duck.co/ia/view/rust_types_cheat_sheet
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @NateBrune

rust types : added floating point types

---

lib/DDG/Goodie/Conversions.pm
t/Conversions.t

Conversions: Hack tweaks for #3160

---

lib/DDG/Goodie/EmailValidator.pm
t/EmailValidator.t

@lamanh 
---
Instant Answer Page: https://duck.co/ia/view/email_validator
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @stelim

EmailValidator: Switching to text template

---

share/goodie/cheat_sheets/json/objective-c.json

Add Objective-C programming language cheat sheet
---
Instant Answer Page: https://duck.co/ia/view/objective_c_cheat_sheet
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @qqq3

New Objective-C Cheat Sheet

---

share/goodie/cheat_sheets/json/java.json

Fixes #1816
* Remove `0x00ad` values from text
* Replace multiple `&nbsp;` with `\t`
* Fix minor typo
Instant Answer Page: https://duck.co/ia/view/java_cheat_sheet

Fix #1816 Replace <br> with linebreaks in java cheatsheet

---

share/goodie/cheat_sheets/json/vim.json

Some day-to-day commands in vim like screen movement section and
window-related subcommands were not added in the cheatsheet.
* description of cheatsheet modified
* screen movement section added
* window-related and other subcommands added/modified
---
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @kablamo

Modify vim cheatsheet

---

share/goodie/cheat_sheets/json/linux.json

There would be users who might search for aliases such as
gnu linux cheatsheet. so, aliases would be necessary meta-data
to this cheatsheet. There could also be minor modifications to some
commands listed.
* alias meta-data added
* description and title modified
* commands modified
---
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @crashrane

Tweak linux cheatsheet

---

share/goodie/cheat_sheets/json/language/german.json

The alias of german is deutsch. This would help users
who query for alias to trigger the cheatsheet.
* alias data added for cheatsheet
---
Instant Answer Page: https://duck.co/ia/view/german_cheat_sheet
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @AdamSC1-ddg

Add alias for german cheatsheet

---

share/goodie/cheat_sheets/json/opencv-python.json

https://duck.co/ia/view/opencv_python_cheat_sheet

OpenCV Python: Break up code at Rotation

---

share/goodie/cheat_sheets/json/neko/neko-operators.json
share/goodie/cheat_sheets/json/neko/neko-ops.json

IA: https://duck.co/ia/view/neko_operators

New Neko Operators Cheat Sheet

---

share/goodie/cheat_sheets/json/neko/neko-cli.json

IA: https://duck.co/ia/view/neko_cli_cheat_sheet

New Neko Console Commands  Cheat Sheet

---

share/goodie/cheat_sheets/json/golang.json

Fixes https://github.com/duckduckgo/zeroclickinfo-goodies/issues/2257
IA Page: https://duck.co/ia/view/golang_cheat_sheet
Maintainer: @MsPseudolus

Correct formatting

---

share/goodie/cheat_sheets/json/elm.json

Introduces the cheat sheet for the Elm programming language.
**Screenshot 1**
**Screenshot 2**
---
Instant Answer Page: https://duck.co/ia/view/elm_cheat_sheet
[Maintainer](https://github.com/pjhampton): @pjhampton

New Elm Cheat Sheet

---

share/goodie/cheat_sheets/json/indian-spices.json

https://duck.co/ia/view/indian_spices_cheat_sheet
Maintainer: @shahbaz17

Add more spices into indian spices cheatsheet

---

share/goodie/cheat_sheets/json/vim.json

There were some minor typos and uncertain symbols used
on cheatsheet' JSON data. This could confuse the user.
* refactored JSON data
Related: PR https://github.com/duckduckgo/zeroclickinfo-goodies/pull/3071
---
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @kablamo

vim_cheat_sheet: Refactor vim cheatsheet json data

---

share/goodie/cheat_sheets/cheat_sheets.css

This PR fixes https://github.com/duckduckgo/zeroclickinfo-goodies/issues/2507
https://duck.co/ia/view/cheat_sheets

Cheat Sheets: fix css issue

---

share/goodie/cheat_sheets/json/nodejs.json

The nodejs cheatsheet does not trigger for query
`node.js`. This could be fixed by adding alias
meta-data on json file.
* added alias meta-data for cheatsheet
* triggers for `node.js` query
See also: #3116
---
Instant Answer Page: https://duck.co/ia/view/nodejs_cheat_sheet
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @stanly-johnson

Add alias meta-data to nodejs cheatsheet

---

share/goodie/cheat_sheets/json/indian-spices.json

https://duck.co/ia/view/indian_spices_cheat_sheet

Indian Spices Names fixed suggested changes

---

share/goodie/cheat_sheets/json/vim.json

The key-value data presentation on json data in vim_cheatsheet
goodie should be modified to follow Doc guidelines.
* refactored json data
---
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @NaveenKarippai

vim_cheat_sheet: Modify json data to follow doc guidelines

---

share/goodie/cheat_sheets/json/language/esperanto.json

- [* ] Improvement
- [* ] Enhancement: **`Esperanto cheat sheet: Correct grammatical errors`**
Corrects grammatical errors in the current cheat sheet.
---
Instant Answer Page: https://duck.co/ia/view/esperanto_cheat_sheet
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @abadojack

Esperanto cheat sheet: Correct grammatical errors

---

t/CalendarConversion.t

Ref: #3121
@mintsoft 
---
Instant Answer Page: https://duck.co/ia/view/calendar_conversion

CalendarConversion: Update Role tests

---

lib/DDG/Goodie/AltCalendars.pm
share/goodie/alt_calendars/definitions.json
t/AltCalendars.t

Triggers and calendar metadata now come from a JSON file so that additional calendar conversions can be added easily and more reliably. I also added some new calendars I found while searching through wikipedia.
https://duck.co/ia/view/alt_calendars
Maintainer: **_NONE_**

Improvements to AltCalendars IA

---

lib/DDG/Goodie/URLDecode.pm
t/URLDecode.t

Fixes https://github.com/duckduckgo/zeroclickinfo-goodies/issues/3202
---
Instant Answer Page: https://duck.co/ia/view/urldecode

URLDecode: should trigger with uri as well as url

---

share/goodie/cheat_sheets/json/webstorm-mac.json
share/goodie/cheat_sheets/json/webstorm.json

My IA Page: [IA Page](https://duck.co/ia/view/webstorm_mac_cheat_sheet)
A Cheat Sheet for [Webstorm](https://www.jetbrains.com/webstorm/) Shortcuts.
The Shortcuts are for Mac Users.
-
Instant Answer Page: https://duck.co/ia/view/webstorm_mac_cheat_sheet
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @universeofsolutions
https://duck.co/ia/view/webstorm_mac_cheat_sheet

New Webstorm Mac Cheat Sheet

---

share/goodie/cheat_sheets/json/evernote.json

Adds a new cheat sheet for Evernote keyboard shortcuts
https://duck.co/ia/view/evernote_cheat_sheet
---
Instant Answer Page: https://duck.co/ia/view/evernote_cheat_sheet
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @mention @smitche60

New Evernote Cheat Sheet

---

lib/DDG/Goodie/Rc4.pm
t/Rc4.t

---
Instant Answer Page: https://duck.co/ia/view/rc4
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @puskin94

RC4: Converting to text template

---

lib/DDG/Goodie/Jira.pm
share/goodie/jira/content.handlebars
t/Jira.t

REF: https://github.com/duckduckgo/zeroclickinfo-goodies/issues/2767
---
Instant Answer Page: https://duck.co/ia/view/jira
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @arroway

JIRA: Switching to info template

---

lib/DDG/Goodie/MacAddress.pm
share/goodie/mac_address/content.handlebars
t/MacAddress.t

ref: https://github.com/duckduckgo/zeroclickinfo-goodies/issues/2767
---
Instant Answer Page: https://duck.co/ia/view/mac_address
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @mogigoma

MacAddress: Convert to template

---

share/goodie/cheat_sheets/json/csharp.json

---
Instant Answer Page: https://duck.co/ia/view/csharp_cheat_sheet
---
https://duck.co/ia/view/csharp_cheat_sheet

Added cheatsheet for csharp

---

lib/DDG/Goodie/CoffeeToWaterRatio.pm
t/CoffeeToWaterRatio.t

Re: #2767
Finishing off https://github.com/duckduckgo/zeroclickinfo-goodies/pull/2819 Thanks @lamanh for the work!
---
Instant Answer Page: https://duck.co/ia/view/coffee_to_water_ratio
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @nickselpa

CoffeeToWaterRatio: Convert to Full Template

---

lib/DDG/Goodie/Stopwatch.pm
share/goodie/stopwatch/stopwatch.css
share/goodie/stopwatch/stopwatch.handlebars
share/goodie/stopwatch/stopwatch.js
t/Stopwatch.t

Porting Issue: https://github.com/duckduckgo/zeroclickinfo-spice/issues/2463
Deleting PR: https://github.com/duckduckgo/zeroclickinfo-spice/pull/2665
https://duck.co/ia/view/goodie

Port Stopwatch to Goodies

---

t/ChordDiagrams.t
t/EmailValidator.t

In Ref to: https://github.com/duckduckgo/duckduckgo/pull/194#issuecomment-224994104
---

Switching to Test::Deep for Email Validator and ChordDiagrams

---

share/goodie/conversions/ratios.yml
t/Conversions.t

Fixes https://github.com/duckduckgo/zeroclickinfo-goodies/issues/3221
@edgesince84 
---

Conversions: Improving accuracy of the US Gallon/Cubic Inch

---

share/goodie/cheat_sheets/json/xamarin.json

Added Xamarin Studio Cheat Sheet
---
Instant Answer Page: https://duck.co/ia/view/xamarin_cheat_sheet
---
https://duck.co/ia/view/xamarin_cheat_sheet

Added Xamarin Studio Cheat Sheet

---

share/goodie/cheat_sheets/json/tmux.json

Fixed source URL.
Fixes #3240 - updates source URL.
https://duck.co/ia/view/tmux_cheat_sheet

fixed tmux url (issue #3240)

---

t/Game2048.t

---
Instant Answer Page: https://duck.co/ia/view/game2048
This one was merged *after* the DuckDuckGo changes.

Game2048: Update tests to use Test::Deep

---

share/goodie/cheat_sheets/json/c-char-manipulation.json

This pull request adds `toascii` to the C Character Manipulation Cheatsheet. There were some other methods mentioned in the [source](http://www.gnu.org/software/libc/manual/html_mono/libc.html) but are not part of `ctype.h`. Please share your thoughts on this.
None
---
Instant Answer Page: https://duck.co/ia/view/c_char_manipulation_cheat_sheet
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): 
@lemueldsouza

C char manipulation update

---

share/goodie/cheat_sheets/json/minecraft.json

Updated minecraft controls according to http://minecraft.gamepedia.com/Controls
---
Instant Answer Page: https://duck.co/ia/view/minecraft_cheat_sheet
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @therealkbhat

Minecraft cheat sheet: update controls

---

share/goodie/cheat_sheets/json/notepad-plus-plus.json

Correction of minor formatting issue
Fixes #3254 - Reformats single key shortcuts to remove square brackets
---
Instant Answer Page: http://duck.co/ia/view/notepad_plus_plus_cheat_sheet
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @biscuitNinja

Fix 'boxing' of some shortcut key combinations

---

share/goodie/cheat_sheets/json/lxde.json

Seeing a warning message in the recent builds refering to this cheat sheet I tried to fix it.
---
Instant Answer Page: https://duck.co/ia/view/lxde_cheat_sheet
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @benabrahamson

Lxde Cheat Sheet: added spacing

---

share/goodie/cheat_sheets/json/greensock.json

---
Instant Answer Page: https://duck.co/ia/view/greensock_cheat_sheet

greensock cheat sheet created

---

share/goodie/cheat_sheets/json/c-char-manipulation.json

---
Instant Answer Page: https://duck.co/ia/view/c_char_manipulation_cheat_sheet
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @lemueldsouza

CCharManipulationCheatSheet: Remove trailing whitespaces

---

share/goodie/cheat_sheets/json/cpp-strings.json

Currently C++ Strings Cheat Sheet is of Template Type `code` which is making it unreadable on DuckDuckGo. This pull request changes its type to `reference` to make it more readable. Screenshots attached.
**Before**
**After**
None
---
Instant Answer Page: https://duck.co/ia/view/cpp_strings_cheat_sheet
@gohar94

Makes C++ Strings Cheat Sheet visually more readable

---

share/goodie/cheat_sheets/json/nano.json

Introduce a new cheat sheet of the nano editor.
---
Instant Answer Page: https://duck.co/ia/view/nano_cheat_sheet
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @N0vaPixel

New Nano editor Cheat Sheet

---

share/goodie/cheat_sheets/json/cpp-complex.json

This pull request adds C++ <complex> library cheat sheet for reference.
None
---
Instant Answer Page: https://duck.co/ia/view/cpp_complex_cheat_sheet
None

C++ <complex> Number Cheat Sheet

---

share/goodie/cheat_sheets/json/virtual-box.json

Virtual box cheatsheet continuing #2214
---
Instant Answer Page: https://duck.co/ia/view/virtual_box_cheat_sheet

Create virtual-box cheatsheet

---

share/goodie/cheat_sheets/json/duckduckgo.json

According to cheathseet guidelines, we don't need extra paranthesis
enclosing each json "value". The unnecessary paranthesis could be removed
to make the cheatsheet more readable.
* cleaned up cheathseet according to docs guidelines 
Fixes: #3141 
---
Instant Answer Page: https://duck.co/ia/view/duckduckgo_cheat_sheet
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @Qeole

DDG_cheat_sheet: Remove unnecessary paranthesis on json data

---

share/goodie/sha3/sha3.css

Fixes https://github.com/duckduckgo/zeroclickinfo-goodies/issues/3147 - 
@moollaza @MariagraziaAlastra 
---
Instant Answer Page: https://duck.co/ia/view/sha3

SHA3: Adding break-all

---

share/goodie/fibonacci/fibonacci.css

#3215 was missing a CSS file to allow wrapping for long Fibonacci numbers. 
Fixes #3215, #3068 - Additional CSS file to allow wrapping for long Fibonacci numbers.
@moollaza 
---
Instant Answer Page: https://duck.co/ia/view/fibonacci
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @koosha--

Added css to break lines for long Fibonacci numbers.

---

lib/DDG/Goodie/DurationCalculator.pm
t/DurationCalculator.t

Add a new IA to answer queries asking for addition or subtraction of two time quantities.
---
Instant Answer Page: https://duck.co/ia/view/duration_calculator

Add Duration Calculator

---

share/goodie/cheat_sheets/json/xamarin.json

Fixes #3266
---
Instant Answer Page: http://duck.co/ia/view/xamarin_cheat_sheet
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @gitcodes

Update xamarin cheatsheet:fixes #3266

---

lib/DDG/Goodie/HelpLine.pm
t/HelpLine.t

There should be more tests cases added to the suite for code coverage.
PR https://github.com/duckduckgo/zeroclickinfo-goodies/pull/3096 was merged before completion of test suite and it has to be completed.
* test cases added
Related to: PR https://github.com/duckduckgo/zeroclickinfo-goodies/pull/3096
---
Instant Answer Page: https://duck.co/ia/view/help_line
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @conorfl

HelpLine: Add test cases to the suite 

---

share/goodie/cheat_sheets/json/duckduckgo-syntax.json

- Removed unnecessary triggers generating warnings because `syntax` is already defined in `code` template
- Added new triggers
---
Instant Answer Page: https://duck.co/ia/view/duckduckgo_syntax_cheat_sheet

DDGSyntaxCheatSheet: Improve triggering

---

share/goodie/cheat_sheets/json/ajax.json

Add overview of different terms associated with AJAX
---
Instant Answer Page: https://duck.co/ia/view/ajax_cheat_sheet

New AJAX Cheat Sheet

---

share/goodie/cheat_sheets/json/apache-pig.json
share/goodie/cheat_sheets/json/cassandra.json
share/goodie/cheat_sheets/json/csharp.json
share/goodie/cheat_sheets/json/java-file-handling.json
share/goodie/cheat_sheets/json/multisim.json
share/goodie/cheat_sheets/json/nasm.json
share/goodie/cheat_sheets/json/ocaml.json
share/goodie/cheat_sheets/json/rails-devops.json
share/goodie/cheat_sheets/json/redhat.json
share/goodie/cheat_sheets/json/sas.json
share/goodie/cheat_sheets/json/vscode.json
share/goodie/cheat_sheets/json/youtubedl.json

Fixes some warnings in Travis CI Builds.
Cheat sheets: apache-pig, cassandra, csharp, java-file-handling, multisim, nasm, ocaml, rails-devops, Redhat, sas, vscode and youtubedl.

Trailing whitespaces fix

---

lib/DDG/Goodie/BirthStone.pm
t/BirthStone.t

Clean up after recent commits.
---
Instant Answer Page: https://duck.co/ia/view/birth_stone
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @austinheimark 
- Fixed white space
- Improved use of Perl idioms

BirthStone: Clean up

---

share/goodie/cheat_sheets/json/language/swahili.json

- [* ] New Instant Answer
- [ *] Cheat Sheets: **`New Swahili Cheat Sheet`**
Creates new Swahili cheat sheet.
---
Instant Answer Page: https://duck.co/ia/view/swahili_cheat_sheet

New Swahili Cheat Sheet

---

share/goodie/cheat_sheets/json/virtual-box.json

- [ .] Improvement
- [.] Enhancement: **`virtual box cheat sheet: Add source`**
The cheat sheet does not have a source. This PR adds a source to the existing cheat sheet.
@gautamkrishnar @zekiel 
---
Instant Answer Page: https://duck.co/ia/view/virtual_box_cheat_sheet

virtual box cheat sheet: Add source

---

share/goodie/cheat_sheets/json/cpp-complex.json

This pull request makes CPP Complex more verbose and readable.
None.
---
Instant Answer Page: https://duck.co/ia/view/cpp_complex_cheat_sheet
@ManrajGrover

Makes CPP Complex more verbose

---

share/goodie/cheat_sheets/json/differential.json

This pull request adds Common Differential rules and solutions Cheat Sheet.
#3270 
---
Instant Answer Page: https://duck.co/ia/view/differential_cheat_sheet
None

Differentiation rules

---

share/goodie/cheat_sheets/json/integral.json

Shows simple integrals for calculus.
Adds an instant answer for "integral cheat sheet"
---
Instant Answer Page: https://duck.co/ia/view/integral_cheat_sheet
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @chuckclift

New Integral Cheat Sheet

---

share/goodie/cheat_sheets/json/tmux.json

The cheatsheet should be refactored to follow Docs cheatsheet
guidelines with some minor modifications on commands included.
* refactored tmux cheatsheet json data
---
Instant Answer Page: https://duck.co/ia/view/tmux_cheat_sheet
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @charles-l

tmux_cheat_sheet: Refactor json data

---

share/goodie/cheat_sheets/json/cpp-strings.json

This pull request fixes CPP Strings Key Value error
None
---
Instant Answer Page: https://duck.co/ia/view/cpp_strings_cheat_sheet
@gohar94

Fixes CPP Strings Key Val error

---

share/goodie/cheat_sheets/json/cpp-deque.json

This pull request adds CPP Deque Cheat Sheet
None
---
Instant Answer Page: https://duck.co/ia/view/cpp_deque_cheat_sheet
None

C++ Deque Cheat Sheet

---

share/goodie/cheat_sheets/json/cpp-arrays.json

This pull request adds CPP Arrays Cheat Sheet
None
---
Instant Answer Page: https://duck.co/ia/view/cpp_arrays_cheat_sheet
None

C++ Arrays Cheat Sheet

---

share/goodie/cheat_sheets/json/php.json

I feel that many functions under sections PHP array functions and string functions weren't in proper order. I have sorted the functions according to their relevancy.
Fixes #3183 
---
Instant Answer Page: https://duck.co/ia/view/php_cheat_sheet 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @rathoreanirudh

PhpCheatSheet: Change order of functions according to relevancy

---

share/goodie/cheat_sheets/json/slack-formatting.json

Markdown message formatting for Slack
Hello!
I tried to pass tests via `duckpan test CheatSheets` and every time got same error `Failed test 'FAIL: No Instant Answer page found with ID 'slack_formatting_cheat_sheet'' at t/CheatSheets/CheatSheetsJSON.t line 274.` even after I create IA page with proper ID. 
What I missed? Visual test passed, cheat sheet triggers correctly and looks as I expected. 
---
Instant Answer Page: https://duck.co/ia/view/slack_formatting_cheat_sheet

New Slack Formatting Cheat Sheet

---

share/goodie/cheat_sheets/json/serbian.json

Instant Answer Page: https://duck.co/ia/view/serbian_cheat_sheet
edit: Changed the IA link.
edit2: Deleted the aliases.

New Serbian Cheat Sheet

---

share/goodie/cheat_sheets/json/ajax.json

Added more information (new section) about AJAX request ReadyState values significance.
@moollaza 
---
Instant Answer Page: https://duck.co/ia/view/ajax_cheat_sheet
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @sahildua2305

AJAXCheatSheet: Improve; add more information (new section)

---

share/goodie/cheat_sheets/json/cpp-forward-list.json

This pull request adds CPP Forward List to Instant Answers.
None
---
Instant Answer Page: https://duck.co/ia/view/cpp_forward_list_cheat_sheet
None

C++ forward list

---

t/DurationCalculator.t

Instant Answer Page: https://duck.co/ia/view/duration_calculator

Fix failing tests

---

share/goodie/cheat_sheets/json/cpp-list.json

This pull request adds CPP List IA.
None
---
Instant Answer Page: https://duck.co/ia/view/cpp_list_cheat_sheet
None

CPP List Cheat Sheet

---

share/goodie/cheat_sheets/json/cpp-arrays.json

This pull request fixes version in CPP Arrays IA description
None
None
---
Instant Answer Page: https://duck.co/ia/view/cpp_arrays_cheat_sheet
@ManrajGrover

Quick Fix: Fixes version in CPP Arrays IA

---

share/goodie/cheat_sheets/json/cpp-forward-list.json

This pull request adds version to description of CPP Forward List IA.
None
---
Instant Answer Page: https://duck.co/ia/view/cpp_forward_list_cheat_sheet
@ManrajGrover

Quick Fix: Fixes version for Forward List Library

---

share/goodie/cheat_sheets/json/ajax.json

@moollaza 
---
Instant Answer Page: https://duck.co/ia/view/ajax_cheat_sheet

AjaxCheatSheet: Minor Fix; Include full form in description

---

share/goodie/cheat_sheets/json/csgo.json

Added cheatsheet of csgo abbreviations
---
https://duck.co/ia/view/csgo_cheat_sheet

Added cheatsheet for csgo

---

share/goodie/cheat_sheets/json/cpp-forward-list.json

Changes mylist.begin() to mylist.end()
None
---
Instant Answer Page: https://duck.co/ia/view/cpp_forward_list_cheat_sheet
@ManrajGrover

CPP Forward list: Update method name

---

lib/DDG/Goodie/Dewey.pm
share/goodie/dewey/dewey.txt
t/Dewey.t

Finishing off: https://github.com/duckduckgo/zeroclickinfo-goodies/pull/3213
@AlterationBrick 
---
Instant Answer Page: https://duck.co/ia/view/dewey
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @navneetzz

Dewey: Converting to structured answer

---

share/goodie/cheat_sheets/json/htaccess.json

@moollaza 
---
Instant Answer Page: https://duck.co/ia/view/htaccess_cheat_sheet

Add new htaccess cheat sheet

---

share/goodie/cheat_sheets/json/apt-get.json

- [*] Improvement
- [*] Bug fix: **`apt-get cheat sheet: Fix issue 3316`**
{Short Description}`**
Fixes [issue 3316](https://github.com/duckduckgo/zeroclickinfo-goodies/issues/3316) - Add sudo prefix to listed commands.
---
Instant Answer Page: http://duck.co/ia/view/apt_get_cheat_sheet

apt-get cheat sheet: Fix issue 3316

---

share/goodie/cheat_sheets/json/kabaddi-terms.json
share/goodie/cheat_sheets/json/language/cantonese.json
share/goodie/cheat_sheets/json/language/esperanto.json
share/goodie/cheat_sheets/json/language/hindi.json
share/goodie/cheat_sheets/json/language/konkani.json
share/goodie/cheat_sheets/json/language/spanish.json
share/goodie/cheat_sheets/json/language/swahili.json
share/goodie/cheat_sheets/triggers.yaml

@moollaza As you had mentioned in a comment on one of my previous PRs, I have added more relevant important triggers to `language` cheat sheets. Please review :smile: 
---
People to notify

Add more trigger words for language cheat sheets

---

share/goodie/cheat_sheets/json/cpp-maps.json

This pull request adds new cheat sheet CPP Maps.
None
---
Instant Answer Page: https://duck.co/ia/view/cpp_maps_cheat_sheet
None

CPP Maps IA Added

---

template/lib/DDG/Goodie/Example.pm
template/lib/DDG/Goodie/Minimal.pm
template/share/goodie/example/example.js
template/t/Example.t

Made changes to use single quotes everywhere in the template
Fixes: #3347 
@moollaza @GuiltyDolphin

Template: Use of single quotes

---

share/goodie/cheat_sheets/json/visual-studio.json

}: {added description}`**
Added description
---
Instant Answer Page: https://duck.co/ia/view/visual_studio_cheat_sheet

Visual Studio Cheat Sheet  : Add description

---

lib/DDG/Goodie/ChineseToPinyin.pm
t/ChineseToPinyin.t

---
Instant Answer Page: https://duck.co/ia/view/chinese_to_pinyin
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @eflyjason

New Chinese to Pinyin Goodies

---

template/templates.yml

Fixes an issue with `duckpan new` producing cheat sheets with underscores in the filename.
This should be merged *after* duckduckgo/p5-app-duckpan#359.
See duckduckgo/p5-app-duckpan#353
cc @zachthompson

Templates: Ensure cheat sheet file names are hyphenated

---

share/goodie/cheat_sheets/json/chinese-dynasties.json

- Add space between Chinese character and English name.
- Add name in Traditional Chinese for some dynasty/period
---
Instant Answer Page: https://duck.co/ia/view/chinese_dynasties_cheat_sheet

Optimize Chinese Dynasties Cheat Sheet

---

share/goodie/mac_address/oui_update.sh

Fixed de broken link related to: #3022 
IA Page: https://duck.co/ia/view/mac_address
maintainer: @mogigoma

Fix broken link

---

lib/DDG/Goodie/ChordDiagrams.pm

The tests for this were throwing loads of errors; all of which looked like real problems. I don't believe I've altered the functionality here, although it's worth a good look over:
```
rob@set $ prove -Ilib -j8 t/ChordDiagrams.t
t/ChordDiagrams.t .. 1/? Use of uninitialized value $chord in string eq at /home/rob/scripts/ddg/ddh/goodies/lib/DDG/Goodie/ChordDiagrams.pm line 164.
Use of uninitialized value $chord in pattern match (m//) at /home/rob/scripts/ddg/ddh/goodies/lib/DDG/Goodie/ChordDiagrams.pm line 164.
Use of uninitialized value $chord in string eq at /home/rob/scripts/ddg/ddh/goodies/lib/DDG/Goodie/ChordDiagrams.pm line 165.
Use of uninitialized value $chord in pattern match (m//) at /home/rob/scripts/ddg/ddh/goodies/lib/DDG/Goodie/ChordDiagrams.pm line 165.
Use of uninitialized …
```

ChordDiagrams: Was throwing various errors during the test suite

---

share/goodie/cheat_sheets/json/notepad-plus-plus.json

}: {added description}`**
Added description
---
Instant Answer Page: https://duck.co/ia/view/notepad_plus_plus_cheat_sheet
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @biscuitNinja

Notepad++ Cheat Sheet: Add description

---

share/goodie/cheat_sheets/json/bash.json

Adding TCP/UDP From #3189 into its own category
@scellef
---
Instant Answer Page: https://duck.co/ia/view/bash_cheat_sheet
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @synbit

BashCheatSheet: Adding TCP/UDP & Finishing off #3189

---

share/goodie/cheat_sheets/json/emberjs.json

@moollaza 
---
Instant Answer Page: https://duck.co/ia/view/emberjs_cheat_sheet
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @vikashvverma

EmberCheatSheet: Quick fix; trailing white space

---

share/goodie/cheat_sheets/json/geometry-formula.json
share/goodie/cheat_sheets/triggers.yaml

- Added custom triggers in .yaml file (as proposed by @GuiltyDolphin in #3251)
- Added perimeter
@zachthompson 
---
Instant Answer Page: https://duck.co/ia/view/geometry_formula_cheat_sheet
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @VeerpalBrar

Geometry Formula Cheat Sheet: Added perimeter and aliases

---

share/goodie/cheat_sheets/json/pokemon-go.json

A new cheat sheet explaining the features of Pokemon Go.
@zekiel @edgesince84 As the resident experts, could you check this looks OK please?
---
Instant Answer Page: https://duck.co/ia/view/pokemon_go_cheat_sheet
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @tagawa

Pokemon Go: Created cheat sheet

---

share/goodie/cheat_sheets/json/ace-editor.json

- [ X] New Instant Answer
- [X ] Cheat Sheets: **`New Ace Editor Cheat Sheet`**
New Ace Editor (Cloud 9) cheat sheet.
---
Instant Answer Page: https://duck.co/ia/view/ace_editor_cheat_sheet
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @bernardodsanderson

Ace Editor Cheat Sheet

---

lib/DDG/Goodie/Luhn.pm
t/Luhn.t

https://duck.co/ia/view/luhn_algorithm
New IA, calculating Luhn checksum.
---
Instant Answer Page: https://duck.co/ia/view/luhn_algorithm

New Luhn instant answer

---

share/goodie/cheat_sheets/json/csgo.json

Fixes #3385 
@tagawa 
---
Instant Answer Page: http://duck.co/ia/view/csgo_cheat_sheet
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @aiyankovil

Counter-Strike Go Cheat Sheet: Add aliases and update description

---

share/goodie/cheat_sheets/json/java-file-handling.json

Added description and meta to the cheat sheet and refactored two sections, made Buffered Streams and Line Oriented I/O sections look somewhat pretty.
@moollaza 
---
Instant Answer Page: https://duck.co/ia/view/java_file_handling_cheat_sheet

Java File Handling Cheat Sheet: Modify contents

---

share/goodie/cheat_sheets/json/language/catalan.json

A cheat sheet for the Catalan language.
---
Instant Answer Page: https://duck.co/ia/view/catalan_cheat_sheet

New Catalan Cheat Sheet

---

share/goodie/cheat_sheets/json/cpp-queue.json

This pull request adds CPP Queues IA 
None
---
Instant Answer Page: https://duck.co/ia/view/cpp_queue_cheat_sheet
None

CPP Queues IA Added

---

share/goodie/cheat_sheets/json/minecraft-commands.json

Add a cheat sheet for Minecraft chat commands
---
Instant Answer Page: https://duck.co/ia/view/minecraft_commands_cheat_sheet
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @122131

New Minecraft Commands Cheat Sheet

---

share/goodie/cheat_sheets/json/skyscanner-apis.json
share/goodie/cheat_sheets/json/skyscanner_apis.json

This is a reference cheat sheet for Skyscanner's APIs.
---
Instant Answer Page: https://duck.co/ia/view/skyscanner_apis_cheat_sheet

New Skyscanner apis Cheat Sheet

---

share/goodie/cheat_sheets/json/unity.json

New Cheat Sheet for the Unity game engine
---
Instant Answer Page: https://duck.co/ia/view/unity_engine_cheat_sheet
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @MSDOStoevsky

New Unity Engine Cheat Sheet

---

lib/DDG/Goodie/Luhn.pm
t/Luhn.t

Updated subtitle so as to remove redundancy.
Fixes #3396 by updating the subtitle as per feedback.
@moollaza 
---
Instant Answer Page: https://duck.co/ia/view/luhn_algorithm
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @regagain

Luhn Algorithm: Reduce subtitle redundancy

---

share/goodie/cheat_sheets/json/crontab.json

Add JSON file to change the Crontab Goodie to a cheat sheet.
---
Instant Answer Page: https://duck.co/ia/view/crontab_cheat_sheet
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @nkorth

Crontab Cheat Sheet: Add JSON file

---

lib/DDG/Goodie/JsMinify.pm
share/goodie/js_minify/content.handlebars
share/goodie/js_minify/js_minify.css
share/goodie/js_minify/js_minify.js
share/goodie/js_minify/triggers.txt
t/JsMinify.t

Changes as mentioned in #3415 
Perl
---
JS
---
CSS & Handlebars
---
More details on DDG CSS classes here: https://duckduckgo.com/styleguide
Fixes #3415 
@moollaza @MariagraziaAlastra 
---
Instant Answer Page: https://duck.co/ia/view/js_minify
Maintainer: @sahildua2305

JsMinify: Code Refactor and Design Adjustments [WIP]

---

lib/DDG/Goodie/URLDecode.pm
t/URLDecode.t

Fixes: https://github.com/duckduckgo/zeroclickinfo-goodies/issues/3395
@suryansh-tibarewal
---
IA Page: http://duck.co/ia/view/urldecode
Maintainer: @mintsoft

URLDecode: Fixing case sensitive triggers

---

share/goodie/cheat_sheets/json/evernote.json

- [ X] Improvement
- [X ] Bug fix: **`{Evernote Cheat Sheet}: Fix 3252`**
- [X ] Enhancement: **`{IA Name}: {Description of Improvements}`**
Added Mac shortcuts to Evernote cheat sheet
Fixes #3252 - how specifically does it fix the issue?
---
Instant Answer Page: https://duck.co/ia/view/evernote_cheat_sheet
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @smitche60

Added Mac shortcuts to Evernote cheat sheet

---

share/goodie/cheat_sheets/json/language/german.json

- [ x] Improvement
- [x ] Bug fix: **`{IA Name}: Fix #2960`**
- Changed "Mein Name ist.." to the more common "Ich heiße..."
- Added "Goodbye!" Translation
- Changed "Entree" to "Appetizer"
Fixes #2960 - how specifically does it fix the issue?
---
Instant Answer Page: https://duck.co/ia/view/german_cheat_sheet

Correct German IA according to #2960

---

share/goodie/cheat_sheets/json/conda.json

This PR adds conda cheat sheet.
None
@zekiel @tagawa 
---
Instant Answer Page: https://duck.co/ia/view/conda_cheat_sheet
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @adityasiwan

Conda Cheat Sheet

---

share/goodie/cheat_sheets/json/nmap.json

It changes the the command for nmap scanning all ports on a target from "nmap -p "*" [target]" 
to "nmap -p 1-63535 [target]".
@aleksandar-todorovic 
---
Instant Answer Page: https://duck.co/ia/view/nmap_cheat_sheet
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @aleksandar-todorovic

nmap cheat sheet : Update command for scanning all ports

---

share/goodie/cheat_sheets/json/cpp-stack.json

Adds CPP Stack IA
None
---
Instant Answer Page: https://duck.co/ia/view/cpp_stack_cheat_sheet
None

Cpp Stack IA added

---

share/goodie/cheat_sheets/json/chess.json

Adding the icons for the chess pieces to the cheat sheet so beginners know which piece is named which
Fixes #3442 - Adds the piece icons recommended in the Issue
@DPAUTHe
---
Instant Answer Page: https://duck.co/ia/view/chess_cheat_sheet
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @samskeller

Chess Cheat Sheet: Adding Icons

---

share/goodie/cheat_sheets/json/proton-mail.json

---
Instant Answer Page: https://duck.co/ia/view/proton_mail_cheat_sheet

Proton Mail Cheat Sheet: Bug Fix

---

share/goodie/cheat_sheets/json/rwanda.json

- [ X] New Instant Answer
- [X ] Cheat Sheets: **`New Rwanda Cheat Sheet`**
Basic Kinyarwanda words and phrases. Kinyarwanda is the official language of Rwanda along with english and french.
---
Instant Answer Page: https://duck.co/ia/view/rwanda_cheat_sheet
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @jenzzly

New Kinyarwanda Cheat Sheet

---

share/goodie/cheat_sheets/json/meat-cooking-temperature.json

A new cheat sheet providing internal cooking temperatures for meat, as provided by the Food Network.
Solves https://duck.co/ideas/idea/4899/temperature-guidelines-cooking-meat
N/A
---
Instant Answer Page: https://duck.co/ia/view/meat_cooking_temperature_cheat_sheet

New Meat Cooking Temperature Cheat Sheet

---

share/goodie/cheat_sheets/json/skyscanner-apis.json

@moollaza please deploy this on beta so that we can test how #3353 works :wink: 
---
Instant Answer Page: https://duck.co/ia/view/skyscanner_apis_cheat_sheet
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @samheyman

SkyscannerAPICheatSheet: Add columns parameter to the cheatsheet for testing #3353

---

lib/DDG/Goodie/JSONValidator.pm
share/goodie/jsonvalidator/jsonvalidator.js
share/goodie/jsonvalidator/triggers.txt
t/JSONValidator.t

Fixes #3459 
@MariagraziaAlastra 
---

JSON Validator: Add Feature: Prettyprint JSON when it's valid

---

share/goodie/cheat_sheets/json/apache-cordova.json

Apache Cordova Cheat Sheet
https://duck.co/ia/view/apache_cordova_cheat_sheet
---
Instant Answer Page: https://duck.co/ia/view/apache_cordova_cheat_sheet
Maintainer: @mention
@marti1125
marti1125@gmail.com

Add apache cordova cheat sheet

---

lib/DDG/Goodie/SHA3.pm
t/SHA3.t

Added 'sha-3' trigger.
None
---
Instant Answer Page: https://duck.co/ia/view/sha3

SHA-3: Added 'sha-3' trigger

---

share/goodie/cheat_sheets/json/i3.json

The i3wm cheatsheet should be triggered for more queries like
`i3wm cheatsheet`. This could be fixed by adding alias meta-data.
The description of cheatsheet should be updated and json data
should be refactored  to follow docs guidelines.
* alias meta-data added
* refactored json data according to docs guidelines
* description of cheatsheet updated
See also: #3175
---
Instant Answer Page: https://duck.co/ia/view/i3_cheat_sheet
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @goromlagche

i3_cheat_sheet: Add alias meta-data and refactor json file

---

share/goodie/cheat_sheets/json/ufc-weight-classes.json

---
Instant Answer Page: https://duck.co/ia/view/ufc_weight_classes_cheat_sheet

New UFC weight classes cheat sheet

---

share/goodie/cheat_sheets/json/substitute-olive-oil-for-butter.json

- [X ] New Instant Answer
- [X ] Cheat Sheets: **`New {Cheat Sheet Name} Cheat Sheet`**
List for reference of olive oil instead of butter for baking measurements
---
Instant Answer Page: https://duck.co/ia/view/substitute_olive_oil_for_butter

New cheatsheet olive oil substitute for butter. Hack Days attempt

---

share/goodie/cheat_sheets/json/blood-type.json

---
Instant Answer Page: https://duck.co/ia/view/blood_type_cheat_sheet

New Blood Type Cheat Sheet

---

share/goodie/cheat_sheets/json/cpp-unordered-map.json

This PR adds CPP Unordered Map Cheat Sheet
None
---
Instant Answer Page: https://duck.co/ia/view/cpp_unordered_map_cheat_sheet
None

CPP Unordered Map IA Added

---

share/goodie/cheat_sheets/json/xmonad.json

Adds a cheatsheet for the xmonad window manager default keybindings.
---
Instant Answer Page: https://duck.co/ia/view/xmonad_cheat_sheet

New Xmonad Cheat Sheet

---

share/goodie/cheat_sheets/json/mediawiki.json

https://duck.co/ia/view/mediawiki_cheat_sheet

New MediaWiki Cheatsheet

---

lib/DDG/Goodie/JsMinify.pm
share/goodie/js_minify/content.handlebars
share/goodie/js_minify/js_minify.css
share/goodie/js_minify/js_minify.js
t/JsMinify.t

- Better button sizing and position for desktop and mobile
- Adjust  textarea height for mobile
- Add DDG Form style classes to textarea
- Add placeholder text to input
- Adjust subtitle text
UI now looks like:
@sahildua2305 @MariagraziaAlastra 
---
Instant Answer Page: https://duck.co/ia/view/js_minify

JS Minify Visual Improvements

---

share/goodie/cheat_sheets/json/harry-potter.json

gives information about the series of books and movies based on a fictional character named Harry Potter
Instant Answer Page: https://duck.co/ia/view/harry_potter_cheat_sheet
Screenshot:

Harry Potter cheat sheet

---

share/goodie/cheat_sheets/json/cpp-unordered-set.json

This PR adds CPP Unordered Set Cheat Sheet
None
None
---
Instant Answer Page: https://duck.co/ia/view/cpp_unordered_set_cheat_sheet
None

CPP Unordered Set IA

---

share/goodie/cheat_sheets/json/cpp-unordered-multiset.json

This PR adds CPP Unordered Multiset Cheat Sheet
None
None
---
Instant Answer Page: https://duck.co/ia/view/cpp_unordered_multiset_cheat_sheet
None

CPP Unordered Multiset

---

share/goodie/cheat_sheets/json/youtube.json

Adds a Cheat Sheet for the YouTube website.
IA Page: [https://duck.co/ia/view/youtube_cheat_sheet](https://duck.co/ia/view/youtube_cheat_sheet)

New YouTube Cheat Sheet

---

share/goodie/cheat_sheets/json/arch-linux.json

---
Instant Answer Page:  https://duck.co/ia/view/arch_linux_cheat_sheet
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @direwolf424

Updated some language etc 

---

share/goodie/cheat_sheets/json/cpp-unordered-multimap.json

This PR adds CPP Unordered Multimap IA.
None
---
Instant Answer Page: https://duck.co/ia/view/cpp_unordered_multimap_cheat_sheet
None

CPP Unordered Multimap

---

share/goodie/cheat_sheets/json/ruby-webcomics.json

Added ruby-webcomics.json
N/A
---
Instant Answer Page: https://duck.co/ia/view/ruby_webcomics_cheat_sheet
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @mav7

added ruby webcomics

---

share/goodie/cheat_sheets/json/php.json

Fixes #3515 
@edgesince84 @moollaza 
---
Instant Answer Page: https://duck.co/ia/view/php_cheat_sheet

PHP CheatSheet: Update the cheat sheet to make it more relevant

---

share/goodie/cheat_sheets/json/cpp-set.json
share/goodie/cheat_sheets/json/cppset.json

This pull request adds Cpp Set IA
None
---
Instant Answer Page: https://duck.co/ia/view/cpp_set_cheat_sheet
None

Cpp Set IA Added

---

lib/DDG/Goodie/DaysBetween.pm
t/DaysBetween.t

Add 'Days since' feature. User can search queries like 'days since 31 August 2016'.
Fixes #3454 
@tagawa 
---
Instant Answer Page: https://duck.co/ia/view/days_between
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @JetFault

DaysBetween: Add 'Days since' feature

---

share/goodie/cheat_sheets/json/libre-office-writer.json

---
Instant Answer Page: https://duck.co/ia/view/libre_office_writer_cheat_sheet

New Libre Office Writer Cheat Sheet

---

share/goodie/cheat_sheets/json/youtube.json

Added @theniels17 and [Thom Wiggers'](https://twitter.com/ThomWiggers/status/765909511446159361) suggestions.
#3548
Instant Answer Page: https://duck.co/ia/view/youtube_cheat_sheet
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @benabrahamson

Added Suggestions

---

share/goodie/cheat_sheets/json/org-mode.json

Add org-mode cheatsheet
None
---
Instant Answer Page: https://duck.co/ia/view/org_mode_cheat_sheet

New Org Mode Cheat Sheet

---

share/goodie/cheat_sheets/json/grep.json

Instant Answer Page: https://duck.co/ia/view/grep_cheat_sheet
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @adityabhushan

New Pull request for grep cheat sheet

---

lib/DDG/Goodie/Uppercase.pm

We no longer need to `html_enc` the text returned from Goodies thanks to recent internal changes.
RE: https://twitter.com/FlorianFun/status/768427593045467136/photo/1
---
Instant Answer Page: https://duck.co/ia/view/uppercase
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html):

upercase: Remove HTML Encoding of output text

---

lib/DDG/Goodie/CssColors.pm
t/CssColors.t

Fixes #3564 
@moollaza 
---
Instant Answer Page: https://duck.co/ia/view/css_colors

CSSColors: Improve handle to avoid over-triggering

---

lib/DDG/Goodie/URLDecode.pm
lib/DDG/Goodie/URLEncode.pm
t/URLDecode.t
t/URLEncode.t

Fixes #3563 
@moollaza 
---
Instant Answer Page: https://duck.co/ia/view/urlencode, https://duck.co/ia/view/urldecode
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html):

Remove HTML encoding from multiple goodies

---

share/goodie/cheat_sheets/json/cpp-bitset.json

This PR adds CPP Bitset IA 
None
---
Instant Answer Page: https://duck.co/ia/view/cpp_bitset_cheat_sheet
None

CPP Bitset IA Added

---

README.md

1. Updated README to reflect the Programming Mission: https://forum.duckduckhack.com/t/duckduckhack-programming-mission-overview/53
- We are focused on validating the tools/processes used to create Instant Answers on DuckDuckGo by working directly with contributors to a single search topic: Programming-related searches. We're starting with CSS, JS, Perl, Python, and Swift but plan to expand into other programming languages/frameworks (and other topics) as the new community grows. 
2. Introduces the focus and policy on programming-related Instant Answers: 
- We are only reviewing/accepting Pull Requests/Issues within the Programming Mission.

Updated README for prog mission alert

---

.github/PULL_REQUEST_TEMPLATE.md
CONTRIBUTING.md

Update the PR template and contributing.md for Programming Mission callouts
@alohaas

more updates for programming mission

---

share/goodie/jsonvalidator/content.handlebars
share/goodie/jsonvalidator/jsonvalidator.css
share/goodie/jsonvalidator/jsonvalidator.js

JSON Validator: Design Tweaks

---

lib/DDG/Goodie/ABC.pm
lib/DDG/Goodie/Anagram.pm
lib/DDG/Goodie/Average.pm
lib/DDG/Goodie/Base64.pm
lib/DDG/Goodie/Bitsum.pm
lib/DDG/Goodie/Chars.pm
t/Average.t
t/Base64.t
t/Bitsum.t
t/Chars.t

We no longer need to html_enc the text returned from Goodies thanks to recent internal changes.
@moollaza

removed html_enc from ABC,ANAGRAM,AVERAGE,BASE64,BITSUM,CHARS

---

share/goodie/cheat_sheets/json/pokemon-go.json

Added new sections for "Tips" and "Key Levels"
None
---
Instant Answer Page: https://duck.co/ia/view/pokemon_go_cheat_sheet
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @tagawa

Pokemon GO cheat sheet: Added tips and key levels

---

lib/DDG/Goodie/RandomDate.pm
t/RandomDate.t

Removed html_enc() from RandomDate.pm

---

lib/DDG/Goodie/Cusip.pm
lib/DDG/Goodie/DaysBetween.pm
lib/DDG/Goodie/GreatestCommonFactor.pm
lib/DDG/Goodie/POTUS.pm
lib/DDG/Goodie/ReverseResistorColours.pm
lib/DDG/Goodie/SunInfo.pm
lib/DDG/Goodie/TwelveOclock.pm
lib/DDG/Goodie/Week.pm
lib/DDG/Goodie/WeekdaysBetween.pm
lib/DDG/Goodie/Weight.pm
lib/DDG/Goodie/WorkdaysBetween.pm
t/Cusip.t
t/DaysBetween.t
t/GreatestCommonFactor.t
t/POTUS.t
t/ReverseResistorColours.t
t/SunInfo.t
t/TwelveOclock.t
t/Week.t
t/WeekdaysBetween.t
t/Weight.t
t/WorkdaysBetween.t

Small change removing periods from titles and subtitles, as pointed out [here](https://github.com/duckduckgo/zeroclickinfo-goodies/pull/3086#discussion_r64656831)
---

Goodies: Remove periods from titles, subtitles and plaintext responses

---

lib/DDG/Goodie/HTMLEntitiesEncode.pm

fixes #3607 
---
Instant Answer Page:  http://duck.co/ia/view/htmlentities_encode
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @nishanths

Updated HTMLEntriesEncode.pm: Fixes #3607

---

share/goodie/cheat_sheets/json/gedit.json

Cheat sheet to display gedit keyboard shortcuts.
Instant Answer Page: https://duck.co/ia/view/gedit_cheat_sheet

New Gedit Cheat Sheet

---

share/goodie/cheat_sheets/json/silmarillion.json

https://duck.co/ia/view/silmarillion_cheat_sheet

New Silmarillion Cheat Sheet

---

share/goodie/cheat_sheets/json/silmarillion.json

fixed a few spelling errors, replaced a stray remaining semicolon with a comma, etc.
@GuiltyDolphin
---
Instant Answer Page: https://duck.co/ia/view/silmarillion_cheat_sheet
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @lsma

fixed typos

---

lib/DDG/Goodie/DurationCalculator.pm

I'm upgrading DateTime to v1.39 (currently its 1.06).  This pr makes this code compatible with the new version.
cc @moollaza 
---
Instant Answer Page: https://duck.co/ia/view/duration_calculator
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @sam09

Make this work with DateTimev1.39

---

share/goodie/cheat_sheets/json/htaccess.json

modification: updated aliases entry, added ".htaccess"
.htaccess cheat sheet is awesome!
But the only thing that should be changed or modified is "when should this cheat sheet trigger"
According to me, the cheat sheet should also trigger when some searches ".httaccess cheat sheet"
because many users might search with that DOT "."
https://duck.co/ia/view/htaccess_cheat_sheet
https://github.com/duckduckgo/zeroclickinfo-goodies/issues/3646
@sahildua2305 
---
Instant Answer Page: https://duck.co/ia/view/htaccess_cheat_sheet …

modification: updated aliases entry, added ".htaccess"

---

share/goodie/cheat_sheets/json/pygame.json

New Goodie: Python Cheat Sheet
@pjhampton 
---
Instant Answer Page:  https://duck.co/ia/view/pygame_cheat_sheet

Pygame cheat sheet

---

share/goodie/cheat_sheets/json/numpy.json

New Goodie: NumPy Cheat Sheet
@pjhampton 
---
Instant Answer Page: https://duck.co/ia/view/numpy_cheat_sheet

New Goodie: NumPy Cheat Sheet

---

share/goodie/cheat_sheets/json/requests.json

`requests` is a popular Python library for interacting with HTTP requests. It is well-documented but this means that sometimes it takes a minute or two to find the syntax you're looking for. This is a perfect candidate for solution by cheat sheet!
---
Instant Answer Page: https://duck.co/ia/view/requests_cheat_sheet
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @daneah

New Requests Cheat Sheet

---

lib/DDG/Goodie/JSONValidator.pm
t/JSONValidator.t

JSONValidator: Improve title/subtitle to clarify usage

---

share/goodie/cheat_sheets/json/java.json

This PR change updates the description of 'For Each Loop' to 'For Each Loop ( Also known as Advanced or Enhanced For Loop )'. This change is done because it will allow some novice users to easily understand the meaning of For Each Loop which is more clear with terms like Enhanced and Advanced. 
@arajparaj @MoriTanosuke 
---
Instant Answer Page: https://duck.co/ia/view/java_cheat_sheet
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @arajparaj

update description of 'For each' loop

---

share/goodie/cheat_sheets/json/onenote.json

- [x ] New Instant Answer
- x[ ] Cheat Sheets: **`New Microsoft OneNote Cheat Sheet`**
Creation of a new cheatsheet for Microsoft OneNote
---
Instant Answer Page: https://duck.co/ia/view/onenote_cheat_sheet

OneNote cheat sheet

---

share/goodie/cheat_sheets/json/git-flow.json

Adding a cheat sheet for git flow which would help git users have an easier access to the basic git flow commands when working with features, releases and hotfixes.
Screenshot
---
Instant Answer Page: https://duck.co/ia/view/git_flow_cheat_sheet
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @tricinel

New Git flow Cheat Sheet

---

share/goodie/duck_duck_go/responses.yml

---
Instant Answer Page: https://duck.co/ia/view/{{ID}}

share/goodie/duck_duck_go/responses.yml: remove Yahoo responses.

---

share/goodie/cheat_sheets/json/django.json

https://duck.co/ia/view/django_cheat_sheet
Fixes #3664 Added en entry for the `django-admin createsuperuser` command

django cheat sheet: add django-admin createsuperuser

---

share/goodie/cheat_sheets/json/lombok.json

Developer and Maintainer: @marti1125
---
https://duck.co/ia/view/lombok_cheat_sheet

add lombok cheat sheet

---

share/goodie/cheat_sheets/json/google-analytics-regex.json

This PR includes a google-analytics.json file in the \share\goodie\cheat_sheets\json\ folder .
This file is meant to introduce the new cheat sheet.
Please let me know what you think
---
Instant Answer Page: https://duck.co/ia/view/google_analytics_regex_cheat_sheet

Cheat Sheet for Google Analytics Regular Expressions

---

share/goodie/cheat_sheets/json/quackhack.json

fixes:#3584
NB:
looking fine on codio:
---
IA Page: http://duck.co/ia/view/quackhack_cheat_sheet
Maintainer: @zekiel

changed template type for quackhack.json: fixes #3584

---

share/goodie/cheat_sheets/json/adobe-flash.json

This will trigger the cheat sheet using the alias or common names 
---
Instant Answer Page :https://duck.co/ia/view/adobe_flash_cheat_sheet

Adobe Flash Cheat sheet : Alias added

---

share/goodie/cheat_sheets/json/docker.json

fixes #3694 
#3694 
@sahildua2305 
---
Instant Answer Page: https://duck.co/ia/view/docker_cheat_sheet
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @preemeijer

DockerCheatSheet : updated according to the official docs

---

share/goodie/cheat_sheets/json/yarn.json

Adding a cheat sheet for yarn, the new Javascript package manager. More info about yarn [here](https://yarnpkg.com/).
Screenshot
---
Instant Answer Page: https://duck.co/ia/view/yarn_cheat_sheet
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @tricinel

New Yarn Cheat Sheet

---

share/goodie/cheat_sheets/json/language/sinhala.json

creates Sinhala cheat sheet
---
Instant Answer Page: https://duck.co/ia/view/sinhala_cheat_sheets
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @ar-naseef

New Sinhala cheat sheet

---

share/goodie/latex/latex.css

This will make the font color implicit to the theme of DDG instead of specific color unlike other IAs.
#3590 
@tagawa 
---
Instant Answer Page: https://duck.co/ia/view/latex
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @jdorweiler

Removed the explicit color property from Latex IA

---

share/goodie/cheat_sheets/json/array-sorting.json

---
Instant Answer Page: https://duck.co/ia/view/array_sorting_cheat_sheet

Array sorting cheat sheet: Fix typos and add more sorting techniques

---

share/goodie/cheat_sheets/json/medieval-2-total-war.json

@tagawa 
---
Instant Answer Page: https://duck.co/ia/view/medieval_2_total_war_cheat_sheet
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html):

New Medieval 2 Total War Cheat Sheet

---

share/goodie/jsonvalidator/jsonvalidator.js

Changing indentation to 4 spaces because that's more common instead
of 2 spaces
@moollaza @MariagraziaAlastra 
---

JSONValidator: Change default indentation to 4 spaces

---

share/goodie/cheat_sheets/json/sublime-text.json

Proper JSON formatting using JSON Validator.
@moollaza 
---
Instant Answer Page: https://duck.co/ia/view/sublime_text_cheat_sheet
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @codenirvana

SublimeText Cheat Sheet: Proper JSON formatting

---

lib/DDG/Goodie/JsBeautifier.pm
share/goodie/js_beautifier/content.handlebars
share/goodie/js_beautifier/js_beautifier.css
share/goodie/js_beautifier/js_beautifier.js
share/goodie/js_beautifier/triggers.txt
t/JsBeautifier.t

It will add a new JS tool to beautify the minified javascript.
@tagawa @moollaza @bfmags 
---
Instant Answer Page: https://duck.co/ia/view/js_beautifier
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @moollaza

New JS Beautifier Goodie

---

share/goodie/cheat_sheets/json/django.json
share/goodie/cheat_sheets/json/google-drive.json
share/goodie/cheat_sheets/json/google-hacks.json
share/goodie/cheat_sheets/json/harry-potter.json
share/goodie/cheat_sheets/json/json-syntax.json
share/goodie/cheat_sheets/json/pygame.json

Fixes Travis CI warnings
---
Forum Topic:

Fix CI warnings

---

.github/ISSUE_TEMPLATE.md
.github/PULL_REQUEST_TEMPLATE.md

Simplified the content of the PR and Issue templates to make them easier to read/use

PR and Issue Templates: Simplification of HTML Comments

---

share/goodie/cheat_sheets/json/whitespace.json

A brand new cheat sheet to the [Whitespace](https://en.wikipedia.org/wiki/Whitespace_%28programming_language%29) language!  
---
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @Sayan98
Instant Answer Page: https://duck.co/ia/view/whitespace_cheat_sheet

Whitespace cheat sheet

---

share/goodie/cheat_sheets/json/latex.json

Fixes: #3691 
I have made a new cheat sheet for Latex and Tex. I have tried to make it comprehensive and concise. I divided it into sections on the basis of their uses. Most of these stem from those commonly used in papers and online.
This cheat sheet is inspired by #3691 .
The IA page `latex_cheat_sheet` appeared to be taken, however no work etc had been mentioned. It would be nice if I could use the same, otherwise that needs to be deleted. It would be great if mods could address this.
@QVaucher @gautamkrishnar 
---
Forum Topic:
IA Page: https://duck.co/ia/view/latex_cheat_sheet

New Latex CheatSheet

---

share/goodie/cheat_sheets/json/selenium.json

Selenium Cheat sheet
---
IA Page: https://duck.co/ia/view/selenium_cheat_sheet
Forum Topic:

New Cheat Sheet : Selenium

---

share/goodie/jsonvalidator/content.handlebars

---
IA Page: https://duck.co/ia/view/{ID}
Forum Topic:
Most words in JSON files are mostly non spellcheck-able. Those red underlines are somewhat distracting.

Should disable spellcheck

---

share/goodie/cheat_sheets/json/urllib.json

Add new cheatsheet urllib
@mention
---
Instant Answer Page: https://duck.co/ia/view/urllib_cheat_sheet
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @kumarankit0411

New cheatsheet: urllib

---

.github/ISSUE_TEMPLATE.md
.github/PULL_REQUEST_TEMPLATE.md
README.md

- Simplify README and highlight Programming Mission
- Simplify ISSUE_TEMPLATE, and PULL_REQUEST_TEMPLATES
@MariagraziaAlastra @tagawa

Update README, ISSUE_TEMPLATE, and PULL_REQUEST_TEMPLATE

---

share/goodie/cheat_sheets/json/visual-studio.json

A more comprehensive set of shortcut key combinations for use with Visual Studio
Fixes #3230
---
Instant Answer Page: https://duck.co/ia/view/visual_studio_cheat_sheet

Visual studio cheat sheet

---

lib/DDG/Goodie/EmailValidator.pm
t/EmailValidator.t

Fixes #3748
@sahildua2305
---
Instant Answer Page: https://duck.co/ia/view/email_validator

#3748 fix invalid email format

---

share/goodie/cheat_sheets/json/angularjs.json

Add extra`services`, 'directives` and `module` in the cheatsheet.
Fixes https://github.com/duckduckgo/zeroclickinfo-goodies/issues/2934
Maintainer: @SibuStephen
---
Instant Answer Page: https://duck.co/ia/view/angularjs_cheat_sheet

AngularJS Cheatsheet: Add extra info in cheatsheet

---

share/goodie/cheat_sheets/json/libre-office-writer.json

Fixes: #3727 
---
IA Page: http://duck.co/ia/view/libre_office_writer_cheat_sheet

Libre office cheatsheet: Fixed wrong information

---

share/goodie/cheat_sheets/json/jinja.json
share/goodie/cheat_sheets/json/jinja2.json

This PR adds Jinja Cheat Sheet.
None
---
Instant Answer Page: https://duck.co/ia/view/jinja_cheat_sheet

Jinja Cheat Sheet

---

share/goodie/cheat_sheets/json/japanese-language.json
share/goodie/cheat_sheets/json/language/japanese.json

This will trigger the cheat sheet with alias 
---
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @MathewtheCoder
IA Page: https://duck.co/ia/view/japanese_language_cheat_sheet

Japanese Cheat Sheet : moved cheatsheet to languages folder

---

share/goodie/cheat_sheets/json/jinja.json

the braces are now escaped.
escaping braces
---
Instant Answer Page: https://duck.co/ia/view/jinja_cheat_sheet

escaping braces

---

share/goodie/jsonvalidator/content.handlebars
share/goodie/jsonvalidator/jsonvalidator.css
share/goodie/jsonvalidator/jsonvalidator.js

Fixes #3713 
@MariagraziaAlastra @moollaza 
---
Forum Topic:
IA Page: https://duck.co/ia/view/json_validator

JSONValidator: Add option to choose indentation in formatted output

---

share/goodie/cheat_sheets/json/arch-linux.json

- Change Name and Description
- Add aliases for distros that use pacman
- Remove general commands sections
Fixes #3516 
@akanshgulati 
---
IA Page: https://duck.co/ia/view/arch_linux_cheat_sheet

Arch Linux Cheat Sheet: Add more aliases and Remove general commands section

---

share/goodie/cheat_sheets/json/qt-creator.json

A cheat sheet for the C++ IDE "Qt Creator"
---
Instant Answer Page: https://duck.co/ia/view/qt_creator

New Qt Creator Cheatsheet

---

share/goodie/jsonvalidator/triggers.txt

Add `jsonlint` to trigger words.
@moollaza 
---

JSONValidator: Add 'jsonlint' keyword as trigger word

---

share/goodie/cheat_sheets/json/flex.json

This PR adds Flex Cheat Sheet.
None
@moollaza 
---
Instant Answer Page: https://duck.co/ia/view/flex_cheat_sheet

New Flex cheat sheet

---

share/goodie/cheat_sheets/json/sql.json

Fixes a duplicate IA for AS and UNION SQL Statements
Fixes #3772
@gautamkrishnar
---
Instant Answer Page: https://duck.co/ia/view/sql_cheat_sheet

SQL: AS and UNION duplicate removal

---

share/goodie/cheat_sheets/json/jinja.json

fixes: escaping braces
fix: typo
---
Instant Answer Page: https://duck.co/ia/view/jinja_cheat_sheet

Fixes 3755: escaping braces

---

share/goodie/cheat_sheets/json/play14commandline.json

play framework v1.4 command line cheat sheet 
@marti1125
---
Instant Answer Page: https://duck.co/ia/view/play14commandline_cheat_sheet

add play framework v1.4 command line cheat sheet

---

share/goodie/cheat_sheets/json/spring-annotations.json

Displays the most common Spring-Framework annotations.
@pjhampton
---
Instant Answer Page: https://duck.co/ia/view/spring_annotations_cheat_sheet

New Spring Annotations Cheat Sheet

---

share/goodie/cheat_sheets/json/jupyter-notebook.json
share/goodie/cheat_sheets/json/jupyternotebook.json

Instant Answer Page: https://duck.co/ia/view/jupyter_notebook_cheat_sheet
fixes #3807

Jupyter/Ipython Notebook Cheat Sheet

---

share/goodie/cheat_sheets/json/jupyter-notebook.json

Changes spaces in sourceUrl to hyphens
N/A
@Hasil-Sharma 
---
Instant Answer Page: https://duck.co/ia/view/jupyter_notebook_cheat_sheet

JupyterCheatSheet: Fix sourceUrl

---

lib/DDG/Goodie/HistoricalEvents.pm
share/goodie/historical_events/events.yml
t/HistoricalEvents.t

Provides a link to further information for various historical events
@nilnilnil 
---
Instant Answer Page: https://duck.co/ia/view/historical_events

New HistoricalEvents Goodie

---

share/goodie/cheat_sheets/json/duckduckgo-syntax.json

Fixing typo from pr #3829 which caused the test to fail..
----
https://duck.co/ia/view/duckduckgo_syntax_cheat_sheet

Fixing typo

---

share/goodie/cheat_sheets/json/apache-maven.json

CheatSheet for Apache Maven, Java Build Tool
Fixes #3818
---
Instant Answer Page: https://duck.co/ia/view/apache_maven_cheat_sheet

New Cheat Sheet Apache Maven Goodies

---

lib/DDG/Goodie/GUID.pm

I typed "GUID generator" into ddg in when I was looking to trigger this goodie. This change would make that trigger this Goodie
---
Instant Answer Page: https://duck.co/ia/view/GUID

GUID: add trigger word

---

share/goodie/cheat_sheets/json/johntheripper.json

Commands and Cheat sheet for password cracking tool, John the Ripper
N/A
@vduddu
---
---
https://duck.co/ia/view/johntheripper_cheat_sheet

New Cheat Sheet: John the Ripper

---

share/goodie/cheat_sheets/json/capybara.json

IA page: https://duck.co/ia/view/capybara_cheat_sheet

New Capybara Cheatsheet

---

share/goodie/jsonvalidator/triggers.txt

JSONValidator: Updated triggers
Fixes #3831
* @sahildua2305 
* @duckduckgo/duckduckhack-contributors Need your suggestions for the trigger words
---

JSONValidator: Updated triggers Fixes #3831

---

share/goodie/cheat_sheets/json/dorks.json

This cheat sheet is showing a list of the most relevant commands that can be used in DuckDuckGo to perform advanced searches including dorks, bangs and some instant answers.
None.
@febrezo
@i3visio
---
Instant Answer Page: https://duck.co/ia/view/duckduckgo_dorks_cheat_sheet

New advanced search (dork) cheat sheet.

---

share/goodie/cheat_sheets/json/vim.json

Added new alias
Fixes:#3828
@sahildua2305 @NaveenKarippai 
---

Vim cheatsheet: fixes#3828

---

share/goodie/cheat_sheets/json/discord.json

Addition of `discord.json`, provides keyboard shortcuts for the VoIP program Discord.
---
Instant Answer Page: https://duck.co/ia/view/discord_cheat_sheet

New Discord Cheatsheet

---

lib/DDG/Goodie/GoldenRatio.pm
t/GoldenRatio.t

This addresses part of #1163 (Convert HTML Goodies to use templates)
https://duck.co/ia/view/golden_ratio

GoldenRatio: Use structured_answer

---

share/goodie/cheat_sheets/json/apache-hive.json

Cheat Sheet for Apache Hive Commands
Fixes #3832
---
Instant Answer Page: http://duck.co/ia/view/apache_hive_cheat_sheet

New Apache Hive Cheat Sheet

---

share/goodie/cheat_sheets/json/desktop-environments.json

@laorynas
---
Instant Answer Page: https://duck.co/ia/view/desktop_environments

New cheat sheet: Desktop Environments

---

share/goodie/cheat_sheets/json/chrome.json

Removed Duplicate Listing.
Fixes #3858 
@moinism 
---
Instant Answer Page: https://duck.co/ia/view/chrome_cheat_sheet

Fix #3858: Chrome Cheat Sheet - Removed Duplicate Listing.

---

share/goodie/cheat_sheets/json/tmux.json

Added resize keybindings to tmux cheat sheet.
closes:#3857 
---
Instant Answer Page: https://duck.co/ia/view/tmux_cheat_sheet

tmux_cheat_sheet: Added resize shortcuts (as per requested: #3857)

---

lib/DDG/Goodie/Calculator.pm
t/Calculator.t

@moollaza Simplified trigger intended to address https://github.com/duckduckgo/zeroclickinfo-goodies/issues/3853.  Tests pass and I've run a number of sample queries through it.
Fixes #3853 
cc @b2ddg 
---
IA Page: https://duck.co/ia/view/calculator

Calculator: Dumb down the trigger

---

share/goodie/html_beautifier/content.handlebars
share/goodie/html_beautifier/html_beautifier.js

Added Clear button and options for beautification.
@moollaza @tagawa 
---
Instant Answer Page: https://duck.co/ia/view/html_beautifier

Enhancement(html-beautifier): Added options and clear button.

---

lib/DDG/Goodie/Calculator.pm
t/Calculator.t

Reverts duckduckgo/zeroclickinfo-goodies#3866

Revert "Calculator: Dumb down the trigger"

---

lib/DDG/Goodie/Conversions.pm
share/goodie/conversions/ratios.yml
t/Conversions.t

Fixes https://github.com/duckduckgo/zeroclickinfo-goodies/issues/3874
@bsstoner 
---

Conversions: Support for Centigrade

---

lib/DDG/Goodie/Calculator.pm
t/Calculator.t

* Update trigger
* Run expression with Safe with minimum ops
* Add tests
Have fun @moollaza ;)
---
IA Page: https://duck.co/ia/view/calculator

calculator: trigger/safe

---

lib/DDG/Goodie/Calculator.pm
t/Calculator.t

Reverts duckduckgo/zeroclickinfo-goodies#3878

Revert "calculator: trigger/safe"

---

lib/DDG/Goodie/Calculator.pm
t/Calculator.t

For reference https://github.com/duckduckgo/zeroclickinfo-goodies/pull/3878
Ignore reval's warnings
---
IA Page: https://duck.co/ia/view/calculator

ignore reval's warnings

---

lib/DDG/Goodie/Calculator.pm
t/Calculator.t

Reverts duckduckgo/zeroclickinfo-goodies#3892

Revert "ignore reval's warnings"

---

share/goodie/cheat_sheets/json/window-managers.json

Window Managers is list of Window Managers and their descriptions.
@laorynas
---
Instant Answer Page: https://duck.co/ia/view/window_managers

New Window Managers CheatSheet

---

lib/DDG/Goodie/Stopwatch.pm
t/Stopwatch.t

fixes #3843 
---
Instant Answer Page: https://duck.co/ia/view/stopwatch

Stopwatch: add "chronometer" trigger

---

lib/DDG/Goodie/Calculator.pm
t/Calculator.t

- Relaxes trigger regex to prevent long running evaluation of bad queries
- uses `Safe` eval for increased security.
---

Calculator: Improve triggering and execution

---

lib/DDG/Goodie/Calculator.pm
t/Calculator.t

Fix calculator triggering, and handling of certain queries. More tests added as proof.
---

Calculator: More fixes -- Trigger regex contained a bug

---

share/goodie/duck_duck_go/responses.yml
t/DuckDuckGo.t

Fixes the link in the IA shown for the "duckduckgo blog" search term. 
None
@moollaza 
---

DuckDuckGo Goodie: Fixed link to blog

---

share/goodie/cheat_sheets/json/angularjs.json

Added `component`  in module reference.
Maintainer: @SibuStephen
---
IA Page: https://duck.co/ia/view/angularjs_cheat_sheet

AngularJS: Add component in module

---

share/goodie/constants/constants.yml

**Constants**: Added some more constants
New and some popular constants like value of pi, value of e, nuclear magneton, etc are added to the Constants IA page.
Thanks to **@moollaza** and **@hemanth** for helping me in pulling out these changes. 
Instant Answer Page: https://duck.co/ia/view/constants

Added some more constants

---

share/goodie/duck_duck_go/responses.yml

We're not going to point to the one in the community page anymore. This links to the new hiring page.
@moollaza 
---

DuckDuckGo: Change the link to the hiring page

---

share/goodie/cheat_sheets/json/wireshark.json

New Wireshark Cheat Sheet
**This Instant Answer provides the navigation shortcuts and display filters for wireshark** 
@vduddu 
---
Instant Answer Page: https://duck.co/ia/view/wireshark_cheat_sheet

New IA Wireshark Cheat Sheet

---

share/goodie/cheat_sheets/json/tshark.json

A network protocol analyzer
@moollaza @vduddu 
---
Instant Answer Page: https://duck.co/ia/view/tshark_cheat_sheet

TShark Cheat Sheet

---

lib/DDG/Goodie/Calculator.pm
share/goodie/calculator/title_content.handlebars
t/Calculator.t

- Switch the Calculator to use the standard text template
- Update tests accordingly
---

Calculator: Switch to canonical structured answer

---

share/goodie/cheat_sheets/json/git.json

Adding git remotes commands
@adityatandon007 @gautamkrishnar 
---

GitCheatSheet: Added new git commands

---

share/goodie/dice/dice.css

Reverts duckduckgo/zeroclickinfo-goodies#3886
Causing breakage on mobile

Revert "Dice: Increased dice size"

---

share/goodie/cheat_sheets/json/c-statements.json

Add a new cheat sheet for C Statements like while, do-while, for, if, switch, etc.
@moollaza 
---
Forum Topic: https://forum.duckduckhack.com/t/new-c-statements-cheat-sheet/1092
IA Page: https://duck.co/ia/view/c_statements_cheat_sheet

New Cheat Sheet: C Statements

---

share/goodie/cheat_sheets/json/sublime-text.json

Sublime Text Cheat Sheet: Adds alias **sublime text2**
Fixes #3928  A
Fixes #3928 
@pjhampton @gautamkrishnar 
---
Instant Answer Page: https://duck.co/ia/view/sublime_text_cheat_sheet

Fixes #3928 Adds alias sublime text2

---

share/goodie/cheat_sheets/json/sublime-text3.json

**New Sublime Text 3 Cheat Sheet**
This IA gives the keyboard shortcuts for sublime text 3 editor
Fixes #3929
@pjhampton 
Instant Answer Page: https://duck.co/ia/view/sublime_text_3

New Sublime Text 3 Cheat Sheet : Fixes #3929

---

share/goodie/cheat_sheets/json/python.json

Python Language Cheat Sheet: Adds aliases **python2** and **python 2** for this IA
Adds aliases for the improving this cheat sheet
Fixes #3947 
@ethanchewy @sahildua2305 
---
Instant Answer Page: https://duck.co/ia/view/python_cheat_sheet

Fixex #3947 Adds aliases 

---

share/goodie/cheat_sheets/json/rails-console.json

Reference for rails console commands.
---
Instant Answer Page: https://duck.co/ia/view/rails_console_cheat_sheet

New Cheat Sheet: Rails Console

---

t/DaysBetween.t

Quickfix to prevent use of un-initialised value of `$inclusive` in test file. Fix can be verified here: https://travis-ci.org/duckduckgo/zeroclickinfo-goodies/builds/204217928#L947
Fixes #3939 
@JetFault @mintsoft
---
Instant Answer Page: https://duck.co/ia/view/days_between

Days Between: Fix to tests file

---

share/goodie/cheat_sheets/json/i3.json

Now in square brackets and with less/greater signs
---
Instant Answer Page: https://duck.co/ia/view/i3_cheat_sheet

i3 cheat sheet: Unify <Number> key

---

share/goodie/cheat_sheets/json/python-datetime.json

This PR adds a new instant answer (Cheat sheet) for Pythons `DateTime` class, The most important part of this Cheat sheet is the Date formatting section.
@pjhampton The Python `DateTime` Cheatsheet is ready for review.
---
Instant Answer Page: https://duck.co/ia/view/python_datetime_cheatsheet

New Cheatsheet: Python Datetime

---

share/goodie/cheat_sheets/json/flexbox.json

---
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @karunk
Instant Answer Page: https://duck.co/ia/view/css_flexbox_cheat_sheet

New Cheat Sheet: CSS Flexbox

---

share/goodie/cheat_sheets/json/language/tamil.json

The current [source url](http://www.linguanaut.com/learnlanguages.html) points to a page that does not exist. This PR adds the [correct source url](http://www.linguanaut.com/learnlanguages.htm). 
@saumyasurendiran 
---
Instant Answer Page: https://duck.co/ia/view/tamil_cheat_sheet

Tamil cheat sheet : Add the correct source URL

---

lib/DDG/Goodie/MD5.pm

Ignores the file extensions in the query.
Fixes #3974 
@pjhampton @gautamkrishnar 
---
Instant Answer Page: https://duck.co/ia/view/md5

MD5: Ignore file extensions

---

share/goodie/cheat_sheets/json/dplyr.json

Dplyr is a library in R to perform various data manipulation tasks with data frame like objects
---
Instant Answer Page: https://duck.co/ia/view/dplyr_cheat_sheet

New dplyr Cheat Sheet

---

share/goodie/cheat_sheets/json/iptables.json

New cheat sheet for a GNU/Linux SysAdmin including commonly used iptables commands, options, and terms
---
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @akiratk0355
IA Page: https://duck.co/ia/view/iptables_cheat_sheet

New Iptables Cheat Sheet

---

share/goodie/cheat_sheets/json/duckpan.json

---
Instant Answer Page: https://duck.co/ia/view/duckpan_cheat_sheet

DuckPAN Cheat Sheet

---

lib/DDG/Goodie/MD5.pm

Escaped the dot in the regular expression for files extensions.
#3974
@moollaza @gautamkrishnar 
---
Instant Answer Page: https://duck.co/ia/view/md5

MD5: Escaped dot

---

t/MD5.t

Added some test examples for the (Ignore files extensions) update.
#3976
@moollaza @mintsoft 
---
Instant Answer Page: https://duck.co/ia/view/md5

md5: Added test examples

---

share/goodie/cheat_sheets/json/json-syntax.json

Fixes #3595
#3595
@edgesince84 @GuiltyDolphin 
---
Instant Answer Page: http://duck.co/ia/view/json_syntax_cheat_sheet 
@vCillusion

Fixes JSON Cheat Sheet #3595

---

share/goodie/cheat_sheets/json/yeoman.json

This Instant Answer provides a cheat sheet to some basic commands to use with the Yeoman application framework.
---
Instant Answer Page: https://duck.co/ia/view/yeoman_cheat_sheet

New Yeoman Cheat Sheet Goodies

---

share/goodie/cheat_sheets/json/android-views.json

New android views cheatsheet
---
Instant Answer Page: https://duck.co/ia/view/android_views_cheat_sheet

New android views cheatsheet

---

.github/PULL_REQUEST_TEMPLATE.md

This PR template update aims to:
- Reflect the redirected focus on improving existing IAs based on user feedback
- Reflect the success of the Fathead PR template
- Encourage better IA Pages and IA testing practices
- Encourage the reviewer merging to merge appropriately
@moollaza 
- This will be used as the Spice PR template as well
- An easy way to view is to copy and paste into a [Gist](https://gist.github.com/)

REPO: New PR template

---

share/goodie/cheat_sheets/json/powershell.json

"There was a typo under switch statement in the powershell cheat sheet that said 'CaseSentitive' instead of 'CaseSensitive'. "
Fixes #3472 
@AnthonyNeace @pjhampton 
- **Source Name** exists if applicable (for "More at {source_name}" link)
**Code**
--- …

powershell_cheat_sheet : Fixed typo under switch statement from "CaseSentitive" to "CaseSensitive"

---

lib/DDG/Goodie/Base.pm
t/Base.t

Fixes an issue where the IA was wrongly being triggered by some form of input
Fixes #3985
@mintsoft @pjhampton @moollaza 
- **Source Name** exists if applicable (for "More at {source_name}" link)
**Code**
---
Instant Answer Page: 
https://duck.co/ia/view/base

Base Conversion : Fixed wrong triggering for this IA

---

share/goodie/cheat_sheets/json/iex.json

Update IEx cheat sheet to Elixir 1.4.2
None
@pjhampton 
**Code**
---
Instant Answer Page: https://duck.co/ia/view/iex_cheat_sheet

IEx Cheat Sheet: Update IEx cheat sheet to Elixir 1.4.2

---

share/goodie/cheat_sheets/json/ggplot2.json

Cheatsheet for http://ggplot2.org/
Screenshot: 
Fixes https://github.com/duckduckgo/zeroclickinfo-goodies/issues/3754
---
Instant Answer Page: https://duck.co/ia/view/ggplot2_cheat_sheet

New ggplot2 Cheatsheet

---

lib/DDG/Goodie/SolarSystem.pm

Changed "a object" into "an object" in the IA abstract.
**Code**
---
Instant Answer Page: https://duck.co/ia/view/solar_system

SolarSystem: Fixed typo error in the abstract

---

share/goodie/cheat_sheets/json/latex.json

Added document writing commands
Fixing issue form Latex #3994 
- **Source Name** exists if applicable (for "More at {source_name}" link)
**Code**
---
Instant Answer Page: https://duck.co/ia/view/latex_cheat_sheet

Added document writing commands

---

share/goodie/public_dns/providers.yml

Fixes #4016: Added public DNS Server's from Freenom World.
@mintsoft 
**Code**
---
Instant Answer Page: https://duck.co/ia/view/public_dns

Fixes #4016: Added public DNS Server's from Freenom World to providers.yml

---

share/goodie/shruggie/shruggiesfriends.json

Added "Table Replace" to Shruggie & Friends.  
---
Instant Answer Page: https://duck.co/ia/view/shruggie
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @epik

added "replace table" to shruggie

---

lib/DDG/Goodie/Timer.pm
share/goodie/timer/timer.js

Pass GoodieBundle version from Perl to JS to fix audio asset loading
---

Goodie: Pass GoodieBundle version from Perl to JS to fix audio asset loading

---

t/Timer.t

Add goodieVersion to test

---

share/goodie/cheat_sheets/json/wireshark.json

Add installation command for arch linux
**Code**
---

Add installation command for arch linux

---

share/goodie/cheat_sheets/json/linux.json

Make use of capitalisation & period consistent.
https://github.com/duckduckgo/zeroclickinfo-goodies/pull/4040#discussion_r108060081
@ManrajGrover
**Code**
---

Linux Cheat Sheet: Make use of capitalisation & period consistent

---

share/goodie/cheat_sheets/json/quackhack.json

Updates the link for the meetup groups on meetup.com
**Code**
---
Instant Answer Page: https://duck.co/ia/view/quackhack_cheat_sheet

Quack & Hack cheatsheet: Updated meetup.com URL

---

share/goodie/cheat_sheets/json/quackhack.json

Made the meetup.com and duckduckhack.com links HTTPS.
**Code**
---
Instant Answer Page: https://duck.co/ia/view/quackhack_cheat_sheet

Quack & Hack cheatsheet: Updated links to HTTPS

---

share/goodie/cheat_sheets/json/epl.json

Removed the relegated teams after the 2016 season and added the promoted teams from Championship and updated the current title holder.
@gautamkrishnar  @moollaza 
- **Source Name** exists if applicable (for "More at {source_name}" link)
**Code**
--- …

EnglishPremierLeagueCheatSheet: Updated the participated teams. 

---

share/goodie/cheat_sheets/json/awesome-window-manager.json

The current URL "works", but it's a redirect. It should use the new URL
in case the redirect is later removed.
This fixes #4036.
**Code**
---
Instant Answer Page: https://duck.co/ia/view/awesome_window_manager_cheat_sheet

AWM Cheat Sheet: Update source url

---

share/goodie/cheat_sheets/json/npm.json

Use npm short forms '-S', '-O', and '-D' in the cheat-sheet to provide maximum productivity.
**Code**
---
Instant Answer Page: https://duck.co/ia/view/npm_cheat_sheet

NPM Cheat Sheet: Short versions for save to be consistent with -g

---

lib/DDG/Goodie/Chars.pm
share/goodie/shruggie/shruggiesfriends.json
t/Chars.t

Fixes #4028 for Chars IA.
-> I set the trigger location to be the start of the string
-> I removed the triggers 'chars' and 'length of string' as they get confused with programmer requests
-> I removed the trigger 'characters count' as it wasn't very intuitive
-> I added the word 'of' to be removed from the character count when it is a leading word
-> I updated the chars.t test file to reflect these changes
- All **Example Queries** trigger on …

Chars: Reduce overtriggering

---

lib/DDG/Goodie/Calculator.pm
share/goodie/calculator/calculator.css
share/goodie/calculator/calculator.handlebars
share/goodie/calculator/calculator.js
share/goodie/calculator/content.handlebars
share/goodie/calculator/title_content.handlebars
t/Calculator.t

Add Basic calculator UI to existing calculator IA. Now on [beta.duckduckgo.com](https://beta.duckduckgo.com/?q=10+*+234&t=hd&ia=answer)
----
Fixes https://github.com/duckduckgo/zeroclickinfo-goodies/issues/4020
@moollaza 
**Code**
--- …

Calculator: [Phase 1] Add basic calculator

---

lib/DDG/Goodie/Calculator.pm
share/goodie/calculator/calculator.css
share/goodie/calculator/calculator.js
share/goodie/calculator/content.handlebars
t/Calculator.t

Calculator: Phase 2 -- PR Against pjhampton/calculator

---

lib/DDG/Goodie/Timer.pm
t/Timer.t

Added trigger words of `hrs, mins, secs, hours, minutes, seconds`.
Removed one unnecessary test, which should trigger the IA.
Fixes #4038 
@pjhampton 
**Code**
---

Timer: Fixing trigger

---

t/Passphrase.t

Add's support for `-` in passphrase words. There are 4 in words.txt (e.g. "yo-yo", "drop-down").
Without this, the tests are susceptible to failure.
**Code**
---
Instant Answer Page: https://duck.co/ia/view/passphrase

Passphrase: Add dash to regex accepted characters

---

lib/DDG/Goodie/Dice.pm
t/Dice.t

This PR will set an upper limit on the max dice rolls to be 10 and max number of sides per side to be 31.
Fixes #3989
@mintsoft, @pjhampton, @moollaza 
**Code**
---
Instant Answer Page: https://duck.co/ia/view/dice

Dice: Fixes #3989 Set upper limit on max dice rolls and number of sides per dice

---

share/goodie/duck_duck_go/responses.yml

Removes Instant Answer for the DuckDuckGo XMPP service, [which is shutting down](https://duck.co/blog/post/4/xmpp-services-at-duckduckgo).
@jkv 
**Code**
---

DuckDuckGo Responses: Removed XMPP entry

---

lib/DDG/Goodie/Calculator.pm
share/goodie/calculator/calculator.js
share/goodie/calculator/content.handlebars
share/goodie/calculator/ledger_item.handlebars

Implements Phase 3 - Ledger (History). Reloading + Calculation continuation available.
Continues: https://github.com/duckduckgo/zeroclickinfo-goodies/pull/4067
Fixes: #4066
@moollaza 
@bsstoner 
@russellholt 
**Code**
---
Instant Answer …

Calculator: [Phase 3] Add History / Calc reloading

---

share/goodie/calculator/calculator.js

This updates the signal for the calculator IA so it opens on a medium signal instead of a low one.
https://app.asana.com/0/inbox/246900294405161/318733718583130/318772374958320
@moollaza 
**Code**
--- …

Calculator: Update signal

---

share/goodie/calculator/calculator.css
share/goodie/calculator/calculator.js

- Updated CSS to apply `user-select: none` only to the scientific and basic calculator tabs
- Add better support for Numpad keys in certain browsers (e.g. Safari)
**Code**
---

Calculator: Allow user-select on history ledger, Add support for Numpad

---

share/goodie/calculator/calculator.js

It introduces the ability to do multi factorial operations such as `3!!`, `4!!!!` and `(5!)!`
I also cleaned up some code.
https://app.asana.com/0/246900294405162/319472456064055
Based on user request
@moollaza 
**Code**
---
Instant …

Calculator: Support multi factorial operations

---

share/goodie/calculator/calculator.js

The initial plan was to update the PercentNormalizer object to include multiplyPercent and dividePercent, but this has since been abandoned because other search engines don't provide this function and Wolfram alpha also doesn't agree with this logic.
This PR: 
- Removes the TODO notes
- Improves triggering / calc handling with percent operations
- Refactors `addPercentage` in an attempt to make it less verbose
- https://app.asana.com/0/246900294405162/319472456064058
- https://app.asana.com/0/246900294405162/319472456064059
@moollaza 
- The …

Calculator: Update / Refactor Percent Normalizer

---

lib/DDG/Goodie/AsciiTable.pm
share/goodie/ascii_table/triggers.txt
t/AsciiTable.t

Fixes #4107 
**Code**
---
Instant Answer Page: https://duck.co/ia/view/ascii_table

ASCII Table: Add additional trigger words

---

lib/DDG/Goodie/CalendarToday.pm
t/CalendarToday.t

Fixes #4102 Calendar: Shouldn't trigger on query for calendar.google.com
In case when there is no remainder, there is now a check to only proceed if query_lc is set to 'calendar'.
@pjhampton @moollaza @Mailkov 
**Code**
---
Instant Answer …

Calendar: Shouldn't trigger on query for calendar.google.com Fixes #4102 

---

lib/DDG/Goodie/Conversions.pm
share/goodie/conversions/ratios.yml
t/Conversions.t

Conversions: This PR fixes some of the triggers mentioned in #4112 
This PR resolves some of the mentioned triggering issues for conversions IA
Fixes #4112 
@pjhampton @mintsoft 
**Code**
--- …

Conversions: Improve triggering

---

lib/DDG/Goodie/Calculator.pm
lib/DDG/Goodie/PercentOf.pm
t/Calculator.t

Deprecating [Percent Of](https://duck.co/ia/view/percent_of). It's a confusing user experience to not show the calc. I have merged the tests and triggering into the [Calculator](https://duck.co/ia/view/calculator) Instant Answer. 
n/a
@moollaza 
**Code** …

Calculator: Add Percent Of trigger / tests to Calculator

---

lib/DDG/Goodie/AsciiTable.pm
share/goodie/ascii_table/triggers.txt
t/AsciiTable.t

Improves triggering as discussed in #4111
#4111 
@pjhampton @moollaza 
**Code**
---
Instant Answer Page: https://duck.co/ia/view/ascii_table

AsciiTable: Improves triggering

---

share/goodie/geometry/geometry.js

Switch JS from temporary `geometry_goodie` id to correct `geometry` id
@bsinger98 
**Code**
---
Instant Answer Page: https://duck.co/ia/view/geometry

Fix Goodie ID in JS

---

lib/DDG/Goodie/Calculator.pm
t/Calculator.t

This PR removes the portion of the regex I added to handle numbers with units. This pattern, combined with `query_nowhitespace` makes it too easy to trigger on irrelevant queries.
Once we add the ability for the Goodie to prevent showing the UI, we can try and bring this back with more logic to ensure the query is valid.
Fixes: https://github.com/duckduckgo/zeroclickinfo-goodies/issues/4127 …

Calculator: Tighten regex, update tests

---

share/goodie/calculator/calculator.js

Fixes the rounding errors described here: 
https://twitter.com/PontoonDock/status/856947909606211585
https://app.asana.com/0/inbox/246900294405161/328040889249394/328049587646152
@moollaza 
**Code**
---

Calculator: Fix rounding errors.

---

lib/DDG/Goodie/Conversions.pm
t/Conversions.t

**Conversions IA**: This PR makes the queries flexible as mentioned in comment of #4118 
Improves triggering
Continuing #4118 
@moollaza @mintsoft
**Code**
---

Conversions: Makes conversion queries more flexible

---

lib/DDG/Goodie/Timer.pm
t/Timer.t

It will stop invoking Timer IA on ambigous cases.
Fixes #4089 
**Code**
---

Timer IA: triggering on edge cases fixed. (#4089)

---

.travis.yml
spec/support/jasmine.json

- Add jasmine to `.travis.yml`, installs and executes jasmine
- Add generated jasmine.json file to repo
This will enable us to start unit testing out Instant Answer JavaScript 😃 
You can see this in action in the JS Conversions PR: #4135 

Add Jasmine.js to Goodies repo

---

share/goodie/geometry/objectInfo.yml

This PR does minor changes to the answers displayed by this IA.
This PR does small changes in its `yaml` file (formatting the results to be displayed)
**Code**
--- …

Geometry IA: Formatting the answers

---

share/goodie/cheat_sheets/json/javascript.json

**JavaScript (Core) Cheat Sheet**: This PR fixes the `more at` URL mentioned in #4146 
Fixes #4146 
@pjhampton 
**Code**
---
Instant Answer Page: https://duck.co/ia/view/javascript_cheat_sheet

JavaScript (Core) CheatSheet: Fixes #4146 broken more at link

---

.travis.yml
package.json
share/goodie/conversions/conversions.js
share/goodie/conversions/triggers.yml
spec/conversions_spec.js

Spelling fix. Failed before hand
Based on slack discussion
Fixes: https://github.com/duckduckgo/zeroclickinfo-goodies/issues/4163
@moollaza 
@mintsoft 
**Code**
---

Conversions: Fixed spelling of cmH2O and Cups, Fixes FE-Tests

---

lib/DDG/Goodie/PrimeFactors.pm
t/PrimeFactors.t

Previously, PrimeFactors could not detect a trigger of the form "is 83 prime". The following changes were made to fix this issue:
- Added check to regex guard if query matches form "is <number> prime"
- Strips all preceeding non-digit characters from remainder
- Includes test cases for new trigger
Fixes #2799
@moollaza @stevenmg @austinheimark 
**Code** …

PrimeFactors: Improve triggering

---

lib/DDG/Goodie/Conversions.pm
share/goodie/conversions/conversions.css

- Adjust design to stack input and select on desktop
- Reduce desktop width to 80%
- Increase input font size
**Code**
---

Conversions: Use stacked input/select on desktop

---

lib/DDG/Goodie/Timer.pm
t/Timer.t

This IA fix adds the phrase "count down" to the list of triggers for the Timer IA.
Fixes #4167 
@mattr555 @spagy 
**Code**
---

Timer: Trigger on "count down timer"

---

share/goodie/conversions/conversions.js
share/goodie/conversions/triggers.yml
spec/conversions_spec.js
t/Conversions.t

Adds missing area units
Fixes: https://github.com/duckduckgo/zeroclickinfo-goodies/issues/4171
**Code**
---

Conversions: Add in missing area units. 

---

share/goodie/conversions/conversions.js
share/goodie/conversions/triggers.yml
t/Conversions.t

Adds frequency conversions such as hertz -> kilohertz
I think this is good to go. If anybody can spot some quick wins, just shout!
n/a
cc/ @duckduckgo/community-leaders 
**Code**
--- …

Conversions: Enable Frequency Conversions

---

share/goodie/conversions/conversions.js
share/goodie/conversions/triggers.yml
spec/conversions_spec.js
t/Conversions.t

This PR adds the missing units for force type conversion
Fixes #4174 
@pjhampton @mintsoft 
**Code**
---

Conversions: Adds missing units for Force conversion type

---

lib/DDG/Goodie/Conversions.pm
share/goodie/conversions/conversions.js
share/goodie/conversions/triggers.yml
spec/conversions_spec.js
t/Conversions.t

Adds the remaining duration units. 
Fixes: https://github.com/duckduckgo/zeroclickinfo-goodies/issues/4172
@mintsoft @moollaza 
**Code**
---

Conversions: Add in missing duration units.

---

share/goodie/conversions/conversions.js
share/goodie/conversions/triggers.yml
spec/conversions_spec.js
t/Conversions.t

Added kilo/mega/giga/tera/peta/exawatt conversions
Fixes #4177 
@pjhampton 
**Code**
---

Conversions: Add missing units (POWER)

---

share/goodie/cheat_sheets/json/linux.json

Add sed command example 
**Code**
---

Linux Cheat Sheet: Add sed command example

---

lib/DDG/Goodie/Timer.pm
t/Timer.t

This change will replace from using raw string to more normalized string.
Discussed in pull request [4134](https://github.com/duckduckgo/zeroclickinfo-goodies/pull/4134)
@moollaza 
Instant Answer Page:  https://duck.co/ia/view/timer

Timer: Changed query_raw to query_lc

---

share/goodie/conversions/triggers.yml
t/Conversions.t

enables queries such as `28 deg c to f`
Internal discussions
@bsstoner 
**Code**
---

Conversions: add 'deg' to temperature aliases

---

share/goodie/calculator/calculator.js

Removes 0 on bail
https://app.asana.com/0/inbox/246900294405161/314049407432152/314049360427352
@moollaza 
@bsstoner 
**Code**
---

Calculator: Removes 0 on bail

---

share/goodie/conversions/conversions.js
share/goodie/conversions/triggers.yml
spec/conversions_spec.js
t/Conversions.t

Adds missing energy units
Fixes: https://github.com/duckduckgo/zeroclickinfo-goodies/issues/4173
@moollaza 
**Code**
---

Conversions: Add missing energy units.

---

share/goodie/conversions/content.handlebars
share/goodie/conversions/conversions.css
share/goodie/conversions/conversions.js

Remove forced 100% width on select to allow custom dropdown arrow
@pjhampton 
**Code**
---

Conversions: Remove forced 100% width on select to allow custom dropdown arrow

---

lib/DDG/Goodie/Calculator.pm
share/goodie/calculator/calculator.js

https://app.asana.com/0/inbox/246900294405161/351128734898313/351128734898315
@bsstoner @moollaza 
**Code**
---

Calculator: Fixes onload js issue / Patch triggering

---

share/goodie/calculator/calculator.js

Fixes keyboard bug in firefox.
Fixes: https://github.com/duckduckgo/zeroclickinfo-goodies/issues/4233
@bsstoner 
**Code**
---

Calculator: Allow keyboard input in firefox.

---

share/goodie/cheat_sheets/json/sublime-text.json

**Sublime Text 2 Cheat sheet**: This PR updates the aliases for sublime text 2
Updates the aliases
@sahildua2305 @pjhampton 
**Code**
---
Instant Answer Page: https://duck.co/ia/view/sublime_text_cheat_sheet

Updating the aliases for sublime 2

---

share/goodie/calculator/calculator.js

Allows queries from the search bar with comma's in them
Fixes: https://github.com/duckduckgo/zeroclickinfo-goodies/issues/4236
@tagawa 
**Code**
---

Calculator: Fix bail on commas issue

---

share/goodie/calculator/calculator.js

Allows queries such as 100 + 150%
@moollaza @bsstoner 
**Code**
---

Calculator: Fix non-whole expression rewriting

---

lib/DDG/Goodie/MolarMass.pm

There was some weird syntactical error that was throwing a runtime error due to a perl version mismatch. This should be fixed now. I'm really surprised this wasn't picked up in the automated testing. Sorry for the trouble everyone!
n/a
@joshliu cc/ @bsstoner  
**Code** …

MolarMass: Fix syntactical error.

---

share/goodie/cheat_sheets/json/elementary.json

Cheat Sheets : resolved error #4247
"Fixes #4247"
IA Page: http://duck.co/ia/view/elementary_cheat_sheet
@adab4d
@typo
**Code**
---

Elementary Cheat Sheets: resolved issue #4247

---

share/goodie/conversions/conversions.css

These changes ensure that the dropdown text does not overlap the dropdown icon. This is particularly noticeable on mobile.
@pjhampton 
**Code**
---

Conversions: Fix dropdown text overlapping

---

share/goodie/cheat_sheets/json/iptables.json

This fixes the following warning from travis.cli:
```
```
**Code**
---
Instant Answer Page: https://duck.co/ia/view/iptables_cheat_sheet

Iptables white space triggering travis warning 

---

share/goodie/cheat_sheets/json/svn.json

Add descriptions for svn log and its parameters -l and -v. Fixes #4268.
Fixes #4268.
**Code**
---
Instant Answer Page: http://duck.co/ia/view/svn_cheat_sheet

SVN Cheat Sheet: Add description for "svn log"

---

share/goodie/cheat_sheets/json/cpp-streams-io.json

This change addresses a warning from `travis.cli`:
```
```
**Code**
---
Instant Answer Page: https://duck.co/ia/view/cpp_streams_io_cheat_sheet

add missing description on cpp-streams-io

---

lib/DDG/Goodie/Conversions.pm
share/goodie/conversions/conversions.js
share/goodie/conversions/triggers.yml
t/Conversions.t

* Allow for a single unit input with an amount to be converted.
E.g. "35 cm", "1 acre", "200 lbs"
**Note**: Because we use word triggers, only single-unit queries where the number and unit are separated by a space (or dash) will work. A query like "35m" will not trigger currently. We may enable that later with internal triggering improvements.
* Lowercased additional units in the YAML that don't require case-sensitive comparisons. And added case-insensitive check comparing lowercased match against symbol. This will allow all the energy units to use lowercased units in queries. 
E.g. "covert w to kw", "35kw to w"
* Corrected the symbol for kilojoules so that queries like `3 kj to j` will work.
@pjhampton 
**Pull …

Conversions: Support single unit input, case-insensitive fallback check

---

share/goodie/cheat_sheets/json/systemd.json

New **Systemd CheatSheet** 
This is a cheat sheet for systemd commands for managing system
https://duck.co/ia/view/systemd_cheat_sheet
**Code**
---
Instant Answer Page: https://duck.co/ia/view/systemd_cheat_sheet

CheatSheet: New Systemd Cheatsheet

---

share/goodie/color_codes/color_codes.css

ColorCode: The columns in the color code IA were misaligned. This is a 1 line CSS change.
Issue is : 
[Current Error] https://duckduckgo.com/?q=%23bb0000&t=ffab&ia=answer
[Expected] https://duckduckgo.com/?q=%23123123&t=ffab&ia=answer 
@moollaza 
**Code** …

ColorCode: Fixed alignment of columns in IA

---

share/goodie/conversions/conversions.css

Reduced font-size to improve UX as requested by design
@moollaza 
**Code**
---

Conversions: reduced font-size

---

CONTRIBUTING.md

New local contributing md page. Approved version will be rolled out across the DDH ZCI repos. Thoughts? [See it live](https://github.com/duckduckgo/zeroclickinfo-goodies/blob/pjhampton/repo--update-contributing/CONTRIBUTING.md)
@moollaza @ManrajGrover 
Maybe @tagawa wants to weigh in too.
---
Instant Answer Page: n/a

Repo: Update CONTRIBUTING.md

---

share/goodie/conversions/conversions.js
share/goodie/conversions/triggers.yml

erg is wrongly defined in math.js
```
> math.eval('1 erg to joule')
{ [String: '1e-5 joule']
units: [ { unit: [Object], prefix: [Object], power: 1 } ],
dimensions: [ 1, 2, -2, 0, 0, 0, 0, 0, 0 ],
value: 0.00001,
fixPrefix: true,
isUnitListSimplified: true }
```
This PR adds a work around. It's not possible to monkey patch, so that's why I went with the name `ergfixed`
@moollaza 
cc/ @bsstoner 
**Code**
---

Conversions: Workaround math.js erg bug

---

share/goodie/conversions/langTriggers.yml

removes duplicate trigger
**Code**
---

Conversions: Removed duplicate from lang triggers.

---

share/goodie/conversions/conversions.js

**Due to popular demand,** we're moving away from e notation into fixed numbers. 🎉 
The precision is determined by the length of the users input, but never greater than 7.
n/a
@moollaza 
**Code**
--- …

Conversions: Long numbers instead of e notation.

---

lib/DDG/Goodie/Conversions.pm
share/goodie/conversions/langTriggers.yml
share/goodie/conversions/triggers.yml
t/Conversions.t

This PR: 
1. Lets in some unambiguous abbreviations (cm, mm, kgs, etc) through.
2. Adds a couple of aliases
n/a
@moollaza 
**Code**
---

Conversions: Expand abbreviation triggering

---

lib/DDG/Goodie/Conversions.pm
share/goodie/conversions/langTriggers.yml
share/goodie/conversions/triggers.yml
t/Conversions.t

Adds popular general triggers that we're not hitting such as:
- convert
- conversion
- conversion calculator
- metric conversion calculator
- convertidor (Spanish for converter)
- convertisseur (French for converter)
@moollaza 
**Code** …

Conversions: Add general triggers. Add aditional aliases.

---

lib/DDG/Goodie/Calculator.pm
share/goodie/calculator/calculator.js
t/Calculator.t

Sorry this PR took so long... working on other issues.
- **This PR requires the latest version of Math.js**
- Fixes a load of issues (See Section 2)
- Fixes so correct answer shows when the user enters `0/0` == Error
- Calculator was showing weird rounding issue
- Now handling multiplications as space properly. ie `2^2 5` via UI
- bails on spaces in query such as `5 232 + 234 * 2` as other search engines do
- Calculator now handles modulo from search bar
- Now impossible to use the percentage sign as a modulo operator in the UI
- Stops showing hideous evaluated expression in subbar
- Handles queries such as `log of 5 plus 10 mult 8`
Fixes: #4253
Fixes: #4279  
Fixes: #4166 
Fixes: #3933
Fixes: #3861 
Fixes: #1364 
@moollaza 
cc/ @mintsoft you might want to weigh in too
To be completed by …

Calculator: Various improvements.

---

lib/DDG/Goodie/Conversions.pm
share/goodie/conversions/langTriggers.yml
t/Conversions.t

Adds **10,000 new triggering opportunities** (postfixes) such as:
- cm calculator
- grams calc
- fluid ounce converter
- miles conversion
etc etc
@moollaza 
cc/ @mintsoft @bsstoner 
**Code**
--- …

Conversions: Add expanded triggers.

---

lib/DDG/Goodie/Conversions.pm

Fixes the spelling of a var
@moollaza 
**Code**
---

Conversions: Fixes var spelling

---

lib/DDG/Goodie/Calculator.pm
t/Calculator.t

- Adds factorial support.
- Improves modulo support
- Reduces overtriggering (IAFD from pixel)
Fixes: #1917 
Fixes: #2778
@moollaza 
**Code**
---

Calculator: Improve factorial/modulo support. IAFD Fixes

---

lib/DDG/Goodie/Calculator.pm
share/goodie/calculator/calculator.js
t/Calculator.t

This fixes up the trig (tan,sin,cos) functions
Fixes: #4340 on the side with another `1/(x)` ui error.
@moollaza 
**Code**
---

Calculator: Fixes up trig functions.

---

lib/DDG/Goodie/Poker.pm
t/Poker.t

- Converts poker goodie to structured answer
- Replace tabs with spaces
- Add negative tests
#1163
@moollaza @mintsoft 
**Code**
---
Instant Answer Page: https://duck.co/ia/view/poker

Poker: Convert to structured answer

---

lib/DDG/Goodie/RandomName.pm
t/RandomName.t

Converting random_name to return structured answer
https://github.com/duckduckgo/zeroclickinfo-goodies/issues/1163
**Code**
---
Instant Answer Page: https://duck.co/ia/view/random_name

converting random_name to return structured answer

---

lib/DDG/Goodie/Factors.pm
t/Factors.t

Factors: Add support for factoring negative numbers. Also add negative cases to test, and tidy code.
Fixes #4245. For thoroughness' sake, first confirmed that the mathematically correct process for finding factors for a negative number involves the following steps:
* Find positive factors
* Duplicate positive factors and change sign
* Sort in ascending order
* Concatenate with sorted positive factors
Implemented function as described above. Also, there were no negative cases in the test, so added two negative tests according to testing standards. Tidied code with perltidy.
@pjhampton @austinheimark @keeganjk
- The **Title** is appropriately …

Factors: Add support for negative numbers. Add negative cases and tidy (#4245)

---

lib/DDG/Goodie/TextConverter.pm
share/goodie/text_converter/content.handlebars
share/goodie/text_converter/text_converter.css
share/goodie/text_converter/text_converter.handlebars
share/goodie/text_converter/text_converter.js
share/goodie/text_converter/text_converter.yml
t/TextConverter.t

The new Text Converter IA
**Code**
---

New Text Converter IA

---

lib/DDG/Goodie/Calculator.pm
share/goodie/calculator/calculator.js
share/goodie/calculator/content.handlebars
t/Calculator.t

- stop triggering on queries such as `ecos, e2e4, (20, X.509, )9, 784)((`, 
- Stop `Lne, tane, cose` from triggering. Based on Click throughs people aren't looking for `cos(e)` etc
- `44 EE pi` now working in UI
- Support `exp()` function (search bar only)
- Removes `sec` and `csc` - better handled by symbolab IA
- Stop triggering on `7/11` - it's a store!
- stop triggering on `e+` form
- Suppressed the rounding in the evaluated expression
- Support inverse trig from search bar (search bar only)
- atan / arctan
- acos / arccos
- asin / arcsin
- sinh / asinh
- cosh
- tanh
- Added error text back
- Add cubic operations (^3) via search bar
- Reign in triggering on square roots (dep https://duck.co/ia/view/calc_roots and close issues)
- Add support for the ° symbol
- Makes it easier to expand …

Calculator: Various Fixes

---

share/goodie/calculator/calculator.css
share/goodie/calculator/calculator.js
share/goodie/calculator/content.handlebars

- Prevent mouseup from firing to prevent selected text in calculator from losing focus
- Update CSS styles to indicate calculator input hover and focus state
- Update keyhandler to allow Cmd + C in Firefox to copy text
Fixes: #4341 
@mintsoft 
**Code**
---

Calculator: Fix text selection/copy for Firefox

---

lib/DDG/Goodie/Palindrome.pm
t/Palindrome.t

- Convert to structured answer.
- Don't match for "what is a palindrome".
- Add negative tests.
- Replace tabs with spaces.
#1163
@moollaza @mintsoft
**Code**
---
Instant Answer Page: https://duck.co/ia/view/Palindrome

Palindrome: Convert to Structured

---

lib/DDG/Goodie/Timer.pm
t/Timer.t

Improves coverage for language based queries such as:
> start a timer for 20 minutes
> set a timer to 60 minutes
This is reflected in the autocomplete and user feedback
**Code**
---

Timer: Improve coverage.

---

lib/DDG/Goodie/Calculator.pm

Allows the `asinh` and `acosh` functions to through the triggering guard.
**Code**
---

Calculator: asinh and acosh support

---

.travis.yml

Postpones Trusty (14.04.5 LTS) move and keeps the builds against Precise (12.04.5 LTS)

Repo: Update travis config

---

share/goodie/tips/content.handlebars

**Here is the story**:
I was just calculating tip for my bill using tip calculator but then I when I changed the no of person to 2 using arrow button the tip amount divided into two which was fine and then i just casually started playing with the arrow button and then I noticed something that if we set the number of people to 0 using arrow button then the bill shows the same result as when `number` of people = 1`. 
This PR sets min attribute to 1
**Further Improvements** :
I know somebody can still trick this by typing it manually but at least it will complain them by placing a red border around the input box and asking them politely `select  a value no less than 1` instead. 
Right now every input accepts letters and even negatives numbers, and adds to unnecessary processing which we …

Tips: Sets min attribute to 1

---

share/goodie/cheat_sheets/json/pandas.json

There was a trailing ")" on line 95 as reported in issue #4382.
**Fixes #4382.** Fixed a typo: There was a trailing ")" in line 95. 
**Code**
---
Instant Answer Page: https://duck.co/ia/view/pandas_cheat_sheet

Pandas: Fixed typo

---

share/goodie/calculator/calculator.css

Adds a dark theme to the calculator
cc/ @abeyang 
**Code**
---

Calculator: Add dark theme.

---

share/goodie/text_converter/text_converter.css
share/goodie/text_converter/text_converter.js

Adds padding to binary output.
@moollaza 
**Code**
---

Text Converter: Add padding to binary output

---

share/goodie/cheat_sheets/json/aptitude.json

Cheat Sheet: Aptitude cheat sheet. Mainly shortcuts about how to manage packages of the Debian distribution.
None.
@ManrajGrover
**Code**
---
Instant Answer Page: https://duck.co/ia/view/aptitude_cheat_sheet

New Aptitude Cheat Sheet

---

README.md

It took me a about an hour of trial-and-error before I found a link to the _DuckDuckHack Docs_ book inside the template module. I think it would be way more useful if this link was nearer the top of the README.
duckduckgo/zeroclickinfo-spice#3381
**Code** …

Docs: Add a link to the DuckDuckHack Docs

---

lib/DDG/Goodie/Conversions.pm
share/goodie/conversions/triggers.yml
t/Conversions.t

- Fixes temperature ambiguity.
- celsius to Fahrenheit
- Fahrenheit to Celcius 
- centigrade to Celcius 
- Defaults to US types if the user is in the US and has requested a generic term
- cup -> us cup (if in us), otherwise imperial cup
- Adds some more aliases
**Code** …

Conversions: US locale defaulting

---

lib/DDG/Goodie/Conversions.pm
share/goodie/conversions/triggers.yml
t/Conversions.t

Fixes: #4405
Fixes: #4371
**Code**
---

Conversions: Add case sensitivity. Fix ambiguity collisions

---

lib/DDG/Goodie/Geometry.pm

Fixes https://github.com/duckduckgo/zeroclickinfo-goodies/issues/4414
**Code**
---
Instant Answer Page: https://duck.co/ia/view/geometry

Geometry: keys on hashref is fatal under perl 5.24

---

share/goodie/conversions/triggers.yml
t/Conversions.t

Adds `micron` alias to Micrometers
@moollaza 
**Code**
---

Conversions: Add micron alias.

---

share/goodie/calculator/calculator.css
share/goodie/calculator/calculator.js
share/goodie/calculator/content.handlebars

- Simplified click handling; only apply focus when necessary
Fixes #4409 
**Code**
---

Calculator: Fix text selection across all browsers

---

lib/DDG/Goodie/PrimeFactors.pm

Not sure why, but there was an extra character in the tr which was throwing a warning for me
**Code**
---
Instant Answer Page: https://duck.co/ia/view/prime_factors

PrimeFactors: there appears to be an extra character in the tr/// ?

---

lib/DDG/Goodie/Tips.pm

The smartmatch operator is defined as experimental in perl 5.18  or above, its use is discouraged for production use until the behaviour is better defined : http://search.cpan.org/dist/perl-5.18.0/pod/perldelta.pod#The_smartmatch_family_of_features_are_now_experimental
It'll give a warning when used.
**Code**
**Pull Request Review …

Tips: Removing smartmatch in favour of grep

---

lib/DDG/Goodie/Passphrase.pm
lib/DDG/Goodie/Password.pm

The old Passphrase implementation used the builtin random generator and didn't even seed it on every request. Therefore, you'd get the same passphrase on multiple requests. This PR implements a random function based on [Crypt::URandom](https://metacpan.org/pod/Crypt::URandom).
While fixing the Passphrase goodie I also noticed the Password one [suffers from a similar problem](https://github.com/duckduckgo/zeroclickinfo-goodies/issues/3509#issuecomment-310729022) and plugged the same random function in there, though I'd love a recomendation on how I should only define the function once as it currently is copy-pasted from one file to the other (please don't get mad 😞).
Fixes #3509 
@kirkins  …

Passphrase, Password: Implemented secure random

---

share/goodie/cheat_sheets/json/lol.json

This Instant Answer responds to user's queries such as "lol cheat sheet" or "lol commands" with a cheat sheet containing all the Hotkeys and Chat Commands available in the popular MOBA game, League of Legends.
**Code**
---
Instant Answer …

New League of Legends Cheat Sheet

---

lib/DDG/Goodie/Unidecode.pm
t/Unidecode.t

Just converting the IA to return a structured_answer and use templates
Instant Answer Page: 
This is just converting the IA to use a template instead of returning HTML
Part of #1163
@pjhampton @moollaza 
**Code**
--- …

Unidecode: Convert to use template

---

lib/DDG/Goodie/Geometry.pm
share/goodie/text_converter/text_converter.js

Fixes the conversion errors with hex/bin/base64. 
Fixes: https://github.com/duckduckgo/zeroclickinfo-goodies/issues/4411
@moollaza 
**Code**
---

TextConverter: Fix hex/bin/base64 conversion bugs.

---

share/goodie/cheat_sheets/json/vim.json

Add moving on line based on instances of a search
**Code**
---

Vim Cheat Sheet: Add moving on line based on instances of a search

---

.github/PULL_REQUEST_TEMPLATE.md

It looks like the content for this page was moved when the programming mission [was removed](https://github.com/duckduckgo/duckduckhack-docs/commit/ce835742c9d0ee21ce8ff5ea90538a9a4b889a21) from the docs.
Bug was noticed in #4432
**Code** …

Goodies: fix broken link in template

---

share/goodie/cheat_sheets/json/tmux.json

Added:
- Close current window
- Previous/Next window
- Delete session
---
Instant Answer Page: https://duck.co/ia/view/tmux_cheat_sheet

Update cheat sheets of tmux

---

share/goodie/cheat_sheets/json/recycle.json

This cheat sheet is intended to aid the user in understanding what plastics can be recycled to help them sort their trash and make them more aware of the recyclability of the plastics they buy. The user is presented with definitions of plastic recycling numbers, how recyclable the plastic is by number, and examples of plastics by number.
https://duck.co/ia/view/recycle_cheat_sheet
**Code**
- …

New Recycle Cheat Sheet

---

share/goodie/cheat_sheets/json/c.json

If this is something else:
C cheatsheet: Added pointers to c cheatsheet
@harisphnx 
**Code**
---
Instant Answer Page: https://duck.co/ia/view/c_cheat_sheet

C cheatsheet: Added pointers to c cheatsheet

---

lib/DDG/Goodie/SumOfNaturalNumbers.pm
t/SumOfNaturalNumbers.t

This returns a structured answer for sum of natural numbers.
#1163
**Code**
---
Instant Answer Page: https://duck.co/ia/view/sum_of_natural_numbers

sumOfNaturalNumbers: Convert to structured answer

---

share/goodie/cheat_sheets/json/telegram-desktop.json

Add cheat sheet for Telegram Desktop:
- Keyboard Shortcuts.
---
Instant Answer Page: https://duck.co/ia/view/telegram_desktop_cheat_sheet

New Telegram Desktop Cheat Sheet

---

share/goodie/pi/pi.css

Fixing: https://github.com/duckduckgo/zeroclickinfo-goodies/pull/4217#pullrequestreview-57063445
@moollaza 
**Code**
---
Instant Answer Page: https://duck.co/ia/view/pi

Pi: CSS selectors need to be namespaced

---

share/goodie/cheat_sheets/json/qutebrowser.json

This adds a new cheat sheet for [qutebrowser](http://qutebrowser.org/), a open source web browser based on PyQt and qtwebengine/qtwebkit. It features DuckDuckGo as it's default searchengine and homepage.
Please let me know if you have any issues with this PR and I'll fix them! I'm also happy to squash these commits into one if you prefer that, let me know what you think.
Here is a render of the initial version to save time there:
Closes https://github.com/qutebrowser/qutebrowser/issues/2894
@The-Compiler
- The **Description** is clear and …

New Qutebrowser CheatSheet Goodie

---

lib/DDG/Goodie/Pi.pm
t/Pi.t

This fixes the issue where the Pi Goodie would trigger beyond the max digits provided by the Goodie. 
The issue was related to the max digits being calculated by the length of pi, problem being that `3.` was included in the calculation of length.
#4440
**Code** …

Pi: correct parsing for max length

---

share/goodie/cheat_sheets/json/scapy.json

https://duck.co/ia/view/scapy_cheat_sheet
**Code**
---
Instant Answer Page: https://duck.co/ia/view/scapy_cheat_sheet

Addition of Scapy cheat sheet goodie

---

share/goodie/duck_duck_go/responses.yml
t/DuckDuckGo.t

DuckDuckGo: Update https refs

---

lib/DDG/Goodie/Geometry.pm
share/goodie/geometry/objectInfo.yml
share/goodie/geometry/svg/triangle.svg
t/Geometry.t

This PR adds support for triangle area in the Geometry Instant Answer. I also added "of an" as a trigger word, because I noticed that only "of a" was included. This meant that searching "area of an equilateral triangle" didn't trigger anything, but "area of a equilateral triangle" did. Presumably this is because "equilateral triangle" is the only shape right now that starts with a vowel, but I figure it couldn't hurt (others that this will be relevant for when they have a Geometry IA - oval, ellipse, octagon).
I added 2 tests - one for equilateral triangle and one for triangle. I also made sure that the `duckpan query` and `duckpan server`, and `duckpan test` looked good.
Here is the relevant IA - https://duck.co/ia/view/geometry.
Fixes #4286 
Maintainer of Geometry: @pixunil
To be …

Geometry: Add Triangle Area

---

share/goodie/cheat_sheets/json/prolog.json

https://duck.co/ia/view/prolog_cheat_sheet
**Code**
---
Instant Answer Page: https://duck.co/ia/view/prolog_cheat_sheet

New Prolog Cheat Sheet

---

share/goodie/cheat_sheets/json/xlrd.json

New XLRD cheat sheet

---

share/goodie/cheat_sheets/json/lolcode.json

Provides an overview of the basic syntax and data types used in LOLCODE.
IA Page : https://duck.co/ia/view/lolcode_cheat_sheet
The cheat sheet has been tested on the duckpan server.
**Code**
--- …

Lolcode Cheat Sheet

---

share/goodie/cheat_sheets/json/feedly.json

Creates a cheat sheet for the keyboard shortcuts of the Feedly RSS reader web app.
**Code**
---
Instant Answer Page: https://duck.co/ia/view/feedly_cheat_sheet

New Feedly Cheat Sheet

---

share/goodie/cheat_sheets/json/diskpart.json

Diskpart is a command-line disk partitioning utility in windows 2000 and later, replacing its predecessor fdisk. 
**Code**
---
Instant Answer Page: https://duck.co/ia/view/diskpart_cheat_sheet

Cheat sheet for windows diskpart command

---

share/goodie/cheat_sheets/json/flask-ask.json

Flask-Ask Cheat sheet.  
Flask-Ask is a Flask extension that makes building Alexa skills for the Amazon Echo easier and much more fun. Flask-Ask: Has decorators to map Alexa requests and intent slots to view functions, Helps construct ask and tell responses, reprompts and cards, Makes session management easy, Allows for the separation of code and speech through Jinja templates, Verifies Alexa request signatures.  
@pjhampton 
- All **Example Queries** trigger on …

New Flask-Ask Cheat sheet

---

lib/DDG/Goodie/IDN.pm
t/IDN.t

- Convert to structured answer.
- Replace tabs with spaces.
#1163
@mintsoft sorry to spam you, I'm into Perl right now and I want to finish #1163 so I can work on a new Goodie.
**Code**
---
Instant Answer Page: https://duck.co/ia/view/IDN

IDN: Structured Answer

---

lib/DDG/Goodie/Loan.pm
t/Loan.t

- Convert to structured answer.
- Replace tabs with spaces.
#1163
**Code**
---
Instant Answer Page: https://duck.co/ia/view/Loan

Loan: Make structured answer

---

share/goodie/geometry/objectInfo.yml
share/goodie/geometry/svg/cone.svg
share/goodie/geometry/svg/cylinder.svg
share/goodie/geometry/svg/sphere.svg
t/Geometry.t

This PR adds the geometry of cylinder and cone
**Improvements**
More geometrical shapes are yet to be added
**Code**
---
Instant Answer Page: https://duck.co/ia/view/geometry

Geometry: Adds geometry of cylinder and cone

---

lib/DDG/Goodie/Unicode.pm

Throws an error under 5.24 and won't load ::  
`Unescaped left brace in regex is deprecated, passed through in regex; marked by <-- HERE in m/^ \s* (?:U \+?|\\(?:u|x{ <-- HERE (?=.*}))) (?<codepoint> [a-f0
-9]{4,6})}? \s* $/ at lib/DDG/Goodie/Unicode.pm line 12`
**Code** …

Unicode: Fixing 5.24 upgrade 

---

share/goodie/cheat_sheets/json/nodejs-tutorials.json

Updated references.
@moollaza 
---
Instant Answer Page: https://duck.co/ia/view/nodejs_tutorials_cheat_sheet

Node.js Tutorials Cheat Sheet: Updated references

---

share/goodie/cheat_sheets/json/nursing.json

Provide quick reference guide for common nursing topics.
**Code**
---
Instant Answer Page: https://duck.co/ia/view/nursing_cheat_sheet

New Nursing Cheat Sheet

---

lib/DDG/Goodie/JsMinify.pm
share/goodie/js_minify/content.handlebars
share/goodie/js_minify/js_minify.css
share/goodie/js_minify/js_minify.js
share/goodie/js_minify/triggers.txt
t/JsMinify.t

- Adds CSS Support
- Adds Beutify support
- Adds triggering capabilities
- Tests included
**Todo:**
- Rename this IA (Separate PR)
Fixes: https://github.com/duckduckgo/zeroclickinfo-goodies/issues/3413
Fixes: https://github.com/duckduckgo/zeroclickinfo-goodies/issues/3414
**Code** …

JS Minifier: Added CSS support, Added Beautify support

---

share/goodie/cheat_sheets/json/age-of-empires.json

Adds an Instant Answer for a cheat sheet for the 1997 RTS video game, Age of Empires.
https://duck.co/ia/view/age_of_empires_cheat_sheet
**Code**
---
Instant Answer Page: https://duck.co/ia/view/age_of_empires_cheat_sheet

New Age of Empires Cheat Sheet

---

lib/DDG/Goodie/Calculator.pm
t/Calculator.t

Fixes overtriggering edge case from the pixel logs
@moollaza 
**Code**
---

Calculator: Fix overtriggering (Edge case)

---

lib/DDG/Goodie/Shuffle.pm
t/Shuffle.t

Updates the Shuffle Instant Answer to use the Parse::List Role.
@mintsoft 
---
Instant Answer Page: https://duck.co/ia/view/shuffle

Shuffle: Update to use Parse::List Role

---

lib/DDG/Goodie/Calculator.pm
t/Calculator.t

Fixes some over-triggering with the calculator
@moollaza 
**Code**
---

Calculator: Fix over-triggering on dates.

---

.github/PULL_REQUEST_TEMPLATE.md
README.md

Updates the PR Template and READMEs.

REPO: Update pr/readme template

---

lib/DDG/Goodie/SolarSystem.pm
t/SolarSystem.t

The display is soon to break on our html/lite sites.  
This uses unicode superscripts and multiplication symbol instead of html/entities.
See if it makes sense.
**Code**
---
Instant Answer Page: https://duck.co/ia/view/solar_system

SolarSystem: Use unicode superscripts, multiplication symbol

---

lib/DDG/Goodie/ColorCodes.pm
t/ColorCodes.t

Fixes: https://github.com/duckduckgo/zeroclickinfo-goodies/issues/190
also fixes: https://github.com/duckduckgo/zeroclickinfo-goodies/issues/3758
Also a bit of a kick-about of the code in general (referred to in: https://github.com/duckduckgo/zeroclickinfo-goodies/pull/4220#issuecomment-314547895) , this IA was incredibly convoluted when using `handle => matches` at least now the only real complexity is the regex. There are some minor behaviour changes around triggering breadth.
- **Source Name** exists …

Colourcodes: new query patterns 

---

lib/DDG/Goodie/Calculator.pm
t/Calculator.t

Calculator: Divide bug

---

lib/DDG/Goodie/Conversions.pm
share/goodie/conversions/triggers.yml
t/Conversions.t

Hack around deep rooted micro symbol issue
Fix: https://github.com/duckduckgo/zeroclickinfo-goodies/issues/4470
@moollaza 
---

Conversions: Fix micro symbol issue.

---

lib/DDG/Goodie/DaysBetween.pm
t/DaysBetween.t

This improves the DaysBetween IA to add `days until` as a trigger.
Fixes #2844 
@mintsoft 
@JetFault 
**Code**
---
Instant Answer Page: https://duck.co/ia/view/days_between

DaysBetween: Fix #2844 Improve triggering

---

share/goodie/calculator/calculator.js

Fixes mobile scrolling when calculator displayed
Fixes #4482
@adityatandon007 
---

Calculator: Listen to touchend on mobile

---

share/goodie/conversions/conversions.js

Updates the Fluid Ounces (US) definition) 
Fixes: https://github.com/duckduckgo/zeroclickinfo-goodies/issues/4491
@moollaza 
---

Conversions: Update floz definition.

---

share/goodie/currency_in/currencies.json

Fixes outdated currency information
Fixes #4504
---
Instant Answer Page: https://duck.co/ia/view/currency_in

Currency In: Correct currencies for Latvia and Lithuania

---

share/goodie/duck_duck_go/responses.yml
t/DuckDuckGo.t

- Update links related too DuckDuckHack.com
- Add answer for DDG Search Box
---

DuckDuckGo Answers: Update links to DDH.com and Forum

---

share/goodie/help_line/triggers.yml

New triggers for the suicide helpline IA as per [discussion on /r/duckduckgo](https://www.reddit.com/r/duckduckgo/comments/78fksf/saw_this_on_rteenagers_as_a_teenager_myself_i/).
@moollaza @duckduckgo/community-leaders Hoping for a quick resolution on this, thanks.
---
Instant Answer Page: https://duck.co/ia/view/help_line

HelpLine: new triggers

---

share/goodie/conversions/conversions.js

Conversions
IA says, that in 1mm² is 100cm² and add decimeter
Fixes #4523 
---

Conversions: Fix #4523

---

.travis.yml
lib/DDG/Goodie/Combination.pm
lib/DDG/Goodie/RandomDate.pm
t/Unicode.t

Eric/perl 5.26.0

---

share/goodie/cheat_sheets/json/org-mode.json

Fix typo in org-mode cheat sheet
Fixes #4549 
---
Instant Answer Page: https://duck.co/ia/view/org_mode_cheat_sheet

Org Mode Cheat Sheet: Fix typo

---

share/goodie/conversions/conversions.js
t/Conversions.t

There was a misspelling in the conversions.js for decilitre unit.
Fixes [#4551](https://github.com/duckduckgo/zeroclickinfo-goodies/issues/4551)
@bsstoner @pjhampton 
---

Conversions: JS error (#4551)

---

lib/DDG/Goodie/Conversions.pm
t/Conversions.t

Conversions fix (#4506)

---

share/goodie/cheat_sheets/json/eclipse.json
share/goodie/cheat_sheets/json/language/assamese.json
share/goodie/cheat_sheets/json/language/bengali.json
share/goodie/cheat_sheets/json/language/chinese.json
share/goodie/cheat_sheets/json/machine-learning.json
share/goodie/cheat_sheets/json/ruby-webcomics.json
share/goodie/cheat_sheets/json/xmonad.json

Fixes invalid JSON in multiple cheat sheets

Fix invalid JSON for cheatsheets

---

share/goodie/public_dns/providers.yml

Added a new Public DNS on that specific IA
Fixes #4602
---
Instant Answer Page: https://duck.co/ia/view/public_dns

Public DNS: Add 1.1.1.1 to the list of Public DNS servers

---

share/goodie/cheat_sheets/json/serbian.json

This fixes a url which was input with an extra `e` at the end.
Fixes #4597
---
Instant Answer Page: https://duck.co/ia/view/serbian_cheat_sheet

serbian_cheat_sheet: Fix url

---

share/goodie/constants/constants.yml

Fixing incorrect gravitation value; source for new value: https://physics.nist.gov/cgi-bin/cuu/Value?bg
Fixes: #4616
@fwSmit @hemanth 
---
Instant Answer Page: https://duck.co/ia/view/constants

Constants: Fixing Big-G (quick fix)

---

share/goodie/cheat_sheets/json/nodejs-tutorials.json

I changed the protocol from `http://` to `https://` for user security reasons. I also removed non existing sites with an 404 error.
@moollaza 
**Pull Request Review Guidelines:** https://docs.duckduckhack.com/testing-reference/pr-review.html
---
Instant Answer Page: https://duck.co/ia/view/nodejs_tutorials_cheat_sheet

Node.js Tutorials Cheat Sheet: Use HTTPS protocol & Removed non existing websites

---

share/goodie/cheat_sheets/json/nodejs-tutorials.json

Use new link for "Smashing Node.js" book
Related to #4608
@gautamkrishnar @bsstoner 
---
Instant Answer Page: https://duck.co/ia/view/nodejs_tutorials_cheat_sheet

Node.js Tutorials Cheat Sheet: Use new link for "Smashing Node.js" book

---

lib/DDG/Goodie/Factors.pm
lib/DDG/Goodie/PrimeFactors.pm
t/Factors.t
t/PrimeFactors.t

Limits input size to numbers <= 1M
---
Instant Answer Page: https://duck.co/ia/view/factors

Factors & Prime Factors: Limit input size to <= 1M

---

lib/DDG/GoodieBundle/OpenSourceDuckDuckGo.pm

just testing the new auto release process
---

Added whitespace to test auto release

---

share/goodie/cheat_sheets/cheat_sheets.css
share/goodie/timer/timer.css

- Updates CheatSheet keyboard items, and Timer inputs
@bsstoner @bbraithwaite

Update border-radius to 4px

---

lib/DDG/Goodie/Timezonetime.pm
t/Timezonetime.t

Removes caching of results
@bbraithwaite

Fix timezonetime
