duckduckgo/zeroclickinfo-goodies

- lib/DDG/Goodie/IsAwesome/TheAdamGalloway.pm
- t/IsAwesome/TheAdamGalloway.t
- t/LeapYear.t
Provides simple feedback to the user when typing 'duckduckhack TheAdamGalloway'.
This was created to solve the problem of me not knowing how to make a DuckDuckGo goodie.
Simple text.
The tutorial told me to.
Of course not.
**What are some example queries that trigger …
> TheAdamGalloway's first Goodie

- lib/DDG/Goodie/IsAwesome/Blito.pm
- t/IsAwesome/Blito.t
Says I'm awesome.
It teaches ignorant people about how awesome I am.
Myself. You can know more about me once you merge this pull request and look for "duckduckhack blito" in duckduckgo.com
It's the best one available.
Better? Not sure.
**What are some example queries …
> Blito's First Goodie

- lib/DDG/Goodie/IsAwesome/purplehuman.pm
- t/IsAwesome/purplehuman.t
I did the first tutorial, and when you search "duckduckhack purplehuman", it says "purplehuman is awesome!"
It says "purplehuman is awesome!" ! No other search engine would say that, would they?
Hmm, me.
Err, because Instant Answer is about me.
I don't think so, I'm not …
> purplehuman's first Goodie

- lib/DDG/Goodie/IsAwesome/enricofoltran.pm
- t/IsAwesome/enricofoltran.t
> enricofoltran's First Goodie

- lib/DDG/Goodie/IsAwesome/sagarhani.pm
- t/IsAwesome/sagarhani.t
If we type duckduckhack in duckduckgo search engine it will show "sagarhani is awesome and has completed the Goodie tutorial!" 
This is just a basick goodie to show the world the "sagarhani is awesome"
common
yes
**What are some example queries that trigger this Instant …
> Created my first Goodie.

- lib/DDG/Goodie/IsAwesome/ashleyglidden.pm
- t/IsAwesome/ashleyglidden.t
It's my first goodie - it says my github user name is awesome
I'm currently just testing out goodies via the tutorial
N/A
N/A
N/A
duckduckhack ashleyglidden
N/A
N/A
**Which existing Instant Answers will this one …
> ashleyglidden's First Goodie

- lib/DDG/Goodie/IsAwesome/omareduardo.pm
- t/IsAwesome/omareduardo.t
Returns "omareduardo is awesome and has successfully completed the DuckDuckHack Goodie tutorial!" as an instant answer for search term 'duckduckhack omareduardo'
It's a hack for tutorial purposes; no organic link would answer such a way. 
My personal opinion and the instructions from the quick start guide: https://duck.co/duckduckhack/goodie_quickstart
**Why did you …
> Omareduardo's first Goodie

- lib/DDG/Goodie/IsAwesome/roshanr95.pm
- t/IsAwesome/roshanr95.t
It says I am awesome!
n/a
n/a
n/a
n/a
duckduckhack roshanr95
Probably only myself...
The quick start goodie.
Nothing
**Are you having any problems? Do …
> Created my first Goodie

- lib/DDG/Goodie/DuckDuckGo.pm
- share/goodie/duck_duck_go/responses.yml
adding to the ddg_goodie
should've done --amend instead of continuous commiting.
> Updated DuckDuckGo Goodie

- lib/DDG/Goodie/IsAwesome/alexishancock.pm
- t/IsAwesome/alexishancock.t
Trigger for IsAwesome practice Goodie
Helps me understand DuckDuckGo's Goodies. 
duckduckhack alexishancock
My geeky self
Other IsAwesome Goodies
An article discussing internet privacy
```
[x] Added metadata and attribution information …
```
> Test Goodie: duckduckhack

- lib/DDG/Goodie/IsAwesome/amneher.pm
- t/IsAwesome/amneher.t
tells people i'm awesome
because i'm awesome
my awesomeness
because i'm awesome
nope
duckduckhack amneher
**Which communities will this Instant Answer be especially useful for? (gamers, book lovers, …
> amneher's first Goodie

- lib/DDG/Goodie/IsAwesome/watermelonwarrior.pm
- t/IsAwesome/watermelonwarrior.t
Displays text describing how awesome my username is
Otherwise the user would have no idea that I am awesome
Hardcoded text
Tutorial
N/A
duckduckhack watermelonwarrior
**Which communities will this …
> Watermelonwarrior's first Goodie

- lib/DDG/Goodie/IsAwesome/dl00.pm
- t/IsAwesome/dl00.t
It does as instructed by the Goodie Quickstart tutorial (although I made some small modifications to the return text)
It inspires a potential developer to make more goodies
String supplied in the Goodie
Because it is constant
No
**What are some example queries that …
> dl00's First Goodie

- lib/DDG/Goodie/IsAwesome/Dronov.pm
- t/IsAwesome/Dronov.t
Just saying a few words about Mikhail Dronov when user entered "duckduckhack dronov" at the search input on the DuckDuckGo webpage.
It's educational Goodie.
You can find that the Mikhail Dronov is real by looking at the website: http://dronov.net
Cause I started write to dronov.net five years ago.
**Are there any other …
> Dronov's First Goodie

- LICENSE
With a slightly modified APPENDIX section - no mentions of placeholder-field replacement.  Fixes #931, low-hangig fruit indeed.
> A basic LICENSE file

- lib/DDG/Goodie/SalesTax.pm
- t/SalesTax.t
**Sales tax for: Pennsylvania** => **Sales Tax: Pennsylvania**
_____________________________
> SalesTax: Rename operation

- lib/DDG/Goodie/IsAwesome/bfmags.pm
- t/IsAwesome/bfmags.t
Following goodie_quickstart tutorial.
"duckduckhack bfmags" 
EDX Computer Science course
```
[x] Added metadata and attribution information (https://duck.co/duckduckhack/metadata)
[x] Wrote test file and added to t/ directory (https://duck.co/duckduckhack/goodie_tests)
[x] Verified that instant answer adheres to design guidelines (https://duck.co/duckduckhack/design_styleguide)
[x] Verified that instant answer adheres to code styleguide …
```
> bfmags's First Goodie

- lib/DDG/Goodie/IsAwesome/PandiyanCool.pm
- t/IsAwesome/PandiyanCool.t
First goodie
First goodie
**Where did you hear about DuckDuckHack? (For first …
> PandiyanCool's First Goodie

- t/IsAwesome/PandiyanCool.t
Noticed: https://travis-ci.org/duckduckgo/zeroclickinfo-goodies/jobs/48673103#L1699
This should get the tests passing again :)
/cc @jagtalon
> Fix casing in PandiyanCool.t

- lib/DDG/Goodie/IsAwesome/justinvee.pm
- t/IsAwesome/justinvee.t
My Instant Answer answers the ever important question about whether I am awesome or not. I'd like to set the record straight with my Instant Answer by including an emphatic yes in DuckDuckGo regarding my completion of the Goodie tutorial on duck.co.
tl;dr: DuckDuckGo tutorial to include whether my GitHub's username is awesome & has completed the tutorial.
The only authoritative answer on the subject.
**What is the data source for your Instant …
> justinvee's first Goodie.

- lib/DDG/Goodie/IsAwesome/SueSmith.pm
- t/IsAwesome/SueSmith.t
It indicates whether or not I am awesome - I followed the quick start tutorial to ___start___ getting myself acquainted with the Instant Answer functionality and process.
The problem created by people not knowing whether or not I am awesome.
Just reality.
It does the job.
**Are there any other alternative (better) data …
> SueSmith's first Goodie

- lib/DDG/Goodie/IsAwesome/aseemraj.pm
- t/IsAwesome/aseemraj.t
It tells everyone that I am awesome and I've completed the goodie tutorial.
It solves no problems, this is just to see my implemented code as mentioned in the tutorial
https://duck.co/duckduckhack/goodie_quickstart
Because this is the official tutorial resource for contributing to Duckduckgo.
**Are there any other alternative …
> aseemraj's first Goodie

- lib/DDG/Goodie/PhoneAlphabet.pm
- t/PhoneAlphabet.t
Continuation of #849 
/cc @jagtalon @MrChrisW @stevelippert
> Phonewords to Phone Numbers

- lib/DDG/Goodie/IsAwesome/samph.pm
- t/IsAwesome/samph.t
Returns 'SamPH is awesome and has successfully completed the DuckDuckHack Goodie tutorial!' on use of 'duckduckhack samph'
It solves my lack of knowledge about how to create DDH Instant Answers by following the tutorial.
N/A
N/A
N/A
duckduckhack samph
Only me!
**Is this Instant Answer connected to a DuckDuckHack [Instant …
> SamPH's First Goodie

- lib/DDG/Goodie/IsAwesome/5ika.pm
- t/IsAwesome/5ika.t
My IA just introduces me :-P
Because i've learn how to make good IA.
No data source
``duckduckhack 5ika``
geeks
No
All others duckduckhack first …
> 5ika's First Goodie

- lib/DDG/Goodie/IsAwesome/mougias.pm
- t/IsAwesome/mougias.t
It says that I'm awesome!
Organic links don't say that I'm awesome =(
Plain text
Because you asked me to!
My ex girlfriend.
duckduckhack mougias …
> mougias's First Goodie

- t/MacAddress.t
Fixed the tests, should all be passing now :smile: 
/cc @mintsoft @mogigoma
> MacAddress: Update tests to check HTML result

- lib/DDG/Goodie/IsAwesome/CalaveraTheNine.pm
- t/IsAwesome/CalaveraTheNine.t
Adds my first instant answer from tutorial.
Duckduckhacks first tutorial
Duckduckhack
Advised by the tutorial
No
duckduckhack CalaveraTheNine
**Which communities will this Instant Answer be especially …
> CalaveraTheNine's first Goodie

- lib/DDG/Goodie/IsAwesome/sonny7.pm
- t/IsAwesome/sonny7.t
> sonny7's First Goodie

- pull_request_template_goodie.md
More checklist like feel.
//cc @MrChrisW
> More checklist kind of feel.

- lib/DDG/Goodie/BPMToMs.pm
- share/goodie/bpmto_ms/bpmto_ms.css
- share/goodie/bpmto_ms/bpmto_ms.old
- t/BPMToMs.t
It converts BPM (beats per minute) into note values in milliseconds. It is useful in musical applications for example when needing to calculate delay times, reverb times, compressor attack and release settings etc.
There exists sites with bmp to ms calculators but it is more convenient to get the results directly in the search engine.
The calculation is done inside …
> First commit of BPM to ms converter Goodie

- lib/DDG/Goodie/PhoneAlphabet.pm
- t/PhoneAlphabet.t
Addresses PhoneAlphabet: Should also trigger on "to numbers" #990
> PhoneAlphabet: Also triggers on to numbers

- lib/DDG/Goodie/IsAwesome/hackwa.pm
- t/IsAwesome/hackwa.t
Returns "hackwa is awesome" when trigger is "duckduckhack hackwa"
Tell the world about duckduckgo's and mine awesomeness.
None
I read the tutorial :P
No
duckduckhack GitUserName
Me
No
**Which existing Instant Answers will …
> hackwa's first goodie

- lib/DDG/Goodie/IsAwesome/aarohmankad.pm
- t/IsAwesome/aarohmankad.t
**What does your Instant Answer do?** It lets people know I'm awesome and that I'm ready to contribute to DuckDuckGo in the future
**What problem does your Instant Answer solve (Why is it better than organic links)?** It tells anyone who searches this that I'm awesome.
**What is the data source for your Instant Answer? (Provide a link if possible)** No Data Source needed.
**Why did you choose this data source?** N/A
**Are there any other alternative (better) data sources?** N/A
**What are some example queries that trigger this Instant Answer?** duckduckhack aarohmankad
**Which communities will this Instant Answer be especially useful for? (gamers, book lovers, etc)** My huge fanbase jk.
**Is this Instant Answer connected to a DuckDuckHack [Instant Answer idea](https://duck.co/ideas)?** No …
> aarohmankad's first goodie

- lib/DDG/Goodie/IsAwesome/francisbrito.pm
- t/IsAwesome/francisbrito.t
Tells the world how awesome I'm for creating my first goodie.
duckduckhack francisbrito
Me and my dev. friends
No
At the "We're hiring" article in [Duck.co](https://duck.co/help/company/hiring)
```
- [] Verified that instant answer adheres to design guidelines …
```
> francisbrito's First Goodie

- lib/DDG/Goodie/IsAwesome/chaw.pm
- t/IsAwesome/chaw.t
Wishes everyone "Happy Hacking!"
It's a simple getting started exercise.
None needed.
NA.
NA.
duckduckhack chaw
**Which communities will this Instant Answer be especially useful for? (gamers, book …
> chaw's first Goodie, spreading Happy Hacking wishes.

- lib/DDG/Goodie/IsAwesome/NickCalabs.pm
- t/IsAwesome/NickCalabs.t
> NickCalabs' First Goodie

- lib/DDG/Goodie/IsAwesome/murz.pm
- t/IsAwesome/murz.t
It's my noobie "IsAwesome" goodie.
It solves the problem of wanting to know if I completed the DuckDuckHack goodie tutorial.
duckduckhack murz
Pretty much no one
```
> murz's IsAwesome Goodie

- dist.ini
Continuing #1006 
Note: I'll need to update the Conversions test file to include the new abbreviations.
> Dist.ini: Update Convert::Pluggable

- t/Conversions.t
Continuing comment left in #1009 releated to #1006
Include new tests for the new unit abbreviations
+ mi to km
+ sq mi to square meters
//CC @moollaza @mintsoft
> Conversions: Update tests to include new unit abbreviations 

- lib/DDG/Goodie/IsAwesome/fish9.pm
- t/IsAwesome/fish9.t
tells me how unawesome I am
finished quickstart tutorial
noe
duckduckhack fish9
none
**Is this Instant …
> fish9's First GoodieCreated my first Goodie

- lib/DDG/Goodie/IsAwesome/chercolvin.pm
- t/IsAwesome/chercolvin.t
It displays the results of my first Goodie: "chercolvin is awesome..."
It just solves that I can submit a Goodie IA and a pull request.
duckduckgo
It's in the tutorial.
duckduckhack chercolvin
**Which …
> chercolvin's First Goodie

- lib/DDG/Goodie/Base64.pm
> Base64: Escape result of base64.

- lib/DDG/Goodie/IsAwesome/ilv.pm
- t/IsAwesome/ilv.t
It tells people that ilv is awesome and has successfully completed the Goodie tutorial.
None.
No data source.
I can't choose what it doesn't exist.
Everything is better than nothing.
duckduckhack ilv
None.
It isn't.
**Which …
> ilv's First Goodie

- lib/DDG/Goodie/IsAwesome/Lynbarry.pm
- t/IsAwesome/Lynbarry.t
> Lynbarry's first Goodie

- lib/DDG/Goodie/GuitarChords.pm
- t/GuitarChords.t
I believe I've fixed it with this regex. It's not very lenient, so let me know if I should add more options for what is a valid guitar chord.
/cc @jagtalon @mintsoft @moollaza
> Guitar Chord Goodie: Regex Fixes

- lib/DDG/Goodie/IsAwesome/rafacas.pm
- t/IsAwesome/rafacas.t
Returns "rafacas is awesome and has successfully completed the DuckDuckHack Goodie tutorial!" when trigger is "duckduckhack rafacas"
It doesn't solve anything _per se_ but it's pretty cool to be able to _create_ and instant answer for duckduckgo :)
None
duckduckhack rafacas
geek
**Is this Instant Answer connected to a …
> rafacas' first Goodie

- template/lib/DDG/Goodie/Example.pm
/cc @mintsoft this likely explains the weird indentation issues!
> switch from tabs to spaces

- lib/DDG/Goodie/IsAwesome/Black616Angel.pm
- t/IsAwesome/Black616Angel.t
It is awesome.
Telling me I am awesome.
https://duck.co/duckduckhack/goodie_quickstart
Boredom and Excitement
https://lmddgtfy.net/?q=no
IsAwesome Black616Angel
**Which communities will this Instant …
> Black616Angels First Goodie

- lib/DDG/Goodie/IsAwesome/ufanete.pm
- t/IsAwesome/ufanete.t
Returns the static text "ufanete is awesome and has successfully completed the DuckDuckHack Goodie tutorial!"
My first tutorial
Static text
Not applicable.
Not applicable.
duckduckhack ufanete
**Which …
> Ufanete's First Goodie

- lib/DDG/Goodie/IsAwesome/afelicioni.pm
- t/IsAwesome/afelicioni.t
Tells the world about my awesomeness
Tells I'm awesome at those who don't know
https://duck.co/user/afelicioni
Because I'm very conceited
https://lmddgtfy.net/?q=no
duckduckhack afelicioni
**Which …
> afelicioni's First Goodie

- dist.ini
- lib/DDG/Goodie/Base64.pm
- t/Base64.t
This is a fix for Issue #1051.
> Base64 Fix

- lib/DDG/Goodie/Wavelength.pm
- t/Wavelength.t
Calculates the wavelength in meters/cm/mm for a given frequency expressed in Hz/kHz/MHz/Ghz/THz and velocity factor as a ratio of the speed of light.
Answers and/or tests could potentially be rounded to account for differences in architecture float precision
Wavelength can be directly calculated, so any organic link would be unnecessary indirection.
wavelength 144.39Mhz
λ 2.4GHz
Amateur radio enthusiasts
RF engineers
RTL-SDR or SatNogs hackers
**Is this Instant Answer connected to a DuckDuckHack …
> Frequency to Wavelength instant answer

- dist.ini
- lib/DDG/Goodie/IsAwesome/ufanete.pm
- lib/DDG/Goodie/Meta.pm
- lib/DDG/Goodie/Uptime.pm
- lib/DDG/Goodie/Wavelength.pm
- lib/DDG/Goodie/Zodiac.pm
Running `dzil smoke --release --author` exhibited several warnings.
This Pull Request tries to address those warnings.
> Fix dzil warnings

- dist.ini
- lib/DDG/Goodie/MD4.pm
- t/MD4.t
Computes the MD4 cryptographic hash function.
Users interested in the MD4 hash of a string will be able to get it as an Instant Answer instead of going to a specific page that calculates it or writing a small script.
None
N/A
N/A
md4 this string
md4sum this string
MD4 this string
md4 hash of this string
md4 base64 this string
**Which communities will this Instant Answer be especially useful for? (gamers, book lovers, …
> Added MD4 Goodie

- lib/DDG/Goodie/IsAwesome/jgkamat.pm
- t/IsAwesome/jgkamat.t
Tells the world 'jgkamat' is awesome!
Teaching me DDH
A string
N/A
N/A
duckduckhack jgkamat
N/A
**Is …
> Jgkamat's First Goodie!

- lib/DDG/Goodie/Calculator.pm
- t/Calculator.t
Added sqrt functionality to the DDG caclulator
People who want to use DDG to find the square root of something usually type out 'sqrt(x)' instead of 'x^0.5'
Math?
N/A
N/A
sqrt(4), sqrt(pi), sqrt(4+23) …
> Added sqrt to the goodie caclulator

- lib/DDG/Goodie/AltCalendars.pm
- t/AltCalendars.t
Converted the AltCalendars Goodie and its tests to structured answer.
> AltCalendars converted to a structured answer (#402)

- lib/DDG/Goodie/IsAwesome/ngzhian.pm
- t/IsAwesome/ngzhian.t
Tell the world that I have completed the tutorial!
That not enough people are using duckduckgo and contributing :P
n/a
n/a
n/a
duckduckhack ngzhian …
> Created my first Goodie!

- lib/DDG/Goodie/IsAwesome/organiker.pm
- t/IsAwesome/organiker.t
returns a statement that organiker "is awesome and has successfully completed the DuckDuckHack Goodie tutorial!"
**Which communities will this Instant Answer be especially useful for? (gamers, book …
> organiker's First Goodie

- share/goodie/cheat_sheets/cheat_sheets.css
- share/goodie/cheat_sheets/cheat_sheets.js
- share/goodie/cheat_sheets/detail.handlebars
/cc @jagtalon @russellholt 
Just noticed this isn't working -- I must have forgot to commit something. This fixes things so they work as expected.
I'll remove the existing IA's later once this is ready to go live. That way we don't risk breaking any existing CheatSheets.
> fixed display bugs, manually show/hide content

- lib/DDG/Goodie/IsAwesome/valcrist73.pm
- t/IsAwesome/valcrist73.t
answers with the message "Valcrist73 is awesome and has successfully completed the DuckDuckHack Goodie tutorial! - Valcrist73 es genial y ha completado exitosamente el tutorial DuckDuckHack Goodie!"
answer about valcrist awesomess
N/A
N/A
N/A
**What are some example …
> Valcrist73 first goodie

- lib/DDG/Goodie/IsAwesome/wongalvis.pm
- t/IsAwesome/wongalvis.t
My first Goodie, it lets the world know that wongalvis is awesome
duckduckhack wongalvis
I found a link to DuckDuckGo on Google and I found it very interesting and inspiring. I like it so much that it shares the same vision as me. Then I found information about developing on DuckDuckHack via https://duck.co/.
**What does the Instant Answer look like? (Provide a screenshot for new or updated …
> wongalvis' First Goodie

- lib/DDG/Goodie/IsAwesome/uniphil.pm
- t/IsAwesome/uniphil.t
Says I'm awesome...
Well it's not info they'll be convinced of otherwise, maybe
It's a hard-coded phrase
What is free will, really? do any of us choose?
until there is an API for my mother...
Exactly only `duckduckhack uniphil`
My few friends …
> uniphil's first goodie

- lib/DDG/Goodie/BRT.pm
- t/BRT.t
Providing tracking information handled by [BRT](http://www.brt.it/) shipping carrier services
Links directly to shipment details
[BRT](http://www.brt.it/) web service
The information is the only available from BRT
No
12 digit shipment code
``brt 123456789012``
19 digit "BRTcode"
``brtcode 1234567890123456789`` or ``brt 1234567890123456789``
**Which communities will this Instant Answer be especially useful for? (gamers, …
> Add BRT Shipment Tracking

- dist.ini
> Fix PromptIfStale index_base_url

- lib/DDG/Goodie/PercentOf.pm
- t/PercentOf.t
Hei, I fixed this bug: https://github.com/duckduckgo/zeroclickinfo-goodies/issues/1109
Sorry for the drawback ! :)
// cc @yegg @MrChrisW
> PercentOf: fix #1109 bug

- lib/DDG/Goodie/Conversions.pm
- t/Conversions.t
> Conversions: "oz" = "oz fl" if "ml" contained in query

- lib/DDG/Goodie/IsAwesome/v0tti.pm
- t/IsAwesome/v0tti.t
It shows that I am awesome! (Goodie Quick Start Tutorial)
Because the links don't show that I am awesome
https://duck.co/duckduckhack/goodie_quickstart
Its the official Tutorial :D
Nope
duckduckhack v0tti
For me!
Nope …
> v0ttis first Goodie

- share/goodie/minecraft/crafting-guide.json
> Minecraft: Fix JSON formatting

- lib/DDG/Goodie/Pi.pm
- t/Pi.t
@jagtalon Hei, I improved the triggers as suggested here https://github.com/duckduckgo/zeroclickinfo-goodies/issues/1038 and https://github.com/duckduckgo/zeroclickinfo-goodies/issues/1037
> Pi IA: triggers improved

- lib/DDG/Goodie/SunInfo.pm
`$loc->country` doesn't exist, this corrects that.
> typo fix, need to use ->country_name

- lib/DDG/Goodie/GuitarChords.pm
- lib/DDG/Goodie/IsAwesome/Black616Angel.pm
- lib/DDG/Goodie/IsAwesome/afelicioni.pm
- lib/DDG/Goodie/IsAwesome/ngzhian.pm
- lib/DDG/Goodie/IsAwesome/organiker.pm
- lib/DDG/Goodie/IsAwesome/rafacas.pm
- lib/DDG/Goodie/IsAwesome/rramyr.pm
- lib/DDG/Goodie/IsAwesome/wongalvis.pm
- lib/DDG/Goodie/SolarSystem.pm
- template/lib/DDG/Goodie/Example.pm
Whacking use strict on the remaining goodies that don't already have it. 
Also submitted a PR here: duckduckgo/duckduckgo-documentation/pull/245
cc @mintsoft
> Adding "use strict"

- lib/DDG/Goodie/IsAwesome/fabrgu.pm
- t/IsAwesome/fabrgu.t
My Instant Answer displays "fabrgu is awesome and has successfully completed the DuckDuckHack Goodie tutorial!" when "duckduckhack fabrgu" is queried. 
It's the goodie quick start tutorial.
It's the goodie quick start tutorial.
It's the goodie quick start tutorial.
It's the goodie quick start tutorial.
"duckduckhack fabrgu"
**Which communities will this Instant Answer be especially useful for? (gamers, book lovers, …
> fabrgu's first Goodie

- lib/DDG/Goodie/IsAwesome/fabrgu.pm
> Fix line ending. Stop warning from DDG lib

- lib/DDG/Goodie/IsAwesome/abrahimladha.pm
- t/IsAwesome/abrahimladha.t
This is the simple duckduckhack hello world example.
No problems solved
No data source
No data source
No data source
"duckduckhack abrahimladha" …
> abrahimladha's First Goodie

- share/goodie/cheat_sheets/regexp.json
- share/goodie/cheat_sheets/regular-expression.json
- share/goodie/cheat_sheets/regular-expressions.json
As examples of how to do aliases/alternates for cheat sheet names, added some for the regex cheat sheet.  These will handle:
* regular expression cheat sheet
* regular expressions cheat sheet
* regexp cheat sheet
They should also handle irregular/multiple spacing between words.
> Add regex cheat sheet aliases

- share/goodie/cheat_sheets/awesome bar.json
IA Page: https://duck.co/ia/view/awesome_bar_cheat_sheet
> Awesome Bar Cheatsheet

- lib/DDG/Goodie/CalendarConversion.pm
- lib/DDG/Goodie/DuckDuckGo.pm
- lib/DDG/Goodie/HelpLine.pm
- lib/DDG/Goodie/Jira.pm
- lib/DDG/Goodie/POTUS.pm
- lib/DDG/Goodie/Paper.pm
- lib/DDG/Goodie/PeriodicTable.pm
- lib/DDG/Goodie/PublicDNS.pm
- lib/DDG/Goodie/SolarSystem.pm
- lib/DDG/Goodie/ZappBrannigan.pm
Use LoadFile to ingest YAML from disk.  Addresses https://github.com/duckduckgo/zeroclickinfo-goodies/issues/1114.
> Convert slurp/Load to LoadFile

- share/goodie/cheat_sheets/git.json
Shows a cheat sheet for git commands.
What problem does your Instant Answer solve (Why is it better than organic links)?
Doesn't require clicking. 
Github's own training docs. 
They happen to be an authority on the matter. 
No. If there are, they can be added on. 
What are some example queries that trigger this Instant Answer?
git cheat sheet
Anyone who uses github! 
Nope
Which existing Instant Answers will this one …
> git cheat sheet

- share/goodie/cheat_sheets/git.json
> Capitalize GitHub properly

- lib/DDG/Goodie/Minecraft.pm
- t/Minecraft.t
It is more reputable and official. I would have switched the images to use it to, but they generate them dynamically... perhaps someone should make an API for this :D
> Use the official Minecraft wiki as the source

- share/goodie/cheat_sheets/cheat_sheets.css
/cc @chrismorast @abeyang 
Updated look:
> Bump footer padding to 10px

- share/goodie/cheat_sheets/harry-potter-spells.json
It lists out all the Harry Potter spells.
http://harrypotterspells.net/
Because it had all of the spells mentioned in the book
Wikipedia and harrypotterspells have pretty much the same thing covered.
harry potter spells guide, harry potter spells cheatsheet
Wizards and witches who need a quick reference while dueling. ;D
Heard it from …
> Harry Potter spell cheatsheet

- lib/DDG/Goodie/IsAwesome/fdavidcl.pm
- t/IsAwesome/fdavidcl.t
**What does your Instant Answer do?**  
This is the [Quick Start](https://duck.co/duckduckhack/goodie_quickstart) Goodie for my user. 
**What are some example queries that trigger this Instant Answer?**  
`duckduckhack fdavidcl`
**Where did you hear about DuckDuckHack? (For first time contributors)**  
I read about people contributing their own Instant Answers and decided to give it a try.
```
- [] Tested cross-browser compatibility
- Linux
- Windows 8
- [] Google Chrome
- [] Firefox
- [] Opera
- [] IE 10
- Windows 7
- [] Google Chrome
- [] Firefox
- [] Opera
- [] IE 8
- [] IE 9
- [] IE 10
- Windows XP
- [] IE 7
- [] IE 8
- Mac OSX
- [] Google Chrome
- [] Firefox
- [] Opera
- [] Safari
- iOS …
```
> fdavidcl's First Goodie

- lib/DDG/Goodie/Conversions.pm
- t/Conversions.t
This is in reference to @chrismorast 's comment in #1188 .
> Enable ml to ounces trigger

- lib/DDG/Goodie/UnixPermissions.pm
- t/UnixPermissions.t
Moved the UnixPermissions goodie to use a template as part of #1163. If there is a more suitable template let me know. 
Tests still need amending to match the changes.
> use record template in UnixPermissions goodie

- share/goodie/cheat_sheets/coffee-script.json
- share/goodie/cheat_sheets/coffeescript.json
My cheat sheet provides help for [CoffeeScript](http://coffeescript.org)
Provides a cheat sheet for common CoffeeScript syntax and  usage without visiting the main website or checking any manual.
The CoffeeScript website and cheatography.com
It's the source.
Not that I'm aware of.
coffeescript cheat sheet, coffeescript  Installation, coffeescript operators 
**Which communities will this Instant Answer be especially …
> Added coffee-script cheat sheet

- share/goodie/cheat_sheets/lgbt.json
Trigger a cheat sheet for LGBT Terms
Clears misconceptions quickly on terms regarding LGBT people and their lives
http://web.jhu.edu/LGBTQ/glossary.html
It's an official source approved by academia
Safezone Project's PDF training material
lgbt cheat sheet
Education
**Is this Instant Answer connected to a DuckDuckHack …
> alexishancock's  LGBT Terms Cheat Sheet Goodie

- share/goodie/cheat_sheets/ed.json
> Ed Cheat Sheet: remove extra newlines and NBSP's

- share/goodie/cheat_sheets/wu-tang.json
Shows the members of the Wu-Tang Clan
When you're trying to remember who's bringing the ruckus -- this will help. 
https://en.wikipedia.org/wiki/Wu-Tang_Clan#Members
It's accurate
No
wu tang cheat sheet …
> zekiel's Wu-Tang members cheat sheet

- lib/DDG/Goodie/CheatSheets.pm
- share/goodie/cheat_sheets/the-witcher-3.json
- share/goodie/cheat_sheets/wild-hunt.json
- share/goodie/cheat_sheets/witcher-3.json
- share/goodie/cheat_sheets/witcher-wild-hunt.json
A cheat sheet to display the default PC key bindings for The Witcher 3: Wild Hunt.
Gives a quick overview of shortcuts without having to click
The PC game itself.
Seemed appropriate ;D
There are probably tons of alternates around but I doubt better.
"witcher 3 cheat sheet", "wild hunt key bindings", "the witcher 3 default keys"
**Which communities will this Instant Answer be especially useful for? (gamers, book lovers, …
> The Witcher 3: Wild Hunt key bindings

- share/goodie/cheat_sheets/game-of-thrones-houses.json
//cc @moollaza 
---
IA Page: https://duck.co/ia/view/game_of_thrones_houses_cheat_sheet
> Added game of thrones houses

- lib/DDG/Goodie/ColorCodes.pm
> ColorCodes - Fix images link url

- share/goodie/cheat_sheets/emacs.json
> Emacs Cheatsheet - Correct source url

- lib/DDG/Goodie/IsAwesome/gokul1794.pm
- t/IsAwesome/gokul1794.t
**Goodie tutorial pull request**
DuckDuckHack goodie tutorial
duckduckhack gokul1794
Looks like this
```
- [] Added metadata and attribution information (https://duck.co/duckduckhack/metadata)
- [] Wrote test file and added to t/ directory (https://duck.co/duckduckhack/goodie_tests)
- [] Verified that instant answer adheres to design guidelines (https://duck.co/duckduckhack/design_styleguide)
- [] Verified that instant answer adheres to code styleguide (https://duck.co/duckduckhack/code_styleguide)
- Windows 8
- [] Google Chrome
- [] Firefox
- [] Opera
- [] IE 10
- Windows 7
- [] Google …
```
> goodie tutorial

- share/goodie/cheat_sheets/sublime-text.json
A cheat sheet that lists Sublime Text keyboard shortcuts.
It summarizes most of the keyboard shortcuts so you don't have to go through several links/sources.
[Cheatography](http://www.cheatography.com/njovin/cheat-sheets/sublime-text-2-windows)
List all the most commonly used Sublime Text keyboard shortcuts.
* sublime text cheat sheet
* sublime cheat sheet
* sublime text keyboard shortcuts
* sublime keyboard shortcuts
**Which communities will this Instant Answer be especially …
> sublime text cheat sheet

- share/goodie/cheat_sheets/sublime-text.json
> Fix Single keys;  Shouldn't be wrapped in brackets

- lib/DDG/Goodie/ScreenResolution.pm
As per @moollaza in https://github.com/duckduckgo/zeroclickinfo-goodies/pull/1172#discussion_r33170090
> ScreenResolution: change title

- share/goodie/cheat_sheets/tennis.json
Shows key facts about tennis such as scoring system, history, match and shot types, etc.
The information is in one place and easier to skim than reading full articles.
https://en.wikipedia.org/wiki/Tennis and linked sub-pages on Wikipedia.
Because it's Wimbledon time!
Perhaps from the International Tennis Federation website but there may be usage restrictions.
```tennis cheatsheet```
```tennis cheat sheet```
**Which …
> Created tennis cheat sheet

- share/goodie/cheat_sheets/photoshop.json
Provides a cheatsheet for Adobe Photoshop.
It serves as a quick reference for Photoshop shortcuts. Zero-clicks!
I've primarily used [this](https://helpx.adobe.com/content/dam/help/attachments/PhotoshopCC-KBSC.pdf), the official documentation. [This](http://morris-photographics.com/photoshop/shortcuts/downloads/PSCC%20Keyboard%20Shortcuts%20Win.pdf) provided a few more shortcuts.
It's the official reference; seemed alright to me.
The two I've listed seem pretty comprehensive, so I'm going …
> New Cheatsheet: Photoshop

- lib/DDG/Goodie/IsAwesome/Sloff.pm
- t/IsAwesome/Sloff.t
It displays the text "Ettienne Pitts is awesome and has successfully completed the DuckDuckHack Goodie tutorial!" when searching "duckduckhack sloff"
Only "duckduckhack sloff"
On the DuckDuckGo website
```
- [] Tested cross-browser compatibility
- Windows 8
- [] Google Chrome
- [] Opera
- [] IE 10
- Windows 7
- [] Google Chrome
- [] Firefox
- [] Opera
- [] IE 8
- [] IE 9
- [] IE 10
- Windows XP
- [] IE 7
- [] IE 8
- …
```
> Sloff's Awesome Tutorial Goodie

- share/goodie/cheat_sheets/the-witcher-3.json
I often found myself getting the signs confused at first.  This should give a quick reminder of what each does.
> Add brief sign description to Witcher 3 cheat sheet

- CONTRIBUTING.md
Changing to reflect the messaging in the contributing guide https://duck.co/help/contributing/create-instant-answer
[Same as PR on spice](https://github.com/duckduckgo/zeroclickinfo-spice/pull/2003)
cc @zekiel
> Improving contributing file to reflect contributor guide

- share/goodie/cheat_sheets/cheat_sheets.css
- share/goodie/cheat_sheets/cheat_sheets.js
Resolving Issue #1157
Let me know if there's anything I need to change and I'll get it fixed @moollaza
> Converting CSS nth-child to jQuery

- share/goodie/cheat_sheets/svn.json
My Cheat sheet displays some common commands for Subversion, or svn, version control system.
Data source is the book "Version Control with Subversion" that is available at http://svnbook.red-bean.com/.
It is the guide to Subversion that is promoted at https://subversion.apache.org/docs/ as the user manual for Subversion.
There could be ones that are clearer, but I chose this one as it is the nearest to official documentation.
Software developers that use Subversion.
**Is …
> Subversion (svn) cheatsheet

- lib/DDG/Goodie/ColorCodes.pm
- t/ColorCodes.t
Fixes #1048
Would like some extra eyes on this one, it's kind of hacky :eyes:
> ColorCodes: add support for queries like <color> to <type>

- lib/DDG/Goodie/LeapYear.pm
- t/LeapYear.t
Fixes #415 and was pull request #1280
Shows whether a certain year is a leap year or not, among other leap year related functions
Immediately shows if it is a leap year
"is it a leap year"
"was 2010 a leap year"
"next 50 leap years"
It adds structured answers to the existing leap year module
```
- [] Tested cross-browser compatibility
Please let us know which browsers/devices you've tested …
```
> Leap Year structured answer and template added

- share/goodie/cheat_sheets/emacs.json
> End buffer key fixed

- share/goodie/cheat_sheets/cheat_sheets.css
Hey @moollaza @abeyang 
Sorry I made a new PR, since this was so far behind I pulled from the update and then merged the styles from the old PR. Also it doesn't include my other commits as well, so hopefully that should help.
> Updating CSS from issue #1226

- share/goodie/cheat_sheets/vim.json
> Added source URL for vim cheat sheet

- share/goodie/cheat_sheets/vim.json
> Adds * search to vim cheatsheet

- share/goodie/cheat_sheets/affinity-designer.json
Display keyboard shortcuts for Affinity Designer :sparkles: 
Affinity Designer's homepage, last slide on the slideshow towards the bottom of https://affinity.serif.com/en-us/designer/ :+1: 
In addition to the Mac menubar (examples:)
Official data source :zap: 
Zero. :see_no_evil: Zip. :hear_no_evil: Nada. :speak_no_evil: 
Vector artists using Affinity Designer.
No. :goat: 
About a week ago I heard about this DuckDuckHack meetup ;)
-----
IA Page: https://duck.co/ia/view/affinity_designer_cheat_sheet
> Add Affinity Designer Cheat Sheet

- share/goodie/cheat_sheets/microsoft-windows.json
- share/goodie/cheat_sheets/windows-shortcuts.json
It shows a cheat sheets of all the windows shortcuts
[Wikipedia](https://en.wikipedia.org/wiki/Table_of_keyboard_shortcuts)
It's very extensive and regularly updated
[Windows Help](http://windows.microsoft.com/en-us/windows/keyboard-shortcuts#keyboard-shortcuts=windows-8), but it is specific to a certain version of windows
Shortcut lovers
-----
IA Page: …
> Windows shortcut cheat sheet created

- share/goodie/cheat_sheets/minecraft.json
Provides PC shortcuts for the popular game Minecraft.
Zero-click info!
[This](http://minecraft.gamepedia.com/Controls) is where I got my data from.
It's the official Minecraft list of shortcuts.
I don't think so.
* minecraft cheatsheet
* minecraft cheat sheet
Gamers, definitely. Minecraft is one of the most popular games …
> New Cheatsheet: Minecraft

- share/goodie/cheat_sheets/gmail.json
> Fix syntax, cleanup trailing space, better source

- share/goodie/cheat_sheets/tennis.json
- share/goodie/cheat_sheets/the-witcher-3.json
The Open Era dividing line is a significant event in tennis history.
> Add Open Era to tennis cheat sheet

- share/goodie/cheat_sheets/vlc.json
A cheat sheet that lists useful VLC keyboard shortcuts.
It summarizes all the VLC shortcuts so you don't have to go through several links/sources.
[Videolan](https://wiki.videolan.org/Hotkeys_table) official wiki website.
They list all the most commonly used VLC keyboard shortcuts.
* VLC keyboard shortcuts
* VLC cheat sheet
VLC media player users.
**Which existing Instant Answers …
> VLC Cheat Sheet

- share/goodie/cheat_sheets/sublime-text.json
This just updates the keys in the sublime cheatsheet to the newest standard
> Sublime cheatsheet keys altered

- share/goodie/cheat_sheets/git.json
git stash list help message was used for git stash drop command
> fix git-stash help message

- lib/DDG/Goodie/IsAwesome/rohit.pm
- t/IsAwesome/rohit.t
IT is providing a result Rohit is awesome
It solve my problems(identification)
Goodies- Perl and text file work for me
Perl and duck hack documents
**Are there any other alternative (better) data sources?*
No. In my case
DuckDuckhack rohit
**Which communities …
> First Is Awesome goodie

- lib/DDG/Goodie/CamelCase.pm
- t/CamelCase.t
It converts a query to camelCase
It instantly converts a query to camelCase
```camelcase this is a test```
```my variable camel case```
Programmers
```
- [] Tested cross-browser compatibility
- Windows 8
- [] Google Chrome
- [] Opera
- [] IE 10
- Windows 7
- [] Google Chrome
- [] Firefox
- [] Opera
- [] …
```
> camelCase IA added

- lib/DDG/Goodie/Perimeter.pm
- t/Perimeter.t
> Perimeter altered to use templates

- share/goodie/cheat_sheets/vim.json
Just added a Miscellaneous section for the Vim cheatsheet, along with one Vim method.
It solves the problem of there not being a place to add methods/commands to the Vim cheatsheet when they don't quite fit the current existing ones. Solves the problem of being able to print current buffer into an HTML file.  
A JSON file.
I …
> Chief10's addition to Vim cheatsheet goodie.

- lib/DDG/Goodie/Unicornify.pm
- share/goodie/unicornify/unicornify.css
- t/Unicornify.t
Replaces #1292 
-----
IA Page: https://duck.co/ia/view/unicornify
> Unicornify Display results using structured answers and templates

- share/goodie/cheat_sheets/german.json
Fixed translations, grammar, spelling and typos in the cheat sheet for German.
> Fixed translations, grammar, spelling and typos in the cheat sheet for German.

- share/goodie/cheat_sheets/german.json
Some translations weren't quite right and formatting was inconsistent in places (Thanks @thm!)
> Update German cheat sheet

- share/goodie/cheat_sheets/drush.json
- It's cheat sheet for drush command.
- Show commands/cheat sheet for drush utility.
- JSON
- drush commands or drush cheat sheet
- web developers, software engineers
- yes (https://duck.co/ia/view/drush_cheat_sheet) …
> Drush Cheat Sheet

- lib/DDG/Goodie/Password.pm
- t/Password.t
> Password: Set minimum password length

- lib/DDG/Goodie/BinaryLogic.pm
- t/BinaryLogic.t
Fixes part of #1163 
Before:
After:
> Binary Logic altered to use templates

- share/goodie/cheat_sheets/anniversary.json
Display a Cheatsheet for latin and common anniversaries names
https://en.wikipedia.org/wiki/Anniversary#Latin-derived_numerical_names
Complete and fairly trusted.
No.
History ,Literature ,everybody.
**Is this Instant Answer connected to a DuckDuckHack …
> Anniversary cheatsheet

- share/goodie/cheat_sheets/firefox.json
I completed the whole cheat sheet and updated it. With New Sections and Shortcuts.....
> Firefox Cheatsheet Improvement

- lib/DDG/Goodie/Week.pm
- lib/DDG/GoodieRole/Dates.pm
- t/00-roles.t
- t/Week.t
Following on from @moollaza's fixes here: https://github.com/duckduckgo/zeroclickinfo-goodies/pull/950
I've wrapped the year handling up into the DatesRole so it's all together for now and fixed the issues that @jagtalon noticed
> Continuation: Convert Week Goodie to Structured Template, update tests 

- t/Week.t
> Week: Temporal test that's already covered with MockTime

- share/goodie/cheat_sheets/poker-hands.json
It provides CheatSheet for Poker Hands.
It's better because it's a Zero Click Info
[Wikipedia](https://en.wikipedia.org/wiki/List_of_poker_hands)
Reliable and constantly updated by the community.
Not required.
"poker hands cheatsheet"
"poker hands shortcut"
Gamers (online/offline)
**Is this Instant Answer connected to a …
> Poker Hands Cheatsheet

- share/goodie/cheat_sheets/openshot.json
Cheat sheet for the OpenShot video editing software (Linux)
Keyboard shortcut lookup.
http://www.openshotusers.com/help/1.4/en/ar01s05.html
It's the definitive source.
Not that I'm aware of.
openshot cheatsheet
openshot cheat sheet
Linux users, video editing people
**Is this Instant Answer connected to a DuckDuckHack …
> Added OpenShot CheatSheet

- share/goodie/cheat_sheets/chrome.json
It provides keyboard shortcuts about Google Chrome.
https://support.google.com/chrome/answer/157179?hl=en
Its the official Google help.
Nope.
Internet users looking to get more productive with their browsers.
No, couldn't find any.
No. …
> moinism's chrome cheat sheet

- share/goodie/cheat_sheets/ubuntu.json
It displays the common keyboard shortcuts for Linux Ubuntu Unity.
Even though many of these shortcuts can be accessed by holding down the Super key on Ubuntu, that list is A) easily forgotten about for new users, B) somewhat incomplete, and C) inaccessible for someone who is providing tech help over the phone to an Ubuntu user, but is away from Ubuntu at the moment.
Ubuntu itself - hold down the Super key. The rest are found on System Settings -> Keyboards -> Shortcuts.
It was built in. …
> CodeMouse92's Ubuntu Cheatsheet Goodie

- share/goodie/cheat_sheets/perldoc.json
new file:   lib/DDG/Goodie/PerldocCheatSheet.pm
new file:   share/goodie/perldoc_cheat_sheet/perldoc_cheat_sheet.css
new file:   share/goodie/perldoc_cheat_sheet/perldoc_cheat_sheet.html
new file:   share/goodie/perldoc_cheat_sheet/perldoc_cheat_sheet.txt
new file:   t/PerldocCheatSheet.t
-----
IA Page: https://duck.co/ia/view/perldoc_cheat_sheet
> Created new instant answer goodie for perldoc

- lib/DDG/Goodie/CheatSheets.pm
- share/goodie/cheat_sheets/awesome-bar.json
- share/goodie/cheat_sheets/basic-german-phrases.json
- share/goodie/cheat_sheets/basic-german.json
- share/goodie/cheat_sheets/coffee-script.json
- share/goodie/cheat_sheets/coffeescript.json
- share/goodie/cheat_sheets/english-to-german.json
- share/goodie/cheat_sheets/firefox-awesome-bar.json
- share/goodie/cheat_sheets/german-phrases.json
- share/goodie/cheat_sheets/german.json
- share/goodie/cheat_sheets/microsoft-windows.json
- share/goodie/cheat_sheets/nato-alphabet.json
- share/goodie/cheat_sheets/nato-phonetic-alphabet.json
- share/goodie/cheat_sheets/regex.json
- share/goodie/cheat_sheets/regexp.json
- share/goodie/cheat_sheets/regular-expression.json
- share/goodie/cheat_sheets/regular-expressions.json
- share/goodie/cheat_sheets/the-witcher-3.json
- share/goodie/cheat_sheets/wild-hunt.json
- share/goodie/cheat_sheets/witcher-3.json
- share/goodie/cheat_sheets/witcher-wild-hunt.json
Hi @moollaza, as discussed in #1322 I've added an alias functionality that uses an `aliases` array within the json files, let me know if you think I should do something differently.
> Cheat sheets aliases added

- share/goodie/cheat_sheets/cryptography.json
Cheat sheet about Cryptography
https://en.wikipedia.org/wiki/Cryptography
It provides a lot of information about the subject.
There are many sources about cryptography. But most "serious" sources are not for someone with zero-to-little knowledge about the subject. Hence …
> Added Cryptography Cheat Sheet

- lib/DDG/Goodie/CheatSheets.pm
- t/CheatSheets.t
Test file for cheat sheets added.
cc @zachthompson @mintsoft @moollaza
> Cheatsheet tests added

- share/goodie/duck_duck_go/responses.yml
//cc @moollaza  for global quack
> fixed link to goodies page should go to /ia

- t/DuckDuckGo.t
Whoops, forgot to update the tests when I made these changes!
> Fix DuckDuckGo.t

- lib/DDG/Goodie/IsAwesome/jeet09.pm
- t/IsAwesome/jeet09.t
* Crated IsAweosme
* First tutorial
* jeet09 duckduckhack
* No
**Where did you …
> jeet09 isAwesome Goodie

- share/goodie/cheat_sheets/json/quackhack.json
Gives quick reference info for attendees of our meetup events: meetup.com/pro/duckduckgo 
N/A
N/A
N/A
DuckDuckHackers
Only in a very meta way
No thank you. 
At work. 
**What does the Instant Answer look like? (Provide a screenshot for …
> New IA - Quack & Hack Reference Cheat Sheet

- share/goodie/cheat_sheets/w3m.json
Cheat sheet for w3m text based browser
http://w3m.sourceforge.net/MANUAL#Key:orig
Original page
Linux users
Yes
Had a problem with making a screenshot but restarting Codio helped
-----
IA Page: …
> preemeijer w3m cheat sheet Goodie

- lib/DDG/Goodie/IndependenceDay.pm
- share/goodie/independence_day/independence_day.css
- share/goodie/independence_day/independence_day.js
- t/IndependenceDay.t
> Independence Day: Convert to icon template, display country flag

- lib/DDG/Goodie/Factorial.pm
- t/Factorial.t
Find the factorial of a given number
It calculate the factorial of a number so that user don't have to use any other 3rd party tool/website.
No
* 7 factorial
* 5 fact
Maths
Yes
None
Yes, I want to trigger …
> Factorial of a number

- share/goodie/cheat_sheets/json/colorado-14ers.json
Somehow this got dropped (https://github.com/duckduckgo/zeroclickinfo-goodies/pull/1359).
> Colorado 14ers cheat sheet redux

- share/goodie/cheat_sheets/json/sip-response-codes.json
This IA shows the response/status codes used in the SIP protocol.
https://en.wikipedia.org/wiki/List_of_SIP_response_codes
https://tools.ietf.org/html/rfc3261
RFC3261 is the definition of the standard and the Wikipedia source is an easy to handle, boiled down version of the response/status codes.
No. …
> New Cheat Sheet: SIP Response Codes

- share/goodie/cheat_sheets/cheat_sheets.js
This seems to work... fixes #1414
/cc @moollaza @mintsoft
> CheatSheets: htmlencode < >

- pull_request_template_cheat_sheet.md
Thoughts?
/cc @zekiel @talsraviv @tagawa
> Update PR Template with more explicit instructions

- share/goodie/cheat_sheets/json/jive-talk.json
A Cheat Sheet explaining the language of Jive
Hepcats Jive Dictionary
sourceUrl: "http://www.scribd.com/doc/57707658/Hepcats-Jive-Dictionary"
Reliable and extensive
No
Jive Talk lovers
Yes, https://duck.co/ia/view/jive_talk_cheat_sheet
Not yet
**What does the Instant Answer look like? (Provide a screenshot …
> Jive Talk cheat sheet

- share/goodie/cheat_sheets/json/ubuntu-unity.json
There is an incoming (previously started) Ubuntu Cheat Sheet which is more general. I've decided to rename this one as a result.
\/cc @sagarhani @CodeMouse92
> rename to ubuntu-unity, update name and ID accordingly

- share/goodie/cheat_sheets/inkscape.json
Hi everyone,
This is my first zci :) No surprise here, it's a basic cheat sheet dedicated to inkscape.
IA Page: https://duck.co/ia/view/inkscape_cheat_sheet
Gives you a basic inkscape cheat sheet.
https://inkscape.org/en/doc/keys091.html
It's the Inkscape doc, it's reliable, regularly updated, and is just the biggest inkscape hotkeys source.
Not that I know off :)
Designers, graphist that don't have the money to use Illustrator :)
**Is this Instant Answer connected to a …
> [Goodie] Inkscape cheat sheet

- share/goodie/cheat_sheets/json/geany.json
Shows a list of keyboard shortcuts for the Geany code editor (Linux only).
http://wiki.geany.org/howtos/sorted_keyboard_shortcuts
This is the definitive wiki for Geany.
Not that I'm aware of.
Developers using Linux.
https://duck.co/ia/view/geany_cheat_sheet
Nope.
**Where did you hear about DuckDuckHack? (For …
> Added Geany cheat sheet

- share/goodie/cheat_sheets/json/wordpress.json
Makes a Wordpress cheatsheet.
https://codex.wordpress.org/Keyboard_Shortcuts
The one I used is located on a wordpress.org domain, so I'm assuming the answer is no.
Web developers
https://duck.co/ideas/idea/6311/wordpress-cheat-sheet
The first category is way longer then the rest of the categories, so it kind of doesn't look good ecstatically.
**What does the Instant Answer …
> Creates Wordpress cheat sheet

- share/goodie/cheat_sheets/json/rust-types.json
Provide a cheat sheet for rust object types
https://doc.rust-lang.org/stable/reference.html#type-system
rust-lang.org is the primary authority of the rust language specification.
Probably not.
Rust programmers
No.
No.
I am already …
> Added rust types cheat sheet

- share/goodie/cheat_sheets/json/slack.json
Provide a cheat sheet for Slack users.
https://slack.zendesk.com/hc/en-us/articles/201374536-Slack-keyboard-shortcuts
It's Slack's official documentation.
Probably not.
Slack users. …
> alexander95015's Slack Cheat Sheet

- share/goodie/cheat_sheets/eclipse.json
Display keyboard shortcuts for Eclipse IDE
http://www.shortcutworld.com/shortcuts.php?l=en&p=win&application=Eclipse
Nicely categorised.
Didn't come across one.
Programmers, productivity enthusiasts, geeks, hackers etc.,
Yes. https://duck.co/ideas/idea/6042/keyboard-shortcuts-cheatsheet-for-eclipse-ide
No blockers so far. 
Meetup.com. Attended Duck Duck Hack here at Bangalore, India.
-----
IA Page: https://duck.co/ia/view/eclipse_cheat_sheet
> Eclipse cheatsheet

- share/goodie/cheat_sheets/json/blender.json
- share/goodie/cheat_sheets/json/mac-keyboard.json
- Minor cleanup to syntax
- Wrapped a few remaining alternatives properly
> Cleanup blender and mac-keyboard cheat sheet syntax

- share/goodie/cheat_sheets/json/metasploit.json
cheatsheet goodies
http://www.cheatography.com/huntereight/cheat-sheets/metasploit-4-5-0-dev-15713/
It is cool cheat sheet and most people used it
yes there many data source, but it is good and descriptive compare to other.
security, sysadmin
Yes, it is cheatsheet for security professional and pen tester.
No
**Where did you hear …
> metasploit cheat-sheet

- share/goodie/cheat_sheets/json/docker.json
Docker Cheatsheet
https://github.com/wsargent/docker-cheat-sheet
It is complete and usefull to use (made for to my own GitHub so if it will be removed I could change the IA to somewhere else)
Not of my knowledge.
Linux devops
Yes
URL: https://duck.co/ideas/idea/6282/docker-cheat-sheet
no
**What does the …
> preemeijer docker cheatsheet

- share/goodie/cheat_sheets/json/jquery.json
Cheat sheet for JQuery
http://api.jquery.com/
It is the official documentation for JQuery
No
Javascript programmers and web developers
No
No
Google
**What does the Instant Answer look like? (Provide a screenshot for new or updated …
> Added JQuery cheat sheet

- share/goodie/cheat_sheets/json/linux.json
<b>What does your Instant Answer do?</b>
Show all The Linux commands as cheat sheet.
<b>What is the data source for your Instant Answer? (Provide a link if possible)</b>
http://www.linuxstall.com/wp-content/uploads/2012/01/linux-command-line-cheat-sheet.png
<b>Why did you choose this data source?</b>
One of the Best and even recommended.
<b>Are there any other alternative (better) data sources?</b>
There are chances.
<b>Which communities will this Instant Answer be especially useful for? (gamers, book lovers, etc)</b>
Linux users, Geeks etc.
<b>Is this Instant Answer connected to a DuckDuckHack Instant Answer idea?</b>
Yes, https://duck.co/ideas/idea/6169/linux-cheat-sheet
<b>Are you having any problems? Do you need our help with anything?</b>
No
-----
IA Page: …
> Linux Cheat Sheet

- share/goodie/cheat_sheets/json/nikto.json
It will produce a cheatsheet for perl based vulnerability scanner that scans web-server for thousands of vulnerabilities and other known issues. It is advanced and more accurate and people would like the concept.
r00tsec
http://www.r00tsec.com/2014/06/cheatsheet-nikto-cheat-sheet.html
Offical site of nikto: cirt
https://cirt.net/nikto2-docs/options.html#id2741238
Both source are ingredient for good cheatsheet recipe, include some basic and advanced options with installation on different platform.
Cheatography provide same stuff as r00tsec do
Which communities will this Instant Answer be …
> Nikto Cheatsheet

- share/goodie/cheat_sheets/json/brackets.json
Provides a cheatsheet of keyboard shortcuts for [Brackets](http://brackets.io)
https://github.com/adobe/brackets/wiki/Brackets-Shortcuts
It was the only list I could find
Not that I know of (if there are, please let me know!)
Developers who use Brackets
No, should I have created a submission over there?  …
> Add brackets.json

- share/goodie/cheat_sheets/json/brackets.json
Adjusted `id`, `name` and `aliases`.
/cc @KK4OXJ
> update id to adobe_brackets_cheat_sheet, add Adobe to name, add aliases

- share/goodie/cheat_sheets/json/intellij.json
My answer displays useful shortcuts for the IntelliJ IDEA software.
Shortcut world:
http://www.shortcutworld.com/en/win/IntelliJ.html
I've seen it recommended for the eclipse cheat sheet, having read over the IntelliJ commands, all the shortcuts I use are there and a bunch which I've since learnt from reading it.
Not that I have came across.
Developers, geeks, programmers.  …
> jamie23's Intellij Goodie

- share/goodie/cheat_sheets/json/intellij.json
- updated name to `IntelliJ IDEA`
- updated description to be more descriptive
- added triggering aliases
/cc @jamie23
> update name to IntelliJ IDEA, updarte description, add aliases

- lib/DDG/Goodie/HTMLEntitiesDecode.pm
- t/HTMLEntitiesDecode.t
I've had to bomb out some of the information in the response, I'm not sure it was actually useful.
> HTMLEntitiesDecode: Converting to structured answer

- share/goodie/cheat_sheets/json/angular.json
The goodie provided here helps the developers to make it easy to take the angular directives
for their references easily , so that they can use it in their applications ,i personally felt this
because their are many times when i needed some directives but was not able to find it instantly rather
i had to go to the site and search for angular directives.So this goodie might help some instant actions                                                                                                                                                                              and save time as well.
https://docs.angularjs.org/api/ng/directive
**Why did you choose this data …
> AngularJS cheatsheet

- share/goodie/cheat_sheets/json/sublime-text.json
A few months ago I made this pull request: https://github.com/duckduckgo/zeroclickinfo-goodies/pull/1248 But moollaza told me that there was already someone else building a Sublime Text cheat sheet. Therefore I added a few shortcuts to the existing cheat sheet as additional information :smiley:
> svdsande__updateSublimeTextCheatSheet

- share/goodie/cheat_sheets/atom.json
Show all The Atom shortcut keys as cheat sheet.
https://bugsnag.com/blog/atom-editor-cheat-sheet
One of the Best and even recommended.
Their are chances.
Coder, Atom Users, Git users, Geeks etc.
Yes, https://duck.co/ideas/idea/6270/atom-cheatsheet
Yes, have a look at line 47, 61, 93, 97, 121.
What does the Instant Answer look like? (Provide a screenshot for …
> Atom Cheat Sheet

- share/goodie/cheat_sheets/atom.json
/cc @namandistro 
-----
IA Page: https://duck.co/ia/view/github_atom_cheat_sheet
> small fixes to atom cheat sheet

- share/goodie/cheat_sheets/json/secret-service-codename.json
Gives the secret service codename of United States President and vice President and their families.
[Wikipedia](https://en.wikipedia.org/wiki/Secret_Service_codename)
There is a lot of information and references at the bottom of the page are the sources of the wikipedia article.
Maybe
I dont really know 
I found the idea …
> New CheatSheet : Secret Service Codename

- share/goodie/cheat_sheets/json/groovy.json
A Cheat Sheet for Groovy-Language
Groovy-Language,
sourceUrl: http://www.groovy-lang.org/syntax.html
Reliable and easy-to-understand
No
Programmers
https://duck.co/ideas/idea/6153/groovy-language-cheat-sheet
Not yet
-----
IA Page: …
> Groovy Language Cheat sheet

- share/goodie/cheat_sheets/json/nodejs.json
A Cheat Sheet listing the commands in NodeJS
Gosquared,
sourceUrl: https://www.gosquared.com/resources/node-cheat-sheet/
Reliable and easy-to-understand
No
Programmers
Yes, https://duck.co/ideas/idea/6177/nodejs-cheat-sheet
Not yet …
> NodeJS cheat sheet

- lib/DDG/Goodie/Weight.pm
- t/Weight.t
Calculate the weight of provided mass (default in kg).
It calculates the weight with the value of the mass provided by the user.
http://physics.nist.gov/cgi-bin/cuu/Value?gn (For taking value of acceleration due to gravity on Earth as 9.80665m/s^2)
It is from a trustworthy authority (National Institute of Standards and …
> Created Weight Goodie

- lib/DDG/Goodie/Morse.pm
- t/Morse.t
Hello,
Related to #1376 
Could you please have a look and let me know if that's OK?
Thanks!
> Morse Code: the triggers and the tests have been changed according to #1376

- lib/DDG/Goodie/FirefoxOS.pm
- share/goodie/firefox_os/apis.yml
- t/FirefoxOS.t
Shows information for individual Firefox OS device APIs
Goes straight to information for a particular API rather than to the table of all APIs.
Mozilla Developer Network:
https://developer.mozilla.org/en-US/Apps/Reference/Firefox_OS_device_APIs
They created the APIs
No.
fxos alarm api
firefoxos
Firefox OS app developers …
> Added Firefox OS device API lookup

- share/goodie/cheat_sheets/json/colorado-14ers.json
- share/goodie/cheat_sheets/json/ubuntu-unity.json
- share/goodie/cheat_sheets/json/w3m.json
This one fixes issues #1538, #1540 & #1541.
> fixes a couple typos (fixes #1538, #1540 & #1541)

- share/goodie/cheat_sheets/json/angular.json
- share/goodie/cheat_sheets/json/brackets.json
- share/goodie/cheat_sheets/json/photoshop.json
- share/goodie/cheat_sheets/json/secret-service-codename.json
adds a couple aliases
removes non existing section in photoshop.json
fixes #1545, #1546, #1547 & #1548
> adds a couple aliases and removes unused section (fixes #1545, #1546, #1547 & #1548)

- pull_request_template_goodie.md
- share/goodie/cheat_sheets/i3.json
Using this template will help us better understand your Instant Answer and assist you when necessary.  Simply copy and paste the markdown below into the description of
our GitHub pull request and complete as appropriate.                                                                                                                      
**What does your Instant Answer do?**                                                                                                                                     
This is a cheat-sheet for [i3](http://i3wm.org/) window manager.                                                                                                                               …
> creating i3 cheatsheet for ddg

- share/goodie/cheat_sheets/json/military-slang.json
A Cheat Sheet defining slang terms used in the Military 
Wikitionary
sourceUrl: "http://www.military.com/join-armed-forces/military-terms-and-jargon.html"
Reliable and extensive
Alternative - Yes
Better -No
Anyone interested in military slangs 
Yes, https://duck.co/ia/view/military_slang_cheat_sheet
Not Yet …
> Military slang cheat sheet

- share/goodie/cheat_sheets/json/http-status-codes.json
This IA shows response/status codes returned by the HTTP.
http://www.cheatography.com/kstep/cheat-sheets/http-status-codes/
It shows a simplified reference to most HTTP status codes.
No.
Network admins, people using proxies.
No.
No.
-----
IA Page: https://duck.co/ia/view/http_status_codes_cheat_sheet
> HTTP Status Codes Cheatsheet

- share/goodie/cheat_sheets/json/golang.json
> simplify and separate control structures

- share/goodie/cheat_sheets/json/german.json
Hi,
i went through the list of open PRs and found #1358 which had reasonable improvements to the german cheat sheet. The original author did not finish it so i thought i pick this up and submit a new PR based on the latest master. If this one is accepted #1358 can be closed.
cheers
Stephan
> fixes typo and adds minor improvements to german.json (picks up #1358)

- lib/DDG/Goodie/NameDays.pm
- share/goodie/name_days/name_days.css
- t/NameDays.t
> Name Days: Set max-width on table

- share/goodie/cheat_sheets/json/opera.json
Show all The Opera shortcut keys as cheat sheet.
http://www.makeuseof.com/tag/opera-shortcuts/
One of the Best and even recommended.
Their are chances.
Opera users.
Yes, https://duck.co/ideas/idea/6291/opera-browser-cheat-sheet
No
What does the Instant Answer look like? (Provide a screenshot for new or updated Instant Answers)
-----
IA Page: …
> Opera Cheat Sheet

- share/goodie/cheat_sheets/idris-emacs.json
A cheatsheet for the Emacs mode for the Idris programming language.
The data source is the source for the emacs mode
https://github.com/idris-hackers/idris-mode
These are the official sources of information.
No.
For developers, researchers, and enthusiasts of the dependently typed language Idris.
Not that I am aware of.
**Are you having any problems? Do you need our help with …
> Added cheatheet for the idris emacs-mode.

- share/goodie/cheat_sheets/json/kmplayer.json
Give an instant answer to a searched Keyword
It gives cheatsheets for KMplayer 
KMplayer Software , The data source is the software , I reviewed each menus in it.
Because KMplayer is an widely used Software . I hope it will be helpful for many users
I dont no , lets duck it !!!
Kmplayer , KMplayer cheatsheet
People who use …
> kmplayer Cheat Sheet

- share/goodie/cheat_sheets/json/chess.json
This Instant Answer provides basic information on the different pieces in chess and how they move, basic gameplay, how the game ends, and special movements like castling.
Wikipedia: https://en.wikipedia.org/wiki/Chess
Because it had the most comprehensive and yet still readable guide on how the game is played as we as additional resources if the user wants to read more.
Chess.com has a pretty good explanation as well (http://www.chess.com/learn-how-to-play-chess) but I thought the Wikipedia page would give better context. …
> New Chess Cheat Sheet

- share/goodie/cheat_sheets/json/microsoft-windows.json
- share/goodie/cheat_sheets/json/windows10.json
Shows cheat sheet of short cuts only available for windows 10
Shows cheat sheet of windows 10 keyboard short cuts which makes things easy for windows 10 users.
http://www.howtogeek.com/198122/32-new-keyboard-shortcuts-in-the-windows-10-technical-preview
Shows every windows 10 short cuts 
No I find it better than any thing else
windows 10 cheat sheet
**Which communities will this Instant Answer be especially useful for? …
> zandip's windows 10 Goodie

- share/goodie/cheat_sheets/json/dutch.json
Dutch cheatsheet added #1481 follow-up.
Sorry people for this new pull request and thanks to thm for pointing out the two problems.
----
IA Page: https://duck.co/ia/view/dutch_cheat_sheet
> Dutch Cheat Sheet improvements

- share/goodie/cheat_sheets/json/xwing-alliance.json
Displays keyboard shortcuts of X-Wing Alliance videogame.
No dynamic datasource (original scanned reference card on Darksaber's X-Wing Station).
Contains all keyboard shortcuts. 
No. 
Gamers.
No.
No, thanks.
From DuckDuckGo search page! …
> New X-Wing Alliance (videogame) Cheat Sheet

- share/goodie/cheat_sheets/json/java.json
Display the cheat sheet for Java.
http://www.cheatography.com/sschaub/cheat-sheets/java-fundamentals/
Got from a basic search.
yes there is.
Developers.
Yes. [Link](https://duck.co/ideas/idea/6164/java-cheat-sheet)
No
reddit.com
**What …
> Java cheat sheet

- lib/DDG/Goodie/IsAwesome/gmahesh23.pm
- t/IsAwesome/gmahesh23.t
It prints my Github Username and tells that I am awesome and completed the Goodie Hack.
It helps to find me among all other Github users.
https://duck.co/duckduckhack/goodie_quickstart
Because it is my first Goodie Hack.
No
duckduckhack gmahesh23
Github Users.
**Is this Instant Answer connected to a DuckDuckHack Instant …
> First Goodie Hack

- share/goodie/cheat_sheets/json/mplayer.json
MPlayer cheat sheet
Brief overview of  MPlayer key sequences
http://www.mplayerhq.hu/DOCS/man/en/mplayer.1.html
Complete key sequence documentation
alternative: http://sheet.shiar.nl/mplayer, but some keys are interchanged
mplayer cheat sheet
MPlayer users
**Is this Instant Answer connected to a DuckDuckHack [Instant …
> MPlayer cheat sheet created

- share/goodie/cheat_sheets/json/cmus.json
It provides a cheat sheet for cmus music player.
As cmus is a console based player, there are lots of keybindings. It's easier to remember when having a cheat sheet.
https://github.com/cmus/cmus/blob/master/Doc/cmus.txt
It is the official manual provided by cmus developers.
I don't know of.
cmus cheat sheet, cmus guide …
> New Cmus Cheat Sheet

- share/goodie/cheat_sheets/json/opencv.json
A Cheat Sheet explaining the functions of OpenCV
opencv.org
sourceUrl: "http://docs.opencv.org/modules/refman.html"
Reliable and extensive
No
Programmers
https://duck.co/ideas/idea/6294/linux-terminal-commands-cheat-sheet
Not yet …
> OpenCV 2.4 cheat sheet

- share/goodie/cheat_sheets/json/processing.json
A Cheat Sheet explaining the commands in Processing
Processing.org
sourceUrl: "http://www.processing.org/reference/"
Reliable and extensive
No
Programmers
Yes, https://duck.co/ideas/idea/6295/processing-cheat-sheet
Not yet
-----
IA …
> Processing Cheat Sheet

- lib/DDG/Goodie/UnixTime.pm
Allow "time since epoch" to trigger the UnixTime script.
> Added new Epoch Trigger

- share/goodie/cheat_sheets/homebrew.json
My cheatsheet submission provides help for the most common [homebrew](http://brew.sh) commands
Provides a cheatsheet for common homebrew commands without visiting the home page or checking the brew man page.
The homebrew man page as well as the [homebrew site](http://brew.sh).
it's the source.
not that I'm aware of.
homebrew cheat sheet
homebrew commands
**Which communities will this Instant Answer be especially useful …
> adding homebrew.json

- lib/DDG/Goodie/DaysBetween.pm
- t/DaysBetween.t
As requested in #1221, added the "how many days between" trigger.
> DaysBetween - Added another trigger

- share/goodie/cheat_sheets/json/turkish.json
Provides a quick reference of beginner phrases for travelers in Turkey.
http://www.linguanaut.com/english_turkish.htm
Accurate and saw that it was previously used by German cheat sheet.
Nope, as far as I know. However, as a native Turkish speaker, I've changed some of the translations provided by the source.
People traveling to Turkey.
Nope.
**Are you having any problems? Do …
> New CheatSheet: Turkish

- share/goodie/cheat_sheets/json/age-of-mythology.json
Provides a cheat sheet about the game "Age of Mythology"
It is a fans 's site about this game.
http://aom.heavengames.com/gameinfo/cheats
Because it contains all the information from other sources that I found.
A good one could be http://www.gamefaqs.com/pc/476277-age-of-mythology/cheats
Gamers
yes->https://duck.co/ideas/idea/6387/age-of-mythology-cheatsheet
**Are you having …
> Age of mythology cheat sheet

- share/goodie/cheat_sheets/json/c++-algorithms.json
My answer displays useful quick references for the functions in <algorithm> in C++.
Shortcut world:
http://www.cplusplus.com/reference/algorithm/
I've seen it recommended for the original cheat sheet idea as a good source.
Not sure about better, I've always used this website for references when using C++.
Developers, geeks, programmers.
Yes,
https://duck.co/ideas/idea/6137/c-algorithms
**Are you …
> New C++ Algorithms Cheat Sheet

- share/goodie/cheat_sheets/elementary.json
- Shows all The Elementary OS Commands as cheat sheet.
- http://lmelinux.net/2014/07/26/elementary-os-keyboard-shortcuts/
- One of the Best and even recommended.
- There are chances.
- Elementary OS users, Geeks, Linux.
- Yes, https://duck.co/ideas/idea/6240/elementary-os-keyboard-shortcuts
- Nopes.
-----
IA Page: https://duck.co/ia/view/elementary_cheat_sheet
> elementary OS Cheat Sheet

- share/goodie/cheat_sheets/json/si-units.json
Provide a list of SI units
Instantly displays a list of commonly used SI units
http://physics.nist.gov/cuu/Units/units.html
It is from a trustworthy authority (National Institute of Standards and Technology).
Not sure.
SI Units cheat sheet, international system of units reference, si physics help
Students or people who …
> Created SI Units Cheat Sheet

- t/UnixTime.t
> Add test for PR #1573 new trigger

- share/goodie/cheat_sheets/json/command-prompt.json
- share/goodie/cheat_sheets/json/windows-command-prompt.json
It will display all basic command prompt commands and shortcut keys
(n/a)
(n/a)
(n/a)
Geeks
https://duck.co/ideas/idea/6303/command-prompt-cmd-exe-cheatsheet
-----
IA Page: https://duck.co/ia/view/windows_cmd_cheat_sheet
> Added command prompt cheatsheet

- share/goodie/cheat_sheets/json/mercurial.json
This instant answer is a cheat sheet for working with the mercurial (hg) dvcs.
http://www.cheatography.com/codeshane/cheat-sheets/mercurial-hg/
This was the data source that was linked to in the instant answer idea page (6223)
https://mercurial.selenic.com/wiki/QuickReferenceCardsAndCheatSheets?action=AttachFile&do=view&target=Mercurial-Usage-v1.0bz-300dpi-b%26w.png
programmers, sysadmins …
> New Mercurial(hg) Cheat Sheet

- share/goodie/cheat_sheets/json/poker-hands.json
@moollaza Here you go. I merged PR #1383 into the poker hands cheat sheet. Once this is merged, #1383 can be closed. This is how it looks now:
> adds poker hands probabilities to poker hands cheat sheet (completes #1383)

- lib/DDG/Goodie/CurrencyIn.pm
- t/CurrencyIn.t
> CurrencyIn: fixes #1599

- lib/DDG/Goodie/CurrencyIn.pm
- lib/DDG/Goodie/UN.pm
- share/goodie/currency_in/currency.txt
- t/CurrencyIn.t
- t/UN.t
**UN:**
Before:
After:
**CurrencyIn:**
Before I:
After I:
Before II:
After II:
> UN & CurrencyIn: Convert to Structured Answer

- share/goodie/cheat_sheets/json/jive-talk.json
Also removed a couple of blank lines and fixed indenting consistency.
> Jive Talk Cheatsheet: Removed duplicate entry

- share/goodie/cheat_sheets/states-of-india.json
It provides you Capital cities of  States and Union Territory of India
[ States of India ]( https://en.wikipedia.org/wiki/List_of_state_and_union_territory_capitals_in_India)
official Wikipedia page
It provides basic knowledge about India and its states
Students, Travellers
No
No
Via other …
>  States Of India & their Capital

- share/goodie/cheat_sheets/json/us-government-agencies.json
Displays acronyms for common US government agencies. 
It's shortens the list of government agencies provided in the source. It only shows common agencies that people are more likely to be interested in.
A Guide to U.S. Government Acronyms & Abbreviations
http://ucsd.libguides.com/c.php?g=90902&p=584912
It has, if not all, most of the us government agencies.
Not that I know of.
us government agencies, us government, us …
> New us government agencies cheat sheet

- share/goodie/cheat_sheets/json/chess.json
Just fixing some typos and making the language a bit more consistent and sound nicer
> Fixing typos and tightening up language for Chess cheat sheet

- share/goodie/cheat_sheets/json/data-size.json
- share/goodie/cheat_sheets/json/digital-information-units.json
Shows information about size of standard units of information, e.g. KB, GB, etc.
It allows you to quickly have a look at data hierarchy and relative/absolutely sizes. 
Wikipedia: https://en.wikipedia.org/wiki/Units_of_information
It's worldwide use source, it's especially good for encyclopedic knowledge.
There are standard articles (e.g. IEC 80000-13:2008), but it's not freely distributed. 
"units of data cheat sheet", …
> New Units of Information Cheat Sheet

- share/goodie/cheat_sheets/json/bbcode.json
- Provides a cheatsheet for BBCodes (used by many online forums, including the DDG forums)
- http://bbcode.org
- http://bbcode.org/reference.php
This is pretty much the defacto resource for BBCodes
- There are others, but most are specific to particular forum software BBCode implementations. The source that I selected is primarily the standard codes used by most forums.
- Those that use online forums on other online communities that support BBCode formatting.
**Is this …
> New BBCode Cheat Sheet

- pull_request_template_goodie.md
fixes #1625
* Added windows 10 as a new platform.
* Added Linux as a new platform.
> Added Windows 10 and Linux as platforms for goodies

- share/goodie/cheat_sheets/json/elementary.json
- share/goodie/cheat_sheets/json/idris-emacs.json
- share/goodie/cheat_sheets/json/nmap.json
- share/goodie/cheat_sheets/json/opera.json
- share/goodie/cheat_sheets/json/sms.json
- share/goodie/cheat_sheets/json/sublime-text.json
- share/goodie/cheat_sheets/json/windows-command-prompt.json
Fixes based on in-progress Cheat Sheet Tester #1612 
/cc @MariagraziaAlastra
> Minor Cheat Sheet fixes

- share/goodie/cheat_sheets/json/shell.json
It features a quick overview over things you need to know about writing shell scripts. The categories are variables, loops, built-in variables, operators, comments, conditionals and other.
You have a quicker overview over shell scripting than you would have if you would need to search for a source which might be too extensive.
[Bash Cheat Sheet](http://www.johnstowers.co.nz/blog/pages/bash-cheat-sheet.html)
Because it features a short overview over the most important things you need to know about shell scripting.
**Are there any other …
> New Cheat Sheet for Shell Language

- share/goodie/cheat_sheets/json/currency.json
A Cheat Sheet for currencies of different countries
Wikipedia,
sourceUrl: https://en.wikipedia.org/wiki/List_of_countries_and_capitals_with_currency_and_language
Reliable and easy-to-understand
No
**Which communities will this Instant Answer be especially useful for? (gamers, book lovers, etc)
Anyone
Yes, https://duck.co/ia/view/6441
Not yet
**What does the Instant Answer look like? (Provide a screenshot for new or updated Instant …
> New Currency Cheat Sheet

- share/goodie/cheat_sheets/json/coffeescript.json
- share/goodie/cheat_sheets/json/gnupg.json
- share/goodie/cheat_sheets/json/nmap.json
- share/goodie/cheat_sheets/json/tar.json
Hello @moollaza,
I did a search on all the files on the string "key": "$ and found these files (there are more files I was getting back but as far as I could understand legit use of the $ signs)
This pull request fixes #1624 
Greetings, Paul
> Dollarsign removal for tar.json nmap.json gnupg.json coffeescript.json

- share/goodie/cheat_sheets/json/aoeii.json
My Instant Answer provides a cheat sheet for the Age of Empires II video game.
It provides a single view of all hotkeys, instead of a scrollable list.
http://www.angelfire.com/biz5/age2/hotkeys.html
It had an easy format that I could read and convert into the JSON format needed to create a cheat sheet.
Some data sources included pictures and color codings, however these lists were tall and required scrolling as well. …
> New Age of Empires II Cheat Sheet

- lib/DDG/Goodie/Bitsum.pm
- t/Bitsum.t
This is in reference to #1685 .
Hope this helps!
> Bitsum: Accept binary input

- share/goodie/cheat_sheets/json/indian-languages.json
- share/goodie/cheat_sheets/json/indianstates.json
- share/goodie/cheat_sheets/json/languages-of-india.json
- share/goodie/cheat_sheets/json/states-of-india.json
This is the cheat sheet for indian languages:
> New Languages of India Cheat Sheet

- lib/DDG/Goodie/Calculator.pm
- t/Calculator.t
Fixes [#1393 ](https://github.com/duckduckgo/zeroclickinfo-goodies/issues/1393).
> Calculator - Ignore phone numbers

- share/goodie/cheat_sheets/json/toontown.json
Gives mod commands for the Toontown Video Game
Source code
Most accurate 
Nope
Gamers, the Toontown community
No
Nope!
Duckduckgo search :smiley: !
-----
IA Page: https://duck.co/ia/view/toontown_cheat_sheet
> Create Toontown Cheatsheet

- share/goodie/cheat_sheets/kerbal-space-program.json
Cheat sheet added.
http://wiki.kerbalspaceprogram.com/wiki/Key_bindings
It comes directly from the company that makes the game.
There are not.
Gamers.
No.
No thanks.
I don't think this applies to cheatsheet …
> Add Kerbal Space Program cheatsheet

- share/goodie/cheat_sheets/json/atom.json
- Changed Description to official [atom](http://atom.io) description
- Added aliases
- Added optional template_type
- Fixed some typo
> Atom cheat sheet minor fixes

- share/goodie/cheat_sheets/json/golf-majors.json
Returns basic info on the men's major golf championships
To remember the basics on the golf majors, don't need to click a link
Wikipedia - https://en.wikipedia.org/wiki/Men%27s_major_golf_championships
Optimal
Nope
mens golf majors cheat sheet, golf majors cheat sheet
golf & sports fans
**Is this Instant Answer connected …
> Golf majors cheat sheet

- share/goodie/cheat_sheets/json/aoeii.json
- Removed unnecessary alias
- Fixed Typo
> Aoeii Cheat Sheet Fixes

- lib/DDG/Goodie/SolarSystem.pm
- share/goodie/solar_system/content.handlebars
- share/goodie/solar_system/mobile.handlebars
Reverts duckduckgo/zeroclickinfo-goodies#1718
> Revert "get share path rather than constructing from version"

- share/goodie/cheat_sheets/json/apple-mac-os.json
- Formatted JSON
- Used Cmd icon
- + other fixes
> Fixed OSX Cheat Sheet

- share/goodie/cheat_sheets/json/imgur.json
- share/goodie/cheat_sheets/json/w3m.json
- share/goodie/cheat_sheets/json/xcode.json
All cheat sheets have ```template_type```property now :smile:
> Added template_type for XCode, Imgur, w3m

- share/goodie/cheat_sheets/json/heroku.json
My instant answer provides a cheat sheet for the Heroku command-line tool, an interface to the Heroku Platform API.
[Command Line | Heroku Dev Center](https://devcenter.heroku.com/categories/command-line)
This is the official reference for the heroku command line tool, but a cheat sheet is much required.
None
Developers using Heroku as a platform to deploy their apps.
No …
> New Cheat Sheet for Heroku

- lib/DDG/Goodie/MagicEightBall.pm
- t/MagicEightBall.t
It answer any query with a random answer like a magic eight ball
Its a fun easter egg to emulate the experience of a magic eight ball on the duckduckgo site.
I used the wikipedia article on a magic eight ball for a list of proper responses.
https://en.wikipedia.org/wiki/Magic_8-Ball
It was the first one I found but all other sites I checked were in agreement with what the standard responses are.
None that offered a different list of possible answers
**What are some example queries that …
> New MagicEightBall Goodie

- share/goodie/cheat_sheets/safari.json
It displays the keyboard shortcuts for safari browser
[Apple Support](https://support.apple.com/kb/PH17148?locale=en_US)
Internet users
NO
-----
IA Page: https://duck.co/ia/view/safari_cheat_sheet
> safari cheat sheet

- dist.ini
New dzil plugin to send a message about new releases and what has changed.
> Add announce release plugin

- share/goodie/cheat_sheets/json/kabaddi-terms.json
It tells about terms used in kabadii and its definitions.
Wikipedia, https://en.wikipedia.org/wiki/Kabaddi
This is perfect.
Ya, http://www.prokabaddi.com/prokabaddi-rules
Kabaddi lovers 
yup
Nope, thanks
Where did you hear about DuckDuckHack? (For first time contributors)
from hackathon sponsered by DuckDuckGo
What does the Instant Answer look like? (Provide a …
> New kabaddi Terms Cheat Sheet

- share/goodie/cheat_sheets/json/filezilla.json
A cheat sheet that lists useful Filezilla keyboard shortcuts.
It summaries all the most commonly used shortcuts so you don't have to go through several links/sources.
[Filezilla](https://wiki.filezilla-project.org/Keyboard_shortcuts) official wiki
They list all the most commonly used Filezilla keyboard shortcuts.
- Filezilla cheat sheet
Web developers
**Which existing Instant …
> Filezilla cheat sheet

- share/goodie/public_dns/providers.yml
Adding missing string, prevents the test from failing
/cc @jdorweiler
> Add URL for Level3 DNS, remove trailing spaces

- share/goodie/cheat_sheets/json/fallout-4.json
https://duck.co/ia/view/fallout_4_cheat_sheet
> Cheat sheet for Fallout 4 default key bindings

- template/lib/DDG/Goodie/Example.pm
* Remove metadata from module template
* Clean up the syntax
> Remove metadata from template

- .travis.yml
Cache:
* Perl deps
* npm install
* metadata
> Cache our junk on travis

- share/goodie/cheat_sheets/json/dockerfile.json
Show instructions used in a Dockerfile file.
<http://docs.docker.com/engine/reference/builder/>
It's in the main page of the docker project.
not that I know
developers
<https://duck.co/ideas/idea/6700/dockerfile-cheatsheet>
no, but I really appreciate if you guys have a docker image.
**Where did you hear …
> Cheatsheets for Dockerfile added.

- template/lib/DDG/Goodie/Example.pm
- template/share/goodie/example/example.js
- Update the Goodie Perl template to suggest structured answers w/ full templating.
- If we plan to continue supporting the simplified templating, we could use that as the default?
- Added a JS skeleton for a Goodie, adapted from Russell's "Game of Life"
- This won't be used until the DuckPAN template code is updated to use the file
> Goodie Template Updates

- share/goodie/cheat_sheets/cheat_sheets.js
- share/goodie/cheat_sheets/json/eclipse.json
Issue #1646 - Eclipse IDE Cheat Sheet: fix JS Error.
> Issue #1646 - Eclipse IDE Cheat Sheet: fix JS Error

- share/goodie/cheat_sheets/json/nodejs-tutorials.json
Figured I'd finish this up, it's basically been done for the past while :)
/cc @alohaas 
Result:
-----
IA Page: https://duck.co/ia/view/nodejs_tutorials_cheat_sheet
> re-format JSON

- share/goodie/cheat_sheets/json/crochet-pattern.json
My instant answer provides abbreviations for crochet patterns
Crochet patterns use a code that is referenced often when learning
http://craftyarncouncil.com/crochet.html
It was recommended to me as canonical
I believe most sources are based on this one.
'crochet pattern cheat sheet' 
crocheters, crafters
**Is this Instant …
> New Crochet Pattern Cheat Sheet

- share/goodie/cheat_sheets/json/scratch.json
Scratch cheatsheet for the buildingblocks
http://www.dummies.com/how-to/content/scratch-for-kids-for-dummies-cheat-sheet.html
http://wiki.scratch.mit.edu/wiki/Scratch_Wiki:Table_of_Contents/Program
It was the best that I could find for this purpose
Yes used the original wiki for the value texts
What are some example queries that trigger this Instant Answer?
scratch cheatsheet
For students who get some lessons with this program; starting programmers.
Is this Instant Answer connected to a …
> Scratch cheatsheet

- share/goodie/cheat_sheets/json/bootstrap.json
Demo link: https://drive.google.com/file/d/0B_0VuTZLjvTQUWZBYTNYT1hkckk/view?usp=sharing
It gives a quick description of core CSS classes in the Boostrap frameworks. 
It is much better than organic links IMO because I aggregated this information from StackOverflow, w3schools, and the Bootstrap documentation. I thought that for a quick reference, the bootstrap documentation can be confusing so I sought to make this easier by explaining it a little bit more specifically.
Mainly http://getbootstrap.com/ as a guide but I also used http://www.w3schools.com/bootstrap, , …
> New Bootstrap Cheat Sheet

- share/goodie/cheat_sheets/json/mainframe.json
Show all The Mainframe system basic commands as cheat sheet.
http://www.mainframes.com/Commands.html
Mainframe is a large high-speed computer, especially one supporting numerous workstations or peripherals. Hence it will be easy to follow the commands.
No
Large organizations, DevOPs, SystemAdmins, etc.
Yes, https://duck.co/ideas/idea/6681/mainframe-cheat-sheet
**Are you having any problems? Do you …
> Mainframe cheat sheet

- share/goodie/cheat_sheets/json/arch-linux.json
It is a cheat sheet for Pacman which is the default Package Manager for Arch Linux.
Every distro consist of its own package manager and so different commands . thus a cheat sheet is neccesary.
https://wiki.archlinux.org/index.php/Pacman
It is the official page for Arch Linux.
Man Page of Pacman and Yaourt
arch linux cheat sheet , pacman cheat sheet , yaourt cheat sheet …
> New Arch_Linux Cheat Sheet

- lib/DDG/Goodie/PackageTracking.pm
- t/PackageTracking.t
> Issue #1138 - start working

- share/goodie/cheat_sheets/json/slovak.json
Displays common phrases in Slovak language with appropriate English translations.
It shows common phrases just now without searching for good page or tracking.
I translated [Czech cheat sheet](https://github.com/duckduckgo/zeroclickinfo-goodies/blob/master/share/goodie/cheat_sheets/json/czech.json).
I choose it as starting point for this cheat sheet as it provides common phrases and it is easy to translate as Slovak is similar language.
Can't think of any.
**What are some example queries …
> New Slovak cheat sheet

- share/goodie/cheat_sheets/json/kabaddi-terms.json
This is the only kabaddi Instant Answer at the moment so I think it's OK to have a general "kabaddi" trigger. If there's another one in future then we could consider returning to more precise triggers.
> Kabaddi cheat sheet: Added 'kabaddi' as an alias

- share/goodie/cheat_sheets/json/japanese-prefectures.json
Lists Japan's prefectures (like states) and their capitals.
https://en.wikipedia.org/wiki/Japanese_prefectures
It's an accurate, comprehensive list.
No.
People learning more about Japan.
No.
No.
N/A
**What does the Instant Answer look …
> Added Japanese prefectures cheat sheet

- lib/DDG/Goodie/ColorCodes.pm
- share/goodie/color_codes/color_codes.css
- share/goodie/color_codes/content.handlebars
- t/ColorCodes.t
Fixes #1163 
-----
IA Page: https://duck.co/ia/view/color_codes
> Issue #1163 - Convert ColorCodes to use template

- lib/DDG/Goodie/Anagram.pm
- lib/DDG/Goodie/Scramble.pm
- t/Anagram.t
- t/Scramble.t
This is WIP
-----
IA Page: https://duck.co/ia/view/scramble
> Issue #437 - Anagram.pm - Should be separated into Anagram.pm and Scramble.pm

- lib/DDG/Goodie/ResistorColors.pm
- share/goodie/resistor_colors/content.handlebars
- share/goodie/resistor_colors/resistor_colors.css
- t/ResistorColors.t
@moollaza I don't use fix becuse this PR does not closes Issue 1163
-----
IA Page: https://duck.co/ia/view/resistor_colors
> Issue #1163 - Convert ResistorColors to use template

- share/goodie/cheat_sheets/json/intellij.json
- share/goodie/cheat_sheets/json/jive-talk.json
- share/goodie/cheat_sheets/json/kerbal-space-program.json
> Update intellij, jive-talk, kerbal-space json files

- lib/DDG/Goodie/RubiksCubePatterns.pm
- t/RubiksCubePatterns.t
-----
IA Page: https://duck.co/ia/view/rubiks_cube_patterns
> Issue #1163 - Convert RubiksCubePatterns to use templates

- share/goodie/cheat_sheets/json/c.json
Its a cheatsheet for the Basics of the C programming language.
It gives access to some of the basic of the C language like conversion characters, and precedence order.
http://www.dummies.com/how-to/content/beginning-c-programming-for-dummies-cheat-sheet.html
Because this contains a good collection of basic c content
I didn't find any
c cheatsheet OR C cheatsheet. I can add more aliases if needed.
**Which communities will …
> New C Cheatsheet

- lib/DDG/Goodie/Sort.pm
- t/Sort.t
I think that this IA should sort the words too ...
> Fix #1837 - ensure it has a remainder to sort

- lib/DDG/Goodie/BloodDonor.pm
- t/BloodDonor.t
`-ve` and `+ve` are also in usage. //cc @moollaza @mintsoft
> Support `-ve` and `+ve`

- share/goodie/cheat_sheets/json/wunderlist.json
Adds a keyboard-shortcut cheat sheet for Wunderlist.
https://support.wunderlist.com/customer/en/portal/articles/889536-shortcuts
It is from the official site and gives a good overview of the basic shortcuts.
[Another](https://support.wunderlist.com/customer/en/portal/articles/1988210-wunderlist-keyboard-navigation) page from the same site provides a good overview of some of the navigation shortcuts, but doesn't cover some of the more general shortcuts (and is longer).
People …
> New Wunderlist Cheat Sheet

- share/goodie/cheat_sheets/json/8085.json
8085 instructions reference
http://home.iitk.ac.in/~ajalan/8085_is_details.pdf
Its reliable
Yes,may be
students
no
no
From my friend
-----
IA Page: …
> New 8085 instructions cheat sheet

- lib/DDG/Goodie/Average.pm
- t/Average.t
> Add rms as root mean square on Average

- lib/DDG/Goodie/Calculator.pm
- t/Calculator.t
**Which issues (if any) does this change solve? (please link them here)**
Fixes issue #1694 
**Briefly describe your fix. Are there any important details we should know about?**
I've just corrected some regular expressions to make the expressions work (and added
tests to make sure they continue working in the future).
Not really.
> Calculator: Fix issue #1694

- template/lib/DDG/Goodie/Example.pm
- template/share/goodie/example/example.js
- template/t/Example.t
Tested with changes introduced in https://github.com/duckduckgo/p5-app-duckpan/pull/289
> templates: use ia_id instead of lia_name

- share/goodie/cheat_sheets/json/scala.json
It is a cheat sheet for Scala programming language.
http://docs.scala-lang.org/cheatsheets/ with some minor corrections to make it simpler.
This is part of the official Scala documentation.
[There are](https://duckduckgo.com/?q=scala+cheat+sheet) some other data sources, but the above one seems to be better. We could add missing topics from other data sources also to improve this.
Programmers. …
> New Scala cheatsheet

- share/goodie/cheat_sheets/json/sketch.json
Cheat sheet added.
http://sketchshortcuts.com/
It had the most comprehensive shortcut list I could find.
There are alternatives, but not as comprehensive.
Designers.
No.
No, thank you.
---
https://duck.co/ia/view/sketch_cheat_sheet
> Create Sketch cheatsheet

- share/goodie/cheat_sheets/json/perl.json
It is a cheat sheet for Perl language.
http://www.cheatography.com/mishin/cheat-sheets/perl-reference-card/
It was well organised and compact.
http://michaelgoerz.net/refcards/perl_refcard.pdf
It is useful for Perl programmers and developers.
No
From a friend …
> new perl cheat sheet

- share/goodie/cheat_sheets/json/perl.json
Corrected PR #1874 ,Removing Unnecessary Alias.
> Cheat Sheet : Fixes #1874

- lib/DDG/Goodie/Lowercase.pm
- t/Lowercase.t
> Lowercase: Nil return when output is equal to input

- share/goodie/cheat_sheets/json/apple-mac-os.json
> Update apple-mac-os.json: fixes #1881

- lib/DDG/Goodie/Constants.pm
Remove default description in metadata.  Updated with description provided in IA page.
------
IA Page:  http://duck.co/ia/view/constants
> Constants: Update IA description

- share/goodie/cheat_sheets/json/vcgencmd.json
Removed unnecessary alias and added two more.
> vcgencmd: Updated aliases

- share/goodie/chess960/chess960.js
Some changes on chess960.js 
You can see discussion on https://github.com/duckduckgo/zeroclickinfo-goodies/pull/1791
> some changes on chess960.js

- share/goodie/cheat_sheets/json/phpstorm-osx.json
It shows small portion of keyboard shortcuts for OSX version of PHPStorm. By small I mean the the most useful ones in my opinion.
http://overapi.com/phpstorm
The PDF is provided by JetBrains, but it looks like they don't host it anymore, so this link is one working that I found.
I gonna go with 'no'.
PHP programmers.
To Cheat Sheet Goodie.
**Are you having any problems? Do you need our help with …
> New PHPStorm OSX cheat sheet

- lib/DDG/Goodie/RubiksCubePatterns.pm
- t/RubiksCubePatterns.t
-----
IA Page: https://duck.co/ia/view/rubiks_cube_patterns
> Fix #1873 - Shouldn't trigger when query is only 'Rubics Cube'

- share/goodie/cheat_sheets/json/apt-get.json
My instant answer provides the most commonly used commands of the AptGet package manager for Debian based GNU/Linux systems.
[Ubuntu Wiki](https://help.ubuntu.com/community/AptGet/Howto)
Ubuntu Wiki has the most comprehensive documentation of the AptGet package managet
[Debian Wiki](https://wiki.debian.org/Apt)
GNU/Linux users
No
**Are you having any problems? Do you need our …
> add apt-get.json

- share/goodie/cheat_sheets/json/bash.json
> Updated bash.json to more descriptive

- share/goodie/cheat_sheets/json/eclipse.json
> added description to eclipse.json

- share/goodie/cheat_sheets/json/cpp.json
> added description to cpp.json

- share/goodie/cheat_sheets/json/emacs.json
made emacs.json more descriptive
> More descriptive emacs.json

- share/goodie/cheat_sheets/json/golang.json
- share/goodie/cheat_sheets/json/i3.json
- share/goodie/cheat_sheets/json/irc.json
- share/goodie/cheat_sheets/json/java.json
- share/goodie/cheat_sheets/json/jira.json
- share/goodie/cheat_sheets/json/jquery.json
- share/goodie/cheat_sheets/json/linux.json
- share/goodie/cheat_sheets/json/lua.json
- share/goodie/cheat_sheets/json/mercurial.json
- share/goodie/cheat_sheets/json/minecraft.json
- share/goodie/cheat_sheets/json/nato-alphabet.json
- share/goodie/cheat_sheets/json/redis.json
- share/goodie/cheat_sheets/json/scala.json
- share/goodie/cheat_sheets/json/shell-variables.json
- share/goodie/cheat_sheets/json/shell.json
- share/goodie/cheat_sheets/json/si-units.json
- share/goodie/cheat_sheets/json/sip-response-codes.json
- share/goodie/cheat_sheets/json/slack.json
- share/goodie/cheat_sheets/json/ssh.json
- share/goodie/cheat_sheets/json/sublime-text-mac.json
Fixes:
* Missing descriptions
* Extra spaces
> Fixes several missing descriptions and extra spaces

- share/goodie/cheat_sheets/json/markdown.json
Fixes #1906 
---
https://duck.co/ia/view/markdown_cheat_sheet
> Added markdown cheatsheet

- share/goodie/cheat_sheets/json/php.json
It is cheat sheet for PHP which is a server side scripting language and very commonly used.
http://php.net/manual/en/funcref.php
It is the official page for php manual.
Here is an alternative source- http://www.cheatography.com/davechild/cheat-sheets/php/
This answer will be really helpful for web developers who extensively use PHP.
No.
**Are you having any problems? Do you …
> New PHP Cheat Sheet

- share/goodie/cheat_sheets/vitamin.json
Continue #1722 
/cc @ankushg07
-----
IA Page: https://duck.co/ia/view/vitamin_cheat_sheet
> Continue PR #1722

- share/goodie/cheat_sheets/json/mongodb.json
Show all The MongoDB basic queries and keys as cheat sheet.
https://blog.codecentric.de/files/2012/12/MongoDB-CheatSheet-v1_0.pdf
One of the Best and even recommended database for open-source development.
There are chances.
Coder, Open source, Git users, Geeks, Hackers, etc.
Yes, https://duck.co/ideas/idea/6304/mongodb-cheet-sheet …
> New MongoDB Cheat Sheet

- t/Week.t
- t/Zodiac.t
Lo,
There's some tests that I missed in last year's MockTime frenzy that are causing trouble with people attempting to test their changes
cc @moollaza @jagtalon
> Temporal Tests breaking Travis/Prove

- share/goodie/cheat_sheets/json/cpp-strings.json
Update cpp-strings.json 
added aliases 
#1983 
-----
IA Page: https://duck.co/ia/view/cpp_strings_cheat_sheet
> Update cpp-strings.json: Fixes #1983

- share/goodie/cheat_sheets/json/filezilla.json
> added description to filezilla.json

- share/goodie/help_line/helplines.yml
@conorfl 
------
IA Page:  http://duck.co/ia/view/help_line
> Added Indian Helpline to the list.

- share/goodie/cheat_sheets/json/eclipse.json
removed some unwanted dots in eclipse.json
https://duck.co/ia/view/eclipse_cheat_sheet
> removed dots in eclipse.json

- lib/DDG/Goodie/UnixTime.pm
- t/UnixTime.t
IA Page: https://duck.co/ia/view/unix_time
> Issue #1163 - Convert UnixTime to use templates

- lib/DDG/Goodie/Cusip.pm
- share/goodie/cusip/cusip.css
- t/Cusip.t
IA Page: https://duck.co/ia/view/cusip
> Issue #1163 - Convert Cusip to use templates

- share/goodie/cheat_sheets/json/cantonese.json
Provide a list of basic Cantonese words and phrases
Instantly displays a list of commonly used and basic Cantonese words and phrases
http://www.cantonese.sheik.co.uk/
It has plenty of information regarding the words and phrases
Yes, there should be a number of alternative data sources.
"cantonese cheat sheet", "cantonese words reference", "cantonese phrases help"
**Which communities will this Instant Answer be especially …
> New Cantonese Cheat Sheet

- share/goodie/cheat_sheets/json/gta-vice-city.json
Continuing from: #1607
-----
IA Page: https://duck.co/ia/view/gta_vice_city_cheat_sheet
> GTA Vice city Cheatsheet

- share/goodie/cheat_sheets/json/language/bengali.json
It will help to find Basic bengali words and phrases instantly for new people who don't know bengali. As bengali is the official language of the state of West Bengal in India and it is also the national language of Bangladesh.
http://www.omniglot.com/language/phrases/bengali.php
It's a nice bengali cheat sheet and I've added some basics into the cheat sheet.
not that I know of.
Bengali phrases, english to bengali, basic bengali phrases, basic bengali words. …
> Bengali cheat sheet added

- share/goodie/cheat_sheets/json/bible-books.json
- share/goodie/cheat_sheets/json/books-of-bible.json
I am sorry that i again made the mistake of creating PR from master.
shows books in bible
http://www.biblebelievers.com/believers-org/kjv-stats.html
Its good
yes
Mostly christians
nope
no
-----
IA Page: …
> New books-of-bible.json

- share/goodie/cheat_sheets/json/github-atom-mac.json
- share/goodie/cheat_sheets/json/github-atom.json
updated to resolve conflicts with #1933 
-----
IA Page: https://duck.co/ia/view/github_atom_mac_cheat_sheet
> github atom mac cheat sheet

- share/goodie/cheat_sheets/json/redis.json
Update redis.json: Fixes #2017
- added HLL
- added Geo
IA Page: https://duck.co/ia/view/redis_cheat_sheet
> Update redis.json: Fixes #2017

- share/goodie/cheat_sheets/json/gnu-screen.json
Added new commands.
[IA page](https://duck.co/ia/view/gnu_screen_cheat_sheet)
> Update Gnu Screen Cheat Sheet

- share/goodie/cheat_sheets/json/safari.json
Fixes #1811.
Addresses PR #1809 as well.
------
IA Page:  http://duck.co/ia/view/meta_cpan
> Amendments to Safari cheatsheet

- template/lib/DDG/Goodie/Example.pm
> Update Goodite template URLs for new documentation

- share/goodie/cheat_sheets/json/mysql.json
My Instant Answer provide information about basic commands used in MySQL.
http://www.cheatography.com/davechild/
I chose this this source because it provided some information of how to make cheat sheets.
There might be better data source.But according to me this gave me desired information for making cheat sheets.  
MySQL user community and database user community will get lot of benefit out of this cheat sheet.
**Where did you hear about DuckDuckHack? (For first time …
> New mysql cheat sheet

- share/goodie/cheat_sheets/json/language/french.json
https://duck.co/ia/view/french_cheat_sheet
> French cheat sheet

- share/goodie/cheat_sheets/json/d3js.json
My Instant answer provide details of the basic syntax used in D3js
Data Driven Document (http://d3js.org/)
Because it's official site for D3js
No
Data visualizations field programmers will get benefits out of it.
No, this not connected to DuckDuckHack Instant Answer.
No I'm not having any problem.
Where did you hear about DuckDuckHack? (For first time …
> new d3js cheat sheet

- lib/DDG/Goodie/SecurityAddons.pm
- share/goodie/security_addons/list_content.handlebars
- t/SecurityAddons.t
Provides links to common browser's add-on pages with the search key "anonymous"
It solves the problem of having to go to an add-on store (i.e. about:addons) and searching for add-ons
https://addons.opera.com/en/search/?query=anonymous&type=extensions
https://addons.mozilla.org/en-US/firefox/tag/anonymous
https://extensions.apple.com/?q=anonymous
https://chrome.google.com/webstore/search/anonymous
They are the official add-on store of each browser.
Not that I know of.
**What are some …
> lights0123's Security Addons Goodie

- lib/DDG/Goodie/ResistorColors.pm
- t/ResistorColors.t
resisto.rs have changed URL from http://resisto.rs/100 to http://resisto.rs/#100.
Closes #2055
> Updated URL

- share/goodie/cheat_sheets/json/language/arabic.json
- share/goodie/cheat_sheets/json/language/bengali.json
- share/goodie/cheat_sheets/json/language/bulgarian.json
- share/goodie/cheat_sheets/json/language/cantonese.json
- share/goodie/cheat_sheets/json/language/czech.json
- share/goodie/cheat_sheets/json/language/dutch.json
- share/goodie/cheat_sheets/json/language/french.json
- share/goodie/cheat_sheets/json/language/german.json
- share/goodie/cheat_sheets/json/language/slovak.json
- share/goodie/cheat_sheets/json/language/turkish.json
And some whitespace clean up.
-----
IA Page: https://duck.co/ia/view/arabic_cheat_sheet
> Language cheatsheets: Changed template_type to 'language' (fixes #2054)

- share/goodie/cheat_sheets/language.handlebars
> Italic transliteration text for language template

- share/goodie/cheat_sheets/json/affinity-designer.json
IA page: https://duck.co/ia/view/affinity_designer_cheat_sheet
> Affinity cheatsheet: Changed source to the official website

- share/goodie/cheat_sheets/json/radare2.json
Serves as a quick reference for radare2 users and developers. radare2 (or r2) is a reverse engineering framework and binary analysis tool. 
<https://github.com/radare/radare2book/blob/master/refcard/radare2_rc.pdf>
It was released today and covers all major commands. Interest in this cheatsheet was expressed [here](https://twitter.com/therealkbhat/status/686547901628039168).
Not that I know of.
r2 users, developers and CTF (capture the flag) players around the world.
**Is …
> New Cheatsheet: radare2

- share/goodie/cheat_sheets/json/gentoo-portage.json
https://duck.co/ia/view/gentoo_portage_cheat_sheet
> New Gentoo Portage Cheat Sheet

- share/goodie/cheat_sheets/json/language/tamil.json
It will display all basic Tamil phrases
(n/a)
(n/a)
(n/a)
Students, Tourists
https://duck.co/ideas/idea/6823/tamil-language-cheatsheet
As of now nothing i am being guided well in ddg.
From a friend(Gautham Krishna R)
**What does the …
> New tamil cheat sheet

- share/goodie/cheat_sheets/json/viml.json
https://duck.co/ia/view/viml_cheat_sheet
> New VimL Cheat Sheet

- share/goodie/cheat_sheets/json/commonescapesequence.json
- share/goodie/cheat_sheets/json/pyescapesequence.json
https://duck.co/ia/view/common_escape_sequences_cheat_sheet
> New Common escape sequences cheat sheet

- share/goodie/cheat_sheets/json/javascript-dom.json
Continue first half of #1603 
- Adds new JavaScript Dom Cheat Sheet
/cc @TanaLandis 
---
IA Page: https://duck.co/ia/view/javascript_dom_cheat_sheet
> Javascript DOM Cheat Sheet added

- share/goodie/cheat_sheets/json/indesign.json
Continuing #1951 
My Instant answer provide shortcut keys used in adobe illustrator.
Adobe help (https://helpx.adobe.com/indesign/using/default-keyboard-shortcuts.html)
Because it's official site for adobe products.
No
Graphic designers and production artists are the principal users.
---
https://duck.co/ia/view/indesign_cheat_sheet
> New indesign cheat sheet

- share/goodie/cheat_sheets/json/asciidoc.json
---
https://duck.co/ia/view/asciidoc_cheat_sheet
> New Asciidoc Cheat Sheet

- share/goodie/cheat_sheets/json/es6.json
https://duck.co/ia/view/es6_cheat_sheet
> New ES6 Cheatsheet

- share/goodie/cheat_sheets/json/github-flavoured-markdown.json
- share/goodie/cheat_sheets/json/github_flavoured_markdown.json
Fixes #1906 
-----
IA Page: https://duck.co/ia/view/github_flavoured_markdown_cheat_sheet
>  Added GitHub Flavoured markdown cheatsheet

- share/goodie/cheat_sheets/json/language/hindi.json
Switch tabs to spaces :+1: 
-----
IA Page: https://duck.co/ia/view/hindi_cheat_sheet
> Hindi Cheat Shet: Fix indentation

- lib/DDG/Goodie/CountryCodes.pm
Needed a PR to get this one onto Beta. Seems to be offline, and I'm not sure why...
-----
IA Page: https://duck.co/ia/view/country_codes
> CountryCodes: remove trailing space, add newline before ABSTRACT

- share/goodie/cheat_sheets/json/language/french.json
This fixes some typos in the French cheat sheet.
From a native French guy ;-)
> French cheat sheet: fix some typos

- share/goodie/cheat_sheets/json/bible-books.json
This reverts commit a484b58301fb9956d92dd0b43ef58af6e53e7302.
-----
IA Page: https://duck.co/ia/view/bible_books_cheat_sheet
/cc @jophab
> Revert "Delete bible-books.json"t

- share/goodie/cheat_sheets/json/npm.json
This cheat sheet shows the most common commands for npm.
<https://duck.co/ia/view/npm_cheat_sheet>
> New Npm Cheat Sheets

- lib/DDG/Goodie/CaesarCipher.pm
- t/CaesarCipher.t
Lets people perform basic Caesar ciphers on text.
Allows quick encoding/decoding of messages without needing to find a site to do it for you.
https://en.wikipedia.org/wiki/Caesar_cipher
It is a fairly well known cipher, and Wikipedia provides examples (and goes into some detail).
[This](http://ocw.mit.edu/courses/electrical-engineering-and-computer-science/6-00sc-introduction-to-computer-science-and-programming-spring-2011/unit-2/lecture-10-hashing-and-classes/MIT6_00SCS11_ps4.pdf) pdf …
> New Caesar Cipher Goodie

- share/goodie/cheat_sheets/json/magic-number.json
My Instant answer provide short cut tricks for calculations.
Word Pandit (http://wordpandit.com/magic-of-numbers/)
Because it helps us to prepare for competitive exams and provide shortcut tricks for calculations.
Might Be
Students preparing for competitive exams and lovers of aptitude.
Navneet Sharma (Contributor).
**Screen Shots of Instant Answer**
#DDG JAIPUR
--- …
> New Cheat Sheet of Magic of Numbers for Number System

- share/goodie/cheat_sheets/json/boolean-algebra.json
While looking through the IAs, I stumbled upon the [Boolean Algebra Cheat Sheet](https://duck.co/ia/view/boolean_algebra_cheat_sheet) and one typo immediately caught my eye!
> Boolean Algebra: Fix Involution law

- share/goodie/cheat_sheets/json/language/hindi.json
Removed second description from hindi.json file
> Removed 2nd description

- share/goodie/cheat_sheets/json/pandas.json
#DDG jaipur
---
https://duck.co/ia/view/pandas_cheat_sheet
> New Pandas Cheatsheet

- share/goodie/cheat_sheets/json/cpp.json
- share/goodie/cheat_sheets/json/elementary.json
- share/goodie/cheat_sheets/json/html.json
- share/goodie/cheat_sheets/json/intellij.json
- share/goodie/cheat_sheets/json/kerbal-space-program.json
- share/goodie/cheat_sheets/json/kmplayer.json
- share/goodie/cheat_sheets/json/phpstorm-osx.json
- share/goodie/cheat_sheets/json/processing-lang.json
- share/goodie/cheat_sheets/json/vlc.json
fixed:
* missing sections
* descriptions
for passing prove test:
prove t/CheatSheets/CheatSheetsJSON.t
fixes:#2015
> Fixed missing sections and descriptions for cheatsheet 2

- share/goodie/cheat_sheets/json/hipchat.json
IA: https://duck.co/ia/view/hipchat_cheat_sheet
> New cheat sheet: HipChat

- lib/DDG/Goodie/Atbash.pm
- t/Atbash.t
Lo,
Fixes: https://github.com/duckduckgo/zeroclickinfo-goodies/issues/1887 by switching to the text template
https://duck.co/ia/view/atbash
> Convert Atbash to text template

- share/goodie/cheat_sheets/json/elementary.json
modified the display format and added proper description to elementary os
https://duck.co/ia/view/elementary_cheat_sheet
> modified the display format

- share/goodie/cheat_sheets/json/kubernetes.json
Show all the Kubernetes basic queries and keys as cheat sheet.
http://k8s.info/cs.html
One of the Best and even recommended database for open-source development.
No.
Coder, Open source, Git users, Geeks, Hackers, etc.
Yes, https://duck.co/ia/view/kubernetes_cheat_sheet
No
What does the Instant Answer look like? (Provide a screenshot for new or updated Instant …
> kubernetes cheat sheet

- share/goodie/cheat_sheets/json/brainfuck.json
IA Page: https://duck.co/ia/view/brainfuck_cheat_sheet
> Add brainfuck cheatsheet

- share/goodie/cheat_sheets/json/brainfuck.json
Added missing description to brainfuck cheat sheet
https://duck.co/ia/view/brainfuck_cheat_sheet
> Brainfuck: Added description to brainfuck

- share/goodie/cheat_sheets/json/cpp.json
**What I did ?**
1.Removed Unwanted section Console Input/Output from section_order.
2.Removed periods.
3.Removed extra spaces from 'val' parts.
4.Rearranged the way cheat sheet was displayed. 
https://duck.co/ia/view/cpp_cheat_sheet
>  cpp : Removed Unwanted section Console Input/Output

- lib/DDG/Goodie/CaesarCipher.pm
- lib/DDG/Goodie/NoteFrequency.pm
- lib/DDG/Goodie/OnionAddress.pm
- lib/DDG/Goodie/PeriodicTable.pm
- lib/DDG/Goodie/Scramble.pm
- lib/DDG/Goodie/SecurityAddons.pm
Some metadata was creeping back in...
/cc @moollaza
> Remove Metadata

- share/goodie/cheat_sheets/json/postgresql.json
New postgresql cheatsheet
idea: https://duck.co/ideas/idea/6188/postgresql-cheat-sheet
**Requires suggestions for more content....**
------
ia: https://duck.co/ia/view/postgresql_cheat_sheet
> New postgresql cheatsheet

- lib/DDG/Goodie/CoffeeToWaterRatio.pm
- pull_request_template_goodie.md
- t/CoffeeToWaterRatio.t
This LGTM :+1:
Removing Perl Metadata before merge.
/cc @nickselpa
-----
IA Page: https://duck.co/ia/view/coffee_to_water_ratio
> Continue #1017

- lib/DDG/Goodie/CoffeeToWaterRatio.pm
- pull_request_template_goodie.md
- t/CoffeeToWaterRatio.t
https://duck.co/ideas/idea/4988/coffee-to-water-ratio-calculator
Image preview:
-----
IA Page: https://duck.co/ia/view/coffee_to_water_ratio
> Coffee to Water Ratio Goodie

- share/goodie/cheat_sheets/json/language/marathi.json
What problem does your Instant Answer solve (Why is it better than organic links)?
It will help to find Basic marathi words and phrases instantly for new people who don't know marathi. It's an Indo-Aryan language spoken predominantly by Marathi people of Maharashtra. It is the official language and co-official language in Maharashtra and Goa states of Western India respectively, and is one of the 23 official languages of India.
http://www.omniglot.com/language/phrases/marathi.php
It's good for learners and also everything is mentioned properly. So, we can go with the track and achieve the milestone while learning.
not …
> Marathi cheat sheet

- share/goodie/cheat_sheets/json/saint.json
- share/goodie/cheat_sheets/json/saints-row.json
Shows all the cheat codes for saints row 4 game.
http://www.cheatcc.com/ps3/saintsrow4cheatscodes.html
Gamers.
What does the Instant Answer look like? (Provide a screenshot for new or updated Instant Answers)
---
https://duck.co/ia/view/saints_row_cheat_sheet
> Saint Game CheatSheet

- share/goodie/cheat_sheets/json/language/assamese.json
Helps you find common Assamese words and phrases to people who are not native speakers of [Assamese or Axomiya](https://en.wikipedia.org/wiki/Assamese_language). It is spoken by over _13 million native speakers_ apart from being the native language of the state Assam, India
- [http://www.omniglot.com](http://www.omniglot.com/language/phrases/assamese.php)
- [http://ilanguages.org](http://ilanguages.org/assamese_vocabulary.php)
Has a bunch load of phrases and terms used in day to day coversations
Nope. Furthermore, _Google Translate_ does not support the language …
> New Assamese Language cheatsheet

- lib/DDG/Goodie/Bin2Unicode.pm
- t/Bin2Unicode.t
Converts binary into unicode characters much like the [Ascii to Binary IA](https://duck.co/ia/view/ascii).  However, it has some additional features:
1. Converts to unicode outside of the ascii range.
2. Will convert a list of binary strings separated by spaces.
3. Retains the original query's spacing.
Every now and again you have some funny person that encodes a sentence in binary and you want to quickly decode it.  Here's your IA.  I don't want to decode it letter by letter.
Geeks and the curious.
**Which existing Instant Answers will this one supercede/overlap …
> Binary to unicode converter

- share/goodie/cheat_sheets/json/cpp-strings.json
IA Page:
https://duck.co/ia/view/cpp_strings_cheat_sheet
> Add much more information to cpp-strings (cheat sheet)'s json

- lib/DDG/Goodie/UnixTime.pm
- t/UnixTime.t
IA Page: https://duck.co/ia/view/unix_time
> UnixTime - Fixes  Use of uninitialized value $+{"trigger"}

- share/goodie/cheat_sheets/json/perforce.json
Continuing #2215 
/cc @lizlam 
-----
IA Page: https://duck.co/ia/view/perforce_cheat_sheet
> Continue Pr/2215

- share/goodie/cheat_sheets/json/gta-v.json
#2168 was closed because of merge conflicts and whole bunch of Git weirdness. 
Here we go...
https://duck.co/ia/view/gta_v_cheat_sheet
> GTA V CheatSheet

- share/goodie/cheat_sheets/json/currency.json
Added the currency of Iran to this cheat sheet
---
https://duck.co/ia/view/currency_cheat_sheet
> Currency Cheat Sheet: Add currency of Iran

- lib/DDG/Goodie/Conversions.pm
- lib/DDG/GoodieRole/NumberStyle.pm
- t/Conversions.t
Fixes an issue with scientific notation.
-----
IA Page: https://duck.co/ia/view/conversions
> Conversions: Fix #2041

- share/goodie/cheat_sheets/json/vagrant.json
Added six additional keys for some missing functions
----
IA Page: https://duck.co/ia/view/vagrant_cheat_sheet
> Updated Vagrant cheat sheet

- share/goodie/cheat_sheets/json/outlook.json
> Removed unwanted quotes from description

- share/goodie/cheat_sheets/json/graph-operations.json
My Instant answer provide reference to Big-O complexities of graph operations.
[Wikipedia](https://en.wikipedia.org/wiki/Graph_theory)
Because it's detailed reference to graph operations.
might be
Coders and programmers
---
---
https://duck.co/ia/view/graph_operations_cheat_sheet
> New graph operations cheat sheet

- share/goodie/cheat_sheets/json/heap-operations.json
My Instant answer provide reference to Big-O complexities of Heap operations.
[Wikipedia](https://en.wikipedia.org/wiki/Heap_%28data_structure%29)
Because it's detailed reference to Heap operations.
No
Coders and programmers
---
https://duck.co/ia/view/heap_operations_cheat_sheet
> New heap operations cheat sheet

- share/goodie/cheat_sheets/json/interview-dress-code.json
My Instant answer provides dress codes for an interview.
Western dress codes - [Wikipedia](https://en.wikipedia.org/wiki/Western_dress_codes)
Because on this source every dress code for both girls and boys are given
Might be
For Job seekers
Social media sites
**Screenshots**
#DDG Jaipur
---
https://duck.co/ia/view/interview_dress_code_cheat_sheet
> interview dress codes

- share/goodie/cheat_sheets/json/es6.json
Added a few es6 features
IA Page : https://duck.co/ia/view/es6_cheat_sheet
> Improve es6 cheatsheet

- lib/DDG/Goodie/ParseCron.pm
- t/ParseCron.t
IA Page: https://duck.co/ia/view/parse_cron
Fixes #2239
> Parsecron: adding support for start + interval arguments

- share/goodie/cheat_sheets/json/angularjs.json
There were directives only in cheat sheet. I have added angular services.
IA Page : [ https://duck.co/ia/view/angular_js_cheat_sheet](https://duck.co/ia/view/angular_js_cheat_sheet)
@moollaza Can you review and merge this.
> Added angular services in cheatsheet

- CONTRIBUTING.md
Thanks to @gautamkrishnar for the idea!
> Better Contributing MD - slightly redundant to docs on purpose

- lib/DDG/Goodie/Bitsum.pm
- t/Bitsum.t
Show the base used to compute the answer.
Fixes #1902
IA Page: http://duck.co/ia/view/bitsum
> Bitsum: Fixes #1902

- share/goodie/cheat_sheets/json/c-string-formatting.json
Created because of merge issues with #2171. 
IA Page: https://duck.co/ia/view/string_fmt_cheat_sheet
> New C String Formatting cheat sheet (continues #2171)

- share/goodie/cheat_sheets/json/emberjs.json
My Instant answer provide reference to basic syntax of ember.js.
---
https://duck.co/ia/view/emberjs_cheat_sheet
> New Ember.js Cheat sheet

- template/lib/DDG/Goodie/Example.pm
- template/lib/DDG/Goodie/Minimal.pm
Allow dev to choose their handle during IA creation.
> Make the handle a template parameter

- share/goodie/cheat_sheets/json/language/hindi.json
This PR fixes translation in Hindi cheat sheet.
IA Page : https://duck.co/ia/view/hindi_cheat_sheet
> Fix translation mistake

- share/goodie/cheat_sheets/json/currency.json
IA Page: [ https://duck.co/ia/view/currency_cheat_sheet](https://duck.co/ia/view/currency_cheat_sheet)
> Add currency of Sri Lanka and Nepal

- template/lib/DDG/Goodie/Example.pm
- template/lib/DDG/Goodie/Minimal.pm
Reverts duckduckgo/zeroclickinfo-goodies#2085
> Revert "Make the handle a template parameter"

- template/lib/DDG/Goodie/Example.pm
- template/lib/DDG/Goodie/Minimal.pm
Reverts duckduckgo/zeroclickinfo-goodies#2315
> Revert "Revert "Make the handle a template parameter""

- share/goodie/cheat_sheets/json/bootstrap.json
IA Page: [ https://duck.co/ia/view/bootstrap_cheat_sheet](https://duck.co/ia/view/bootstrap_cheat_sheet)
> Add responsive classes and format the code

- share/goodie/cheat_sheets/json/git.json
Add rebase and remote branch delete commands
IA Page: [ https://duck.co/ia/view/git_cheat_sheet](https://duck.co/ia/view/git_cheat_sheet)
> Improve git cheat sheet

- share/goodie/cheat_sheets/json/language/polish.json
- t/SunInfo.t
IA page: https://duck.co/ia/view/polish_cheat_sheet
> New Polish Cheat Sheet

- share/goodie/cheat_sheets/json/language/minionese.json
IA: https://duck.co/ia/view/minionese_cheat_sheet
> New Minionese Cheat Sheet

- share/goodie/cheat_sheets/json/gta-san-andreas.json
created gta san andreas cheat sheet
-------------
ia : https://duck.co/ia/view/gta_san_andreas_cheat_sheet
> gta san andreas cheat sheet

- share/goodie/cheat_sheets/json/emmet.json
Open to suggestions and feedback. I have tried selecting only the ones that are used most often. Here's the source documentation: http://docs.emmet.io/cheat-sheet/
IA Page: https://duck.co/ia/view/emmet_cheat_sheet
> Added initial version of Emmet cheat sheet

- share/goodie/cheat_sheets/json/utorrent.json
added utorrent cheat sheet
-------
ia: https://duck.co/ia/view/utorrent_cheat_sheet
> New utorrent cheat sheet

- share/goodie/cheat_sheets/json/ruby.json
IA url: https://duck.co/ia/view/ruby_cheat_sheet
> New Ruby Cheat Sheet

- share/goodie/cheat_sheets/json/iterm2.json
Displays a list of Iterm2 keyboard shortcuts
**Which communities will this Instant Answer be especially useful for? (gamer, book lovers, etc)**
Programmers
No
No
IA Page: [ https://duck.co/ia/view/iterm2_cheat_sheet](https://duck.co/ia/view/iterm2_cheat_sheet)
@moollaza  Can you review this and merge if OK?
> New Iterm2 Cheat Sheet

- share/goodie/cheat_sheets/json/array-sorting.json
My Instant answer provide reference to Big-O complexities of Array Sorting Algorithms.
[Wikipedia](https://en.wikipedia.org/wiki/Sorting_algorithm)
Because it's detailed reference to Sorting Algothims.
No
**Which communities will this Instant Answer be especially useful for?**
Coders and programmers
---
https://duck.co/ia/view/array_sorting_cheat_sheet
> New array sorting cheat sheet

- share/goodie/cheat_sheets/json/db2.json
IA page : https://duck.co/ia/view/ibm_db2_cheat_sheet
> ibm_db2_cheat_sheet

- share/goodie/cheat_sheets/json/data-structure-operations.json
My Instant answer provide reference to Big-O complexities of Data Structure Operations.
---
https://duck.co/ia/view/data_structure_operations_cheat_sheet
> New Data Structure Operations cheat sheet

- share/goodie/cheat_sheets/json/jekyll.json
My Instant answer provide reference to Jekyll a static site generator.
Jekyllrb (https://jekyllrb.com/)
Because it's official site of Jekyll.
No
Web developers and bloggers will find it very useful.
---
https://duck.co/ia/view/jekyll_cheat_sheet
> New jekyll cheat sheet

- share/goodie/cheat_sheets/json/backbonejs.json
This instant answer is a quick reference of Backbone.js, a JavaScript framework with a RESTful JSON interface.
[ http://backbonejs.org/](http://backbonejs.org/)
This is official source for Backbone.js.
Since the source is the official Backbone.js, I don't think there is any other better source.
**Which communities will this Instant Answer be especially useful for? (gamer, book lovers, etc)**
Programmers
No
**What does the Instant Answer look like? (Provide a screenshot for new or updated Instant …
> New Backbone.js Cheat Sheet

- share/goodie/cheat_sheets/json/typescript.json
Displays an overview of TypeScript Types, Arrays, Functions, Generics etc.
Screenshot:
IA Page: [ https://duck.co/ia/view/typescript_cheat_sheet](https://duck.co/ia/view/typescript_cheat_sheet)
> New TypeScript Cheat Sheet

- share/goodie/cheat_sheets/json/codio.json
https://duck.co/ia/view/codio_cheat_sheet
> New Codio Cheat Sheet

- share/goodie/cheat_sheets/json/reactjs.json
This instant answer is a quick reference of React, a JavaScript library for building user interfaces. 
[ https://facebook.github.io/react/docs/getting-started.html](https://facebook.github.io/react/docs/getting-started.html)
This is official source for React.
Since this is the official source, I don't think there is any other better source.
**Which communities will this Instant Answer be especially useful for? (gamer, book lovers, etc)**
Programmers
No
**What does the Instant Answer look like? …
> New React Cheat Sheet

- share/goodie/cheat_sheets/json/powershell.json
This is a cheat sheet for syntax and operators in the PowerShell language.  Most examples are from the language's builtin docs that can also be found [here](https://technet.microsoft.com/en-us/library/hh847856.aspx).
IA: https://duck.co/ia/view/powershell_cheat_sheet
> New PowerShell Cheat Sheet

- share/goodie/cheat_sheets/json/swift.json
Added new topics in the  cheatsheet for Swift arrays, methods, instances, and enums.
---
IA Page: https://duck.co/ia/view/swift_cheat_sheet
> Swift cheat sheet: Fixes #2095

- share/goodie/cheat_sheets/json/iterm2.json
This PR separates arrows and add an alias.
Resolves https://github.com/duckduckgo/zeroclickinfo-goodies/pull/2222
IA Page: [ https://duck.co/ia/view/iterm2_cheat_sheet](https://duck.co/ia/view/iterm2_cheat_sheet)
> Separate arrows and add an alias

- share/goodie/cheat_sheets/json/solar-system.json
IA Page: [ https://duck.co/ia/view/solar_system_cheat_sheet](https://duck.co/ia/view/solar_system_cheat_sheet)
Resolves https://github.com/duckduckgo/zeroclickinfo-goodies/pull/2230
> Add spaces to improve legibility

- share/goodie/cheat_sheets/json/linux.json
> Linux Cheat Sheet: #2332 

- share/goodie/cheat_sheets/json/language/kannada.json
IA Page : https://duck.co/ia/view/kannada_cheat_sheet
> New Kannada Cheat sheet

- t/SecurityAddons.t
My bad, I didn't let the tests finish before merging :frowning: 
/cc @tagawa 
IA Page: https://duck.co/ia/view/security_addons
> SecurityAddons: update tests to pass

- share/goodie/conversions/ratios.yml
IA Page: http://duck.co/ia/view/conversions
Fixes #1523
> Added support for "microgram" abbreviation

- share/goodie/conversions/ratios.yml
IA Page: https://duck.co/ia/view/conversions
> Changed us to µs

- share/goodie/cheat_sheets/json/npm.json
Added new section Uninstalling Packages and some CLI commands for Npm Cheat sheet.
IA Page: https://duck.co/ia/view/npm_cheat_sheet
> Cheat Sheet Npm: Added new section Uninstalling Packages and some CLI commands

- share/goodie/cheat_sheets/json/states-of-india.json
Corrected names of states and removed unnecessary spaces in States of India cheat sheet
IA Page: https://duck.co/ia/view/states_of_india_cheat_sheet
> States of India cheat sheet: Corrected name of states and removed unnecessary spaces

- share/goodie/cheat_sheets/json/sql.json
Improved formatting by removing extra lines and spaces to SQL cheat sheet.
IA Page: https://duck.co/ia/view/sql_cheat_sheet
> SQL cheat sheet: Improved formatting by removing extra lines and spaces

- share/goodie/cheat_sheets/json/sms.json
Added more words frequently used in messaging to SMS cheat sheet.
IA Page: https://duck.co/ia/view/sms_cheat_sheet
> SMS Cheat sheet: Added more words frequently used in messaging.

- share/goodie/cheat_sheets/json/nodejs.json
Fixes https://github.com/duckduckgo/zeroclickinfo-goodies/issues/2388
IA Page: [ https://duck.co/ia/view/nodejs_cheat_sheet](https://duck.co/ia/view/nodejs_cheat_sheet)
> Add alias section in NodeJS cheat sheet

- lib/DDG/Goodie/CalendarConversion.pm
- lib/DDG/Goodie/Constants.pm
- lib/DDG/Goodie/Conversions.pm
- lib/DDG/Goodie/DuckDuckGo.pm
- lib/DDG/Goodie/FirefoxOS.pm
- lib/DDG/Goodie/HelpLine.pm
- lib/DDG/Goodie/Jira.pm
- lib/DDG/Goodie/POTUS.pm
- lib/DDG/Goodie/Paper.pm
- lib/DDG/Goodie/PeriodicTable.pm
- lib/DDG/Goodie/PublicDNS.pm
- lib/DDG/Goodie/SolarSystem.pm
- lib/DDG/Goodie/ZappBrannigan.pm
Fixes an issue that arises with v0.61 of `YAML::XS`.
Does not change any behavior.
See https://github.com/ingydotnet/yaml-libyaml-pm/issues/38
Revert once fix has been released.
> Fix YAML::XS update issue (temporary)

- share/goodie/constants/constants.yml
Added bohr magneton to Constants
IA Page: https://duck.co/ia/view/constants
> Added magnetic constant and bohr magneton to Constants

- share/goodie/cheat_sheets/json/emoticon.json
Added more emoticons for happy face to emoticons cheat sheet
IA Page: https://duck.co/ia/view/emoticon_cheat_sheet
> Emoticons Cheat sheet: Added more emoticons for happy face

- share/goodie/cheat_sheets/json/blender.json
Corrected spelling mistakes in blender cheat sheet.
IA Page: https://duck.co/ia/view/blender_cheat_sheet
> Blender Cheat sheet: Corrected spelling mistakes.

- share/goodie/cheat_sheets/json/cpp.json
Added data types to cpp cheat sheet.
IA Page: https://duck.co/ia/view/cpp_cheat_sheet
> CPP cheat sheet: Added data types

- share/goodie/duck_duck_go/responses.yml
- t/DuckDuckGo.t
- t/OnionAddress.t
Fixed broken links in responses in DuckDuckGo.
IA Page: https://duck.co/ia/view/about_duckduckgo
> Fixed the broken link

- share/goodie/cheat_sheets/json/vim.json
Added more commands to vim cheat sheet.
IA Page: https://duck.co/ia/view/vim_cheat_sheet
> VIM cheat sheet: Added more commands

- share/goodie/cheat_sheets/json/vi.json
Added more commands to Vi cheat sheet and fixed typos also.
IA Page: https://duck.co/ia/view/vi_cheat_sheet
> Vi cheat sheet: Added more commands

- share/goodie/cheat_sheets/json/bootstrap.json
Added more classes for button to Bootstrap cheat sheet.
IA Page: https://duck.co/ia/view/bootstrap_cheat_sheet
> Bootstrap cheat sheet: Added more classes for button

- share/goodie/cheat_sheets/json/maya.json
- share/goodie/cheat_sheets/json/microsoft-windows-ten.json
- share/goodie/cheat_sheets/json/mongodb.json
- share/goodie/cheat_sheets/json/mtg-phases.json
- share/goodie/cheat_sheets/json/nmap.json
- share/goodie/cheat_sheets/json/nodejs-tutorials.json
- share/goodie/cheat_sheets/json/npm.json
- share/goodie/cheat_sheets/json/opencv.json
- share/goodie/cheat_sheets/json/openshot.json
- share/goodie/cheat_sheets/json/opera.json
- share/goodie/cheat_sheets/json/perforce-workshop.json
- share/goodie/cheat_sheets/json/scala.json
- share/goodie/cheat_sheets/json/sketch.json
- share/goodie/cheat_sheets/json/slack.json
- share/goodie/cheat_sheets/json/tmux.json
- share/goodie/cheat_sheets/json/ubuntu-unity.json
- share/goodie/cheat_sheets/json/ubuntu.json
- share/goodie/cheat_sheets/json/us-government-agencies.json
- share/goodie/cheat_sheets/json/vi.json
- share/goodie/cheat_sheets/json/windows-command-prompt.json
This PR fixes typos in several cheat sheets.
> Cheat Sheet: Fix typos in cheats sheets

- share/goodie/cheat_sheets/json/coffeescript.json
Added more operators to Coffeescript cheat sheet.
IA Page: https://duck.co/ia/view/coffeescript_cheat_sheet
> Coffeescript Cheatsheet: Added more operators

- share/goodie/cheat_sheets/json/microsoft-word.json
More shortcuts to MS Word cheat sheet.
MS Word Cheat sheet IA page : https://duck.co/ia/view/microsoft_word_cheat_sheet
> MS Word cheatsheet: Added more shortcuts

- share/goodie/cheat_sheets/json/ssh.json
Fixed typos in ssh cheat sheet
IA Page: https://duck.co/ia/view/ssh_cheat_sheet
> SSH cheat sheet: Fixed typos

- share/goodie/cheat_sheets/json/todoist.json
Added shortcut for new quick comment to Todoist cheat sheet.
IA Page: https://duck.co/ia/view/todoist_cheat_sheet
> Todoist cheat sheet: Added shortcut for new quick comment

- share/goodie/cheat_sheets/json/javascript.json
Added Array methods - map(), filter(), every() and foreach() to Javascript cheat sheet.
Javascript cheat sheet IA page : https://duck.co/ia/view/javascript_cheat_sheet
> Javascript cheatsheet: Added Array methods

- share/goodie/cheat_sheets/json/chrome.json
Added more keyboard shortcuts to chrome cheat sheet
---
IA Page: https://duck.co/ia/view/chrome_cheat_sheet
> Chrome Cheatsheet: Added some more keyboard shortcuts

- share/goodie/cheat_sheets/json/windows-command-prompt.json
Windows command prompt: Added some file management commands and fixed typos
IA Page: https://duck.co/ia/view/windows_command_prompt_cheat_sheet
> Windows command prompt: Added some file management commands and fixed typos

- share/goodie/cheat_sheets/json/default-port-numbers.json
Updated list of port numbers in cheat sheet.
IA Page: [https://duck.co/ia/view/default_port_numbers_cheat_sheet](https://duck.co/ia/view/default_port_numbers_cheat_sheet)
> Port Numbers Cheat Sheet: Update port numbers

- share/goodie/cheat_sheets/json/vlc.json
VLC cheat sheet: Added two shortcuts
IA Page: https://duck.co/ia/view/vlc_cheat_sheet
> VLC cheat sheet: Added two shortcuts

- share/goodie/cheat_sheets/json/apt-get.json
This PR fixes https://github.com/duckduckgo/zeroclickinfo-goodies/issues/2484
IA Page: [https://duck.co/ia/view/apt_get_cheat_sheet](https://duck.co/ia/view/apt_get_cheat_sheet)
> apt-get: Fix typo and add command

- share/goodie/cheat_sheets/json/kmplayer.json
- share/goodie/cheat_sheets/json/microsoft-windows-ten.json
- share/goodie/cheat_sheets/json/sketch.json
- share/goodie/cheat_sheets/json/sms.json
Fixed typos in some cheat sheets
> Fixed typos in some cheat sheets

- share/goodie/cheat_sheets/json/si-units.json
Added five more quantities and their SI units to cheat sheet.
IA Page: https://duck.co/ia/view/si_units_cheat_sheet
> SI Units cheat sheet: Added five more quantities and their SI units

- share/goodie/cheat_sheets/json/perl.json
Perl cheat sheet: Added a command in Input/Output section
IA Page: https://duck.co/ia/view/perl_cheat_sheet
> Perl cheat sheet: Added a command in Input/Output section

- share/goodie/cheat_sheets/json/c-sharp-snippets.json
C-sharp-snippets cheat sheet: Added key for creating destructor in Others section
IA Page: https://duck.co/ia/view/c_sharp_snippets_cheat_sheet
> C-sharp-snippets cheat sheet: Added key for creating destructor in Others section

- share/goodie/cheat_sheets/json/svn.json
SVN Cheat sheets: Added more svn commands and modified one existing command
IA Page: https://duck.co/ia/view/svn_cheat_sheet
> SVN Cheat sheets: Added more svn commands

- share/goodie/cheat_sheets/json/tar.json
Tar cheat sheet: Added new commands and modified some existing commands
IA Page: https://duck.co/ia/view/tar_cheat_sheet
> Tar cheat sheet: Added new commands and modified some existing commands

- share/goodie/cheat_sheets/json/matlab.json
Matlab cheat sheet: Added more keys to Common commands and Line plot styles section
IA Page: https://duck.co/ia/view/matlab_cheat_sheet
> Matlab cheat sheet: Added more keys to Common commands and Line plot styles section

- share/goodie/cheat_sheets/json/knitting-pattern.json
Added two keys and fixed typos to knitting pattern cheat sheet.
IA Page: https://duck.co/ia/view/knitting_pattern_cheat_sheet
> Knitting pattern cheat sheet: Added two keys and fixed typos

- share/goodie/cheat_sheets/json/postgresql.json
Added two new sections namely PostgreSql commands and Role to Postgresql Cheat sheet.
IA Page: https://duck.co/ia/view/postgresql_cheat_sheet
> Postgresql Cheat sheet: Added two new sections

- share/goodie/cheat_sheets/json/w3m.json
W3M cheat sheet: Modified a shortcut and fixed typos
IA Page: https://duck.co/ia/view/w3m_cheat_sheet
> W3M cheat sheet: Modified a shortcut and fixed typos

- share/goodie/cheat_sheets/json/git.json
IA: https://duck.co/ia/view/git_cheat_sheet
> improving git cheatsheet

- share/goodie/cheat_sheets/json/angularjs.json
IA: https://duck.co/ia/view/angular_js_cheat_sheet
> improving angularjs cheatsheet

- share/goodie/cheat_sheets/json/viml.json
Added more functions to viml cheat sheet.
IA Page: https://duck.co/ia/view/viml_cheat_sheet
> Viml cheat sheet: Added more functions

- share/goodie/cheat_sheets/json/vcgencmd.json
Added one command to Vcgencmd cheat sheet
IA Page: https://duck.co/ia/view/vcgencmd_cheat_sheet
> Vcgencmd cheat sheet: Added one command

- share/goodie/cheat_sheets/json/vagrant.json
Added three more commands to vagrant cheat sheet.
IA Page: https://duck.co/ia/view/vagrant_cheat_sheet
> Vagrant cheat sheet: Added three more commands

- share/goodie/cheat_sheets/json/ubuntu.json
Ubuntu cheat sheet: Added one command
IA Page: https://duck.co/ia/view/ubuntu_cheat_sheet
> Ubuntu cheat sheet: Added one command

- share/goodie/cheat_sheets/json/ubuntu-unity.json
Ubuntu unity cheat sheet: Added metadata and fixed typos
IA Page: https://duck.co/ia/view/ubuntu_unity_cheat_sheet
> Ubuntu unity cheat sheet: Added metadata and fixed typos

- share/goodie/cheat_sheets/json/secret-service-codenames.json
Added two more person name in secret service code names cheat sheet
IA Page: https://duck.co/ia/view/secret_service_codenames_cheat_sheet
> Secret service codenames: Added two more person name in the list

- share/goodie/cheat_sheets/json/shell-variables.json
Shell variable cheat sheet: Changed one redundant command and added two more commands
In Display Value section, first two examples were similar, so changed the first one to print a message.
IA Page: https://duck.co/ia/view/shell_variables_cheat_sheet
> Shell variable cheat sheet: Changed one redundant command and added more commands

- share/goodie/cheat_sheets/json/sms.json
SMS cheat sheet: Added some sms terms and fixed typos
IA Page: https://duck.co/ia/view/sms_cheat_sheet
> SMS cheat sheet: Added some sms terms and fixed typos

- share/goodie/cheat_sheets/json/swift.json
Swift cheat sheet: Added two sections - Arithmatic and Comparison Operators
IA Page: https://duck.co/ia/view/swift_cheat_sheet
> Swift cheat sheet: Added two sections - Arithmatic and Comparison Operators

- share/goodie/cheat_sheets/json/mainframe.json
Mainframe cheat sheet: Added one command, fixed typos and improved formatting.
IA Page: https://duck.co/ia/view/mainframe_cheat_sheet
> Mainframe cheat sheet: Added one command, fixed typos and improved formatting

- share/goodie/cheat_sheets/json/markdown.json
Markdown Cheat sheet: Added a new key and corrected some wrong keys
IA Page: https://duck.co/ia/view/markdown_cheat_sheet
> Markdown Cheat sheet: Added a new key and corrected some wrong keys

- share/goodie/cheat_sheets/json/linux.json
Corrects typos and fixes https://github.com/duckduckgo/zeroclickinfo-goodies/issues/2443
IA Page: [https://duck.co/ia/view/linux_cheat_sheet](https://duck.co/ia/view/linux_cheat_sheet)
> Linux Cheat Sheet: Update source url

- share/goodie/cheat_sheets/json/mysql.json
Fixes https://github.com/duckduckgo/zeroclickinfo-goodies/issues/2389
IA Page: [ https://duck.co/ia/view/mysql_cheat_sheet](https://duck.co/ia/view/mysql_cheat_sheet)
> Add alias section in MySQL cheat sheet

- share/goodie/cheat_sheets/json/mercurial.json
Mercurial cheat sheet: Added a new command and fixed typos
IA Page: https://duck.co/ia/view/mercurial_cheat_sheet
> Mercurial cheat sheet: Added a new command and fixed typos

- share/goodie/cheat_sheets/json/metasploit.json
Metasploit cheat sheet: Two new commands in Meterpreter Core and File System section
IA Page: https://duck.co/ia/view/metasploit_cheat_sheet
> Metasploit cheat sheet: Two new commands in Meterpreter Core and File System section

- share/goodie/cheat_sheets/json/midnight-commander.json
Added two commands and improved formatting to Midnight Commander cheat sheet.
IA Page: https://duck.co/ia/view/midnight_commander_cheat_sheet
> Midnight Commander: Added two commands and improved formatting

- share/goodie/cheat_sheets/json/mplayer.json
Mplayer cheat sheet: Added new shortcuts and fixed typos  and removed extra lines
IA Page: https://duck.co/ia/view/mplayer_cheat_sheet
> Mplayer cheat sheet: Added new shortcuts, fixed typos and removed extra lines

- share/goodie/cheat_sheets/json/rust-types.json
Added new section Closure types to rust types cheat sheet.
IA Page: https://duck.co/ia/view/rust_types_cheat_sheet
> Rust types cheat sheet: Added new section Closure Types

- share/goodie/cheat_sheets/json/tmux.json
Tmux cheat sheet: Added more shortcuts and fixed typos
IA Page: https://duck.co/ia/view/tmux_cheat_sheet
> Tmux cheat sheet: Added more shortcuts and fixed typos

- share/goodie/cheat_sheets/json/magit.json
Added three more commands to magit cheat sheet.
IA Page: https://duck.co/ia/view/magit_cheat_sheet
> Magit cheat sheet: Added three more commands

- share/goodie/cheat_sheets/json/kubernetes.json
Kubernetes cheat sheet: Added three commands, fixed typos and improved formatting.
IA Page: https://duck.co/ia/view/kubernetes_cheat_sheet
> Kubernetes cheat sheet: Added three commands, fixed typos and improved formatting

- share/goodie/cheat_sheets/json/kmplayer.json
KM player cheat sheet: Added more shortcuts, removed extra lines and fixed typos
IA Page: https://duck.co/ia/view/kmplayer_cheat_sheet
> KM player cheat sheet: Added more shortcuts, removed extra lines and fixed typos

- share/goodie/cheat_sheets/json/gdb.json
Added two commands to GDB cheat sheet.
IA Page: https://duck.co/ia/view/gdb_cheat_sheet
> GDB cheat sheet: Added two commands

- share/goodie/cheat_sheets/json/apt-get.json
Added more commands to apt-get cheat sheet
IA Page: https://duck.co/ia/view/apt_get_cheat_sheet
> apt-get cheat sheet: added more commands

- share/goodie/cheat_sheets/json/jive-talk.json
Jive talk cheat sheet: Added more jive words and corrected some typos
IA Page: https://duck.co/ia/view/jive_talk_cheat_sheet
> Jive talk cheat sheet: Added more jive words and corrected some typos

- share/goodie/cheat_sheets/json/apple-mac-os.json
Added more keyboard shortcuts to Apple Mac OS Cheat sheet.
Apple mac os cheat sheet IA page : https://duck.co/ia/view/apple_mac_os_cheat_sheet
> Apple Mac OS Cheatsheet: Added more keyboard shortcuts.

- share/goodie/cheat_sheets/json/lua.json
Added eight more operators to Lua cheat sheet.
IA Page: https://duck.co/ia/view/lua_cheat_sheet
> Lua cheat sheet: Added more operators

- share/goodie/cheat_sheets/json/arch-linux.json
IA Page: [https://duck.co/ia/view/arch_linux_cheat_sheet](https://duck.co/ia/view/arch_linux_cheat_sheet)
> arch linux cheat sheet: Add commands for removing packages

- lib/DDG/Goodie/CalendarConversion.pm
- lib/DDG/Goodie/Constants.pm
- lib/DDG/Goodie/Conversions.pm
- lib/DDG/Goodie/DuckDuckGo.pm
- lib/DDG/Goodie/FirefoxOS.pm
- lib/DDG/Goodie/HelpLine.pm
- lib/DDG/Goodie/Jira.pm
- lib/DDG/Goodie/POTUS.pm
- lib/DDG/Goodie/Paper.pm
- lib/DDG/Goodie/PeriodicTable.pm
- lib/DDG/Goodie/PublicDNS.pm
- lib/DDG/Goodie/SolarSystem.pm
- lib/DDG/Goodie/ZappBrannigan.pm
Reverts duckduckgo/zeroclickinfo-goodies#2419
Version 0.62 of YAML::XS now released, can undo the fix.
> Revert "Fix YAML::XS update issue (temporary)"

- share/goodie/cheat_sheets/json/morse-code.json
Morse code cheat sheet: Added new section Punctuation Mark
IA Page: https://duck.co/ia/view/morse_code_cheat_sheet
> Morse code cheat sheet: Added new section Punctuation Mark

- share/goodie/cheat_sheets/json/javascript.json
Added trigonometric methods to Javascript cheat sheet
IA Page: https://duck.co/ia/view/javascript_cheat_sheet
> Javascript cheat sheet: Added trigonometric methods

- share/goodie/cheat_sheets/json/javascript-dom.json
Added more properties to Javascript Dom cheat sheet
IA Page: https://duck.co/ia/view/javascript_dom_cheat_sheet
> Javascript Dom cheat sheet: Added more properties

- share/goodie/cheat_sheets/json/jive-talk.json
Jive talk cheat sheet: Added more jive words and improved formatting
IA Page: https://duck.co/ia/view/jive_talk_cheat_sheet
> Jive talk cheat sheet: Added more jive words and improved formatting

- share/goodie/cheat_sheets/json/js-keycodes.json
Js keycodes cheat sheet: Added code for contextmenu
IA Page: https://duck.co/ia/view/js_keycodes_cheat_sheet
> Js keycodes cheat sheet: Added code for contextmenu

- share/goodie/cheat_sheets/json/military-slang.json
Added more terms to Millitary slang cheat sheet
IA Page: https://duck.co/ia/view/millitary_slang
> Millitary slang cheat sheet: Added more terms

- share/goodie/cheat_sheets/json/minecraft.json
Minecraft cheat sheet: Added some keyboard shortcuts
IA Page: https://duck.co/ia/view/minecraft_cheat_sheet
> Minecraft cheat sheet: Added some keyboard shortcuts

- share/goodie/cheat_sheets/json/illustrator.json
Illustrator cheat sheet: Added some shortcuts and corrected one shortcut
IA Page: https://duck.co/ia/view/illustrator_cheat_sheet
> Illustrator cheat sheet: Added some shortcuts and corrected one shortcut

- share/goodie/cheat_sheets/json/imgur.json
Added more shortcuts to Imgur cheat sheet
IA Page: https://duck.co/ia/view/imgur_cheat_sheet
> Imgur cheat sheet: Added more shortcuts

- share/goodie/cheat_sheets/json/indian-languages.json
Indian languages: Corrected some languages
IA Page: https://duck.co/ia/view/indian_languages_cheat_sheet
> Indian languages: Corrected some languages

- share/goodie/cheat_sheets/json/intel-8085.json
Added more instructions to Intel 8085 cheat sheet
IA Page: https://duck.co/ia/view/intel_8085_cheat_sheet
> Intel 8085 cheat sheet: Added more instructions

- share/goodie/cheat_sheets/json/irc.json
IRC cheat sheet: Added more commands and improved formatting
IA Page: https://duck.co/ia/view/irc_cheat_sheet
> IRC cheat sheet: Added more commands and improved formatting

- share/goodie/cheat_sheets/json/codio.json
This PR removes blank lines from cheat sheet
IA Page: [ https://duck.co/ia/view/codio_cheat_sheet](https://duck.co/ia/view/codio_cheat_sheet)
> Remove blank lines

- share/goodie/cheat_sheets/json/microsoft-powerpoint.json
New Cheat sheet for Microsoft Powerpoint 2013 containing keyboard shortcuts.
IA Page : https://duck.co/ia/view/microsoft_powerpoint_cheat_sheet
> New Cheat sheet Microsoft Powerpoint 2013

- share/goodie/cheat_sheets/json/resharper.json
New Resharper Cheat sheet containing Keyboards shorcuts for it.
IA page: https://duck.co/ia/view/resharper_cheat_sheet
> New Resharper Cheat sheet

- share/goodie/cheat_sheets/json/language/greek.json
Continues PR #1704
IA: https://duck.co/ia/view/greek_cheat_sheet
> Greek Cheat Sheet (Continue PR #1704)

- share/goodie/cheat_sheets/json/imagemagick.json
---
https://duck.co/ia/view/imagemagick_cheat_sheet
> cheatsheets: add imagemagick cheatsheet

- lib/DDG/Goodie/Kana.pm
Fixes #2380 (was getting a bit annoying!)
@mintsoft I could add checks to the other translation subs, but this is the only one that was touched by the tests.
---
[IA Page](https://duck.co/ia/view/kana)
> Silence Kana warning

- share/goodie/cheat_sheets/json/sublime-text.json
Added aliases so as to enable queries like `sublime cheatsheet` and `sublime text 2 cheatsheet` to work
IA : https://duck.co/ia/view/sublime_text_cheat_sheet
> Added aliases

- share/goodie/cheat_sheets/json/aoeii.json
- share/goodie/cheat_sheets/json/cmus.json
- share/goodie/cheat_sheets/json/crochet-pattern.json
- share/goodie/cheat_sheets/json/cryptography.json
- share/goodie/cheat_sheets/json/css.json
- share/goodie/cheat_sheets/json/d3js.json
- share/goodie/cheat_sheets/json/default-port-numbers.json
- share/goodie/cheat_sheets/json/docker.json
- share/goodie/cheat_sheets/json/dockerfile.json
- share/goodie/cheat_sheets/json/drush.json
- share/goodie/cheat_sheets/json/eclipse.json
- share/goodie/cheat_sheets/json/ed.json
- share/goodie/cheat_sheets/json/elementary.json
- share/goodie/cheat_sheets/json/emacs-idris-mode.json
- share/goodie/cheat_sheets/json/emacs.json
- share/goodie/cheat_sheets/json/es6.json
- share/goodie/cheat_sheets/json/html.json
- share/goodie/cheat_sheets/json/wp-cli.json
- share/goodie/cheat_sheets/json/xcode.json
- share/goodie/cheat_sheets/json/xwing-alliance.json
IA Page links:
https://duck.co/ia/view/es6_cheat_sheet
https://duck.co/ia/view/emacs_cheat_sheet
https://duck.co/ia/view/emacs_idris_mode_cheat_sheet
https://duck.co/ia/view/elementary_cheat_sheet
https://duck.co/ia/view/ed_cheat_sheet
https://duck.co/ia/view/eclipse_cheat_sheet
https://duck.co/ia/view/drush_cheat_sheet
https://duck.co/ia/view/dockerfile_cheat_sheet
https://duck.co/ia/view/docker_cheat_sheet
https://duck.co/ia/view/default_port_numbers_cheat_sheet
https://duck.co/ia/view/d3js_cheat_sheet
https://duck.co/ia/view/css_cheat_sheet
https://duck.co/ia/view/cryptography_cheat_sheet
https://duck.co/ia/view/cmus_cheat_sheet
https://duck.co/ia/view/aoeii_cheat_sheet
https://duck.co/ia/view/crochet_pattern_cheat_sheet
https://duck.co/ia/view/xwing_alliance_cheat_sheet …
> CheatSheets: Additions and Corrections Pt.2

- share/goodie/cheat_sheets/json/ed.json
IA Page:  http://duck.co/ia/view/ed_cheat_sheet
Fixes #2664.
> Change ed cheat-sheet from keyboard->terminal template

- share/goodie/cheat_sheets/json/netbeans.json
https://duck.co/ia/view/netbeans_ide_cheat_sheet
> Netbbeans cheat sheet

- share/goodie/cheat_sheets/json/iex.json
This is the IEx (Interactive Elixir) cheat sheet for various shell helpers. 
https://duck.co/ia/view/iex_cheat_sheet
Helpers cheat sheet for Elixir's interactive shell (IEx).
http://elixir-lang.org/docs/stable/iex/IEx.Helpers.html
iex cheat sheet
**Screenshot 1 (Default Theme) - Not Collapsed**
**Screenshot 2 (Dark Theme) - Collapsed**
https://duck.co/ia/view/iex_cheat_sheet
> New IEx (Interactive Elixir) Cheat Sheet.

- share/goodie/cheat_sheets/json/elixir.json
https://duck.co/ia/view/elixir_cheat_sheet
Elixir is a dynamic functional programming language built on top of the Erlang Virtual Machine. This cheat sheet aims to give a non-exhaustive overview of typical language constructs and syntax.
http://elixir-lang.org/
Elixir Cheat Sheet, Elixir overview, Elixir syntax, elixir programming language
**Screenshot 1: Default theme**
**Screenshot 2: Dark theme - collapsed**
> New Elixir cheat sheet.

- share/goodie/cheat_sheets/json/penn-treebank.json
Added `Word Level (Cont.)` by splitting into 2 (18 each).
> Updated Penn Treebank Presentation.

- .travis.yml
We can `dzil smoke` manually if there are big changes outside of lib/share.
> Just use prove

- share/goodie/cheat_sheets/json/activeworlds.json
IA: https://duck.co/ia/view/activeworlds_cheat_sheet
> New ActiveWorlds Cheat Sheet

- lib/DDG/Goodie/LoremIpsum.pm
- share/goodie/lorem_ipsum/content.handlebars
- share/goodie/lorem_ipsum/lorem_ipsum.css
- share/goodie/lorem_ipsum/subtitle.handlebars
- t/LoremIpsum.t
Regards the [Lorem Ipsum IA](https://duck.co/ia/view/lorem_ipsum).
If you look at my [PR for the GibberishGenerator](https://github.com/duckduckgo/zeroclickinfo-goodies/pull/1967) - this now works rather like that (just replace the word `nonsense` with `lorem ipsum`). *Kindah*.
Resolves #958.
> Improve LoremIpsum Goodie

- share/goodie/cheat_sheets/json/json-syntax.json
IA: https://duck.co/ia/view/json_syntax_cheat_sheet
> New JSON Syntax cheat sheet

- share/goodie/cheat_sheets/json/formula-1.json
- share/goodie/cheat_sheets/json/formula1.json
This is the first version of my Formula 1 cheat sheet. 
The cheat sheet will display key facts and information about the current Formula One racing season, such as race dates, teams & drivers, points system and recent rule changes. 
https://duck.co/ia/view/formula_1_cheat_sheet
> Formula 1 Cheat Sheet

- share/goodie/cheat_sheets/json/underscore-js.json
IA : https://duck.co/ia/view/underscore_js_cheatsheet
> Added cheatsheet for Underscore JS

- share/goodie/cheat_sheets/json/ssh.json
Added alias scp for the ssh cheatsheet.
> Added scp alias to the ssh cheatsheet

- lib/DDG/Goodie/LoremIpsum.pm
- share/goodie/lorem_ipsum/content.handlebars
@moollaza Fixes that bug you mentioned.
---
IA Page: https://duck.co/ia/view/lorem_ipsum
> LoremIpsum: Fix display with just words

- lib/DDG/Goodie/GibberishGenerator.pm
- share/goodie/gibberish_generator/content.handlebars
- share/goodie/gibberish_generator/gibberish_generator.css
- t/GibberishGenerator.t
It... Generates 'pronounceable' gibberish.
I feel there is a lerge need for more random nonsense in this world (queries likely to be very specific and links would be a hinderance).
N/A
`3 words of French gibberish`, `a sentence of nonsense`.
Recreationalists?
Not to my knowledge.
**Which existing Instant Answers will this …
> New GibberishGenerator Goodie

- template/share/goodie/cheat_sheets/json/example.json
Add put them in alphabetical order.
> Cheat sheet template: Added missing template types

- share/goodie/cheat_sheets/json/erlang.json
https://duck.co/ia/view/erlang_cheat_sheet
https://duck.co/ideas/idea/6147/erlang-cheat-sheet
Erlang cheat sheet
This Pull Request is the Erlang Cheat Sheet. I consists of 9 sections:
- Erlang Shell
- File Types
- Comparators
- IO
- Functions
- Permutations
- Types
- Escape Sequences
- Date and Time
No data source provided.
No example queries.
No triggers applied.
**Screenshot 1 - Normal View (Default theme)**
**Screenshot 2 - Collapsed (Dark theme)**
The JSON has been validated at http://jsonlint.com/
https://duck.co/ia/view/erlang_cheat_sheet
> New Erlang Cheat Sheet.

- t/GibberishGenerator.t
@mintsoft Fixes #2707 
---
IA Page: https://duck.co/ia/view/gibberish_generator
> GibberishGenerator: Fix failing tests

- share/goodie/cheat_sheets/json/indian-spices.json
https://duck.co/ia/view/indian_spices_cheat_sheet
> New Indian Spices Cheat Sheet

- share/goodie/cheat_sheets/json/indian-spices.json
https://duck.co/ia/view/indian_spices_cheat_sheet
> Indian Spices Cheat Sheet

- lib/DDG/Goodie/SubnetCalc.pm
I did this as a test, might as well get it in master
----------
IA Page : https://duck.co/ia/view/subnet_calc
> SubnetCalc: Minor tidying up of subs

- lib/DDG/Goodie/Conversions.pm
- t/Conversions.t
Includes the entire of: https://github.com/duckduckgo/zeroclickinfo-goodies/pull/2126 plus the fix for the pluralisation (and tests of course)
---------
IA Page: http://duck.co/ia/view/conversions
> Conversions: Fixes #2125

- share/goodie/cheat_sheets/json/punjabi.json
Punjabi Language Cheatsheet
IA Page: [https://duck.co/ia/view/punjabi_cheat_sheet](https://duck.co/ia/view/punjabi_cheat_sheet)
> New Punjabi Language Cheat Sheet

- share/goodie/cheat_sheets/json/raspberrypi.json
IA page : https://duck.co/ia/view/raspberrypi_cheat_sheet
> New Raspberry-PI Cheat Sheet

- share/goodie/cheat_sheets/json/awesome-window-manager.json
This provides a new Awesome WM cheat sheet/reference page for default key
bindings, mouse bindings, and reference material for configuration.
[IA Page][1]
[1]: https://duck.co/ia/view/awesome_window_manager_cheat_sheet
> New Awesome Window Manager Cheat Sheet

- lib/DDG/Goodie/CheatSheets.pm
- lib/DDG/Goodie/CurrencyIn.pm
- lib/DDG/Goodie/IndependenceDay.pm
- lib/DDG/Goodie/Minecraft.pm
- lib/DDG/Goodie/Shruggie.pm
- lib/DDG/Goodie/Zodiac.pm
- t/CheatSheets/CheatSheetsJSON.t
More ***speed***!
IA Pages:
- https://duck.co/ia/view/cheat_sheets
- https://duck.co/ia/view/currency_in
- https://duck.co/ia/view/independence_day
- https://duck.co/ia/view/minecraft
- https://duck.co/ia/view/shruggie
- https://duck.co/ia/view/zodiac
> Update use of 'JSON' to 'JSON::MaybeXS'

- share/goodie/cheat_sheets/json/quackhack.json
Link to IA page: https://duck.co/ia/view/quackhack_cheat_sheet
> updated docs link for QuackHack cheat sheet

- share/goodie/cheat_sheets/json/r.json
https://duck.co/ia/view/r_cheat_sheet
> New R Cheat Sheet

- share/goodie/cheat_sheets/json/r.json
@GuiltyDolphin here's that patch
https://duck.co/ia/view/r_cheat_sheet
> R Cheat Sheet: Fix Unescaped Brackets

- share/goodie/cheat_sheets/json/powershell.json
Minor fixes and various improvements (most notably, new sections for control flow statements) based on [feedback](https://www.reddit.com/r/PowerShell/comments/499via/duckduckgo_powershell_cheat_sheet/) from the PowerShell community on Reddit.
IA: https://duck.co/ia/view/powershell_cheat_sheet
> PowerShell Cheat Sheet: Miscellaneous fixes and improvements

- share/goodie/cheat_sheets/json/lodash.json
IA Page: https://duck.co/ia/view/lodash_cheat_sheet
> New Lodash Cheat Sheet

- share/goodie/cheat_sheets/json/es6.json
IA Page: https://duck.co/ia/view/es6_cheat_sheet
Maintainer: @vikashvverma
> ES6 Cheat Sheet: Update Proxy and Promise examples to avoid confusion

- lib/DDG/Goodie/AltCalendars.pm
- t/AltCalendars.t
Updating tab name to canonical "Answer"
---
IA Page: https://duck.co/ia/view/alt_calendars
> Change Tab name to match IA Page

- share/goodie/cheat_sheets/json/pscp.json
https://duck.co/ia/view/pscp_cheat_sheet
> New pscp Cheat Sheet

- lib/DDG/Goodie/Zodiac.pm
- t/Zodiac.t
I broke something!
Fixes #2751
---
IA Page: https://duck.co/ia/view/zodiac
Maintainer: @n0mady
> Zodiac: Fix broken images

- share/goodie/cheat_sheets/json/epl.json
Correct EPL Cheat Sheet ID
---
https://duck.co/ia/view/epl_cheat_sheet
> Continue Pr/2164

- share/goodie/cheat_sheets/json/epl.json
IA: https://duck.co/ia/view/epl_cheat_sheet
> New EPL cheatsheet

- share/goodie/cheat_sheets/json/finnish.json
https://duck.co/ia/view/finnish_cheat_sheet
> New Finnish Cheat Sheet

- share/goodie/cheat_sheets/json/git-ssh.json
- share/goodie/cheat_sheets/json/git_ssh.json
https://duck.co/ia/view/git_ssh_cheat_sheet
> New git ssh cheat sheet

- share/goodie/cheat_sheets/json/angular2.json
Displays a list of Angular 2 built-in template syntax, directives, components, decorators, dependency injection and their configuration in response to searches like `angular 2 cheatsheet`, `angular 2 cheat sheet`
[ https://angular.io/docs/ts/latest/guide/cheatsheet.html](https://angular.io/docs/ts/latest/guide/cheatsheet.html)
This is official source for Angular 2.
Since the source is the official Angular 2, I don't think there is any other better source.
**Which communities will this Instant Answer be especially useful for? (gamer, book lovers, etc)**
Programmers
**Is …
> New Angular 2 Cheat Sheet

- share/goodie/cheat_sheets/json/rails-devops.json
IA page: https://duck.co/ia/view/rails_devops_cheat_sheet
> rails-devops-cheat-sheet

- share/goodie/cheat_sheets/visual-studio.json
Please refer to #1225 for metadata.
as part of resolving  #980
---
IA Page: https://duck.co/ia/view/visual_studio_cheat_sheet
> Visual Studio cheatsheet (reviving #1225) 

- share/goodie/cheat_sheets/json/language/greek.json
Let me know if that's what you meant.
IA Page: http://duck.co/ia/view/greek_cheat_sheet
> Changes as per issue #2745

- share/goodie/cheat_sheets/json/git-ssh.json
https://duck.co/ia/view/git_ssh_cheat_sheet
> Git SSH Cheat Sheet: Capitalized name

- share/goodie/cheat_sheets/json/prove.json
Following a [request on Twitter](https://twitter.com/oylenshpeegul/status/709907229508571137)
Also capitalised the descriptions.
---
https://duck.co/ia/view/prove_cheat_sheet
> Prove: Added -PPretty option

- share/goodie/cheat_sheets/json/git.json
- share/goodie/cheat_sheets/json/php.json
IAs:
- https://duck.co/ia/view/php_cheat_sheet
- https://duck.co/ia/view/git_cheat_sheet
> improving php cheatsheet

- share/goodie/cheat_sheets/json/pdfimage.json
- share/goodie/cheat_sheets/json/pdfimages.json
https://duck.co/ia/view/pdfimages_cheat_sheet
> New Cheat Sheet added for pdfimage

- lib/DDG/Goodie/JohnCena.pm
- t/JohnCena.t
https://duck.co/ia/view/john_cena
> New JohnCena Goodie

- share/goodie/cheat_sheets/json/nodejs.json
IA: https://duck.co/ia/view/nodejs_cheat_sheet
Maintainer: @stanly-johnson
> improving nodejs cheatsheet

- lib/DDG/Goodie/Anagram.pm
- t/Anagram.t
Updates Anagram Goodie Re: #2767
------
IA Page:  http://duck.co/ia/view/anagram 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @drschwabe
> Anagrams: Update to full template

- share/goodie/cheat_sheets/json/awesome-window-manager.json
---
https://duck.co/ia/view/awesome_window_manager_cheat_sheet 
Maintainer: @kennyballou
> AwesomeWM cheat sheet: Added new alias

- share/goodie/cheat_sheets/json/c-char-manipulation.json
IA: https://duck.co/ia/view/c_character_manipulation_functions_cheat_sheet
> New C char manipulation functions cheat sheet

- lib/DDG/Goodie/BeamMeUpScotty.pm
- t/BeamMeUpScotty.t
A Star Trek catchphrase
IA Page: https://duck.co/ia/view/beam_me_up_scotty
> New Star Trek Code Phrase

- lib/DDG/Goodie/BeamMeUpScotty.pm
- t/BeamMeUpScotty.t
IA Page: https://duck.co/ia/view/beam_me_up_scotty
> Update Beam Me Up Scotty Goodie Re: #2767

- share/goodie/cheat_sheets/json/git.json
https://duck.co/ia/view/git_cheat_sheet
> Git cheat sheet: improve 'fetch' command

- share/goodie/cheat_sheets/json/multisim.json
https://duck.co/ia/view/multisim_cheat_sheet
> New MULTISIM Cheat Sheet

- share/goodie/cheat_sheets/json/adobe-flash.json
https://duck.co/ia/view/adobe_flash_cheat_sheet
> Adobe flash cheat sheet

- share/goodie/cheat_sheets/json/redhat.json
https://duck.co/ia/view/redhat_cheat_sheet
> New Redhat cheat sheet

- lib/DDG/Goodie/WhereAmI.pm
- share/goodie/where_am_i/where_am_i.js
- t/WhereAmI.t
**Fixes** #445
Added  `structured_answer` to show a map instead of a text.
TO_FIX: It seems to have some sort of problem in the front-end and doesn't render the map.
---
IA:[https://duck.co/ia/view/where_am_i]( https://duck.co/ia/view/where_am_i)
> WhereAmI: Map template added

- lib/DDG/Goodie/DayOfWeek.pm
- t/DayOfWeek.t
This is a Goodie as requested at https://duck.co/ideas/idea/6107/day-of-the-week-calculator
Feedback please; I'd like to know if I'm not adhering to any best-practices or conforming to accepted styles for a new IA. 
-----
IA Page: https://duck.co/ia/view/day_of_week
> New Day of Week Goodie

- share/goodie/cheat_sheets/json/microsoft-excel.json
https://duck.co/ia/view/microsoft_excel_cheat_sheet
> MS excel Cheat sheet

- share/goodie/cheat_sheets/json/redhat.json
https://duck.co/ia/view/redhat_cheat_sheet
> fixed typo in PR #2413

- share/goodie/cheat_sheets/json/c-char-manipulation.json
1. Changed indentation
2. Used title case for "name" field in the json file
3. Added respective aliases so that the cheat sheet is visible using different search parameters
New IA link: https://duck.co/ia/view/c_char_manipulation_cheat_sheet
> Updates to New C Char Manipulation cheat sheet

- share/goodie/conversions/ratios.yml
- t/Conversions.t
@moollaza @GuiltyDolphin I've defined these around the ISU definitions of the units; which should suffice for our purposes
----------------------
https://duck.co/ia/view/conversions
> Conversions: Fixing accuracy issues

- share/goodie/cheat_sheets/json/language/konkani.json
IA: https://duck.co/ia/view/konkani_cheat_sheet
> New konkani cheat sheet

- lib/DDG/Goodie/CheatSheets.pm
- t/CheatSheets/CheatSheetsJSON.t
Generates warnings, e.g. https://github.com/duckduckgo/zeroclickinfo-goodies/issues/2835.
> Don't each references in CheatSheets

- share/goodie/cheat_sheets/json/fortran.json
https://duck.co/ia/view/fortran_cheat_sheet
> New FORTRAN Cheat Sheet

- share/goodie/cheat_sheets/json/express.json
This cheat sheet displays a list of properties and methods of Express, a fast, unopinionated, minimalist web framework for NodeJS.
Screenshot:
IA Page: [ https://duck.co/ia/view/express_cheat_sheet](https://duck.co/ia/view/express_cheat_sheet)
> New Express Cheat Sheet

- share/goodie/cheat_sheets/json/nasm.json
IA: https://duck.co/ia/view/nasm_cheat_sheet
> New cheat sheet: NASM

- share/goodie/cheat_sheets/json/asciicode.json
Displays a list of ASCII Code and corresponding character.
Screenshot:
IA Page: [ https://duck.co/ia/view/ascii_code_cheat_sheet](https://duck.co/ia/view/ascii_code_cheat_sheet)
> New ASCII Cheat Sheet

- share/goodie/cheat_sheets/json/svn.json
Added the command to revert all changes on a tree. I think this would be a useful addition.
---
https://duck.co/ia/view/svn_cheat_sheet
Maintainer: @Juholei
> SVN Cheat Sheet: Add command to revert all changes

- share/goodie/cheat_sheets/json/clojure.json
IA: https://duck.co/ia/view/clojure_cheat_sheet
I searched and found the IA already exists for this cheat sheet although didn't find any file under it. Used the previous IA link for this PR instead. I hope thats okay.
> New Clojure cheatsheet

- share/goodie/cheat_sheets/json/elasticsearch.json
https://duck.co/ia/view/elasticsearch_cheat_sheet
> New Elasticsearch Cheat Sheet

- share/goodie/cheat_sheets/json/aws-lambda.json
IA page : https://duck.co/ia/view/aws_lambda_cheat_sheet
> New AWS Lambda Cheat Sheet

- share/goodie/cheat_sheets/json/phoenix-mix.json
https://duck.co/ia/view/phoenix_mix_cheat_sheet
A cheat sheet for searching built-in Phoenix-specific Mix tasks.
http://www.phoenixframework.org/docs/mix-tasks
phoenix mix tasks
phoenix mix tasks, phoenix mix commands, mix phoenix.gen
**Screenshot 1 (Dark theme) not-collapsed**
**Screenshot 2 (Default theme) collapsed**
https://duck.co/ia/view/phoenix_mix_cheat_sheet
> New Phoenix Mix Cheat Sheet

- share/goodie/cheat_sheets/json/latindecl.json
https://duck.co/ia/view/latindecl_cheat_sheet
> New Latin Declensions Cheat Sheet

- share/goodie/cheat_sheets/json/hindu-gods.json
Not sure if such cheat sheets are accepted though we can have a discussion.
Screenshot: 
IA Page: [ https://duck.co/ia/view/hindu_god_cheat_sheet](https://duck.co/ia/view/hindu_god_cheat_sheet)
> New Hindu God and Godess Cheat Sheet

- share/goodie/cheat_sheets/json/high-valyrian.json
IA : https://duck.co/ia/view/high_valyrian_cheat_sheet
> New High Valyrian CheatSheet

- share/goodie/cheat_sheets/json/cassandra.json
https://duck.co/ia/view/cassandra_cheat_sheet
> New Cassandra Cheat Sheet

- share/goodie/cheat_sheets/json/hold-em-starting-hands.json
https://duck.co/ia/view/hold_em_starting_hands_cheat_sheet
> New Poker Cheat Sheet
