duckduckgo/zeroclickinfo-goodies

- lib/DDG/Goodie/LeapYear.pm
- t/LeapYear.t
Fixes to address reduced test coverage caused by: https://github.com/duckduckgo/zeroclickinfo-goodies/issues/888
@MrChrisW this is what's normally done for testing temporal things (see https://github.com/duckduckgo/zeroclickinfo-goodies/blob/master/t/CalendarToday.t#L87 for example)
However, I've just noticed that this technique absolutely hasn't worked here as the current date and time isn't actually used when a query is made, only the time when the goodie was loaded : https://github.com/duckduckgo/zeroclickinfo-goodies/blob/master/lib/DDG/Goodie/LeapYear.pm#L34
> LeapYear: Adding MockTime to output

- t/LeapYear.t
@mintsoft I tested it internally, and I'm not sure why it's failing but this fixes it.
> t/LeapYear.t: Test was failing on Perl 5.16

- lib/DDG/Goodie/Dice.pm
- t/Dice.t
There is an error in Dice.t tests:
3d12 - 4 can be -1 if all three dices show one.
The probability of this error is 1/(12**3) = 0.06% so it seldom appears.
This error was triggered in the Travis build:
https://travis-ci.org/duckduckgo/zeroclickinfo-goodies/jobs/47197374#L1674
(line 1674, search for "Dice.t")
> Fixed errors in Dice tests

- dist.ini
- lib/DDG/Goodie/ResistorColors.pm
- share/goodie/resistor_colors/resistor_colors.css
- t/ResistorColors.t
This improves the markup for the resistor colour codes goodie as per #851.
Is there a standard `zci__something` class/style for the link at the bottom?
> Improve markup for resistor colour codes

- lib/DDG/Goodie/ParseCron.pm
> Fix returning error as structured content in ParseCron, e.g.

- lib/DDG/Goodie/ParseCron.pm
- t/ParseCron.t
HOTFIX
We can go back to it next time to show invalids. For now, the tests with the invalids return immediately.
> ParseCron.t: Let tests pass.

- lib/DDG/Goodie/CrontabCheatSheet.pm
- lib/DDG/Goodie/GimpCheatSheet.pm
- lib/DDG/Goodie/TmuxCheatSheet.pm
- lib/DDG/Goodie/VimCheatSheet.pm
Following on from the conversation on https://github.com/duckduckgo/zeroclickinfo-goodies/pull/949
leading to https://github.com/jim-brighter/zeroclickinfo-goodies/commit/08b7dd21a34b9c4374f046d88e01c14586ff0421
Personally I think the current implementation is a little confusing, especially for perl newbies, without any real advantage. Plus it seems to be spreading:
https://github.com/duckduckgo/zeroclickinfo-goodies/pull/938/files#diff-dfe7ab125d58a2abb86dd17c0b4448cfR37
> Switching cheatsheets to use a more straightforward slurp

- t/WorkdaysBetween.t
'Fixing' https://github.com/duckduckgo/zeroclickinfo-goodies/issues/969 with MockTime; there is still the question as to whether this is counter intuitive
> WorkdaysBetween: Adding MockTime

- lib/DDG/Goodie/TimezoneConverter.pm
- t/TimezoneConverter.t
Addressed TimeZoneConverter: Add support for "1600 GMT" #975 https://github.com/duckduckgo/zeroclickinfo-goodies/issues/975
> TimeZoneConverter: Added support for times with no colon, eg. 1600 GMT

- share/goodie/bpmto_ms/bpmto_ms.css
/cc @abeyang @mintsoft @stefolof
Updated the CSS for slightly improved viewing on mobile screens.
**\< 400px**
Before:
After:
------
**\> 400px**
Before:
After:
> Improve Table CSS for mobile displays

- lib/DDG/Goodie/BashPrimaryExpressions.pm
I've just noticed that my attribution on this is inconsistent with the rest of the Goodies; obviously *mission critical PR* here.
> BashPrimaryExpressions: Harmonising attribution

- t/Conversions.t
The upgrade has broken the tests for Conversions due to small changes in rounding, this fixes it! 
Unfortunately currently there isn't a good workflow that can be used for this as it's quite awkward to test the accuracy of Conversions based on an unreleased module and it's difficult to coordinate the module being updated and the tests at the same time.
cc @moollaza @MrChrisW
> Conversions: Tweaks to tests around rounding and accuracy

- lib/DDG/Goodie/Uppercase.pm
- t/Uppercase.t
Fixes: https://github.com/duckduckgo/zeroclickinfo-goodies/issues/1028
> Uppercase: Should not return if the input isn't upper-case-able

- lib/DDG/Goodie/Conversions.pm
- t/Conversions.t
Fix to #827. I hope it is what you were looking for. 
I also modified the tests file, although there are some tests not related to temperatures that do not pass. Two of them don't pass because of the words mi and sq instead of miles and square. The rest fail because of precision.
> Fix Conversions to show °C and °F

- lib/DDG/Goodie/FrequencySpectrum.pm
This should show the frequency-range labels on the y-axis (#951). The corresponding tspan elements are now children of text elements instead of being their siblings in the SVG.
> Fix for Issue #951: missing diagram labels on the y-axis.

- lib/DDG/Goodie/IsAwesome/kirshapps.pm
- t/IsAwesome/kirshapps.t
It tells people that I am awesome, who would otherwise not know.
What problem does your Instant Answer solve (Why is it better than organic links)?
It tells the world that I am awesome.
What are some example queries that trigger this Instant Answer?
Example: "duckduckhack kirshapps"
This Instant Answer is good for everyone.
Where did you hear about DuckDuckHack? (For first time contributors)
By clicking a link from the DuckDuckGo Search Engine.
What does the Instant Answer look like? (Provide a screenshot for new or updated Instant Answers)
```
- Windows 8
- [] …
```
> KirshApps's First Goodie

- t/00-roles.t
The role tests failed with Perl <5.17.10 installs, due to the used
File::Temp (<0.23) still caring about the casing of the
arguments. Newer versions of File::Temp no longer care about the
casing.
By uppercasing 'suffix' in the tests, we make the tests pass for both
Perl 5.16 and Perl 5.18.
> Fix casing of 'suffix' argument for temp files in tests

- lib/DDG/Goodie/FrequencySpectrum.pm
This is a follow-up fix for #951. This bug didn't show up in duckpan because empty tags weren't recognized and rewritten. It's the same issue as for the y-axis labels.
> Show marker label at the top in FrequencySpectrum

- .travis.yml
- dist.ini
* Remove the generation of .travis.yml from dzil.
* Add Travis container routing to .travis.yml so that we can hopefully speed things up and take advantage of caching.
> Remove dynamic generation of .travis.yml from dzil

- t/Wavelength.t
'\S' is not a valid escape and makes prove complain to stderr (though
the tests pass). Since it seems the '\S' got only introduced to
separate the variable from the word 'Speed', we proper separate them
by switching from the unrecognized escape to proper curly braces.
> Wavelength: Fix string interpolation in test

- lib/DDG/Goodie/FedEx.pm
Fixes the issue with FedEx tracking links leading to an old URL.
I also removed a link in the comments that was outdated. Unfortunately I was not able to find the current URL.
Fixes #1111
> Fix FedEx tracking URL

- share/goodie/duck_duck_go/responses.yml
I shot my mouth off on Twitter, so: here's a better link. That said, I think this is actually at least partially underlying lousy visual styling.
> Improve DuckDuckGo's hiring links

- lib/DDG/Goodie/CallingCodes.pm
- lib/DDG/Goodie/CountryCodes.pm
To clear up warnings from Locale::Country that countries are being renamed/aliased multiple times we need to centralize those calls.  
This PR will need to be coordinated with https://github.com/duckduckgo/duckduckgo/pull/125
> Remove Locale::Country alias/renaming

- lib/DDG/Goodie/PeriodicTable.pm
- t/PeriodicTable.t
The title would link nowhere if we don't add this.
> PeriodicTable.pm: Add `url` to the data.

- share/goodie/cheat_sheets/cheat_sheets.js
/cc @zachthompson @russellholt 
Thanks to @zekiel's Git CheatSheet, he brought a bunch of edge cases to light that I hadn't accounted for, mainly escaped brackets, that aren't inside literal brackets.
The fix is to replace the escaped brackets before checking for any (unescaped) brackets.
Also, I needed to switch the replacements to regex so we replace all occurrences.
> CheatSheet Parsing update

- share/goodie/cheat_sheets/cheat_sheets.js
Whoops! Just noticed this while testing the Blender cheat sheet again
> add in missing right angle bracket to regex

- share/goodie/cheat_sheets/mac-keyboard.json
A cheat sheet that lists useful Mac keyboard shortcuts.
It summarizes all the most commonly used shortcuts so you don't have to go through several links/sources.
[Apple.com](https://support.apple.com/en-us/HT201236),  [How-To-Geek](http://www.howtogeek.com/188530/a-windows-users-guide-to-mac-os-x-keyboard-shortcuts/) and [Dan Rodney's](http://www.danrodney.com/mac/). I'm using Apple.com on the metadata source URL since it's the official one.
They list all the most commonly used Mac keyboard shortcuts. They are also categorized nicely. (e.g. …
> Mac Keyboard Shortcuts cheat sheet

- lib/DDG/Goodie/IndependenceDay.pm
- t/IndependenceDay.t
From what I have read from the duckduckhack mailing list. `structured_answer`s are preferred to html. This PR migrates the independence day goodie to  `structured_answer` and modifies tests appropriately.
The output looks identical to the earlies version.
before:
after:
Would it be more suitable if the name of the country is in the `input` part of the answer? (I chose not to put it there as to not alter the appearance of the output)
> Migrate IndependenceDay goodie from html to structured_answer

- lib/DDG/Goodie/USPS.pm
- t/USPS.t
add some more tests, and make regexes allow whitespaces but not other chars
Should solve #1175
> Do not trigger USPS goodie when query contains other chars besides expected

- share/goodie/cheat_sheets/gnome-keyboard.json
A cheat sheet that lists useful GNOME keyboard shortcuts.
It summarizes all the most commonly used shortcuts so you don't have to go through several links/sources.
[GNOME](https://help.gnome.org/users/gnome-help/stable/shell-keyboard-shortcuts.html.en) official help website.
They list all the most commonly used GNOME keyboard shortcuts.
* GNOME keyboard shortcuts
* GNOME keyboard cheat sheet
**Which communities will this Instant Answer be especially useful for? (gamers, book …
> GNOME Keyboard Shortcuts cheat sheet

- lib/DDG/Goodie/Pi.pm
- t/Pi.t
as discussed with @mintsoft, adding `use utf8` did the trick.
Also added some new tests for the trigger :dart: 
How it looks before the fix:
And after:
should fix #1037
> Trigger Pi goodie with π

- lib/DDG/Goodie/ScreenResolution.pm
- share/goodie/screen_resolution/screen_resolution.js
- t/ScreenResolution.t
Displays the screen resolution to the user in a succinct readout
Reduces the need to clickthrough to whatismyscreenresolution.com or similar
`screen resolution`, `what is my display resolution` (any more potential triggers?)
Computer users
[My own](https://duck.co/ideas/idea/5096/screen-resolution)
The wiki summary for "display …
> Created ScreenResolution, to view your resolution

- share/goodie/cheat_sheets/ed.json
IA Page: https://duck.co/ia/view/ed_cheat_sheet
> Add ed.json for instant answers on ed(1)

- lib/DDG/Goodie/DaysBetween.pm
- t/DaysBetween.t
I have completed one of the five minute fixes suggested by the mailer, specifically issue #1221 . This is my first contribution/pull request so please let me know if there's anything more I should do.
> DaysBetween - Added a few more triggers

- lib/DDG/Goodie/UnixPermissions.pm
- t/UnixPermissions.t
As reported in #1202, if "unix", "file" or "files" was in the query, the IA was triggered but then discarded:
This fixes it:
> Allow "unix" and "files?" in UnixPermissions trigger

- .travis.yml
- lib/DDG/Goodie/EmailValidator.pm
@moollaza @zachthompson this seems to fix the tests for EmailValidator; the stderr redirection was hiding the issue; however there's now a lot of noise in the output due to:
```
Use of uninitialized value in subroutine entry at /home/travis/perl5/perlbrew/perls/5.16/lib/site_perl/5.16.3/File/ShareDir.pm line 329.
```
It looks like autodeps wasn't pulling in `Net::Domain::TLD`; added it into EmailValidator.pm and voila.
I'm not that familiar with dzil, so I guess this isn't solving some root problem somewhere, however at least it shows up the problem!
Secondly, how can we resolve the ShareDir issue; it looks like problem is within the module itself.
> Fixing Tests in Travis for EmailValidator

- share/goodie/cheat_sheets/cheat_sheets.css
- share/goodie/cheat_sheets/detail.handlebars
Directly declaring colors in custom CSS is usually discouraged because it doesn't work great in dark themes - this just brings the cheat sheet css up to speed.
to @bsstoner 
cc @abeyang
> Cheat Sheet Dark Theme Fix

- t/00-roles.t
It shouldn't be here at all; it looks like one I left in when I was test driving it however it gets replaced in the test hash with a correct test anyway (https://github.com/duckduckgo/zeroclickinfo-goodies/pull/1289/files#diff-7360d2d81b9f3f7c544ff758a2985107L367).
> DatesRole: This test would fail if it was ever executed. 

- share/goodie/cheat_sheets/basic-german-phrases.json
- share/goodie/cheat_sheets/basic-german.json
- share/goodie/cheat_sheets/english-to-german.json
- share/goodie/cheat_sheets/german-phrases.json
- share/goodie/cheat_sheets/german.json
Seeing that the old-style, [German Cheat Sheet pr](https://github.com/duckduckgo/zeroclickinfo-goodies/pull/1062) had a nice text file, I just quickly converted it to the new json a while back.  This replaces that pr but @AdamSC1-ddg might want to verify that nothing was lost in the conversion.
> Adam's German cheat sheet converted

- share/goodie/cheat_sheets/emacs.json
Replaces #1291 and fixes #1281 
**Before**
**After**
> Emacs Keys wrapped and commas added for Consecutive Keys

- lib/DDG/Goodie/Uptime.pm
- t/Uptime.t
This updates the uptime module to use the new template system as part of #1163 
**Before**
**After**
> Uptime altered to use templates

- lib/DDG/Goodie/TimezoneConverter.pm
- lib/DDG/GoodieRole/Dates.pm
Fixes https://github.com/duckduckgo/zeroclickinfo-goodies/issues/1286 and since I noticed two lists of timezones in the repo, I made TimezoneConverter use the list from Dates.
> Fix MSK and consolidate timezone lists

- lib/DDG/Goodie/PrimeFactors.pm
- t/PrimeFactors.t
Fixes part of #1163 
Before:
After:
Bug:
Is cached is ```Math::BigInt``` instead of ```0```, not sure why or if it matters
> Prime factors altered to use templates

- lib/DDG/Goodie/Coin.pm
- t/Coin.t
Make "a " optional, so "flip coin" triggers the IA as well.
This goes from:
To:
This should fix #1343
> make 'flip coin' trigger coin flipping ia

- lib/DDG/Goodie/TimezoneConverter.pm
- t/TimezoneConverter.t
Part of https://github.com/duckduckgo/zeroclickinfo-goodies/issues/1163
It drops the styles, but I didn't see a way to keep that without getting more custom than seemed worth it.
Before: 
After:
> TimezoneConverter: switch HTML to template

- share/goodie/cheat_sheets/irc.json
-----
IA Page: https://duck.co/ia/view/irc_cheat_sheet
> IRC Cheat Sheet

- lib/DDG/Goodie/Chess960.pm
- lib/DDG/Goodie/FenViewer.pm
- lib/DDG/GoodieRole/Chess.pm
- share/goodie/chess960/chess960.css
- t/Chess960.t
This changes the output of the Chess960 IA to use the same format as FenViewer, purely done in HTML instead of querying an external website for an image to display.
> Chess960: Use HTML output provided by FenViewer

- share/goodie/cheat_sheets/cheat_sheets.js
Adds `iax=1` to the querystring when you click Show More on a cheat sheet, and restores it to the expanded state on page load if `iax=1` is in the querystring. It uses the same `env.history` API that we use internally to preserve IA state.
This will allows cheat sheets to be bookmarked and shared in the expanded state.
@zachthompson @russellholt @moollaza
> Preserve cheat sheet state and restore it on page load

- share/goodie/cheat_sheets/blender.json
- share/goodie/cheat_sheets/duckduckgo.json
- share/goodie/cheat_sheets/gimp.json
- share/goodie/cheat_sheets/gnome-keyboard.json
- share/goodie/cheat_sheets/mac-keyboard.json
- share/goodie/cheat_sheets/vim.json
Cmd used: `find . -type f -exec sed -i 's!\] + \[!] [!g' {} \;`
Blender:
DuckDuckGo:
Gimp
Gnome
Mac:
Vim:
to @zachthompson 
/cc @jagtalon
> CheatSheets: removed plus sign between consecutive keys as per most recent syntax rules

- lib/DDG/Goodie/CheatSheets.pm
- share/goodie/cheat_sheets/wu-tang.json
* Add `no warnings 'uninitialized'` for missing cheat sheets.
* Add alias `wu-tang` to `wu-tang.json`
> No warnings on not found cheat sheets, new alias

- lib/DDG/Goodie/BinaryLogic.pm
- t/BinaryLogic.t
Fixes #1403
Re-ordered logic to validate input (run through parser) before working on subtitle. @Sloff has added another regex check before parsing to verify the query contains expected logical operators.
/cc @Sloff
> Improve BinaryLogic Goodie, validate input before formatting subtitle.

- lib/DDG/Goodie/CheatSheets.pm
Wrap decode_json in eval so we don't bail entirely for one malformed cheat sheet.
> CheatSheets: eval decode_json

- share/goodie/cheat_sheets/english-braille.json
Add content to the cheatsheet instant answers.
The cheat sheet for english braille is based on the article on wikipedia. <https://en.wikipedia.org/wiki/English_braille>
It is easily accessible compared with digging through the standards which is in a pdf.
Alternative data sources could be from the International Council on English Braille (ICEB) <http://www.iceb.org/ueb> which has the same alphabet encoding on the "Rules of Unified English Braille 2013.pdf" on the same webpage. The encoding is on pg 41 …
> Added English Braille Cheat Sheet

- share/goodie/cheat_sheets/json/english-braille.json
@abeyang I think the "code" template works best here. The reference template looks a little odd because the bullets and braille dots are very similar.
Thoughts?
**Code Template**:
**Reference Template**:
> move json into /json/ dir, switch to code template

- share/goodie/cheat_sheets/json/xcode.json
As suggested here (#1433) i quickly made this change for everyone to see how it looks.
> changes "command" to "⌘", implements #1433

- share/goodie/cheat_sheets/cheat_sheets.css
- share/goodie/cheat_sheets/terminal.handlebars
Displaying the `<code>` elements as `inline-block` seemed to create a bubble of excess space in the right side of the column. Couldn't find a definitive answer as to why that was happening, but by moving a class assignment around in the `terminal.handlebars`, we can display `<code>` elements as `inline`, which solved the problem. CSS is weird :)
> Fixes #1457 - updated code styles for terminal cheat sheet templates

- lib/DDG/Goodie/RandomNumber.pm
- t/RandomNumber.t
If the start or end value was 0, then no matter what, the default rand() value was returned (which is a fractional number). I added a check for the difference of the two numbers. If it's greater than 1, then we enter the random number if block.
Added a few tests to show this.
Here's to hoping I've done PR creation correctly.. it's been a while.
#1466
> iss1466 RandomNumber Correction for bounds of 0

- share/goodie/cheat_sheets/cheat_sheets.css
Moving back to `normal` settings for `word-break`. The `break-all` we introduced to force long "words" (code snippets, etc) to wrap has some unexpected effects on other keys that shouldn't be wrapping.
This is a temporary fix to get things working again. We need to revisit the markup and implementation of the keys and values to make sure they work as we expect them to.
/cc @alohaas @russellholt
> Switch back to normal word-break css

- share/goodie/cheat_sheets/json/emacs.json
Hello guys, I didn't know whether to create a PR or submit this as a suggestion. If this creates more work for you let me know and I'll add a suggestion. I brought my forked repo up-to-date just before if that helps...
I use this shortcut very often and I thought it might be useful to others. One thing is that this shortcut is not on the current source for this cheat sheet. I am sure if that's an issue. In any case let me know what you think. My source is:
http://www.emacswiki.org/emacs/GotoLine
> Emacs cheat sheet suggestion: Added "Go to line" shortcut

- share/goodie/cheat_sheets/json/blender.json
- share/goodie/cheat_sheets/json/duckduckgo.json
- share/goodie/cheat_sheets/json/firefox.json
- share/goodie/cheat_sheets/json/gnome-keyboard.json
- share/goodie/cheat_sheets/json/mac-keyboard.json
- share/goodie/cheat_sheets/json/microsoft-windows.json
- share/goodie/cheat_sheets/json/sublime-text.json
- share/goodie/cheat_sheets/json/ubuntu.json
- share/goodie/cheat_sheets/json/vlc.json
([A]/[B]/[C]) are spaced out to look like this: ( [A] / [B] / [C] )
Used this [script](https://gist.github.com/cskksc/cd410ab4a3e45351146e).
Fixes #1407
> Cheatsheets: Change format of keybindings having alternative keys.

- share/goodie/cheat_sheets/json/apple-mac-os.json
made changes to fix the issue:
https://github.com/duckduckgo/zeroclickinfo-goodies/issues/1498
* id: changed to apple_mac_os_cheat_sheet (to match or other Operating System Cheat Sheets
* name: changed to Apple OS X
* description: updated to specify which versions of Mac OS this applies to
* filename: changed to apple-mac-os.json
* aliases: added osx, os x, mac, apple mac
> Update and rename mac-keyboard.json to apple-mac-os.json

- share/goodie/cheat_sheets/json/html.json
It lists the HTML elements.
[HTML element reference](https://developer.mozilla.org/en-US/docs/Web/HTML/Element) from Mozilla Developer Network.
I chose this because they listed HTML elements in a logical structure, alphabetized, and separated deprecated elements.
Others that I've looked at contained deprecated elements or only listed common HTML elements. There's a lot of outdated sources out there.
Web developers. People learning HTML.
**Is this Instant Answer connected to …
> HTML Cheat Sheet

- share/goodie/cheat_sheets/json/html.json
- Switch to 4 space indent
- Title Cased section names
- Removed periods at the end of each description
- Switched to `code` template -- After more consideration it feels like the most appropriate. It felt a little  cluttered with bullets and angle brackets on each line
Result:
/cc @jsstrn
> HTML.json cleanup

- lib/DDG/Goodie/SubnetCalc.pm
- share/goodie/subnet_calc/subnet_calc.css
- t/SubnetCalc.t
This basically looks the same; however it uses the template:
I found writing the tests for the structured answers really laborious; is there a short `.*` for the hash so that the structure only needs to be tested once?
> SubnetCalc: Updating to use the record template

- lib/DDG/Goodie/HTMLEntitiesEncode.pm
- share/goodie/htmlentities_encode/htmlentities_encode.css
- t/HTMLEntitiesEncode.t
Notes: This is a weird IA to work on, it has single row output and guessed multi-line output, so I've used a basic structured_answer in the "one line" output case and the record template in the multi-line output.
Edge case queries to test:
* right angle brackets htmlencode
* how to encode an apostrophe in html ?
* htmlencode pound
New output (I really doubt many people actually see this record template):
Single lookup answer (much more likely for people to see I think!)
> HTMLEntitiesEncode: Structured answer

- lib/DDG/Goodie/Week.pm
We don't always have a `$loc` or `$loc->time_zone` so we need to ensure we have on before creating a DateTime object.
/cc @mintsoft
> Week: ensure we have a defined location and timezone

- share/goodie/cheat_sheets/json/sublime-text-mac.json
Helps users with shortcuts for OSX in Sublime 2 and provides an easier Format and more readable shortcuts for people using DuckDuckGo.
http://www.cheatography.com/gelicia/cheat-sheets/sublime-text-2-shortcuts-verbose-mac/
Seemed like the best option for Sublime 2 (especially since Sublime 3 is still in beta).
Maybe, but this is the best I found for now. There are a few other shortcut pages for OSX on cheatography.com
Developers, Computer Science Majors, people who use pretty …
> Sublime Text Cheat Sheet for OSX

- share/goodie/cheat_sheets/ghci.json
- share/goodie/cheat_sheets/haskell-repl.json
A cheatsheet for the GHCi prompt. Although the information is available from a command inside the prompt this cheatsheet provides an alternate view.
The data source is the help documentation for ghci, accessible from the program itself.
More information about haskell is [available online](https://wiki.haskell.org/GHC/GHCi)
These are the official sources of information.
No.
For developers, researchers, and enthusiasts of Haskell.
**Is this Instant Answer connected to a …
> Added cheatsheets for ghci

- share/goodie/cheat_sheets/json/german.json
So here we are, let's refine the german cheat sheet finally. I added everything from #1368 as suggested there, changed the order in one section and also changed some minor things i thought looked odd.
Question for the native english folks: In the ```Etiquette``` section, it was suggested to spell "night" lower case. But "Evening" and "Morning" is upper case. Please let me know is that is supposed to be like this. In general it would be good if both native german and native english folks can comment if this is ok now. If not please comment and i'll make the necessary changes. :+1: Maybe we can nail this one once and for all. :wink: 
/cc @moollaza
> german cheat sheet final touches (picks up #1368)

- share/goodie/cheat_sheets/json/vcgencmd.json
Shows a cheat sheet/reference of `vcgencmd`, Raspberry Pi's firmware command for querying the sensors etc
[Embedded Linux wiki](http://elinux.org/RPI_vcgencmd_usage).
It's the preferred source from multiple places.
There is [this source](https://github.com/nezticle/RaspberryPi-BuildRoot/wiki/VideoCore-Tools) which I also consulted. It's not better than the other one.
Raspberry Pi enthusiasts. …
> Cheatsheet for vcgencmd, Raspberry Pi's firmware command

- share/goodie/cheat_sheets/json/regex.json
Need a reference for these sometimes. Good to have them in cheatsheet.
> cheatsheet_regex - added the characters in character classes reference

- share/goodie/cheat_sheets/json/lua.json
The value "Lua Cheat Sheet for Programmers" has been corrected. Previously there was a typing error in the word "programmers".
Thanks to @preemeijer for informing me about this mistake.
> Updated Lua cheat sheet: Fixed typing error

- share/goodie/cheat_sheets/json/nmap.json
Apparently, these two commands have a new preferred syntax since 2010.
I tested it out and it turns out that the old syntax in both of the cases are still functional, so I'm not sure should they be replaced or not, but what the heck, I'm submitting a pull request to fix my own cheat sheet.
Source: @bonsaiviking told me about this [on Twitter](https://twitter.com/r3bl_/status/650077864902193153) so maybe he would be interested in stepping in and explaining the issue a bit further.
> Fixes outdated nmap commands

- share/goodie/cheat_sheets/json/turkish.json
Fix for the apostrophe, pointed by https://twitter.com/bitigchi/status/650688207525408768
Turkish grammar rules state that "No additional apostrophe is needed after the 'Türkçe' word".
> TurkishCheatSheet: Remove unneeded apostrophe

- dist.ini
- lib/DDG/Goodie/Meta.pm
Remove metadata download and placeholder IA. No longer needed.
> Remove metadata

- lib/DDG/Goodie/Password.pm
- share/goodie/cheat_sheets/json/xwing-alliance.json
- t/Password.t
A simple fix, maybe not sufficiently filtering triggers. Let me know what you think about it... 
-----
IA Page: https://duck.co/ia/view/password
> Password: Fixes #1565

- share/goodie/cheat_sheets/json/rust-types.json
fix for #1626 
-----
IA Page: https://duck.co/ia/view/rust_types_cheat_sheet
> Changed Rust Language Object Types Cheat Sheet to reference type

- lib/DDG/Goodie/Conversions.pm
- t/Conversions.t
This fixes the bug where the units were being flipped when the case was ambiguous causing an incorrect result.
Fixes #1102 & fixes #1385 
Each conversion below now works as expected:
light year in mm
light year in cm
light year in m
BTU to KwH
-----
IA Page: https://duck.co/ia/view/conversions
> Fixes issues 1102 & 1385

- share/goodie/cheat_sheets/json/emoticon.json
Displays a quick reference for some basic emoticons.
It is a quick visual reference that allows someone instant access to the emoticon without having to search.
Basic knowledge of how to type emoticons.
It was the quickest to access. This instant answer is supposed to be a quick reference for a basic emoticon, so my memory of texting and IM conventions seemed appropriate.
There are no doubt online sources that provide more extensive lists
**What are some example queries that trigger this …
> New Emoticon Cheat Sheet

- share/goodie/cheat_sheets/json/github.json
Shows the keyboard shortcuts on <https://github.com>.
<https://help.github.com/articles/using-keyboard-shortcuts/> and pressing ? on any github page.
It's straight from github.
Not aware of any.
Programmers that use github.
No.
I haven't tested all keyboard shortcuts.  One that github reports but doesn't …
> add cheat sheet for GitHub

- share/goodie/cheat_sheets/json/wp-cli.json
Adds a WP-CLI Cheat Sheet Goodie (wp-cli.json) with the following headings:
- Installation
- Core Commands
- Plugin Commands
- Theme Commands
-----
IA Page: https://duck.co/ia/view/wp_cli_cheat_sheet
> Adds Initial WP-CLI Cheat Sheet

- share/goodie/cheat_sheets/json/magit.json
Displays a cheat sheet for [Magit](http://magit.vc/).
http://daemianmack.com/magit-cheatsheet.html
It's the cheat sheet that I always end up using.
The manual itself, but that sort of defeats the purpose of a cheat sheet.
Programmers / Emacs users.
Not that I know of.
Nope!
**Where did you hear about …
> Add a cheatsheet for Magit (Emacs Git major mode)

- share/goodie/cheat_sheets/json/country-codes.json
Lists all ISO_3166-1 two letter country codes (alpha-2) with the corresponding country name, numeric and alpha-3 codes.
Display the conplete list of codes instantly.
https://en.wikipedia.org/wiki/ISO_3166-1
The .json file for the cheat sheet can be updated with the following this [ruby gist](https://gist.github.com/nemeth/39415872b502732c4518), which uses the linked data source.
Reliable and easily parseable.
The original ISO definitions are listed here: https://www.iso.org/obp/ui/ …
> New Country Codes Cheat Sheet

- share/goodie/cheat_sheets/json/gnome.json
I've included some more keyboard shortcuts in this cheat sheet. Also, I've updated the sourceURL as the previous sourceURL (https://help.gnome.org/users/gnome-help/stable/shell-keyboard-shortcuts.html.en) does not contains all of the shortcuts.
**Screenshots**
***Previously***
***Updated***
-----
IA Page: https://duck.co/ia/view/gnome_cheat_sheet
> Updated gnome cheatsheet. Added more shortcuts.

- share/goodie/cheat_sheets/json/atom.json
@moollaza this will fix #1703
You was right ```atom``` alias is unnecessary, it works without that.
> #1703 Removed unnecessary alias

- lib/DDG/Goodie/CheatSheets.pm
This small change lets trigger cheatsheet aliases that contain uppercase letters in .json files.
> #1695 - Lowercase cheetsheat aliases

- t/CheatSheets/CheatSheets.t
- t/CheatSheets/CheatSheetsJSON.t
- Moved the tests into a new subdir
- Renamed `cheatsheets_check.t` -> `CheatSheetsJSON.t`
- Print green OK status when only non-fatal WARN's exist
- Remove newline between test to compact output (like regular Perl tests)
to @zachthompson 
/cc @jdorweiler @MariagraziaAlastra
> Move CheatSheet tests into subdir, rename JSON test

- share/goodie/public_dns/README.MD
- share/goodie/public_dns/providers.yml
What has been changed :
- updated links to newer ones and/or make use of https
- Added a lot of providers according to http://pcsupport.about.com/od/tipstricks/a/free-public-dns-servers.htm among others
I have a few questions before possibly merging :
- Is there a limit to the number of IPv4/6 per provider
- OpenDNS has two additional basic DNS, Level3 has 4.2.2.1 to 6  
Adding up to four DNS servers would be enough in most case or displaying them with a "show more" button like in other IAs.
- What are the criteria for the providers
- free & public (naturally)
- basic filtering allowed (spam, botnets, viruses, malwares and the likes ; even pornography/adult content)
- any other criteria such as free registration to have more control over what is filtered
- For the ones that offer …
> Add more public DNS providers

- share/goodie/cheat_sheets/json/redis.json
Filled out PR template as per @MrChrisW's request.
Mirrored the sections given by [Filter by group](http://redis.io/commands#) and removed the '+' between command words as suggested by @zachthompson.
Swapped the template to 'reference' to make it look better.
I also added a few missing bits.
Shows Redis command reference.
http://redis.io/commands
It was given in abandoned PR #1210.
No idea. Probably not as this is the vendors site.
DB admins, programmers...
**Is this Instant …
> add redis command cheat sheet (continues abandoned #1210)

- lib/DDG/Goodie/TimezoneConverter.pm
- t/TimezoneConverter.t
Default timezone was changed to make easier to discover instant answer. 
The change has three parts:
1) Trigger words was replaced with list of timezones. I think it makes more sense than trigger instant answer on each "to" or "into" preposition.
2) Default time zone is user local time zone. 
3) Second part of the query was made optional. In current version it's necessary to implicitly type "to <timezone>", but it would be much more convenient to able to type "19:30 EDT" and have time converted to your local time zone.
> TimezoneConverter: Fixes #1334

- share/goodie/cheat_sheets/detail.handlebars
We're doing this because we don't want to add a separator if we don't have any "More at ..." link.
Before:
After:
> CheatSheets: Don't add the .sep--after class if there is no sourceUrl.

- .travis.yml
So we can use HTTPS with S3 and not fail travis tests, disable host verification for travis only.
> Disable LWP SSL host verification

- share/goodie/cheat_sheets/cheat_sheets.js
- Minor update, can't assume `val` is defined because of new `links` template.
/cc @Mailkov
> ensure val is defined before modifying

- lib/DDG/Goodie/NoteFrequency.pm
- t/NoteFrequency.t
Calculates the frequency in hertz of any musical note.
The typical search results are static tables hosted on aging websites for a limited selection of tuning frequencies. This instant answer calculates the frequency for any note in any tuning.
Goodie perl script.
Because it's a goodie, and not a spice.
No.
"note frequency of c5", "frequency of note c5 432", "notefreq g#6" …
> New Note Frequency Goodie

- template/share/goodie/example/example.js
This PR removes some extra single quotes that don't belong, and comments out the templates block in the JS to prevent it from overwriting the Perl by default
> Small Template Update

- share/goodie/cheat_sheets/json/ubuntu.json
This is a really weird edge case that likely won't occur again, but we should probably have the tests ensure that no alias maps to another cheat sheet (or that no aliases already exist elsewhere)
In most cases the correct IA was triggering, but on a few machines, the ubuntu.json triggered, causing problems because `ubuntu unity cheat sheet` is expected to trigger `ubuntu-unity.json`
/cc @zachthompson @jdorweiler
> remove aliases from ubuntu.json that should trigger ubuntu-unity.json

- lib/DDG/Goodie/Unicode.pm
- t/Unicode.t
Sorry about the late response...
As discussed in the issue, the problem was that the code was returning whatever `unicode_lookup` returns, without validating if it was a defined result
fixes #1430
> only return Unicode match result when there is a match

- share/goodie/cheat_sheets/json/javascript.json
concact() -> concat()
Thanks to @jbinto for spotting.
> JavaScript cheatsheet: Fixed typo

- lib/DDG/Goodie/Unicode.pm
- lib/DDG/Goodie/UnicodeFuzzySearch.pm
- t/Unicode.t
- t/UnicodeFuzzySearch.t
Added utf-8, utf-16, utf-32 triggers, as suggested on Twitter:
https://twitter.com/CogDisNoi/status/675135769095315456
-----
IA Page: https://duck.co/ia/view/unicode_fuzzy_search
> Unicode: Added UTF triggers

- share/goodie/cheat_sheets/json/default-port-numbers.json
This instant answer shows the default port numbers that are used in computer networks
https://en.wikipedia.org/wiki/List_of_TCP_and_UDP_port_numbers
I chose this data source because of its authenticity.
Yes, there are other data sources as well but the information is scattered. You have to lookup different websites. Wikipedia provides consolidated information.
Developers, Computer Programmers, Computer Scientists
**Is this Instant Answer connected to a DuckDuckHack Instant …
> New Cheat Sheet for Default Port Numbers in Networks

- lib/DDG/Goodie/LaserShip.pm
- t/LaserShip.t
Fixes #1836. Updated regex to include anchors so it will not match on strings such as "1LS12345678999999" but will still match on "LS12345678"
> Fix #1836 Regex trigger needs anchors to limit triggering

- share/goodie/cheat_sheets/json/firefox.json
added alias to firefox.json as it is not triggering on the query:
https://duckduckgo.com/?q=mozilla+firefox+cheatsheet
> added alias to firefox.json

- share/goodie/cheat_sheets/json/http-status-codes.json
Changed the value for the status code 202 and codes 500 to 599.
It appears like a lot of the 5XX codes were copied incorrectly from 4XX codes.
Sources are from the following URL's.
http://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html
https://en.wikipedia.org/wiki/List_of_HTTP_status_codes
> HTTP Status Codes: Fixed values for multiple codes.

- lib/DDG/Goodie/Unicode.pm
- t/Unicode.t
Eventually we may have a dedicated emoji IA with better UI but for now this should help people find emojis faster.
Suggested on Twitter: https://twitter.com/sthmcleod/status/679319872980037632
-----
IA Page: https://duck.co/ia/view/unicode
> Unicode: Added 'emoji' trigger word

- lib/DDG/Goodie/URLDecode.pm
- lib/DDG/Goodie/URLEncode.pm
- t/URLDecode.t
- t/URLEncode.t
IA for URLEncode was not handling UTF8 correctly, so round-trip values for URLEncode/URLDecode didn't match. Changed from `en|decodeURIComponent` to `uri_(un)escape` to handle unicode characters. `URI::Escape::XS::uri_escape` expects a byte string, so downgrade the string before encoding.
Tests are comparing HTML entities rather than raw utf8 characters since IA isn't using templated answers. 
IA Page: https://duck.co/ia/view/urlencode
> URLEncode: Fixes #1932

- lib/DDG/Goodie/EmToPx.pm
- t/EmToPx.t
- Converted to 'text' template.
- Improves regular expression matching.
- Fixes some bugs with font-size not being recognized.
- Adds some more tests (I ran some conversions on an existing site).
- Rounds results to 3dp
---
[IA Page](https://duck.co/ia/view/em_to_px)
> EmToPx: Convert to template + improvements

- share/goodie/cheat_sheets/json/language/malayalam.json
[According to Wikipedia](https://en.wikipedia.org/wiki/Malayalam), Malayalam is sometimes referred to as Kairali so added that as a trigger.
> Added 'kairali' trigger word

- share/goodie/cheat_sheets/json/intel-8085.json
- share/goodie/cheat_sheets/json/intel-8086.json
Instant Answer ID's cannot start with numbers as it causes problems.
These are the only two IAs with ID's that start with numbers, so I've opted to change their id's, and add in aliases to ensure they still trigger as before.
/cc @jagtalon 
-----
IA Page: https://duck.co/ia/view/intel_8085_cheat_sheet
IA Page: https://duck.co/ia/view/intel_8086_cheat_sheet
> 8086/8085 Cheat Sheet: Append 'intel' to 8085, 8086.json, update accordingly

- share/goodie/cheat_sheets/json/apt-get.json
Add `apt-get` and `aptget` to aliases for the apt-get cheatsheet.
-----
IA Page: https://duck.co/ia/view/apt_get_cheat_sheet
> Apt-get: Add aliases

- template/lib/DDG/Goodie/Example.pm
- template/lib/DDG/Goodie/Minimal.pm
- template/templates.yml
Add a new template group with a javascript file in the configuration.  Also added a semi-modified Perl module template that puts the query remainder directly in the data, i.e. the processing will be done in the js.
See if this makes sense or if we just want to have people roll through the optional templates and select js to do the same thing.
> A javascript-focused template group

- lib/DDG/Goodie/Conversions.pm
- share/goodie/conversions/ratios.yml
- t/Conversions.t
Hello Everyone.
We've been discussing for a while what we want to do around unit conversion. I've been evaluating a number of API's and npm modules as @moollaza knows. I've not found any which cover the same breadth of units that we do currently and that are easily extensible for us to add more later. I feel that given the profile of this IA, it's important for us to be able to customise, fix and maintain it quickly and easily.
I was in conversation with @GuiltyDolphin about what we can do for the future of both Calculator and Conversions. It seems like a natural progression would be to be able to handle queries such as `33 inches + 5 cm in yards`. Extending the grammar for the calculator in https://github.com/duckduckgo/zeroclickinfo-goodies/pull/1927 for units should be relatively …
> Conversions: "Convert The Future Into The Present"

- CONTRIBUTING.md
I think CONTRIBUTING.md must contain pull request naming conventions.It will help new contributors to chose the correct title for their PR. as you can see in the screenshot below, the link to readme.md is displayed on GitHub while opening a new PR.
> CONTRIBUTING.md must contain pull request naming conventions

- share/goodie/cheat_sheets/json/markdown.json
The spaces change the behaviour, e.g. formatting as a list item instead of emphasis.
---
https://duck.co/ia/view/markdown_cheat_sheet
> Markdown cheat sheet: Removed spaces from Emphasis section

- share/goodie/cheat_sheets/json/adobe-brackets.json
added proper description to this cheat sheet and modified the way cheat sheet was displayed.
before - 
after - 
https://duck.co/ia/view/adobe_brackets_cheat_sheet
> Modified adobe-brackets cheat sheet

- lib/DDG/Goodie/Base.pm
- lib/DDG/Goodie/Conversions.pm
- lib/DDG/Goodie/PrimeFactors.pm
- lib/DDG/Goodie/SumOfNaturalNumbers.pm
`is_cached` gets converted to a BigInt with the pragmas declared in their current spots.  This can cause problems during deep tests.
> Put 'use big*' after is_cached

- share/goodie/cheat_sheets/json/ruby-globals.json
Displays a list of [Ruby](https://www.ruby-lang.org/en/)'s global variables and constants in response to cheat sheet searches like *ruby globals*, *ruby global constants*, *ruby global variables*.
The list items are copied verbatim from the [Ruby source][] at [doc/globals.rdoc][].  This document is rendered at http://docs.ruby-lang.org/en/trunk/globals_rdoc.html, which I've used as the answer `sourceUrl` as it is more readable than the raw rdoc markup.
The source lists variables and constants.  I added sections to break the list of variables up; without the addition of a **Long Variables** section there is a lot of whitespace to the right of the one- and two-character …
> Add Ruby Globals cheat sheet

- lib/DDG/Goodie/Zodiac.pm
- share/goodie/zodiac/dates.json
- t/Zodiac.t
Removes the `DateTime::Event::Zodiac` dependency.
See discussion on #2009 (although fixing this in a future PR may be wise).
---
[IA Page](https://duck.co/ia/view/zodiac)
> Zodiac - Remove DateTime::Event::Zodiac Dependency

- share/goodie/cheat_sheets/json/intel-8085.json
Corrected mistakes in 8085 cheat sheets like spaces problem and sections order
before -
after - 
https://duck.co/ia/view/intel_8085_cheat_sheet
> corrected intel-8085 cheat sheet

- share/goodie/cheat_sheets/json/firefox.json
According to [the official Firefox website](https://support.mozilla.org/en-US/kb/keyboard-shortcuts-perform-firefox-tasks-quickly).
IA page: https://duck.co/ia/view/firefox_cheat_sheet
> Firefox Cheat Sheet: Change shortcuts and adjust descriptions

- t/Base.t
- t/Conversions.t
- t/PrimeFactors.t
- t/SumOfNaturalNumbers.t
Instant answers using the `bignum/int pragmas` are auto-promoting other integer values, e.g. `is_cached`, to `BigInt`.   This causes problems when using `Test::Deep` and not including the same pragmas in the tests.  This is one way of fixing it.
> Use the same bignum/int pragmas in the tests for Test::Deep

- lib/DDG/Goodie/SunInfo.pm
- share/goodie/sun_info/content.handlebars
- share/goodie/sun_info/sun_info.css
- share/goodie/sun_info/title.handlebars
Result: 
The text template has a div at the bottom with extra margin that will be removed. It's a placeholder for the more at link which isn't present
> SunInfo: bring back some CSS, minor visual tweaks

- lib/DDG/Goodie/Regexp.pm
- share/goodie/regexp/regexp.css
- t/Regexp.t
Which of these do you prefer?
**OR**
Yeah, I thought so. The first one is clearly superior ;)
---
[IA Page](https://duck.co/ia/view/regexp)
> Regexp: Improvements!

- lib/DDG/Goodie/Regexp.pm
- t/Regexp.t
Need to HTML escape *everything* to prevent SERP breakage right now.
This updated the code + tests.
/cc @GuiltyDolphin
> Rexep: Ensure HTML chars are escaped

- t/Regexp.t
It's throwing warning on production machines about an uninitialized regex
/cc @jdorweiler @GuiltyDolphin
> Regex: Remove last test temporarily

- dist.ini
Use new dzil plugin to update our tag message on release.
> Use Git::Tag::IAChangelog in dist.ini

- share/goodie/cheat_sheets/json/gnome.json
Noticed when testing today that the gnome cheat sheet doesn't have a `template_type`.
> Add template_type to gnome cheat sheet

- share/goodie/cheat_sheets/json/gta-vice-city.json
- share/goodie/cheat_sheets/json/kerbal-space-program.json
Some cheat sheets were missing a template type @moollaza.
> Add missing 'template_type' to cheat sheets

- share/goodie/cheat_sheets/json/kubernetes.json
**What I did ?**
1. There were $ signs in the cheat sheet. As cheat sheet template_type is already terminal then there is no need to put $ sign.
2. There were extra spaces after the explanations of values.
3. The the json file was not formatted correctly i.e., the brackets were not arranged properly.
https://duck.co/ia/view/kubernetes_cheat_sheet
> Kubernetes : Removed $ signs and spaces

- lib/DDG/Goodie/Regexp.pm
- t/Regexp.t
@moollaza Some other IAs trigger on the obscure regex queries!
See https://duckduckgo.com/?q=hello+%3D~+%2Fhello%2F&t=ffab
> Regexp: Set signal to high

- share/goodie/cheat_sheets/json/html.json
#HTML cheat sheet
1. Fixed display format
2. Removed extra spaces
Fixes #2216 
https://duck.co/ia/view/html_cheat_sheet
> HTML cheat sheet: Fixed display format

- lib/DDG/Goodie/Minecraft.pm
- t/Minecraft.t
Logic for triggers and recipe lookup has changed. Loop through all recipe names looking for exact match in query string; then remove all 'extra' words allowed in query. Continue if no remaining words in query.
Added a couple of 'negative' trigger tests; all existing tests still pass.
Fixes #1949 
IA Page: http://duck.co/ia/view/minecraft
> Minecraft: Fixes #1949

- share/goodie/cheat_sheets/json/perforce-workshop.json
/cc @lizlam 
-----
IA Page: https://duck.co/ia/view/perforce_workshop_cheat_sheet
> Remove Perforce and perforce open source triggers, they belong to perforce_cheat_sheet

- lib/DDG/Goodie/ABC.pm
- t/ABC.t
Lo,
This one's still using the structured answer so I've converted it to the full template.
There are some slight issues with the tests here, the existing `-ANY-` mechanism doesn't work too well for this, as ideally all components of the `structured_answer` would be asserted and then only the random component could be asserted against a regex (something like : https://github.com/duckduckgo/zeroclickinfo-goodies/commit/4ef7c85ce66f15bb62cfdf474bc029a029818b30) 
https://duck.co/ia/view/abc
> Switching ABC to text template

- share/goodie/cheat_sheets/json/apple-mac-os.json
This PR removes redundant keyboard shortcut.
IA Page: https://duck.co/ia/view/apple_mac_os_cheat_sheet
> MacOS cheat sheet: Remove redundant keyboard shortcut

- share/goodie/cheat_sheets/json/mozilla-thunderbird.json
#2317 - removed the command symbol
#2266 - for reference
> Fixes #2317 - Mozilla Thunderbird Cheat Sheet : A Command Symbol shown

- lib/DDG/Goodie/PigLatin.pm
- t/PigLatin.t
Updates the [PigLatin IA](https://duck.co/ia/view/pig_latin) to using the `text` text answer template.
Also Fixes #1969 with a simple trigger check.
-----
IA Page: https://duck.co/ia/view/pig_latin
> PigLatin: Update to use templates

- t/Base.t
- t/Conversions.t
- t/PrimeNumber.t
- t/SumOfNaturalNumbers.t
Preparing for https://github.com/duckduckgo/duckduckgo/pull/172
Once that is installed these tests fail and these changes get them to pass again.
/cc @zachthompson @GuiltyDolphin @mintsoft
> Goodie Tests: Remove `bignum` from tests, no need to cast is_cached to bignum anymore

- share/goodie/cheat_sheets/json/css.json
This PR adds import syntax to cheat sheet.
IA Page : https://duck.co/ia/view/css_cheat_sheet
> CSS cheat sheet: Add import syntax

- share/goodie/cheat_sheets/json/asciidoc.json
Following a Twitter comment and checking in the [Asciidoc user guide](http://asciidoc.org/userguide.html#X46), this looks like better syntax.
---
IA Page: https://duck.co/ia/view/asciidoc_cheat_sheet
> Asciidoc cheatsheet: Changed emphasis syntax

- lib/DDG/Goodie/SecurityAddons.pm
Following a [request on Twitter](https://twitter.com/arosecantrust/status/699594590379237376) I added Vivaldi do the list. It uses the same extensions as Chrome so adding it as "Google Chrome / Vivaldi" is also an option, but it wraps to the next line and looks ugly.
> Security addons: Added Vivaldi to browser list

- share/goodie/cheat_sheets/json/linux.json
Linux cheatsheet: corrected background & stop command shortcut.
Linux cheat sheet IA page: https://duck.co/ia/view/linux_cheat_sheet
> Linux cheatsheet: corrected background & stop command shortcut

- share/goodie/calendar_conversion/calendars.yml
Calendar conversion: Corrected spelling of February
IA Page: https://duck.co/ia/view/calendar_conversion
> Calendar conversion: Corrected spelling of February

- t/Conversions.t
Currently on production this answer is wrong:
On my older version of `Math::BigFloat` it had the same behaviour, however updating the dependency fixes it. It's probably worth having these tests in anyway
> Conversions: Tests for weird 999 problem

- share/goodie/cheat_sheets/json/boolean-algebra.json
Fixed typos and removed extra lines in boolean algebra cheat sheet.
IA Page: https://duck.co/ia/view/boolean_algebra_cheat_sheet
> Boolean Algebra cheat sheet : Fixed typos and removed extra lines

- share/goodie/cheat_sheets/json/currency.json
Added currency of Brunei and Azerbaijan to Currency cheatsheet.
IA Page: https://duck.co/ia/view/currency_cheat_sheet
> Currency Cheatsheet: Added currency of Brunei and Azerbaijan

- share/goodie/cheat_sheets/json/asciidoc.json
This is to reflect the current Asciidoc syntax, as detailed here: https://github.com/asciidoctor/asciidoctor.org/blob/master/docs/_includes/sections.adoc#titles-as-html-headings
Credit to [Twitter](https://twitter.com/epragt/status/700106790462029824) [commenters](https://twitter.com/mojavelinux/status/700594937205641217).
---
IA Page: https://duck.co/ia/view/asciidoc_cheat_sheet
> Asciidoc cheatsheet: Changed heading syntax

- share/goodie/cheat_sheets/json/atom.json
Corrected typos and removed extra lines to Atom cheat sheet
IA Page: https://duck.co/ia/view/atom_cheat_sheet
> Atom cheat sheet: Corrected typos and removed extra lines

- share/goodie/cheat_sheets/json/jira.json
Corrected the keyboard shortcut for Submit Form and removed unnecessary space at one place.
Jira cheat sheet IA page: https://duck.co/ia/view/jira_cheat_sheet
> Jira cheat sheet: Corrected shortcut for submit form

- share/goodie/cheat_sheets/json/unix-time-format.json
Corrected one key in Time zone section in unix time format cheat sheet.
IA Page: https://duck.co/ia/view/unix_time_format_cheat_sheet
> Unix time format cheat sheet: Corrected one key in Time zone section

- share/goodie/cheat_sheets/json/bbcode.json
Corrected command for making text bold in BBCode cheat sheet.
IA Page: https://duck.co/ia/view/bbcode_cheat_sheet
> BBCode cheat sheet: Corrected command for making text bold

- share/goodie/cheat_sheets/json/bible-books.json
Fixed typos in Bible books cheat sheet.
IA Page: https://duck.co/ia/view/bible_books_cheat_sheet
> Bible books: Fixed typos

- share/goodie/cheat_sheets/json/http-status-codes.json
This PR fixes https://github.com/duckduckgo/zeroclickinfo-goodies/issues/2482
IA Page: [https://duck.co/ia/view/http_status_codes_cheat_sheet](https://duck.co/ia/view/http_status_codes_cheat_sheet)
> HTTP Status Codes: fix typo in cheat sheet

- share/goodie/cheat_sheets/json/mozilla-thunderbird.json
Added new shortcuts, corrected shortcut for:
-Undo
-Get new messages for current account
-Get new messages for all account 
and improved formatting by removing extra space and unused lines in Mozilla Thunderbird cheat sheet.
IA Page: https://duck.co/ia/view/mozilla_thunderbird_cheat_sheet
> Mozilla Thunderbird: Added new shortcuts, corrected some wrong shortcuts and improved formatting

- share/goodie/cheat_sheets/json/c-string-formatting.json
Added two more specifiers to c string formatting cheat sheet.
IA Page: https://duck.co/ia/view/c_string_formatting_cheat_sheet
> C string formatting cheat sheet: Added two more specifiers

- share/goodie/cheat_sheets/json/viml.json
Switching to `terminal` template to better handle long `key` strings
IA Page: https://duck.co/ia/view/viml_cheat_sheet
> Viml Cheat Sheet: switch to terminal template

- share/goodie/cheat_sheets/json/saints-row.json
Added two sections Silverlink and DLC to Saints Row Cheat sheet
IA Page: https://duck.co/ia/view/saints_row_cheat_sheet
> Saints Row Cheat sheet: Added two sections Silverlink and DLC

- share/goodie/cheat_sheets/json/sublime-text-mac.json
Sublime Text Mac Cheat sheet: Corrected one keyboard shortcut and removed unnecessary and redundant things.
IA Page: https://duck.co/ia/view/sublime_text_mac_cheat_sheet
> Sublime Text Mac Cheat sheet: Corrected one keyboard shortcut

- share/goodie/cheat_sheets/json/safari.json
Added new section Page Management to Safari cheat sheet with some keyboard shortcuts.
IA Page: https://duck.co/ia/view/safari_cheat_sheet
> Safari cheat sheet: Added new section Page Management with some shortcuts

- share/goodie/cheat_sheets/json/es6.json
This allows the page to automatically redirect for the user's locale.
Suggested by an [eagle-eyed user on Twitter](https://twitter.com/Sphinx_Twitt/status/702029361348743168).
> ES6 cheatsheet: Removed en-US in source URL

- share/goodie/cheat_sheets/json/intel-8086.json
Intel 8086: Added more instructions and corrected typos.
IA Page: https://duck.co/ia/view/intel_8086_cheat_sheet
> Intel 8086: Added more instructions and corrected typos.

- lib/DDG/Goodie/CaesarCipher.pm
- share/goodie/caesar_cipher/content.handlebars
- share/goodie/caesar_cipher/description.txt
- t/CaesarCipher.t
I was looking at related queries for `caesar cipher`:
And it turns out people want to know how to decrypt it!
So I've added a new response for queries like `caesar cipher decoder`:
Which gives an overview of the cipher as well as some example triggers:
---
[IA Page](https://duck.co/ia/view/caesar_cipher)
> CaesarCipher: Add 'How to decode?' response

- share/goodie/cheat_sheets/json/penn-treebank-pos-tags.json
- share/goodie/cheat_sheets/json/penn-treebank.json
This is the cheat sheet for the Penn Treebank tag set cheat sheet. The full details of the PR can be viewed here:
https://duck.co/ia/view/penn_treebank_cheat_sheet
Part of Speech (POS) Tagging is a common preprocessing technique in Natural Language Processing and Text Mining Systems / Research. Often there is quite a lot of confusion as to what these tags actually mean. One well established and popular tag set is the Penn Treebank tag set. This cheat sheet aims to give a brief overview of their meaning.
http://web.mit.edu/6.863/www/PennTreebankTags.html
Penn Treebank tags treebank tags pos tags part of speech tags meaning
> New Penn Treebank Tagset Cheat Sheet

- share/goodie/cheat_sheets/json/chrome.json
- share/goodie/cheat_sheets/json/common-escape-sequences.json
- share/goodie/cheat_sheets/json/drush.json
- share/goodie/cheat_sheets/json/duckduckgo.json
- share/goodie/cheat_sheets/json/game-of-life.json
- share/goodie/cheat_sheets/json/jira.json
- share/goodie/cheat_sheets/json/language/arabic.json
- share/goodie/cheat_sheets/json/language/armenian.json
- share/goodie/cheat_sheets/json/language/assamese.json
- share/goodie/cheat_sheets/json/language/bengali.json
- share/goodie/cheat_sheets/json/language/bulgarian.json
- share/goodie/cheat_sheets/json/language/cantonese.json
- share/goodie/cheat_sheets/json/language/czech.json
- share/goodie/cheat_sheets/json/language/dutch.json
- share/goodie/cheat_sheets/json/language/french.json
- share/goodie/cheat_sheets/json/language/german.json
- share/goodie/cheat_sheets/json/language/hindi.json
- share/goodie/cheat_sheets/json/language/kannada.json
- share/goodie/cheat_sheets/json/language/malayalam.json
- share/goodie/cheat_sheets/json/language/marathi.json
- share/goodie/cheat_sheets/json/language/minionese.json
- share/goodie/cheat_sheets/json/language/polish.json
- share/goodie/cheat_sheets/json/language/portuguese.json
- share/goodie/cheat_sheets/json/language/slovak.json
- share/goodie/cheat_sheets/json/language/tamil.json
- share/goodie/cheat_sheets/json/mainframe.json
- share/goodie/cheat_sheets/json/openstack.json
This removes a bunch of invalid, incorrect, redundant etc... aliases.
As @mintsoft points out, some of the triggers thrown away will reduce functionality until #2170 is merged, so we might want to wait for that.
> Remove redundant and/or irrelevant aliases from cheat sheets

- share/goodie/cheat_sheets/cheat_sheets.js
This PR adds support for `\n` and `\t` to cheat sheets.
Fixes https://github.com/duckduckgo/zeroclickinfo-goodies/issues/2097
Java Cheat sheet after this fix:
> Improve Cheat Sheet Rendering: Add support for new line and tab

- t/CheatSheets/CheatSheetsJSON.t
@moollaza I've added in the reverse check to make sure weird cases don't make it through.
/cc @zachthompson 
Fixes #2685.
Adds some new tests:
* ***Critical*** if a trigger is specified that is already in use.
* ***Critical*** if a category is specified that is already assigned via the `template_type`.
* ***Critical*** if a `template_type` is used that is not present in the `template_map`.
---
IA Page: https://duck.co/ia/view/cheat_sheets
> CheatSheets: Improve file name ID check

- lib/DDG/Goodie/TimezoneConverter.pm
- t/TimezoneConverter.t
Fixes #2697
https://duck.co/ia/view/timezone_converter
> Fixes #2697: 12:00 now parsed as Noon if am not specified

- lib/DDG/Goodie/UltimateAnswer.pm
- t/UltimateAnswer.t
Thought it might be nice to expand the query space a bit. I didn't realize this goodie existed at first because I couldn't get it to trigger.
If you type in 'answer to' in DDG, the second suggestion is currently 'answer to life the universe and everything'.
And if you type this query into Google, it will output 42 as the answer. So I think it makes sense that the query should also trigger this goodie in DDG.
IA: https://duck.co/ia/view/ultimate_answer
> UltimateAnswer: Expand query space

- share/goodie/cheat_sheets/json/duckduckgo-syntax.json
- share/goodie/cheat_sheets/json/sql.json
- share/goodie/cheat_sheets/triggers.yaml
- t/CheatSheets/CheatSheetsJSON.t
@zachthompson These ensure the aliases don't contain triggers (prevents aliases like `X cheat sheet`, `X shortcuts` etc...).
* ***Critical*** if an alias contains a trigger defined by a category that is assigned.
* ***Warning*** if an alias contains a trigger defined by a category that is not assigned.
* ***Critical*** if an alias contains a custom trigger.
These check trigger positions (`start`, `startend` etc...).
---
IA Page: https://duck.co/ia/view/cheat_sheets
> CheatSheets: Add alias trigger tests

- share/goodie/cheat_sheets/json/tar.json
Fix duplicate `the`.
------
IA Page:  https://duck.co/ia/view/tar_cheat_sheet
> Tar Cheat Sheet: Fix typo

- share/goodie/cheat_sheets/json/golang.json
Fix duplicate `the`.
------
IA Page:  https://duck.co/ia/view/golang_cheat_sheet
> Golang Cheat Sheet: Fix typo

- lib/DDG/Goodie/Dice.pm
- t/Dice.t
fixes #1255
I didn't include the part about converting "two" into 2, as I wouldn't know where to stop (one, two, three, ten, twenty???)
> support "dices" spelling for dice trigger

- share/goodie/cheat_sheets/json/nltk.json
Adding Python [NLTK (Natural Language Processing Toolkit) Cheat sheet](https://duck.co/ia/view/nltk_cheat_sheet). The NLTK is a popular Python text mining API which is described in the following book & paper.
**Book**
> Bird, Steven, Edward Loper and Ewan Klein (2009), Natural Language Processing with Python. O’Reilly Media Inc.
**Paper**
> Bird, Steven. "NLTK: the natural language toolkit." Proceedings of the COLING/ACL on Interactive presentation sessions. Association for Computational Linguistics, 2006.
The Cheat Sheet page is: https://duck.co/ia/view/nltk_cheat_sheet
**Screenshot 1 (Dark Theme) - Collapsed**
https://duck.co/ia/view/nltk_cheat_sheet
> New NLTK Cheat Sheet

- share/goodie/conversions/content.handlebars
@GuiltyDolphin I can't really test it from here as I can't get to my instance of `duckpan server`; however this should resolve the HTML issue (https://github.com/duckduckgo/zeroclickinfo-goodies/pull/2044#issuecomment-194817807).
cc @moollaza 
----------
IA Page: http://duck.co/ia/view/conversions
> Conversions: Using unescaped HTML handlebars

- lib/DDG/Goodie/SubnetCalc.pm
- t/SubnetCalc.t
This has the wrong id; which is why the graph is empty on duck.co!
------------
IA Page: https://duck.co/ia/view/subnet_calc
> SubnetCalc: Fixing the id

- share/goodie/cheat_sheets/json/i3.json
The URL in i3.json is 404ing, so I replaced it with a working link.
To see the 404ing link in action, [search for "i3 cheatsheet"](https://duckduckgo.com/?q=i3+cheatsheet&t=ffsb&ia=cheatsheet) and click on the ["More at i3wm"](https://i3wm.org/docs/refcard.pdf) link.
---
IA Page: https://duck.co/ia/view/i3_cheat_sheet
Maintainer: @goromlagche
> add working link to i3wm cheatsheet

- t/CheatSheets/CheatSheetsJSON.t
@zachthompson As promised! This improves the general phrasing of the tests as well as improve the way the tests are reported. There's a bit more info in my commit messages, but you can easily see the new structure through the Travis log.
* Improves phrasing of existing tests
* Improves structure of test reports
* Fixes an issue wherein cheat sheets within directories under `json/` were not being tested
* Allows multiple cheat sheets to be tested via arguments
---
https://duck.co/ia/view/cheat_sheets
> CheatSheets: Improve test phrasing and reports

- lib/DDG/Goodie/Bin2Unicode.pm
- t/Bin2Unicode.t
For a single control character request in binary, tell user what it is (can't see it).  Otherwise, don't return answer.
Hopefully fixes https://github.com/duckduckgo/zeroclickinfo-goodies/issues/2783
IA Page: https://duck.co/ia/view/bin2unicode
> Control characters in bin2unicode

- lib/DDG/Goodie/PrimeFactors.pm
- t/PrimeFactors.t
Cleaning up PrimeFactors IA in preparation for https://github.com/duckduckgo/duckduckgo/pull/172
We no longer need to cast `is_cached` as a `bignum`.
https://duck.co/ia/view/prime_factors
> Remove bignum from is_cached in PrimeFactors.t

- lib/DDG/Goodie/Conversions.pm
- share/goodie/conversions/ratios.yml
- t/Conversions.t
Currently the supported units are:
* m/s
* ft/s
* mph
* km/h
* knots
Will hopefully fix: https://github.com/duckduckgo/zeroclickinfo-goodies/issues/2729
and partially address: https://github.com/duckduckgo/zeroclickinfo-goodies/issues/689
Suggestions for new units welcome, however I don't want to go too berzerk on this as the number of combinations is huge and I'd rather solve it for everything.
cc @duckduckgo/community-leaders @moollaza @tagawa 
--------
https://duck.co/ia/view/conversions
> Conversions: now supports speed!

- lib/DDG/Goodie/URLDecode.pm
- lib/DDG/Goodie/URLEncode.pm
- t/URLDecode.t
- t/URLEncode.t
Reported on IRC: These are breaking in production: 
https://duckduckgo.com/?q=url+decode+https%253A%252F%252Fduckduckgo.com%252F%3C%2Fscript%3E%3E
/cc @cngarrison @zachthompson 
---
/https://duck.co/ia/view/urldecode
Maintainer: @mintsoft 
/https://duck.co/ia/view/urlencode
Maintainer: @nishanths
> Fix Potential XSS: HTML Encode title/subtile for URLEncode and URLDecode

- template/lib/DDG/Goodie/Example.pm
- template/lib/DDG/Goodie/Minimal.pm
- template/share/goodie/example/example.js
- template/t/Example.t
@zachthompson @moollaza I've removed the ID and name attributes from the structured answers in the templates.
I have also (you may disagree with this) added a template for building the structured answer response in tests. Seeing as we are removing 'simple' structured answers I feel this is appropriate as it will reduce the visual load of having many structured answer definitions. Additionally it should make it easier to move to a new testing system if desirable in the future.
> Remove ID and name from templates

- share/goodie/cheat_sheets/json/asciicode.json
@moollaza this cheatsheet fails the tests, and for some reason they didn't run on the PR!
It's missing the numbers section; so I've added it where I think it should go
---------------
IA Page: https://duck.co/ia/view/ascii_code_cheat_sheet
> AsciiCodeCheatSheet: Adding Numbers so the tests pass

- lib/DDG/Goodie/Constants.pm
Yet another example when linguist has screwed up the language detection ¬_¬
Ref: https://github.com/github/linguist/issues/2149
------------------
IA Page: https://duck.co/ia/view/constants
> Constants: Adding use strict to force Perl 5 detection

- share/goodie/cheat_sheets/json/aws-lambda.json
- share/goodie/cheat_sheets/json/wunderlist-mac.json
I merged a couple PRs that didn't appear to be in a failing state, turns out they were :frowning: 
This fixes them!
- Corrected Wunderlist Mac ID
- Removed overlapping alias from AWS Lamba
https://duck.co/ia/view/wunderlist_mac_cheat_sheet
https://duck.co/ia/view/aws_lambda_cheat_sheet
> Cheatsheet Fixes

- share/goodie/cheat_sheets/json/slack-mac.json
- share/goodie/cheat_sheets/json/slack.json
New Slack Cheat Sheet containing keyboard shortcuts for Mac.
IA Page: https://duck.co/ia/view/slack_mac_cheat_sheet
> New Slack Mac Cheat Sheet

- share/goodie/cheat_sheets/json/arduino.json
Fixed casing typo in section_order
https://duck.co/ia/view/arduino_cheat_sheet
> Fix casing in Section Order

- share/goodie/cheat_sheets/json/django-model.json
The essential fields types and relationships of the data being stored when working with the Django Object Relational Mapper (ORM).
https://docs.djangoproject.com/en/1.9/topics/db/models/
django models cheat sheet
https://duck.co/ia/view/django_model_cheat_sheet
> New Django Model Cheat Sheet

- share/goodie/cheat_sheets/json/elixir.json
This PR fix a small typo in the Elixir Cheat Sheet.
-----
IA Page:  https://duck.co/ia/view/elixir_cheat_sheet 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @pjhampton
> Elixir Cheat Sheet: Fix typo

- share/goodie/cheat_sheets/json/multisim.json
- share/goodie/cheat_sheets/triggers.yaml
@zachthompson This adds the necessary triggering for the cheat sheets over on duckduckgo/duckduckhack-docs#52.
Any templates using the `reference` category can now trigger with `help` - that is: `code`, `keyboard`, and `reference`.
Fixes #2831
/cc @Spagy @talsraviv 
---
IA Page: https://duck.co/ia/view/cheat_sheets
Maintainer: @zachthompson
> CheatSheets: Add 'help' trigger to 'reference' category

- share/goodie/cheat_sheets/json/microsoft-windows-ten.json
Fix duplicate `the`.
------
IA Page:  http://duck.co/ia/view/microsoft_windows_ten_cheat_sheet
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @ghostpirate
> Windows 10 Cheat Sheet: Fix typo

- lib/DDG/Goodie/Constants.pm
- t/Constants.t
Setting the signal to `high` so that its display takes priority over the Wikipedia info box.
(Requested in the [Django subreddit](https://www.reddit.com/r/django/comments/4gpkh1/help_improve_duckduckgos_djangorelated_searches/d2juky0))
---
https://duck.co/ia/view/constants
> Constants: Increased display priority

- lib/DDG/Goodie/ConvertLatLon.pm
- t/ConvertLatLon.t
Fixes #2920: replace Unicode minus sign with a hyphen when displaying negative latitudes or longitudes, to allow easier copy pasting to mapping services.
[https://duck.co/ia/view/convert_lat_lon](https://duck.co/ia/view/convert_lat_lon)
> ConvertLatLon: Replace minus sign with hyphen (#2920)

- share/goodie/cheat_sheets/json/scala.json
Fixes #2944
---
Fixed typo where the file type was mentioned as java instead of scala.
Instant Answer Page: https://duck.co/ia/view/scala_cheat_sheet
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @amitdev
> Bug fix: scala_cheat_sheet: Fix #2944

- share/goodie/conversions/ratios.yml
Adds `°` degree symbol for Celsius and Fahrenheit.
Fixes #2950
@mintsoft 
@edgesince84 
---
> Conversions: Add degree symbol alias for celcius and fahrenheit (fixes #2950)

- t/CheatSheets/CheatSheets.t
Updated the cheat sheet tests (not the JSON ones) to only check ID rather than *all* data. For me the tests have gone from 15 seconds before the change to 2 seconds after.
None
@zachthompson 
---
Instant Answer Page: https://duck.co/ia/view/cheat_sheets
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @zachthompson
> CheatSheets: Have tests only check ID rather than all data

- share/goodie/cheat_sheets/json/redhat.json
Look at the official site, they seem to be called "Red Hat" (with a space).
Also added the aliases as this cheat sheet is specifically about yum.
---
https://duck.co/ia/view/redhat_cheat_sheet
Maintainer: @ankushg07
> Red Hat cheatsheet: Added aliases and naming consistency

- share/goodie/cheat_sheets/json/swift.json
Fix for loop syntax for Swift 2.2. The syntax used currently is deprecated and will be removed in Swift 3.
---
Instant Answer Page: https://duck.co/ia/view/swift_cheat_sheet
> Swift Cheat Sheet: Fix #2803 Deprecated syntax in Swift cheatsheet

- share/goodie/cheat_sheets/json/language/italian.json
- share/goodie/cheat_sheets/json/perl.json
---
Fix wrong spelling of vegetarian.
Instant Answer Page: https://duck.co/ia/view/italian_cheat_sheet
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @marcostudios
> Italian cheatsheet fix

- share/goodie/cheat_sheets/json/git.json
**`Short Description`**
Debugging section has been added and modified stash section to add new stash sub commands.
The debugging subcommands are useful to daily programmer and comes handy for a day-to-day debugging process. It would be a good idea to include it in cheatsheet. Git stash subcommands are also required for a daily programming needs. It is useful to include widely used stash subcommands.
git cheatsheet JSON file modified
---
The …
> Add debugging section and modify stash section

- share/goodie/conversions/ratios.yml
Adds tablespoons and teaspoons — both US and Metric — to `ratios.yml`
Fixes https://github.com/duckduckgo/zeroclickinfo-goodies/issues/3008
---
> Conversions: Added tablespoons and teaspoons

- share/goodie/cheat_sheets/json/perl.json
**`perl cheatsheet: Fix shift() syntax #2945 `**
---
Instant Answer Page: https://duck.co/ia/view/perl_cheat_sheet
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @pratik-nagelia
> remove improper use of shift when unpacking from @ARGV

- lib/DDG/Goodie/CheatSheets.pm
- share/goodie/cheat_sheets/triggers.yaml
- t/CheatSheets/CheatSheetsJSON.t
@zachthompson As discussed previously on #2170, this re-introduces the 'ignore' attribute.
I've gone over the purpose in some detail in he message for my first commit, but the TL;DR is they allow 'fluff' words that are ignored when triggering.
These are specified in the `triggers.yaml` file.
---
IA Page: https://duck.co/ia/view/cheat_sheets
Maintainer: @zachthompson
> CheatSheets: Add 'ignore' attribute

- lib/DDG/Goodie/Braille.pm
- t/Braille.t
Fixes: #2771. Use specified triggers to avoid bad triggers. Also add types to show the result is in Braille or ASCII/Unicode. Removed `html_enc()` for `structured_answer->input` since it will show raw braille code instead of braille string.
https://duck.co/ia/view/braille
> Braille: fix for bad triggers #2771

- t/CheatSheets/CheatSheetsJSON.t
Fixes #3016 - we now check the IA page exists.
@zachthompson @jdorweiler 
---
Instant Answer Page: https://duck.co/ia/view/cheat_sheets
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @zachthompson
> CheatSheets: Add check for IA page existence

- lib/DDG/Goodie/GreatestCommonFactor.pm
- t/GreatestCommonFactor.t
Removed custom GCD function and replaced it with `Math::BigInt::bgcd`, and changed to `text` template for view
Fixes #2985
Instant Answer Page: https://duck.co/ia/view/greatest_common_factor
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @austinheimark
> GreatestCommonFactor: Use Math::BigInt & change to text template

- lib/DDG/Goodie/FlipText.pm
- t/FlipText.t
Goodies have full support for templates, and it'd be great to make sure all
Goodies use full templates. The "simple structured_answer" was provided
as a way to get goodies using basic templates before they had full template
support.
* change to 'text' template for structured_answer object
* refactored test suite
* added alias and removed encode
See also: Updates FlipText Goodie Re: #2767
---
Instant Answer Page: https://duck.co/ia/view/flip_text
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @rpicard
> Convert simple structured to full template goodie

- share/goodie/cheat_sheets/json/erlang.json
Add f/1 to shell commands, right next to f/0, in Erlang Cheat Sheet
Fixes #2942 
IA Page: https://duck.co/ia/view/erlang_cheat_sheet
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @pjhampton
> Erlang cheat sheet: Add f/1 to shell commands

- t/WeekdaysBetween.t
Fix incorrect indentation of `structured_answer` in test file for WeekdaysBetween.
---
Instant Answer Page: https://duck.co/ia/view/weekdays_between
> WeekdaysBetween: Correct indentation for structured answer

- share/goodie/cheat_sheets/json/logarithms.json
Correct derivative notation for the calculus portion of the logarithms cheat sheet
Fixes #2929  - Change notation from `f'(g(x))` to `d(f(x))/dx` to minimize ambiguity
---
Instant Answer Page: https://duck.co/ia/view/logarithms_cheat_sheet
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @poornagurram
> Logarithms Cheat Sheet: Correct notation for the calculus portion

- share/goodie/cheat_sheets/json/intellij.json
- [*] Improvement
- [*] Enhancement: **`intellij cheat sheet: add alias "androidaStudio"`**
Add android studio as an alias to intellij.
---
Instant Answer Page: https://duck.co/ia/view/intellij_cheat_sheet
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @jamie23
> Intellij cheat sheet : add alias "Android Studio"

- lib/DDG/Goodie/Timediff.pm
- t/Timediff.t
I found myself looking through a variety of logs today and there's no IA for finding how long it is between two points in time, we have one for days etc but not timestamps accurate to the second. Hence this IA
-----------
https://duck.co/ia/view/timediff
> Timediff: Duration between two datetimes in a variety of units

- lib/DDG/Goodie/GreatestCommonFactor.pm
- t/GreatestCommonFactor.t
Don't trigger on single numbers
Fixes #3407 - I made it so that it outputs "Cannot compute Greatest common factor" if user only inputs one number. On the discussion, it said that it is not usually done that way, so I can change it if need be.
---
Instant Answer Page: https://duck.co/ia/view/greatest_common_factor
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html):  @austinheimark
> GreatestCommonFactor: Don't trigger on single numbers, Fix #3407

- lib/DDG/Goodie/Sort.pm
- t/Sort.t
The sort_goodie should not be triggered for single numbers (input)
query. This could be fixed by using a return statement check on handler.
* goodie not triggered for single number (input)
See also: #3144
---
Instant Answer Page: https://duck.co/ia/view/sort
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @koosha--
> sort: stop triggering for single input query on sort_goodie

- t/Timediff.t
@mintsoft There was a test using locale format without specifying a locale (causing it to break with #2810); I've just updated it to use a more sensible format.
@mintsoft 
---
Instant Answer Page: https://duck.co/ia/view/timediff
> Timediff: Replace locale-format test with ISO8601

- lib/DDG/Goodie/ReverseResistorColours.pm
- t/ReverseResistorColours.t
Currently, the goodie returns 10ohm for "brown black gold silver resistor", which is wrong, as this is the code for 1ohm.
* add gold and silver multipliers (x0.1 and x0.01)
* simplify the multiplier formula
* remove unused "mult" variable
@Mailkov
---
Instant Answer Page: https://duck.co/ia/view/reverse_resistor_colours
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @Mailkov 
Currently, the goodie returns 10ohm for "brown black gold silver resistor", which is wrong, as this is the code for 1ohm.
* add gold and silver multipliers (x0.1 and x0.01)
* simplify the multiplier formula
* remove unused "mult" variable
> ReverseResistorColours: Add x0.1 and x0.01 multipliers

- lib/DDG/Goodie/Constants.pm
- share/goodie/constants/content.handlebars
- share/goodie/constants/title_content.handlebars
- t/Constants.t
In Ref to: https://github.com/duckduckgo/zeroclickinfo-goodies/issues/2767 converting to a full template
This also fixes:
* That the text answer output was HTML;
* The HTML was being encoded so the answers looked terrible
---
Instant Answer Page: https://duck.co/ia/view/constants
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @hemanth
> Constants: Switching to template

- share/goodie/cheat_sheets/json/django-model.json
IA now has more triggers as mentioned in the issue and has template_type = `reference` which makes more sense in this case since more users will be looking for `Django model reference` rather than `Django model commands`. This is my opinion. I am seeking suggestions about this.
Fixes #2940 
---
Instant Answer Page: https://duck.co/ia/view/django_model_cheat_sheet
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): 
@pjhampton
> DjangoModelCheatSheet: Change template_type to reference, add more triggering aliases

- share/goodie/cheat_sheets/json/vim.json
As a vim user, registers make the life easier to get the daily
programming tasks done. Additional ex-commands cheat is also handy
as ex-editor is at the core of vim editor.
* added ex-commands section
* added registers section
---
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @NaveenKarippai
> vim_cheat_sheet: Add ex-commands and registers section

- lib/DDG/Goodie/Tips.pm
- t/Tips.t
- This IA can now trigger off of "tax"
- Conversion to a structured answer response
- Include subtotal to the response for a more immersive answer
- Instead of `percent of` in the percentage response, changed to `% of`
Fixes #1044 - Allow queries to have "tax" in them to trigger this
@mattlehning @moollaza @mattr555 @mintsoft 
---
Instant Answer Page: https://duck.co/ia/view/tips
> Tip IA: Trigger calculations off of 'tax' and some cleanup

- lib/DDG/Goodie/TimezoneConverter.pm
- t/TimezoneConverter.t
The Timezone Converter IA is not showing up on PROD. Had to change `text` to `group` in order for the `templates` block to be valid.
@GlitchMr @moollaza 
---
Instant Answer Page: https://duck.co/ia/view/timezone_converter
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @GlitchMr
> Timezone Converter IA: Templates type should be group

- share/goodie/cheat_sheets/json/vim.json
To improve debugging, we should be able to see across forest and
not just across trees. The folding of functions would help to achieve
the desired behaviour. The vim_cheatsheet should add a section of commands
associated with folding on vim.
* added section for folding commands
---
> vim_cheatsheet: Add `folding commands` section

- lib/DDG/Goodie/URLEncode.pm
- t/URLEncode.t
`uri` is now matched in the same way as `url` was. A few tests have been added. Let me know if you'd like the full test suite replicating.
Fixes #3201 by duplicating all existing triggers to match `uri`.
@nishanths, @tagawa 
---
Instant Answer Page: https://duck.co/ia/view/urlencode
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @nishanths
> URLEncode: enable triggering on 'uri' as well

- share/goodie/cheat_sheets/json/elixir.json
This PR remove the duplicate of `String.reverse/1` in the Elixir Cheat Sheet. Also I fixed some inconsistent usage of spaces.
---
Instant Answer Page: https://duck.co/ia/view/elixir_cheat_sheet
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @pjhampton
> Elixir Cheat Sheet: Remove duplicate "String.reverse/1"

- lib/DDG/Goodie/FlipText.pm
- t/FlipText.t
Switch to `start` trigger to prevent showing on irrelevant queries.
e.g. "photoshop rotate text"
---
Instant Answer Page: https://duck.co/ia/view/flip_text
> FlipText: Force start trigger to improve relevancy

- t/CheatSheets/CheatSheetsJSON.t
1. The metadata check doesn't need to be `critical`.
2. More information on how to get a cheat sheet in the metadata feed.
IA page: https://duck.co/ia/view/cheat_sheets
> CheatSheets: make no metadata a warning

- lib/DDG/Goodie/GenerateMAC.pm
- lib/DDG/Goodie/MacAddress.pm
- t/GenerateMAC.t
- t/MacAddress.t
After a discussion with @GuiltyDolphin and @edgesince84, this is a suggested change to highlight similar Instant Answers the user might be interested in. Both IAs currently use the text template meaning space is available for an infobox for this purpose, similar to the [Caesar cipher IA](https://duckduckgo.com/?q=how+to+use+a+caesar+cipher&ia=answer).
---
https://duck.co/ia/view/generate_mac
https://duck.co/ia/view/mac_address
> Refer MAC address and Generate MAC to each other

- lib/DDG/Goodie/JsMinify.pm
- share/goodie/js_minify/content.handlebars
- share/goodie/js_minify/js_minify.css
- share/goodie/js_minify/js_minify.js
- t/JSMinify.t
- t/JsMinify.t
Developing an interactive JS Minifier using [this library](http://prettydiff.com/prettydiff.js). *Work in progress*
@moollaza @MariagraziaAlastra 
---
Instant Answer Page: https://duck.co/ia/view/js_minify
> Add new JSMinify Instant Answer

- lib/DDG/Goodie/Parcelforce.pm
- t/Parcelforce.t
Fixes https://github.com/duckduckgo/zeroclickinfo-goodies/issues/3391 - this is the same problem as the isbn IA has here; a 4 character a-z followed by a number is valid parcelforce tracking number. 
@tagawa 
---
Instant Answer Page: http://duck.co/ia/view/parcelforce
> Parcelforce: Triggering on luhn!

- lib/DDG/Goodie/Frequency.pm
- share/goodie/frequency/list_content.handlebars
- t/Frequency.t
This IA used to return a plain text response. Now that it's updated it returns a `structured_answer`. The `List` group with the record template works well here. Each letter and its frequency is a row in the table.
Fixes #2715 
@moollaza @tagawa 
---
Instant Answer Page: https://duck.co/ia/view/frequency
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @unlisted
> Frequency: Update IA to use List template

- share/goodie/cheat_sheets/json/differential.json
The differential calculus cheatsheet, proudly showcased in a recent tweet, has some errors int it. This PR aims at fixing this, and also adds some enhancements I find quite useful.
Hope this helps ! :smile: 
---
Instant Answer Page: https://duck.co/ia/view/differential_cheat_sheet
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @ManrajGrover
> Differential calculus cheatsheet : fix mistakes

- lib/DDG/Goodie/RandomDate.pm
- t/RandomDate.t
Adds support for queries of the form `random date in the (past|future)` and ranges (`random date between 1st Jan and 2nd September`)
Fixes #3407 
@tagawa 
---
Instant Answer Page: https://duck.co/ia/view/random_date
> RandomDate: Add support for ranges

- share/goodie/cheat_sheets/cheat_sheets.js
- share/goodie/cheat_sheets/detail.handlebars
@moollaza as we discussed a week ago, I finally found time to hustle with this and found one of the many possible ways to make cheat sheets more flexible regarding number of columns (which is currently fixed at 3). Let's discuss this further to see if there's a better way to make this happen.
As of now, the cheat sheet can now contain this new property to change the number of columns in the cheat sheet.
```javascript
{
...
"columns": 2,
...
}
```
The logic for now, works for 2 columns (can be very easily extended for 1 column as well).
@moollaza 
----
https://duck.co/ia/view/cheat_sheets
> CheatSheets: Support column specification

- share/goodie/cheat_sheets/json/ace-editor.json
Removed the empty string alias defined in this cheat sheet's JSON.
#3517 
@tagawa 
---
Instant Answer Page: https://duck.co/ia/view/ace_editor_cheat_sheet
> Ace Editor Cheat Sheet: Remove empty string alias

- lib/DDG/Goodie/Conversions.pm
- t/Conversions.t
Whenever we're adding a custom template, we always have to use the `base` template because it looks wonky when we use anything else. Notice the extra margins that are added:
Before:
After:
> Conversions.pm: Switch group from 'text' to 'base'.

- share/goodie/cheat_sheets/json/hangeul.json
Hangeul lists all of the letters that comprise the Korean alphabet (hangeul/hangul), along with their names and pronunciation. These letters can be assembled in order to read and write in Korean.
Correct ID
Appended "_cheat_sheet" to name.
@daxtheduck 
---
Instant Answer Page: https://duck.co/ia/view/hangeul_cheat_sheet
> Add Hangeul Cheat Sheet

- lib/DDG/Goodie/Roman.pm
- t/Roman.t
Improvement
Bug fix: **`Roman Numerals: Proposed Fix 3484`**
Add more tests.
Improve regex so that queries like `10 in roman numerals` trigger.
Fixes #3484 - Add tests for this issue and improve regex so that the query now triggers correctly.
---
Instant Answer Page: https://duck.co/ia/view/roman
> Improve triggering of Roman Numerals

- share/goodie/conversions/ratios.yml
I added some more metric measurements and sorted them by size.
Fixes #3534 - Add additional metric measurements.
@mintsoft 
@Zekario
---
> Conversions: Fix #3534

- share/goodie/cheat_sheets/json/quackhack.json
Fixes: #3575: added forum.duckduckhack.com to the Quack and Hack Cheat Sheet 
---
Instant Answer Page: http://duck.co/ia/view/quackhack_cheat_sheet
> Fixes: #3575: added forum.duckduckhack.com to the Quack and Hack Cheat Sheet 

- lib/DDG/Goodie/CurrencyIn.pm
- lib/DDG/Goodie/EmailValidator.pm
- lib/DDG/Goodie/HexToASCII.pm
- lib/DDG/Goodie/Lowercase.pm
- lib/DDG/Goodie/MacAddress.pm
- lib/DDG/Goodie/MagicEightBall.pm
- lib/DDG/Goodie/Morse.pm
- lib/DDG/Goodie/NoteFrequency.pm
- lib/DDG/Goodie/PaleoIngredientCheck.pm
- lib/DDG/Goodie/PhoneAlphabet.pm
- lib/DDG/Goodie/PigLatin.pm
- lib/DDG/Goodie/Rc4.pm
- lib/DDG/Goodie/Reverse.pm
Remove `html_enc` from few IA Goodies
#3563
@moollaza 
---
None
> Remove `html_enc` from few IA Goodies

- lib/DDG/Goodie/Roman.pm
- t/Roman.t
{Short Description}`**
Make 'X to roman numerals' or 'X to arabic' trigger.
Proposed fix for this [issue](https://github.com/duckduckgo/zeroclickinfo-goodies/issues/3592)
---
Instant Answer Page: https://duck.co/ia/view/roman
> Roman Numerals: Add more trigger words.

- lib/DDG/Goodie/Roman.pm
---
Instant Answer Page: https://duck.co/ia/view/roman
> Roman Numerals: Remove repeated \s* in character set.

- lib/DDG/Goodie/SHA3.pm
- t/SHA3.t
Fixes #3563: Sha3.pm removed html_enc()
cc: @moollaza 
---
Instant Answer Page: https://duck.co/ia/view/sha3
> Fixes #3563: Sha3.pm

- lib/DDG/Goodie/HTMLEntitiesEncode.pm
> removed html_enc() from HTMLEntitiesEncode.pm fixes:#3563

- share/goodie/cheat_sheets/json/webstorm-mac.json
Added new shortcut for Webstorm ("Show suggestions")
---
Instant Answer Page: https://duck.co/ia/view/webstorm_mac_cheat_sheet
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @universeofsolutions
> Webstorm Mac Cheat Sheet: Added new shortcut for Webstorm

- lib/DDG/Goodie/RgbColor.pm
- share/goodie/rgb_color/content.handlebars
- t/RgbColor.t
This adds support for displaying the color name/title on hover over the hex/circle respectively.
Resolves #3572 (at least in part - I find this satisfactory for now).
cc @mintsoft 
---
Instant Answer Page: https://duck.co/ia/view/rgb_color
> RgbColor: Add support for color titles

- share/goodie/cheat_sheets/json/sublime-text.json
Cheat Sheet URL: [here](https://duckduckgo.com/?q=sublime+text+cheat+sheet&t=h_&iax=1&ia=cheatsheet)
The cheat sheet is missing the shortcut: **[Ctrl] + [M]** and hence, is added by this pull request.
This shortcut is used to _jump to the matching bracket_.
> Sublime-text cheat sheet : Added shortcut for jumping to matching bracket

- share/goodie/cheat_sheets/json/requests.json
The current version lists `response.json` as the appropriate way to get the cookies from a response, when it is in fact `response.cookies`.
Updates `response.json` to `response.cookies` in the `Headers and Cookies` section
---
Instant Answer Page: https://duck.co/ia/view/requests_cheat_sheet
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @daneah
> Requests Cheat Sheet: Fix incorrect property name

- share/goodie/cheat_sheets/json/javadoc.json
This PR creates a cheat sheet listing the various JavaDoc tags.
_Javadoc_ is a documentation generator created by Sun Microsystems for the Java language (now owned by Oracle Corporation) for generating API documentation in HTML format from Java source code. The tags are used for this purpose.
Check out the cheat sheet : [here](https://beta.duckduckgo.com/?q=javadoc+cheat+sheet&ia=cheatsheet&iax=1)
Cheat Sheet page : [here](https://duck.co/ia/view/javadoc_cheat_sheet)
Developer and Maintainer: [**AdiChat**](https://github.com/AdiChat)
---
https://duck.co/ia/view/javadoc_cheat_sheet
> New JavaDoc cheat sheet

- share/goodie/cheat_sheets/json/numpy.json
Changed sourceURL to https://docs.scipy.org/doc/numpy/reference/ from
https://ipgp.github.io/scientific_python_cheat_sheet/#numpy-import-numpy-as-np
#3703 
@amarlearning 
---
Forum Topic:
IA Page: https://duck.co/ia/view/numpy_cheat_sheet
> NumpyCheatSheet: Change 'More at' link to official one

- share/goodie/cheat_sheets/json/apple-mac-os.json
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @AlfonzM
Add "macos" as an alias because the official name of OS X is changed to macOS.
Instant Answer Page: https://duck.co/ia/view/apple_mac_os_cheat_sheet
> Apple Mac OS Cheat Sheet: Add macOS as alias.

- share/goodie/cheat_sheets/json/cdata-types.json
Adds a new Cheat Sheet for C Data Types including int, short, float, etc.
@moollaza 
@rasikapohankar 
---
IA: [https://duck.co/ia/view/c_data_types_cheat_sheet](https://duck.co/ia/view/c_data_types_cheat_sheet)
Forum Topic: [https://forum.duckduckhack.com/t/new-c-data-types-cheat-sheet/1047](https://forum.duckduckhack.com/t/new-c-data-types-cheat-sheet/1047)
> new C Data Types cheat sheet

- lib/DDG/Goodie/ColorPicker.pm
- t/ColorPicker.t
Fixes https://github.com/duckduckgo/zeroclickinfo-goodies/issues/3788 / https://github.com/duckduckgo/zeroclickinfo-spice/issues/2838 by guaranteeing that the words after the trigger are actual colours
@tagawa 
Just to re-iterate, the metadata for this IA appears to be broken
---
Instant Answer Page: http://duck.co/ia/view/color_picker
> ColorPicker: Fixing over eager triggering

- share/goodie/cheat_sheets/json/postgresql.json
As stated in #3791, there's a bug in PostgreSQL cheat sheet that doesn't display the info about the commands in one section.
Fixes #3791 
---
Instant answer page: https://duck.co/ia/view/postgresql_cheat_sheet
> Fixes #3791 (bug in PostgreSQL cheat sheet)

- share/goodie/cheat_sheets/json/bitwise-ops.json
---
Instant Answer Page: https://duck.co/ia/view/bitwise_ops_cheat_sheet
> New Bitwise Ops IA (cheatsheet)

- lib/DDG/Goodie/HistoricalEvents.pm
- share/goodie/historical_events/events.yml
- share/goodie/historical_events/historical_events.css
- t/HistoricalEvents.t
- Improved subtitle to be less redundant
- simplified code, but made the YAML much more verbose
- we can change this later, but this seems like the simplest solution
- increased font size of title
- allow for triggering with or without articles like `the` in query
@b2ddg @nilnilnil @MariagraziaAlastra 
---
Instant Answer Page: https://duck.co/ia/view/historical_events
> Historical Events: Rephrase subtitle to answer & restate question

- share/goodie/cheat_sheets/json/duckduckgo-syntax.json
- Adds the alias "duckduckgo search syntax", "duck duck go search syntax"
- correct "bangs" to "!Bangs"
- correct drop terms example
---
Instant Answer Page: https://duck.co/ia/view/duckduckgo_syntax_cheat_sheet
> DuckDuckGo Syntax Cheat Sheet: Add alias

- share/goodie/cheat_sheets/json/linux.json
Adding unix in alias list.
Fixes #3812
@crashrane 
---
> LinuxCheatSheet: Added Unix as one of the alias

- share/goodie/cheat_sheets/json/skyscanner-apis.json
If this is something else:
Docs: we have released new documentation for our APIs so have updated the link in our IA
Docs: we have released new documentation for our APIs so have updated the link in our IA
@moollaza 
---
IA page: https://duck.co/ia/view/skyscanner_apis_cheat_sheet
> udating the link to our new documentation

- lib/DDG/Goodie/Conversions.pm
- t/Conversions.t
Introduces support for queries like:
* 5 feet 3 inches in metres
* 6 foot 1 in inches
* 3'6" in cm
fixes https://github.com/duckduckgo/zeroclickinfo-goodies/issues/3875
and fixes https://github.com/duckduckgo/zeroclickinfo-goodies/issues/3433
and fixes https://github.com/duckduckgo/zeroclickinfo-goodies/issues/1118
but not https://github.com/duckduckgo/zeroclickinfo-goodies/issues/3317 (would be a different PR)
@bsstoner 
---
> Conversions: Adding support for n'm" format

- lib/DDG/Goodie/Conversions.pm
- t/Conversions.t
My particular concern is:
When I query: "bytes in 1 mib"
I want a precise response: "1,048,576 bytes"
...instead of "1.05 * 10^6 bytes"
Beyond that, generally, I believe that most people who can cognitively handle numbers up to 1MM can also handle any number with a seven digit integer-part/characteristic (http://math.stackexchange.com/a/64045/92444). Ideally, the decision should be made based on the number of characters in the significand (https://en.wikipedia.org/wiki/Significand) but that's beyond what I have time for at the moment (especially given how rusty my perl is) ;) .
---
> Conversions: Increases threshold before exponent notation

- share/goodie/cheat_sheets/json/grep.json
Adds file and directory options for grep from the [GNU grep manual](https://www.gnu.org/software/grep/manual/grep.html)
Fixes #3944 
@laurengarcia @adityabhushan 
---
Instant Answer Page: https://duck.co/ia/view/grep_cheat_sheet
> Grep Cheat Sheet: Adds file and directory options

- share/goodie/cheat_sheets/json/array-sorting.json
- Better triggers. The cheat sheet seemed to be seriously under triggering to me.
- Added auxiliary memory complexity to all sorts already in cheat sheet.
- Added information about variables used in description. The information doesn't make a lot of sense without these.
- Re-arranged sorts in order of popularity. Slightly opinionated, order as in wikipedia and GeeksforGeeks page.
- Used multiplication symbol ⋅ to show multiplication properly. Earlier notation seemed unclear.
- Added information about comb sort from [wikipedia](https://en.wikipedia.org/wiki/Comb_sort). 
Note: Someone also needs to modify the description on the IA page.
@mintsoft 
---
Instant Answer Page: https://duck.co/ia/view/array_sorting_cheat_sheet
> Array Sorting Cheat Sheet: Improvements

- lib/DDG/Goodie/POTUS.pm
- t/POTUS.t
Fixes https://github.com/duckduckgo/zeroclickinfo-goodies/issues/3760
Unfortunately, the regex isn't actually matching the query, it's replacing bits that we don't need so we can pass the remainder on to `words2nums` to convert. This was defaulting to the current president if it couldn't parse, which basically means it would show the current president for anything that isn't "first" "second" etc i.e. "elect" or "vice".
Whether this is worth fixing or not I'll leave up to the community/staff. If this doesn't work/isn't resliant enough, I'd suggest starting from scratch from a guard regex instead.
@moollaza @bsstoner 
---
Instant Answer Page: https://duck.co/ia/view/potus
> POTUS: Triggering is way too keen

- lib/DDG/Goodie/Conversions.pm
- share/goodie/conversions/ratios.yml
- t/Conversions.t
There are a few issues (for example: https://github.com/duckduckgo/zeroclickinfo-goodies/issues/1132) and comments that I've seen on slack and various locations where users have mentioned the accuracy of our conversions when in scientific notation (x * 10^y). I've introduced a number of sig figs for that notation which is currently 6 and left the accuracy at 3. This seems to look better and more accurate to the user.
Also added an alias "lightyear" for "light year"
Fixes: https://github.com/duckduckgo/zeroclickinfo-goodies/issues/1132
Fixes: https://github.com/duckduckgo/zeroclickinfo-goodies/issues/1517
@abrahimladha
---
> Conversions: Increase significant figures in Scientific Notation

- lib/DDG/Goodie/Parcelforce.pm
- t/Parcelforce.t
Works around https://github.com/duckduckgo/zeroclickinfo-goodies/issues/3900 so that only GB$ codes will trigger parcelforce
Same is also true for https://github.com/duckduckgo/zeroclickinfo-goodies/issues/3986 as `^KB\d` is *possibly* a valid parcelforce tracking number, however it's far more likely that that the user is after a Microsoft KB article. 
Fixes https://github.com/duckduckgo/zeroclickinfo-goodies/issues/3900
Fixes https://github.com/duckduckgo/zeroclickinfo-goodies/issues/3986
@bsstoner  @zappe
---
Instant Answer Page: https://duck.co/ia/view/parcelforce
> ParcelForce: Should not trigger for non-UK parcels

- lib/DDG/Goodie/TimezoneConverter.pm
- t/TimezoneConverter.t
IA Page: https://duck.co/ia/view/timezone_converter
Maintainer: @GlitchMr
> TimezoneConverter: Remove moreAt so that there's no extra space at the bottom of the IA

- lib/DDG/Goodie/Conversions.pm
- t/Conversions.t
Previously, unless the result was large/small enough to warrant scientific notation, it was always given to 3 DP. That's basically fine for large-ish numbers, like 20.345 as the result, however it's crap for 1e-6 < x < 1 as this is where fractions like 1/8 live and it looks crap. 
So now, if the result is >1 and <10,000,000 then we use 3dp (for nice integer handling of things like 2^20 mainly), the same as before. However if it's < 1 then we use 3 significant figures. Everywhere else it's scientific notation, again unchanged.
The `Math::SigFigs` module I already have on my ddh box, so this may be pulled in already by an existing package, if not then it'll need flagging as `needs new perl dependency`.
If it would require the dependency adding to production, I'll probably remove it and …
> Conversions: Improving result aesthetics 

- share/goodie/conversions/ratios.yml
- t/Conversions.t
Previously `convert 65 c to f` worked however `convert 65 degrees c to f` didn't. This remedies that :)
Fixes: https://github.com/duckduckgo/zeroclickinfo-goodies/issues/3918
@bsstoner 
---
> Conversions: Improving triggering for degrees [cf]

- share/goodie/cheat_sheets/json/mips.json
---
Instant Answer Page: https://duck.co/ia/view/mips_cheat_sheet
> New MIPS Cheat Sheet

- share/goodie/timer/timer.js
I broke the handling of the time input data In a recent PR I made + merged. This fixes the bug I introduced.
Fixes #4035 
The `data` obj is initially created as an object which I noticed when I wrote the new code on [line13](https://github.com/duckduckgo/zeroclickinfo-goodies/compare/zaahir/fix-timer-js?expand=1#diff-337bb630aab5f2688c25d7201e0bdfbaR13).
When I saw we were referencing `data` as an array, I thought this was a bug and changed it.
I now realize `data` later becomes an array to handle multiple timers.
---
> Timer: switch back to handling data obj as array

- lib/DDG/Goodie/Conversions.pm
- share/goodie/conversions/ratios.yml
- t/00-roles.t
- t/Conversions.t
This changes the behaviour of conversions as follows:
* Descriptive unit names (microseconds, megabytes, megabits, kilometers etc) should remain case insensitive, if the user puts in MICROSECONDS because they love capslock then it should work
* Things that I've defined as Symbols (based on SI definitions, i.e. `m` for metres, `l` for Litres, `Pa` for Pascals, and crucially: `B` for bytes and `b` for bits) should be *case sensitive* as this is how the symbol is defined. 
* Symbol case sensitivity is also extended to the SI prefixes i.e. `Mm` is megametres and `mm` is millimeters, similiarily `kB` is kilobytes and `kb` is kilobits
I've also extended the volume bodge to add more unit support so that more queries using `oz` as implicitly `fl oz` work
Fixes: …
> Conversions: Case sensitive Units/Symbol handling

- share/goodie/cheat_sheets/cheat_sheets.js
- share/goodie/frequency_spectrum/frequency_spectrum.js
- share/goodie/game2048/game2048.js
Unlike https://github.com/duckduckgo/zeroclickinfo-spice/pull/2885 this can be merged pretty much immediately.
I also fixed an undeclared `bbox` variable in the Frequency Spectrum IA. There's another error with an undeclared variable there, but I don't know enough about what it's meant to do to easily fix it. I'm gonna create an issue for the maintainer.
cc @bsstoner @bbraithwaite
> Remove use of several vars on global scope

- lib/DDG/GoodieRole/Dates.pm
- t/00-roles.t
Adds handling for dates in the format `7th of march 2017`. Also as a *bonus* adds `march the 7th 2017`
Related: https://github.com/duckduckgo/zeroclickinfo-goodies/issues/3980
@bsstoner @Mailkov
> DateRole: Handling 'of' in textual date formats

- share/goodie/calculator/calculator.js
Wrapping the numeric values of the `NOSHIFT_KEYCODES` object in quotes so we handle them as strings. This prevents the 0 value from being interpreted as `false`. Using strings is OK because we use `$.isNumeric()` to check the values which can handle a string of digits.
**Code** …
> Calculator: Use strings in NOSHIFT_KEYCODES to prevent handling 0 as false

- lib/DDG/Goodie/Unicode.pm
- t/Unicode.t
Unicode: Make '+' character in unicode codepoint query optional so that, for example, both u+263A and u263A would work.
Sometimes people don't include the + when writing about unicode, or in file names (such as image files for an emoji font) and copying that into duckduckgo should still yield the unicode instant answer.
In Unicode instant answer, make + in unicode codepoint query optional so that, for example, both u+263A and u263A would work.
- All **Example …
> Unicode: Make '+' character in unicode codepoint query optional.

- share/goodie/conversions/conversions.js
> Remove conversion.js

- lib/DDG/Goodie/HtmlEntities.pm
- share/goodie/html_entities/triggers.txt
- t/HtmlEntities.t
Adds new triggers and tests for the html entities goodie.
Fixes #4086.
Hey, @moollaza, I made another PR since I deleted the previous branch by accident, sorry. I implemented the changes we talked about.
**Code**
--- …
> html_entities: Added new triggers & tests

- lib/DDG/GoodieRole/Dates.pm
- t/00-roles.t
Adds support for queries without years but days months and time i.e. "11 may 08:00:00" or "28 feb 23:00"
@moollaza Mentioned that someone attempted to put a trigger in for the countdown timer using this format
@moollaza 
**Code**
--- …
> DatesRole: Adding support for partial time format

- share/goodie/conversions/triggers.yml
These changes move the alias "tonne" to the metricton unit, instead of imperial ton. I've added additional aliases for the imperial/us ton as well.
@pjhampton 
**Code**
---
> Conversions: Fix metric/imperial ton aliases

- share/goodie/cheat_sheets/json/selenium.json
```
```
**Code**
---
Instant Answer Page: https://duck.co/ia/view/selenium
> Selenium white space triggering travis warning

- lib/DDG/Goodie/Conversions.pm
- share/goodie/conversions/triggers.yml
- t/Conversions.t
Many queries are made with the word celsius misspelled as celcius. Seeing as we already account for the "farenheit" misspelling, I've added in "celcius" to account for these missed opportunities.
@pjhampton 
**Code**
---
> Conversions: Allow "celcius" typo, updated tests

- share/goodie/minecraft/crafting-guide.json
- t/Minecraft.t
This matches British spelling of colour for minecraft guide.
Will re-base with #4271 if it's finished and pulled before this one.
**Code**
---
Instant Answer Page: https://duck.co/ia/view/minecraft
> Minecraft: British spelling of colour

- lib/DDG/Goodie/TimezoneConverter.pm
- t/TimezoneConverter.t
TimezoneConvertor: Fixed error in displaying timezone.The error was because it was taking modulo of negative number while separating it into minutes and hours in parse_timezone function.
Fixes #4210 
@glitchmr
**Code**
---
Instant Answer Page: https://duck.co/ia/view/timezone_converter
> TimezoneConverter: fixes #4210 fixed error in timezone display

- lib/DDG/Goodie/Conversions.pm
- t/Conversions.t
This PR enables single unit queries such as `grams`, `feet`, `meters`, etc but doesn't let trough ambiguous symbols such as `mph`, `gs`, `ms`, `cm`.
**Code**
---
> Conversions: Enable single unit triggers

- lib/DDG/Goodie/MolarMass.pm
- t/MolarMass.t
Removed "atomic mass of" and "atomic weight of" triggers that were conflicting with Periodic Table IA, and added triggers to handle queries such as "H2SO4 molar mass" and "whats the molar mass of water?".
Fixes #4240
@pjhampton @adityatandon007 @moollaza 
**Code**
---
Instant Answer Page: https://duck.co/ia/view/molar_mass
> Molar Mass: Resolve conflicting triggers issue and add new triggers

- lib/DDG/Goodie/Tips.pm
- share/goodie/conversions/conversions.js
- share/goodie/tips/content.handlebars
- share/goodie/tips/tips.css
- share/goodie/tips/tips.js
- t/Tips.t
Adds interactivity to tips. **Good for review** 👍 
@moollaza 
**Code**
---
Instant Answer Page: https://duck.co/ia/view/tips
> Tips: Add interactivity

- lib/DDG/Goodie/Timezonetime.pm
- t/Timezonetime.t
Finish's the Timezone/time IA.
@moollaza 
**Code**
---
Instant Answer Page: https://duck.co/ia/view/timezonetime
> New Timezonetime IA

- share/goodie/cheat_sheets/json/kde.json
KDE cheat sheet: 
- fix "View menu" shortcut
- add "Paste" shortcut
- add "Cut" shortcut
---
Instant Answer Page: https://duck.co/ia/view/kde_cheat_sheet
> KDE shortucuts improved

- lib/DDG/Goodie/CssAnimations.pm
Part-Fixes: https://github.com/duckduckgo/zeroclickinfo-goodies/issues/4414
---
Instant Answer Page: https://duck.co/ia/view/css_animations
> CssAnimations: keys on scalar is forbidden under perl 5.24

- share/goodie/cheat_sheets/json/haskell.json
New cheat sheet for the Haskell language including basic features (data types, operations, comparators, IO, enumerations, lists, tuples, functions, control flow).
---
IA Page: https://duck.co/ia/view/haskell_cheat_sheet
> Add New Haskell Cheat Sheet

- share/goodie/cheat_sheets/json/xaml.json
XAML for WPF Cheat Sheet. Includes Data Binding, Styles and Triggers, Resources, Transforms, Brushes, and Layout.
##IA URL
https://duck.co/ia/view/xaml
**Code**
---
> New XAML Goodie

- share/goodie/cheat_sheets/json/restructuredtext.json
Fixes small typo: `*emphasis` -> `*emphasis*`
Fixes #4454 
@nickschafran 
---
Instant Answer Page: https://duck.co/ia/view/restructuredtext_cheat_sheet
> RestructuredText Cheat Sheet: Fix typo

- lib/DDG/Goodie/AltCalendars.pm
Part-fixes: https://github.com/duckduckgo/zeroclickinfo-goodies/issues/4414
---
Instant Answer Page: https://duck.co/ia/view/alt_calendars
> AltCalendars: keys on ref is fatal under perl 5.24

- lib/DDG/Goodie/HasLHCDestroyedWorld.pm
- t/HasLHCDestroyedWorld.t
Adds an easter egg that determines whether the Large Hadron Collider has destroyed the world yet. Just for giggles; reject it if you don't like it, because it only took about an hour of my time.
N/A
---
Instant Answer Page: https://duck.co/ia/view/has_the_large_hadron_collider_destroyed_the_world_yet
> New LHC Apocalypse Checker Instant Answer

- lib/DDG/Goodie/HasLHCDestroyedWorld.pm
- t/HasLHCDestroyedWorld.t
Limits the query patterns more severely to reduce overtriggering (see https://github.com/duckduckgo/zeroclickinfo-goodies/pull/3597#discussion_r135558510)
@AlterationBrick @moollaza 
**Code**
--- …
> LHC: Limiting overtriggering

- .travis.yml
Adjust .travis.yml to prevent installing modules from BackPAN
> Fix Travis Builds: use --mirror-only option to prevent installing from backpan

- lib/DDG/Goodie/ColorCodes.pm
- t/ColorCodes.t
Total screw-up here, I forgot to map the matched "type" to the type that is supported by `Convert::Color`; I'd written the *guard* in the if correctly, just not the assignment. No idea how I missed that 
Edit: It was working for anything using 3digit numbers (which all the test cases were) but broken if it matched on 2 digits i.e. `rgb(217,37,50)` and also works with 0 so `rgb(0,255,255)` is correct
Fixes: https://github.com/duckduckgo/zeroclickinfo-goodies/issues/4479
@moollaza @mcomella
---
Instant Answer Page: https://duck.co/ia/view/color_codes
> ColourCodes: Fixing handling on RGB with values > 0

- lib/DDG/Goodie/TimezoneConverter.pm
- t/TimezoneConverter.t
Timezone Converter would previously show the converted times 12 PM and 0 AM as "Noon" and "Midnight", respectively. This PR changes the instant answer so 12 PM and 0 AM are always shown in the same time format as all other times.
Fixes #1451 
@moollaza @mintsoft 
---
Instant Answer Page: https://duck.co/ia/view/timezone_converter
> Timezone Coverter: Removed friendly "Noon" and "Midnight" times from TimezoneConverter IA

- lib/DDG/Goodie/Binary.pm
- t/Binary.t
When a string is being converted to binary, this change causes the string to be represented in UTF-8 encoding before being converted to binary.
Fixes #1356
@moollaza @mintsoft @nilnilnil 
---
Instant Answer Page: https://duck.co/ia/view/binary
> Binary: Encoded query string into UTF-8 before string to binary conversion

- .travis.yml
- Switch from Ubuntu Precise to newer Trusty
- Use single process for running CPANM (seems to help prevent builds from failing)
@pjhampton
> Switch Travis to Ubuntu 14 (Trusty)

- lib/DDG/Goodie/CalcRoots.pm
- t/CalcRoots.t
Prevents triggering on strings such as: 'square root of minus garfield'
---
Instant Answer Page: https://duck.co/ia/view/calc_roots
> CalcRoots: Fixes triggering on words.

- lib/DDG/Goodie/TextConverter.pm
- t/TextConverter.t
Queries such as `base64 decode` were showing the instant answer with a conversion from text to base64, but it should be the other way around. The static language words that trigger the instant answer conversion options have been classified into whether the type specified in the query should be the `from_type` or the `to_type`.
Fixes #4365 
@pjhampton @mintsoft @moollaza 
---
> TextConverter: Sorted static trigger words into to and from categories

- share/goodie/public_dns/providers.yml
Adds a new Public DNS on that specific IA
n/a
n/a
---
Instant Answer Page: https://duck.co/ia/view/public_dns
> Public DNS: Add Quad9 to the list of Public DNS servers

- lib/DDG/Goodie/Conversions.pm
- t/Conversions.t
Fixes an issue where implicit conversions without units of the form `x = y` were returning conversions from `y` to `x`, but the conversion from `x` to `y` is expected, just as it occurs for conversions of the form `x to y`.
Fixes #4521 
---
> Conversions: Changed "=" to act like "to" in implicit conversions

- share/goodie/calculator/calculator.js
It is the normalizeExpression that has a decimal limit of `\d{1,2}`.
The fix is to replace it with `\d{1,}`
When Testing it works fine!
Fixes [#4541](https://github.com/duckduckgo/zeroclickinfo-goodies/issues/4541)
@pjhampton 
---
> Calculator: Fix on percentages with 4+ decimal places (#4541)

- share/goodie/text_converter/text_converter.js
Fixes #4513, fixes #4567, fixes #4570 and fixes #4566. For binary-to-decimal conversion we don't need to convert each byte separately. For binary-to-hexadecimal we need to go from the last byte to the first one.
---
> Text Converter: Fix binary conversion bug.

- share/goodie/public_dns/providers.yml
Removed CCC Berlin entry. The CCC Berlin DNS server is no longer in use, as per:
https://twitter.com/clubdiscordia/status/983109445784875009?s=11
Fixes #4664
@Mailkov 
---
Instant Answer Page: https://duck.co/ia/view/public_dns
> public_dns: Fixes #4664 - Removed CCC Berlin entry

- share/goodie/conversions/conversions.js
There should only be 1 "r" in "tera".
This is a 1-character change not in the code that isn't "an essential bug fix", but should be easy to review. The reason I decided to submit this is to avoid teaching people incorrect spellings.
---
> Conversions: Fixed typo

- share/goodie/cheat_sheets/json/markdown.json
As @smilealdway mentioned:
The suggested markdown text to show reference is incorrect. It has for some reason used escape characters to mention reference links.
duckduckgo suggests using \[1\]: http://slashdot.org while actually, it should be just [1]: http://slashdot.org
Fixes #4697
@smilealdway @moollaza 
---
Instant Answer Page: https://duck.co/ia/view/markdown_cheat_sheet
> Markdown Cheat Sheet: Unescape brackets in shortcut description
